doc/tut2.txt
TObject has been deprecated in a recent release of Nim.
=> Update tutorial to use RootObj

lib/pure/asyncdispatch.nim, lib/pure/selectors.nim
I got 100% CPU on some trivial Jester programs after many people access them at the same time. It only happened one on of my machines, but consistently and CPU usage never went down again, until the program was restarted. Might have to do with the hardware or Kernel version (2.6.32 still). The issue was that epoll_wait can return an error (EPOLLERR), which was not handled at all. Now an error causes the affected FD to be closed.
Not sure if EPOLLERR, EPOLLHUP and EPOLLRDHUP should be handled separately. I'm not doing that for now.
=> Async fixes

lib/pure/httpclient.nim
Creating multipart/form-data POST parameters as strings by hand is unhandy, so now you can do it more comfortably. See how the POST example at the top of the documentation changed.
I needed this change for the code to interface with Mediawiki's API to rename all mentions of Nimrod to Nim on Rosetta Code: https://github.com/def-/nim-unsorted/blob/master/rcrename.nim
I think automated cookie handling would also be nice to have in an HTTP client.
=> Add multipart parameter to httpclient's post and postContent

lib/pure/unittest.nim
The documentation for terminal says
> Changing the style is permanent even after program termination! Use the code
> `system.addQuitProc(resetAttributes)` to restore the defaults.
=> Properly use the terminal module

lib/wrappers/mysql.nim
On my systems the libmysqlclient version has moved to 16 and 18. Haven't tested extensively but connecting to database and closing again works.
Not sure if this is the proper way of doing this.
=> Allow higher versions of libmysqlclient

doc/tut2.txt
A "the" was missing before "foreign" in "Macros have to be implemented in pure 
Nim code if foreign function interface (FFI is not enabled in the compiler"
=> doc/tut2.txt: Tiny grammar fix

doc/tut2.txt
The original text was slightly misleading in that it could be read that newLit and newPlus could not be implemented as methods; this is untrue, because newPlus could also be impleented as a method. The reason that newLit can't be implemented as a method is that its first argument (x: int) has a non-object type.
=> doc/tut2.txt: clarified usage of static/dynamic binding

config/nimdoc.cfg
Improves usability of the documentation with low resolutions. See the following examples of what changed:
Old:
New:
Old:
New:
=> Improve documentation CSS for smaller resolutions

config/nim.cfg, tools/niminst/buildsh.tmpl
* there's not much documentation about what's in nim.cfg file
* the build.sh template was updated based on darwin
(Partially addresses #1934)
=> make FreeBSD's compiler clang

doc/lib.txt
Otherwise users will not find them. The .html files for them are already generated, I'm only linking to them.
=> Add missing windows wrappers to the lib.html doc

lib/pure/httpclient.nim
- Never append a newline to the body in a HTTP post.
- Pass the entire body to redirections, including multipart data
As reported here: http://forum.nim-lang.org/t/746
=> Fix body in httpclient

doc/backends.txt, lib/pure/xmltree.nim, tests/manyloc/argument_parser/argument_parser.nim, web/nim.ini, web/question.txt
Fix broken links, looked into it since reported here by MikeP: http://forum.nim-lang.org/t/753
=> GitHub link fixes: nim-code -> nim-lang

doc/manual/exceptions.txt
This new section explains how to use `getCurrentException` and
`getCurrentExceptionMsg`. See the thread http://forum.nim-lang.org/t/752 .
=> New section "Except clauses" in the manual

doc/manual/exceptions.txt
They're called type conversions. Type casts are done with cast\[T\](...)
and are not type safe.
=> Clarify documentation about "except clauses"

compiler/extccomp.nim
Probably fixes #1955 (I don't have Windows to test).
=> quote filenames in when invoking compiler from C backend

lib/pure/selectors.nim
A concrete example is pipe file descriptors: they generate EPOLLHUP instead of a EPOLLIN (then 0 bytes read). The **loop will run wild if this event is not handled**.
This is rather hard to pinpoint because the loop will run wild, and you'll wonder where did you forget to read/write a socket/fd.
=> Handle EPOLLHUP to avoid chaos/runaways when using certain fds

lib/system.nim
Currently the Nim compiler can't be built, should be fixed, was introduced in https://github.com/Araq/Nim/pull/2000
=> setControlCHook's parameter is not nil now

lib/system/chcks.nim, lib/system/embedded.nim
setControlCHook changed its signature, doesn't compile right now.
The warnings aren't important, but still here.
=> Make nimkernel compile again

tools/website.tmpl
01:47 < Danjcla> So the "Online IRC" link that's on the footer of the we site 
is links to "#nimlang" which is an invite-only channel. Is 
here a good place to report that, or should I open a bug or a 
forum thread?
01:47 < Danjcla> s/we/web/g
=> Fix IRC channel at footer

lib/wrappers/zip/zlib.nim
zlib sets the return value to -1 to communicate errors, which won't work if the parameter type is 'char'.
Also, one routine was missing.
Source: http://www.zlib.net/manual.html
=> Same types for chars as in zlib.h

doc/intern.txt, koch.nim
I didn't test the git bisect part yet, due to lack of a proper example. Anything that calls the `exec` function now returns `1` upon failure.
=> Koch temp 125 exit code

lib/posix/posix.nim, lib/pure/osproc.nim
This fixes the parallel build problem on FreeBSD and should not affect Linux builds. 
The problem was that FreeBSD's `waitpid()` changes its second parameter `status` even if the waited-for proccess has not exited, while Linux's doesn't. The nim compiler expects this parameter to be unchanged except when the process has ended.
I added a check `WIFEXITED` that is imported from `<sys/wait.h>` and changed the corresponding C imports.
I was not able to test this thoroughly under Linux as I currently only have an ancient VM image, but firsts tests showed no problems.
=> Fix parallel build on FreeBSD

lib/pure/logging.nim
Just a tiny thing, but annoying nonetheless ;)
=> newRollingFileLogger - fmtStr is always set to defaultFmtStr

lib/system.nim
This can be safely exposed because a proc accessor can be created if the representation changes.
=> Expose exception parent

lib/pure/json.nim
Some people said it's a pain to generate JSON in Nim. Since Nim is statically typed you can't just write
```nim
var j = [{"name": "John", "age": 30}, {"name": "Susan", "age": 31}]
```
Instead you have to add a `%` everywhere to convert to JSON:
```nim
var j = %[%{"name": %"John", "age": %30}, %{"name": %"Susan", "age": %31}]
```
That's annoying if you just want to paste some actual JSON into your source and set a few variables. The new `%*` macro automatically adds `%` where necessary. So you can now write:
```nim
var j = %*[{"name": "John", "age": 30}, {"name": "Susan", "age": 31}]
```
Or even with pretty indentation of your choice:
```nim
var j2 = %*
[
{
"name": "John",
"age": 30
},
{
"name": "Susan",
"age": 31
}
]
echo j2
var name = "John"
let herAge = 30
const hisAge = 31
var j3 = %* …
```
=> Json stuff

lib/impure/db_mysql.nim, lib/wrappers/mysql.nim
I don't know if the (15|16...) is supposed to work on OSX. I have "libmysqlclient.18.dylib" in my lib directory and get "could not load: libmysqlclient.(15|16|17[18).dylib" on execution. After removing the pattern I can run my little example program and it works as "libmysqlclient.dylib" is a softlink to the current version anyway. I also throw a deprecated names fix in.
=> Fixing dylib name for OSX

lib/pure/math.nim
This fixes #2110 . I could not find any guideline on how to contribute patches. Please let me know if I should add some testcase (how?) or do anything else.
=> fix conditions for int size in 'math.nextPowerOfTwo' #2110

lib/system/threads.nim
The -pthread is not needed on Darwin/OS X and the Apple compilers give a warning about this if you use --threads:on with the Nim compiler.
=> Disable -pthread for compiler/linker on OSX

config/nim.cfg
Considering that alternatives to the Apple compiler versions of xcode like GCC 4.9 (as installed by Homebrew) error out because it is an unknown parameter. Modern Xcode's clang + gcc do not seem to need this anymore. 
I think it is ok to remove because developer with old xcode are rare and can easily add this to their systems if needed.
=> Removing -fasm-blocks default for OS X

doc/advopt.txt
All the other documentation delimits with `:`, only this one was with `=`
=> Fix output of --advanced

lib/posix/posix.nim
```
02:27 < pogoplug> I'm having problems bootstraping nim on Ansible linux.  I get the following error: 
"nimcache/stdlib_osproc.c:1628:57: error: use of undeclared identifier 
'POSIX_SPAWN_USEVFORK'                 LOC33 = posix_spawnattr_setflags(&attr, 
(NI32)((NI32)(POSIX_SPAWN_US..."
02:28 < def-> pogoplug: with which C compiler?
02:28 < pogoplug> clang
02:28 < pogoplug> and musl-libc
02:29 < def-> ok, that explains it
02:29 < pogoplug> not to me
02:30 < def-> https://github.com/Araq/Nim/blob/devel/lib/posix/posix.nim#L1732-L1744
02:30 < def-> I noticed the same issue with TCC and added this workaround
02:31 < def-> I guess we need it in a more general way
```
Is there a way to detect whether we have `__USE_GNU` or `POSIX_SPAWN_USEVFORK` from `<spawn.h` directly?
=> Always use 0x40 for POSIX_SPAWN_USEVFORK

lib/system.nim, lib/system/sysio.nim
So far only `openarray[int8]` worked. Now it's `openarray[int8|uint8]`. This
should make sense, since `uint8` is comfortable to represent a byte
(0-255) and there is already `type byte* = uint8` in system.
=> Make readBytes and writeBytes work with uint8

lib/pure/strutils.nim, tests/stdlib/tstrutil.nim
If you specify a len like 32 toHex() will repeat the given value in the output. Besides that I believe my implementation is easier and seems not
to change how negative numbers are handled. I also handle the case of wrapping negative number beyond BiggestInt to "do it right".
P.S.: I am not sure why there was the toU32() in the original. I have no problems compiling it without that?
=> Fixing toHex() to not wrap for long lens + Test

compiler/types.nim
This fix allows the following code to work:
```
import unsigned
type UInt32Range = range[5'u32..15'u32]
proc square(n: UInt32Range): uint32 =
result = n * n
echo square(2'u32)
```
Without the fix, the compiler throws a compilation error, stating:
```
Error: invalid type: 'UInt32Range' in this context: 'proc (UInt32Range): uint32`
```
=> Allow ranges with unsigned integer ordinals to be used as parameter types

lib/pure/uri.nim
While reading the documentation from the uri module, I found little errors in the documentation from combine and /.
=> little documentation fix on combine and /

lib/pure/collections/tables.nim, tests/collections/ttables.nim
Fixes an error with mpairs iterator which was introduced with 5fbcf93860. This is used by nimforum thats why I found it. I also added a testcase for the mpairs iterator.
=> Fix unknown symbol in tables mpairs iterator.

lib/pure/nimprof.nim, lib/system/timers.nim
Had a program exit with the following trace after compiling in the nim profiler:
```
units.nim                nodim
nimprof.nim(135)         hook
timers.nim(32)           -
Error: unhandled exception: value out of range: 474666261244 [RangeError]
```
It's a 32 bit compile target, so the casts `timers.-(a, b: TTicks) : TNanos` was performing was narrowing from int64 -> int32.  I've changed the code to use explicit intXX casts to avoid that.
It came about in the first place because the first time through `nimprof.hook()`, `t0` is uninitilized, which could  be out of range if QueryPerformanceCounter() returned a big enough int64.  Even with the timers fix, it's still possible to overflow the conversion to nanoseconds if you're unlucky, so I changed `nimprof.hook()` to initialize `t0` when it …
=> Fix for timer overflow when using nimprofiler with 32bit Windows target.

lib/windows/windows.nim
This should correct the issue regarding member size on 64-bit systems. The MinGW header winbase.h is not quite right. `dwActiveProcessorMask` should be `DWORD_PTR` instead of `DWORD` as per https://msdn.microsoft.com/en-us/library/windows/desktop/ms724958%28v=vs.85%29.aspx
=> Corrected SYSTEM_INFO structure to match pointer type on 64-bit systems

compiler/semtypes.nim, tests/casestmt/tcase_emptyset_when.nim
Added support for conditional compilation using 'when' with empty sets in 'case of' branches.
Added test category for conditional compilation. Test with `./koch test c conditional`. I think this could be continued with other "when" related code, like in objects or for example if supported in enums.
This was discussed in the forum http://forum.nim-lang.org/t/867 ...
@Araq: Even if that won't be a correct & final solution it seems to work and I am so happy that I could create it :)
=> Allow empty sets in case/of branches.

lib/pure/net.nim, lib/pure/sockets.nim
Add SSLFree after SSLShutdown to prevent memory leak.
=> Add SSLFree after SLShutdown to prevent memory leak

lib/posix/posix.nim, lib/pure/os.nim
We only know that this works on Linux and Mac OS X, so other systems use
the POSIX conforming version still. This removed the lstat call, which
is especially expensive on NFS filesystems for me.
=> Speed up walkDir significantly

lib/pure/complex.nim
=~ does not work between the type of tuple returned by polar().  Instead we have the unit test do a round-trip from rectangular (re,im) -> polar and back to rectangular.  This exposed a bug in rect() with a missing 'r *' factor.  Also fixed the typo in the doc comment.
=> Fix buggy rect(), doc comment, and unit test.

lib/system/sysio.nim
Fix for https://github.com/Araq/Nim/issues/2228 - As I was bugged by that problem too I tried to find a way to make it work on mac. I got no good results with isatty() so I settled with comparing against the stdio file descriptor itself. Please anybody check this on Windows and Linux. (Note to myself: I need to get at least one of my Windows and Linux boxes in shape for Nim testing).
=> Fix for readAll(stdin) problem on OS X and better anyway.

lib/pure/strutils.nim, tests/stdlib/tstrutil.nim
This is more a proposal than just a PR. Why was it named `repeatStr`?
I also think that `"abc".repeat 4` or `repeat("abc", 4)` looks/feels more natural than `repeat(4,"abc")`. So I added a version with parameters swapped. Imho it should be more like "repeat something x times" not "repeat x times something".
=> `repeat` instead of `repeatStr` + parameter swapped

lib/pure/algorithm.nim, lib/pure/collections/sequtils.nim
dom96 said we should care a bit more about functional programming before 1.0.
So I tried to reimplement the top example from here: http://www.vasinov.com/blog/16-months-of-functional-programming/
This is the final code:
```nim
import sequtils
type User = tuple[id: int, firstName, lastName: string, active: bool]
proc activeById(us: seq[User]): seq[string] =
us.filterIt(it.active).sortedBy(it.id).mapIt(string, it.lastName)
let activeUsersById = activeById(@[
(11, "Nick", "Smith", false),
(89, "Ken", "Pratt", true),
(23, "Jack", "Sparrow", true)
])
echo activeUsersById
```
If this code is actually wanted I can extend the documentation and add examples of usage.
It's also quite unfortunate that we even need the `mapIt` and related templates. Would be much nicer if instead we could do `.map(x …
=> sorted & sortByIt

lib/pure/streams.nim
`s.pos` is where data will be written, So `s.pos+bufLen` should be used to determine whether the string buffer should be extended.
Normally this would not be a problem, but after `s.setPosition()` is invoded, the subsequent `s.Write` would result in a wrong `s.data.len`.
=> streams.ssWriteData: Call setLen only when new data truly increases the underlying string buffer

compiler/astalgo.nim, compiler/ccgexprs.nim, compiler/filter_tmpl.nim, compiler/jsgen.nim, compiler/msgs.nim, compiler/nimlexbase.nim, compiler/renderer.nim, koch.nim, lib/impure/re.nim, lib/packages/docutils/rst.nim, lib/packages/docutils/rstast.nim, lib/packages/docutils/rstgen.nim, lib/pure/json.nim, lib/pure/lexbase.nim, lib/pure/times.nim, lib/pure/xmldom.nim, tests/generics/tgeneric3.nim, tests/manyloc/argument_parser/argument_parser.nim, tests/manyloc/keineschweine/dependencies/genpacket/streams_enh.nim, tests/manyloc/keineschweine/enet_server/enet_server.nim, tests/manyloc/keineschweine/keineschweine.nim, tests/manyloc/keineschweine/lib/map_filter.nim, tests/manyloc/keineschweine/lib/zlib_helpers.nim, tests/manyloc/keineschweine/server/old_sg_server.nim, tests/vm/tconsteval.nim, tools/nimgrep.nim, tools/nimweb.nim
As "my" new `repeat()` deprecates `repeatStr()` and `repeatChar()` I thought I should also remove the deprecated usage. I just made the natural replacements but of one file where there where a name clash. I changed the existing (not exported) `space()` into `rspace()` to make it unambiguous what is used (the other `space` made a spaces as Rope, hence my choice of `rspace()`).
P.S.: I also fixed a bug with "biggestInt" vs "BiggestInt" and some usage of identifier l warnings on my way.
=> Updates to remove deprecated repeatStr() and repeatChar() from all files.

lib/pure/redis.nim
Implemented 3 additional commands which implement the whole set of commands to work with Redis HyperLogLog data type:
1) pfadd
2) pfcount
3) pfmerge
=> Added HyperLogLog support to Redis client

tests/testament/categories.nim
I think the original intent was to remove the newline. Also, disable nimble tests for now, they seem to hang.
=> fixed a bug in nimble tests - disable for now

compiler/importer.nim
I believe this is a fix for issue #2281
```nim
import ../usefull/coolmodule
import ../masterlib
```
both work now. Without the fix the second import fails with "../ masterlib" can't be found.
=> Fixing import path support inconsitency.

lib/pure/unicode.nim
As noticed here: http://forum.nim-lang.org/t/897/2#5781
Not sure how to handle the case of an invalid Rune. Wouldn't it be nicer to restrict the rune to be in the valid range of Unicode characters?
=> make toUTF8 support up to 6 bytes

compiler/ast.nim, compiler/evalffi.nim, compiler/parser.nim, compiler/renderer.nim, compiler/semexprs.nim, compiler/semgnrc.nim, compiler/sempass2.nim, compiler/semstmts.nim, compiler/semtypes.nim, compiler/semtypinst.nim, compiler/types.nim, compiler/typesrenderer.nim, lib/core/macros.nim, tests/misc/parsecomb.nim, tests/misc/tparsecombnum.nim
When the indentation syntax is allowed it is always interpreted as a
tuple:
type
Unit = tuple
=> interpret `tuple` as a class and `tuple[]` as the empty tuple, enable syntax for anonymous tuples

lib/system/deepcopy.nim, lib/system/gc.nim, lib/system/gc2.nim, lib/system/sysstr.nim
Capacity may be much bigger, so we end up with strings that are much
larger than they have to be and have to copy more as well.
=> Only copy strings to their size, not capacity

lib/pure/parsexml.nim
- Prevent string copies when not necessary
- Don't allocate a new XMLParser.c all the time
Inspired by this thread: http://forum.nim-lang.org/t/897/
=> Improve performance of parsexml

lib/pure/parsexml.nim
Remeasured with the string copy fix (#2255) and isn't faster anymore, so
we should opt for the simpler code again.
=> Revert my.c changes in parsexml

doc/manual/procs.txt
Otherwise these examples don't work.
=> Fix derivable objects in documentation

lib/pure/net.nim, lib/wrappers/openssl.nim, tests/stdlib/tnet.nim
So to be clear, I don't consider this complete just yet, but I'm looking for some feedback as I'm very new to Nim. This is in fact the first code I've written, so I have a few noobish questions...
- Are there forward declarations for types? I had to move the definition of `TIpAddress` to before `connect`, so that I could use it.
- `RootEffect`, is this a "base" effect? I couldn't compile the code without adding it to the `connect` method definition, and it feels kind of bad.
- The interface on the callback functions is quite poor to use and involves casts, some to deal with net.SslContext being a distinct SslCtx. Is there a way to make this any nicer to use? (See below example)
- I've got a pretty loose set of integers that should be used for the return codes of the servername callback …
=> Add SNI support to client and server sockets.

lib/pure/algorithm.nim
I thought it should be in the docs that you can do nested sorts by using a tuple as argument. 
I am also convinced that @def- is right with
> While we're at it, maybe it should be called sortedByIt because it returns the result, just as sorted, and doesn't modify it directly as sort does.
So I renamed it. I did not leave a deprecated version as it should not break any (a lot of) code since it was still new in the library anyway.
=> Better documentation and rename of sortByIt().

lib/wrappers/openssl.nim
As discussed in the [forum](http://forum.nim-lang.org/t/969) this leads to strange SIGSEGV errors on Mac OS X. As i did not discover any such issues when compiling on Linux, i thought it might be better to just add Mac OS X to the excluded platforms to fix this.
=> openssl: do not set mem functions on osx

lib/pure/times.nim
Fix for https://github.com/Araq/Nim/issues/2301. I think it is OK to do this on all systems even if it works without on linux for me. 
I found that "documented" here: http://www.win.tue.nl/~aeb/ftpdocs/linux-local/libc.archive/libc/libc-4.4.1/jumptable1/time/time_data.c
It will also work if "localtime()" was called before. So it may get initialized "by chance" before.
=> Fixes tzname on osx (and presumable bsd).

compiler/vm.nim
- Fixes #2045
- Old one: Error: conversion from unknown type to unknown type is invalid
- New one: Error: conversion from -1 to [0..255] is invalid
=> Improve error message for failed conversion in VM

lib/pure/logging.nim
writeln line on log proc for RollingFileLogger left out the substituteLog(logger.fmtStr) parameter
=> fixed writeln line on log*( logger: RollingFileLogger)

lib/system/sysio.nim
For a minimal example:
```
$ mkfifo foo.fifo
$ cat foo.nim
echo readFile "foo.fifo"
$ nim -r c foo.nim
$ echo "Hello World" > foo.fifo
```
This used to crash, now it works. Fifos have file size `-1`, just as stdin, so they have to be handled the same way.
=> Make readFile work with FIFO files

lib/pure/fenv.nim
New variable `FP_RADIX` and new templates `mantissaDigits`,
`digits`, `minExponent`, `maxExponent`, `min10Exponent`,
`max10Exponent`, `minimumPositiveValue`, `maximumPositiveValue`, and
`epsilon` added to retrieve the limits of floating-point types.
=> New templates for getting the limits of FP types added.

lib/packages/docutils/rstgen.nim
- Fixes #2269
- Keeps track of higher level section to create unique reference names
=> rstgen: Unique reference names in TOC

lib/impure/db_mysql.nim, lib/impure/db_postgres.nim, lib/impure/db_sqlite.nim
Resolving #2261
The default value for MySQL is different from the others since they seem to use different names for UTF-8.
It's been tested for MySQL and SQLite3.
For PostgreSQL it's written according to the [documentation](http://www.postgresql.org/docs/8.3/static/libpq-control.html#AEN32490) but not tested since I don't have it on my machine.
=> Add character set options when opening DB connection, default to UTF-8

lib/pure/os.nim
Installing nimble on a fresh machine I was greeted with an odd error:
```
nimble.nim(871)          nimble
nimble.nim(134)          parseCmdLine
config.nim(22)           parseConfig
config.nim(14)           initConfig
tools.nim(44)            getNimrodVersion
tools.nim(26)            doCmdEx
Error: unhandled exception: 'nim' not in PATH. [NimbleError]
Error: execution of an external program failed
```
The machine's ``$PATH`` contained a path with a tilde, so ``findExe`` wasn't able to find it despite that compiler instance being used to compile and run nimble itself.
=> Expands tildes for entries in $PATH when looking for a binary.

lib/posix/posix.nim
Entries d_type etc. were disabled on architectures other than Linux,
but also used for OS X and BSD in os.nim.
=> Fixed Tdirent definition for OS X and BSD.

lib/pure/smtp.nim
`smtp.address` should be `address`
=> Fixed typo which prevented to send mails via AsyncSmtp

lib/pure/times.nim
This fixes compilation on Linux. Other platforms should keep working as well according to their manpages.
=> Use <time.h> instead of <sys/time.h> for tzset and time_t

lib/system/gc_ms.nim
This fixes compilation with --gc:markandsweep -d:gcUseBitvectors
=> Fix proc call in gc_ms

doc/manual/procs.txt, doc/manual/types.txt, doc/tut2.txt
Not sure if we want all the `new`s in there or should add `newX` procs instead?
=> Use ref objects with inheritance in Tut2 (fixes #1817)

compiler/vmdeps.nim, tests/macros/typesapi2.nim
=> Make the symbols returned from getType() usable for that type

lib/pure/rawsockets.nim
nimdoc follows windows conditional branches and thus doesn't import posix, so ```signal``` is undefined symbol.
=> Fixed doc generation on mac.

lib/pure/collections/sets.nim
Whenever one imports sthe sets module it spits this message when compiling:
`Hint: 'sets.testModule()' is declared but not used [XDeclaredButNotUsed]`
Because that proc isn't inside the `ẁhen isMainModule`. This fixes it.
=> Fix warning about sets.testModule() not used.

lib/js/dom.nim
Changed object inheritance so that it conforms more to MDN DOM reference: https://developer.mozilla.org/en-US/docs/Web/API
Summary:
- Node inherits from TEventHandlers.
- Element inherits from Node.
- Document, Embed, Link, Form, Option, Image inherit from Element.
Small fixes:
- changed signature of addEventListener function, according to: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
- removed ```type``` and ```value``` fields from Element, as I could not find any reference on them.
- ```getElement*``` methods now return Elements, not Nodes.
=> Correct dom objects inheritance.

compiler/astalgo.nim, compiler/canonicalizer.nim, compiler/ccgcalls.nim, compiler/ccgexprs.nim, compiler/ccgmerge.nim, compiler/ccgstmts.nim, compiler/ccgtypes.nim, compiler/cgen.nim, compiler/docgen.nim, compiler/jsgen.nim, compiler/msgs.nim, compiler/pragmas.nim, compiler/rodwrite.nim, compiler/ropes.nim, lib/pure/ropes.nim
Make compiler ropes API more similar to library ropes, using library API as model, and fix a few small rope bugs here and there..
I kept away from any big rename commits, opting instead to keep the old API around, allowing a gradual change. Can easily be followed up with a separate cleanup run.
=> Comp lib ropes

lib/js/dom.nim
The main idea of the PR is to deprecate old T* names as well as their value-type semantics. Introduced new types with reference type semantics. Also some minor fixes: element-related methods return Elements, not Nodes. This PR changes the names of classes that belong to DOM-Node hierarchy only. Guess I'll do a separate PR for the rest.
=> DOM types renamed.

lib/posix/posix.nim, lib/pure/asyncdispatch.nim, lib/pure/rawsockets.nim
The right way to ignore SIGPIPEs on Mac is to setsockopt(SO_NOSIGPIPE).
=> Fixed SIGPIPE on MacOS

compiler/vmgen.nim, tests/tuples/tuint_tuple.nim
The problem was saveConstant only checked the range
`nkCharLit..nkInt64Lit`, but not up to UInt. This lead to the sonsLen
method being called, where sons was never declared.
This commit changes it to `nkCharLit..nkUint64Lit`, to match the case
statements in the type definition of TNode, in ast.nim.
=> Fixes #1986 when calling sameConstant on uint

compiler/jsgen.nim, tests/js/test2.nim
=> Fix JS codegen: proc header with compiletime arguments

compiler/parser.nim, tests/parser/tstrongspaces.nim
When #!strongSpaces is on, every operator affected by it gains priority higher than any operator not affected by it. This includes comparison operators, addition, etc. Hence the bug #1894. The way to fix it is to apply it to all operators.
It seems that counting spaces for keywords operators don't break anything in the parser. Of course, they can't have 0 spaces between their operands, but at least their precedence will work accordingly to their 1+ spaces.
I had to change one of the tests to compile, as the strongSpaces rule was extended to `and` too. I compiled some other unrelated things (including the compiler itself) and nothing seems broken.
=> Apply strongSpaces to keyword operators too. Fix #1894.

lib/impure/re.nim, web/news.txt
Fixes the split iterator, the main problem was with the incrementation
of 'last'. Last was first incremented to the index of the first
character after the match, but was then incremented again at the
beginning of the while loop. This caused a problem if that character
after the first match, also matched the regular expression. Fixes #2418
=> Fixes matching error #2418

lib/impure/re.nim, tests/stdlib/treloop.nim
Includes a test case:
```nimrod
discard """
output: "@[(, +,  1,  2, )]"
"""
import re
let str = "(+ 1 2)"
var tokenRE = re"""[\s,]*(~@|[\[\]{}()'`~^@]|"(?:\\.|[^\\"])*"|;.*|[^\s\[\]{}('"`,;)]*)"""
echo str.findAll(tokenRE)
```
=> Fix infinite loop in re.findAll

lib/system/sysio.nim
- Only on POSIX and Windows (_fgetc_nolock here) systems
- File is locked to our thread before and unlocked after readLine
- About 3 times faster in some simple tests
=> Speed up readLine by using getc_unlocked

lib/system/atomics.nim
The .importc: was referring to __atomic_compare_exchange_n this corrects
it to be __atomic_compare_exchange.
=> The importc for atomicCompareExchange is incorrectly defined.

lib/packages/docutils/rst.nim
Fixes #2538
I checked that this works, but I'm not sure if there are any side effects.
=> Make RST recognize hyperlinks with two underscores

lib/impure/re.nim
> There is an alternative regular expressions library with a more unified API: [nre](https://github.com/flaviut/nre). It may be added to the standard library in the future, instead of *re*.
Related to https://github.com/Araq/Nim/issues/2511
=> Add a hint about NRE library to 're' module

lib/pure/osproc.nim
This fixes #2552 
There is still a similar issue with `waitForExit`, but I'm not sure how to fix it best:
```nimrod
import osproc
let process = startProcess("./testing")
echo process.waitForExit()
```
=> Make peekExitCode on Posix use WIFEXITED to determine exit

lib/pure/pegs.nim
Certain `replace` examples should be replaces by `replacef`, otherwise you get things like `$1<-$2$2; $1<-$2$2`
=> Corrected code example in pegs

tests/testament/specs.nim, tests/testament/tester.nim
This allows some test to specify error location column, to ensure compiler is
generating diagnostics pointing to exactly right place of an error.
I will use that to ensure in my other PR parser generates errors pointing to the right place:
https://github.com/Araq/Nim/pull/2566
https://github.com/Araq/Nim/pull/2565
Please merge it first.
=> Tests: Optional error location column spec

lib/impure/re.nim, lib/wrappers/pcre.nim
- Version 8.36 (was 8.31)
- <del>Support for editable functions</del>
- Deprecate T,P
- Name arguments according to docs
- Cosmetics
It is largely backwards-compatible (*re* module keeps working, with some deprecation warnings, which I fixed in the 2nd commit), but some differences are present (e.g. there is an argument <del><code>ptr cuchar</code></del> `pointer` that used to be `cstring`).
All tests of *re* pass. I also tried these changes on my library that uses *re*, and all its tests passed.
I based this work on @flaviut's [PCRE wrapper](https://github.com/flaviut/nre/blob/a665279/src/private/pcre.nim).
=> Update and improve PCRE wrapper

compiler/parser.nim
1st commit make `colcom` helper more consistently used. 
2nd slightly rearranges parser's `exprList` helper proc, and fixes issue with inconsistent messages.
try # <- missing something
echo "try"
finally:
echo "finally"
> Triggers: test.nim(2, 6) Error: ':' expected
try:
echo "try"
finally # <- missing something
echo "finally"
> Triggered: test.nim(4, 6) Error: invalid indentation
=> Parser consistency

compiler/lexer.nim, compiler/msgs.nim, compiler/parser.nim, tests/parser/tinvcolonlocation1.nim, tests/parser/tinvcolonlocation2.nim, tests/parser/tinvcolonlocation3.nim
Previously parser was using lexMessage which was taking location from current
buffer position which was pointing after recently consumed token. But since
parser shows diagnostics about that token it should point to the location where
token starts.
This makes diagnostics like: `test.nim(2, 2) Error: ':' expected` point
properly at the beginning of the wrong token.
=> Parser: Fix location (line, col) for diagnostics

config/nim.cfg
When gcc path is set to  r"$nimrod\dist\mingw\bin", the compiler gives
an error:
Error : unhandled exception : invalid format string [Value Error], but
works correctly with gcc.path set to r"$nim\dist\mingw\bin". I think
this issue was caused due to the name change from nimrod to nim , but
the name change was not replicated in the config file.
=> Corrected gcc path on windows

lib/pure/math.nim
isPowerOfTwo returns true on the smallest integer, while it shouldn't on any negative integer. This patch fixes that.
echo 1 shl 63, " power of two ? ", isPowerOfTwo(1 shl 63)
->
-9223372036854775808 power of two ? true
=> fixes isPowerOfTwo returning true on the smallest integer

lib/pure/hashes.nim, tests/collections/tsets.nim
Previously, the added tests would fail to compile with errors complaining that 'hash(float)' didn't exist. The problem was that `hash(float)` was declared below `hash(tuple)` and thus wasn't visible. Rearranging things and adding a few forward declarations fixed it.
Specifically, this was the error:
```
tests/collections/tsets.nim(19, 5) Info: template/generic instantiation from here
lib/pure/collections/sets.nim(200, 20) Info: template/generic instantiation from here
lib/pure/collections/sets.nim(142, 11) Info: template/generic instantiation from here
lib/pure/hashes.nim(149, 27) Error: type mismatch: got (float)
but expected one of: 
hashes.hash(x: string)
hashes.hash(x: char)
hashes.hash(x: T)
hashes.hash(x: int)
hashes.hash(x: pointer)
hashes.hash(x: int64)
hashes.hash(x: T) …
```
=> Fix floats in tuples in HashSets

compiler/extccomp.nim
For example if gProjectName is "src/false.nim" the old static lib name was "libsrc/false.nim.a", now it is "libfalse.a".
=> Fix the lib path used with --app:staticlib

build.sh
We actually need to check for existence of csources/.git and then do git
submodule update --init, which pulls the data for submodule.
@Araq I am sorry, I totally forgot Git leaves `csources` (and any submodule dir) empty after initial clone of main repo.
=> Fixup: csources is empty after clone

compiler/cgen.nim, compiler/extccomp.nim, lib/system.nim, lib/system/arithm.nim, lib/system/chcks.nim, tests/manyloc/standalone/panicoverride.nim
With GCC and Clang this generates `__attribute__((noreturn))` in the function declaration. (both tested) With VCC `__declspec(noreturn)` is used.
=> Pass noReturn pragma to C code.

lib/windows/windows.nim
These are the out of process equivalents of VirtualAlloc and VirtualFree.  Tested on 32 bit and 64 bit environments.
=> Add procs for VirtualAllocEx and VirtualFreeEx in windows.nim

lib/pure/os.nim
The calls to lstat() and stat() were switched. As a result,
links weren't followed for followLink == true and links were
followed for followLink == false.
=> Fix behavior of os.getFileInfo() for symbolic links.

lib/pure/math.nim
Attempt at explicitly documenting the behaviour of math.gcd when arguments are floats, after a discussion on IRC.
=> Document explicitly the behaviour of math.gcd with float arguments

lib/pure/osproc.nim
Deprecated type names are still being referred to.
=> Fix osproc documentation

compiler/sigmatch.nim, tests/metatype/ttypedesc3.nim
There is no point to issue implicit `HiddenStdConv` encountering subtype of
`typedesc[Base]` parameter on overload resolution, since this will anyway never
reach codegen. This change effectively fixes compiler bug for:
~~~nim
iterator it(T: typedesc[Base]) = ...
for s in it(SubclassOfBase): ...
~~~
Where `HiddenStdConv` triggered implicit instantiation of variable of type
typedesc[Base] in `for` transform, that eventually fails at `getUniqueType`, that
refuses to work for `typedesc`.
=> Fix #2662: Don't convert subtype typedesc params

lib/pure/algorithm.nim
This _looked_ trivial. I am not certain about the argument order for the 4-argument version
fill(a, value, first, last)
vs the current
fill(a, first, last, value)
As it stands, `first` and `last` are not checked and when ``first > last`` nothing happens.
=> Fill array with same values (was issue #2462)

lib/pure/asyncdispatch.nim, lib/pure/httpclient.nim, lib/pure/net.nim, lib/pure/osproc.nim, lib/pure/rawsockets.nim, lib/pure/scgi.nim, lib/pure/sockets.nim, lib/pure/times.nim, web/news.txt
Code comments are are corrected. The `miliseconds` property of `TimeInterval` property has been changed to `milliseconds` with deprecated getter/setter procs to supported the old version.
**Breaking changes:**
Code using object initializer syntax with the `miliseconds` field will need to be updated.
The `miliseconds` parameter of the `initInterval` proc has been fixed, so any call to that proc using a named parameter will need to be updated.
=> Fixed 'milliseconds' spelling in code and docs

lib/pure/json.nim
Not marking procs as `{.inline.}` over module boundaries can have significant performance losses, I'm wondering if we can have a better solution for this.
=> Make a few json procs inline, improves performance significantly

lib/core/macros.nim, tests/macros/tgettype.nim
Since typedesc are exception in macros and they are not implicitly converted to
NimNode on macro call, we need some means to perform such conversion on demand.
Fortunately it is as simple as declaring new magic "NGetType" proc with
typedesc parameter.
NOTE: Keeping actual typedesc exception behavior is important, since it allows
passing typedesc macro parameter to other procs or macros expecting type
parameter. If typedesc parameter was implicitly converted, then we would lost
this ability.
=> Macros: Introduce typeNode(t: typedesc): NimNode

config/nim.cfg
This fixes compilation with --cc:clang and cpp.
There is still the problem that clang++ doesn't like conversions from `const type` to `type` and even `-fpermissive` (which fixed it for g++) doesn't help. See for example the rawsockets module.
=> Add -ldl with clang cpp compilation

compiler/jsgen.nim
Fix for #2696. The problem is in condition that emits comma. Comma should not be emitted, if no arguments were emitted.
=> Fixed JS call codegen, when first parameters are compile-time.

compiler/main.nim, compiler/modules.nim, compiler/nim.nim, compiler/options.nim, compiler/passes.nim
Uses "stdinfile" as the module identifier now, which prevents problems with - colliding with the minus operator. This fixes #2422 and #2702.
=> Clean up stdin file reading of compiler.

lib/pure/asyncdispatch.nim
Fixes a bug with asyncdispatch.async and discard statements with non-call params. Eg:
```nim
import asyncdispatch
proc testDiscard {.async.} =
discard "this was broken"
echo "now it's fixed"
waitFor testDiscard()
```
=> Fix asyncdispatch.async bug with discard stmt

lib/pure/algorithm.nim
Since #853 was fixed, this should work fine. The `result = @[]` was swapped to the same syntax, too.
=> Small sequence fix for algorithm.nim

lib/pure/streams.nim
Peeking (reading without changing stream position) procs implemented. That is:
```nim
var ss = newStringStream("The quick brown fox jumped over the lazy dog.\nThe lazy dog ran")
echo ss.getPosition
echo ss.peekStr(5)
echo ss.getPosition
echo ss.readStr(5)
echo ss.getPosition
echo ss.peekLine()
echo ss.getPosition
```
produces
```
0
The q
0
The q
5
uick brown fox jumped over the lazy dog.
5
```
=> Added peeking procedures to streams

lib/system/gc.nim, lib/system/gc_ms.nim
It is possible for jmp_buf to not be word-aligned or addresses
in the register dump to not be word-aligned. This can result in
either addresses in registers being missed or even addresses on
the stack past the register area not being scanned properly.
=> Fix GC scanning of registers on x86_64 architectures.

lib/system.nim
Using this config:
```
warnings:on
warning[shadowIdent]=on
warning[uninit]=on
warning[proveField]=on
warning[proveIndex]=on
warning[gcUnsafe]=on
```
You can now build a basic program with no warnings.
=> system.nim -> disabled Uninit warnings

doc/manual/stmts.txt, doc/manual/types.txt, lib/system.nim
* Corrected `noSideEffect pragma` links in lib/system (the newer documentation uses slightly different links)
* Corrected `noSideEffect pragma` in types.txt links to match the updated link names
* Minor link adjustment in stmts.txt to match the newer link names
=> Corrected various links within documentation

koch.nim, tests/testament/tester.nim
Motivation
----------
External tools need to know whether or not any test in suite failed. For
example buildbot, or packaging tool would like to stop the execution and
mark it as failed if some tests does not pass.
Modification
------------
Add `--pedantic` switch to tester program which will force it to quit
with non-zero exit code if at least one failure detected. Also update
`tests()` proc in koch to inspect result from tester and propagate it to
user.
Result
------
Nothing has changed in default behaviour. But following invocations will
exit with non-zero code if there failed tests:
./koch tests --pedantic all
./tests/testament/tester --pedantic all
Fixes #2793
=> Introduce pedantic mode for tester

lib/system/mmdisp.nim
Motivation
----------
Some linuxes (like Fedora) actually multiarch. And it means that
libgc.so.1 not always installed into /usr/lib. It is better to entrust
this job to ld and system configuration for it.
Modification
------------
Use relative path for Boehm GC on 'other' OS (and linux in particular)
Result
------
It is possible now to build nim with --gc:boehm on linux
=> Fix Boehm GC on linux

koch.nim, tools/niminst/niminst.nim
Motivation
----------
Currenly tarballs for linux created manually. ZIP files are not
suitable, because they do not preserve unix file permissions.
Modification
------------
Implement 'koch xz' command to produce dist tarball in xz format. Also
the same command implemented in niminst.nim.
Result
------
Now it is easy to create source distribution for git stapshot and use it
further in packaging scripts.
=> Implement support for XZ dist tarball

lib/pure/logging.nim
The field `fmtStr` is not accessible outside the logging module. However, this prevents user defined logger implementations from using it.
=> logging: make fmtStr public to be used in user defined loggers

compiler/ast.nim
Since ``len`` became nil tolerant, and ``^`` operator invention, a few procs may now be one-liners.
=> Minor cosmetic changes.

compiler/renderer.nim
While tinkering with JS codegen, I've noticed that renderer may crash on asm nodes. Please review carefully.
=> Fixed renderer for asm node in JS

lib/pure/encodings.nim
Problem: after building aporia on a mac, it could not be started with the error message "could not import: iconv_open" A solution to this is described in https://github.com/nim-lang/Aporia/issues/69. I did the described changes and afterwards, aporia could be started. This the PR that dom96 asked for. As far as I could see, there was no PR for this yet.
=> fix for https://github.com/nim-lang/Aporia/issues/69

lib/pure/logging.nim
newFileLogger and newRollingFileLogger have a new bufSize parameter that
is used in open(). The default value -1 has the same behavior as before.
Use 0 for unbuffered output to log file.
=> In logging.nim, expose bufSize parameter for file-based loggers

compiler/jsgen.nim, tests/js/testmagic.nim
DotDot magic did not genProc, resulting in undefined proc symbol.
=> Fixed codegen for DotDot  magic in JS

compiler/idents.nim, compiler/lexer.nim, lib/pure/etcpriv.nim, lib/pure/hashes.nim
- Unicode runes are allowed in identifers in Nim
- This aims to solve compatibility between humpStyle, snake_style and, by making EN-DASH (U+2013) magic like the former mentioned, to also allow dash–style identifiers to be used by any of the styles preferred.
- The glyph is clearly distinguishable from minus, for those who don't use the style - if they for some reason would read such code. It ties the words together in a great fashion.
- It has wide font support
- Easily typed in many OSes, otherwise easily configured via .xmodmap.
- I've compared the utf-8 encoded byte sequence directly, instead of converting to a code point and comparing. This makes the code more isolated and efficient, in line with the hotness of the code path.
- Should I add a unit-test, or is it overkill?
- There's a …
=> Feature #2811 hump, snake and now dash

lib/system.nim
The inclusivity of a..b (that it is from a <= n <= b) wasn't clear.
PR against devel this time :full_moon_with_face:
=> Added slight explanation for count{down|up}

doc/exception_hierarchy_fragment.txt
Manual contained invalid links. Index on left side of page is correct
=> Fixed Error hierarchy links in manual

lib/impure/zipfiles.nim
This fixes broken b0469c11e334e96cebe53cbe804b6a877831c85a that incompletely
reverted TZipFileStream name change
Didn't create branch as it is fixup.
=> Fixup: Reverted TZipFileStream name change

compiler/ast.nim, compiler/parser.nim, compiler/patterns.nim, compiler/pragmas.nim, compiler/semstmts.nim, compiler/wordrecg.nim
@Araq As discussed on IRC, following PR is about two things.
With new macro we can actually prevent further rewriting on marked piece of code, eg. with given example echo(...) will be rewritten just once:
```nim
template pwnEcho{echo(x)}(x: expr) =
{.noRewrite.}: echo("pwned!")
echo "ab"
```
Last commit extends parser with ability to attach pragma to inline expr using parenthesis, eg.:
```nim
template rewriteAdd{a + b}(a: expr, b: expr): expr =
({.noRewrite.}: a + b) + 1
```
Waiting for your comments.
=> {.noRewrite.} pragma for term rewriting

compiler/lambdalifting.nim, lib/pure/unittest.nim, tests/js/tunittests.nim
The reasoning behind this commit is to enable lambda lifting for JavaScript, but only for the stuff that is only compile time. Inspired by disabled js/tunittest, which is enabled in this PR. Also had to do a couple of changes in unittest.nim, among which changing writeln to echo. I'm not 100% sure about it because of Araq's comment nearby.
=> Perform lambda lifting for compile-time stuff when targeting JS.

lib/pure/asyncnet.nim, lib/pure/net.nim
Exporting newSocket(fd) mimics what asyncnet does and lets you pass in your own socket FD.
newSocket\*(fd) and newAsyncSocket\*(fd) now both take "buffered" instead of "isBuff" and defaults to true to match the other constructors on both.
=> Export newSocket(fd) from net.nim and standardize args in net/asyncnet

lib/system/arithm.nim
This only works with recent Clang and GCC 5.0.
The resulting code is about 3 times faster than the current one for overflow checks on my system. I tested this with `nim c --cc:clang -d:release --checks:on c file`:
```nimrod
var x = 10000000000.int
var y = 0
while true:
y += x
echo y
```
Currently it doesn't work because __has_builtin can't be defined.
This is totally ugly. But we can't reliably detect whether we can use
the builtins from Nim, especially with cross-compiling where the user
may be using an older compiler version. Switching this on/off manually
with a define seems weird as well, this should work automatically.
=> Use builtin overflow functions of Clang and GCC (WIP, RFC)

lib/core/typeinfo.nim
I found when using `marshal` that it would blow up if you tried to unmarshal fields that are defined on a parent object.
Example:
```nim
import marshal
import streams
type
A {.inheritable.} = object
a*: int
B = object of A
b*: int
var b = B()
load[B](newStringStream("""{"a": 1, "b": 2}"""), b)
echo($$(b))
```
This change fixes the above example, but I've no idea if this will interact terribly with other things in the stdlib.
=> Resolve base type fields in `[](TAny, string)`

lib/pure/unicode.nim
Ranges sourced from <http://www.unicode.org/Public/7.0.0/ucd/PropList.txt>_. Wikipedia also uses these ranges on its information page <http://en.wikipedia.org/wiki/Whitespace_character#Unicode>_. 0xfeff isn't included in the list, but it is a no-break space, so I guess it makes sense. 0x200b is actually a format character, but it is a zero-width space. To fit Unicode, both 0x200b and 0xfeff would be removed.
Note: this started from reading Wikipedia. Feel free to ignore if it is just plain wrong.
=> Updated whitespace ranges

doc/manual/generics.txt
I'm happy to change the wording or anything. It does seem like an important thing to mention, though. It might be better not to even mention typeless procs so as not to encourage bad behavior.
=> Note about deprecation in generics.txt

compiler/ast.nim, lib/system.nim
`-|` not used in standard library, so it is moved to ast.nim, where it's used. Fixes #2886
=> Fixes #2886 (moves compiler function into the compiler)

lib/pure/concurrency/threadpool.nim, lib/system/atomics.nim
atomics was not compiling in Visual Studio, and an assertion in threadpool was failing at runtime.  This fix *seems* to work (tested both 32 and 64-bit)
=> fixed threadpool and atomics to work with Visual Studio 32 and 64 bit

lib/pure/unittest.nim
Inspired by "failing" options.nim test, which in fact did not fail, but it's output differs from expected. The reason for it is ``unittest.nim`` writes an escape sequence to terminal upon program exit to reset the attributes. However this is not needed, because that is done by ``styledEcho`` already, and it is needed only in case of messing with attributes directly, which ``unittest.nim`` doesn't do. Oh yeah, and ``options.nim`` does not fail anymore ;)
=> Fixed unittest output.

compiler/jsgen.nim, lib/system/jssys.nim, tests/js/tcopying.nim
Copying of aggregate types will not create new objects, but reuse lvalues instead. Also added a test to demonstrate the fixed bug.
=> Fixed copying of aggregates in JS.

compiler/vm.nim, tests/macros/tnodecompare.nim
Introduces `==` operator for `TNode` next, it uses that to compare nodes for VM's `opcEqNimrodNode` (aka `==` operator from *macros* module).
@Araq This is as we discussed on IRC, nodes shouldn't be compared just pointer wise in macros.
=> Real node compare for macros

compiler/lexer.nim, tests/misc/tunsignedmisc.nim
Fixes #1179, except the `char(-1) < char(0)` which is a different beast.
Also fixes range/bounds checking on non base-10 literals.
Some general readability clean up to my previous edits.
=> Fix 1179 unsigned number literals

lib/pure/os.nim
``` Nimrod
import os
const target = "target_dir"
proc test() =
discard execShellCmd("mkdir -p source_dir")
if not target.existsDir:
discard execShellCmd("ln -s source_dir " & target)
for kind, path in walkDir("."):
echo kind, " with path '", path, "'"
when isMainModule: test()
```
Output:
```
pcDir with path './source_dir'
pcLinkToDir with path './target_dir'
```
=> Fixed #1985

compiler/msgs.nim, lib/pure/terminal.nim
This is extension to @kirbyfan64 great work, long story short:
1. File position prefix is now white bright (like in other compilers)
2. Warning/hint kind is appended, not hardcoded, and also colored in `msgWriteln`.
3. `msgWriteln` is more flexible allowing mixing text chunks with colors.
Waiting for your feedback.
=> More flexible msg colors

lib/pure/math.nim
For Windows, `rand_s` has been available since Windows XP (see https://msdn.microsoft.com/en-us/library/sxtz2fa8.aspx). It gives a better quality random number in a larger range (the max is actually `0xffffffff`). It also negates the need for the `srand` function in the Windows versions, as `rand_s` doesn't use it. 
This seems to be the simplest way to get a better random number generator, since we don't have to import `CryptGenRandom` or anything in this case.
=> Updated random functions. Fixes #2907

doc/astspec.txt
This is a start. Other updates for `macros.nim` are planned, but this at least fleshes out some of the sections.
Comments are appreciated! I'm unsure of the precedence-parsing of infix operators. It looks like that's how it works, but I'm terrible with Reverse Polish Notation, if that's what this is.
I'd prefer if someone checks this before it's committed. There's no running code here, though, so mistakes are very fixable.
=> Added some documentation

doc/tut1.txt
In section "Forward Declarations" it's easy to run into endless negative recursion by calling ```even(1)``` or ```odd(0)```. So I offer to add some border conditions.
=> Tutorial Part I update

lib/system/repr.nim
Made reprRecord go all the way up instead of just one level (wonder who wrote that code :)) and also made it deal with "," more properly (earlier a super type without fields would add a "," anyway in output) though perhaps code can be tweaked even further. Closes #2749.
=> Fixes #2749, traverse full inheritance for reprRecord

tools/niminst/buildbat.tmpl
See #18 on csources. Basically, some Windows systems have gcc as a gcc.bat file. (From what I've seen, happens with Python and GHC installations mainly.) This isn't an issue unless you're calling from another batch file (like here). The call chain will follow to gcc.bat and end there, meaning only one command is processed.
Using "CALL" before the other batch command will keep the calls in the main batch file after completion, meaning the compilation will actually succeed this way ([see technet](https://technet.microsoft.com/en-us/library/bb490873.aspx)). Otherwise you have to hope there is a gcc.exe somewhere instead.
Note this also works even if you don't have gcc.bat (gcc.exe will still work)
=> Fixed gcc batch issue

web/community.txt
The G+ Nim community is another place where discussions related to the language happen. Read and follow various articles, posts and interesting links about Nim.
=> Add G+ Nim community

doc/astspec.txt
Also gave some examples. Really the big change is to let the user know to use ``nnkRec...`` when you're inside an object.
=> More documentation of AST

doc/astspec.txt
Which was broken in #2931.
Also in separate commit, I removed trailing spaces in the file
=> Fix rest syntax in astspec

lib/pure/algorithm.nim
Linear-time verification that an openarray is sorted. Operates on the same parameters as `sort`. Seems much cheaper for large sorts, plus it seems pretty complementary to the sort procedures.
=> Added `isSorted` proc

lib/pure/asyncnet.nim, lib/pure/net.nim
(This is a new version of [pull request 2513](https://github.com/Araq/Nim/pull/2513) so it can pull from a different branch)
Some protocols involve an initial cleartext exchange before the SSL setup starts, which means having to wrap an already-connected socket. This patch adds an argument to wrapSocket() telling it to go ahead and initiate the SSL negotiation (and which side of the negotiation it's on, since SSL is asymmetric wrt the client and server).
I've tested this for both `net` and `asyncnet` but only from the client side.
=>  Add a handshake parameter to wrapSocket() to allow it to work on an already-connected socket.

compiler/jsgen.nim
This fixes a bug introduced in one of my previous PRs. Empty initialiser list produced bad JS code with extra comma in the beginning.
=> JS object initialiser fix.

contributing.rst
Due some latest changes that introduced some substantial noise in the project
history I hereby propose some general commit rules that have proven to work in
many other projects.
Both contributors and maintainers (accepting PRs) are obliged to follow this
rules, for sake of the Nim project and good collaboration.
=> Contributing: Introduce some general commit rules

compiler/commands.nim, doc/advopt.txt
Since we introduced automatic colors on terminals (via isatty) there is no way
to turn it off, since (undocumented) --useColors just turns them on.
This replaces --useColors with --colors:on|off, so anyone who prefers
non-colored compiler messages may now turn it off now.
=> Change --useColors to --colors:on|off and add help

lib/pure/math.nim
Along with a brief example for sign demonstration. Modulo for floats can change based on implementations, but since Nim does the calculation explicity, we know some things for certain; hence the documentation
=> Added documentation for mod

doc/manual/type_rel.txt
Simple example to demonstrate overloading in case technical lingo is confusing
=> Added example for var overloading

lib/posix/posix.nim, lib/pure/asyncdispatch.nim, lib/pure/asyncnet.nim, lib/pure/rawsockets.nim
As suggested in https://github.com/nim-lang/Nim/issues/2003 by Dominik, opening a new PR.
This default change by itself made basic async sockets work in dualstack with e.g. Jester, but by looking at asyncdispatch.nim, such a default change would have impacted connect() and acceptAddr() - both of which still use Sockaddr_in which is IPv4-only.
I've fixed it to work with dualstack, as well as to be backwards compatible in case one uses IPv4-only addresses. I did *not* touch the Windows copy of the code, that part still will be IPv4-only, and will need additional fixes.
I did not write the tests within the modules, used the small test programs within the https://github.com/ayourtch/nim-net-tests.
=> Ipv6 devel - add IPv6 support for asyncsockets, make AF_INET6 a default

doc/manual/types.txt
It's mentioned for enums, for example, but it should probably be explicit in the string section
EDIT typo
=> Added `$` documentation to the manual

doc/astspec.txt
Addresses #2929 . Still mentions ``nnkRange`` as being used internally (really, ``nkRange`` is). I'm not sure what ``nnkRange`` does, but the docs now inform the user to use ``..`` as an infix operator.
=> Updated nnkRange docs. Fixes #2929

doc/astspec.txt
Fixes #2939 to show that the default ``float`` is actually ``float64``. Easy to change if this behavior switches.
=> Clarified nnkFloat64Lit. Fixes #2939

compiler/sigmatch.nim, tests/generics/mgenericprocmatcher.nim, tests/generics/tgenericprocmatcher.nim
Please review tests, so far thats what i came up with.
=> Fixes #3022

lib/wrappers/sqlite3.nim
The old dynlib name referenced an ancient version of SQLite3 and could
not be overridden with --dynlibOverride.
=> Fix SQLite3 dynlib on OS X.

lib/pure/asyncftpclient.nim, lib/pure/ftpclient.nim
Many ftp servers can respond with multiple line 220 messages after connection and this procedure will fail because when sending user friendly command will receive still 220 welcome message. With this, these two libraries will check first multiline 220.messages then will send user and pass command if defined.
=> Allow ftpclient and AsyncFtpClient to handle 220 Multiline messages

contributing.rst
Do not merge until capitalization is decided on.
Part of this depends on #3034 (currently, ``nim doc`` duplicates forward declarations). This doesn't address periods at the end of the documentation. It tries to follow the "capitalize if a full sentence" rule, but says both are fine.
I can make this more detailed easily, but one of Nim's issues is not having enough documentation and examples, so hopefully this will help out contributers.
Should I say that documentation is mandatory for new code? I assume that contributers can read the manual for where to place the ``##`` in different cases.
=> Added documentation guidelines (brief)

lib/pure/algorithm.nim
The proc *algorithm.reversed* seems to be able to accept *first* and *last* (:Natural) args.
But IndexError is raised when first is not 0.
See also http://forum.nim-lang.org/t/1391
=> Fix algorithm.reversed to accept non-zero 'first' arg

compiler/cgen.nim, compiler/commands.nim, compiler/extccomp.nim, compiler/main.nim, compiler/msgs.nim, compiler/nim.nim, compiler/nimblecmd.nim, compiler/nimconf.nim, compiler/options.nim, compiler/passaux.nim, compiler/rodread.nim, compiler/syntaxes.nim, doc/advopt.txt
This PR extends flexibility manipulating notes (warnings, hints) via command line. This PR does not change any existing behavior, so notes are displayed at exactly same verbosity levels as before.
1. Some notes were enabled explicitly for some verbosity levels, so
`--hintName:on` has no effect if verbosity level was too low.
2. Verbosity level for notes is not longer scattered across the source code,
instead if now lives in `msgs.nim` `NotesVerbosity` array
3. Individual note settings have stronger effect than verbosity setting,
so `--hintName:off` will disable hint regardless of high verbosity setting,
and vice-versa `--hintName:on` will enable hint even on low verbosity setting.
4. Added command line `--warnings/hints:list` that allow list and check status
of individual notes.
=> Note verbosity specified in one place & --warnings/hings:list

lib/pure/times.nim
Complements `getDaysInMonth`. Also changed the documentation to match the new proc ("amount" is usually reserved for indefinite/uncountable nouns)
=> Added `getDaysInYear` proc

doc/pegdocs.txt
Otherwise gives "$2: $1; $2: $1"
=> `replace` -> `replacef`

lib/pure/unicode.nim
In reference to #2353, but didn't use the name `runes` (just to avoid confusion with the iterator). Can change whatever. Also put documentation into imperative, capitalized form. Also added some missing periods. I think that's it.
To the trailing periods: do these go there or not? Maybe we could do: put periods if there is more than one sentence.
=> Added new Rune sequence proc

lib/system.nim
Exposes the name of all exceptions to be accessed by code since it's not currently possible to get the runtime type of an exception.
=> Expose the name of an exception.

compiler/main.nim, compiler/msgs.nim
Otherwise when using `nim -r c file` the output will be colorized because of the final `[SuccessX]`.
=> Reset terminal colors before running compiled program

doc/lib.txt, lib/core/unsigned.nim, lib/system.nim
This should lead to less confusion because uint numbers and literals seem to work, but operators are just missing.
Not sure if this is wanted, this just seems like a common gotcha.
=> Move unsigned int operations to system module

lib/pure/net.nim, lib/pure/os.nim, lib/pure/rawsockets.nim, lib/pure/sockets.nim
Fixes #2573.  Uses the new `raiseOSError`  to preserve any additional error message (say, from `gai_strerror`) while making sure that we assign an integer error value (usually from `osLastError()`).
Based on earlier PR made by @HaCk3Dq.
=> Use raiseOSError with additionalInfo parameter from devel

lib/pure/httpclient.nim
Otherwise we always have a Content-Type in the header, even if no multipart is specified.
=> Fix async httpclient post to work without multipart

compiler/options.nim, tests/vm/tslurp.nim
Fix for the issue with absolute paths in staticRead described here: http://forum.nim-lang.org/t/1010/ and here: https://github.com/nim-lang/Nim/pull/2303
=> Added absolute path support to options.findFile

lib/pure/unittest.nim, tests/stdlib/tunittest.nim
Couple of things:
- document unittest.nim and thus fix #460
- make `require` agree with prior stated doc/intent: if `require` fails we directly exit, do not pass go and do not collect 200$.
- `expect` will now fail gracefully if an exception is not thrown AND/OR if an unexpected exception is raised.
- first patch in a set of at least another patch
I tried to follow some of the documentation guides:
- https://github.com/nim-lang/Nim/blob/devel/contributing.rst
- https://github.com/nim-lang/Nim/issues/3089
Please review! I would love it if *all* the Nim documentation was consistent
and felt as though it was written by the same person.
Discussion points/next patch:
- `testSetupIMPL` and `testTeardownIMPL` are public right now, but I don't think they
should be. We should deprecate their …
=> document unittest.nim + code agreement

lib/pure/asyncdispatch.nim, tests/async/tasyncconnect.nim, tests/async/tasynceverror.nim
And handle I/O errors in callbacks instead, so that exceptions can be raised from `send(...)` and `recv(...)`.
=> Ignore EvError in `asyncdispatch.poll(...)` for non-windows systems

lib/pure/httpclient.nim
Ensure the correct destination hostname is used in the request, otherwise the request will fail in one of a number of interesting ways when using a proxy.
Fixes https://github.com/nim-lang/Nim/issues/3166
=> Set correct Host in request header

lib/packages/docutils/rstgen.nim
Saw in https://github.com/nim-lang/nimforum/issues/41 that there was an
issue in rendering inline images.  Traced back through rstgen and found
that it was not counting something like:
`.. image:: http://i.imgur.com/oCem13Y.png` as valid since it contained
a period, and this wasn't in the set of valid characters, so the empty
string is returned by default.
Added a period to the allowable characters, and now renders correctly.
Test case:
```{nimrod}
import rst, rstgen, strtabs
var docConfig: StringTableRef
docConfig = rstgen.defaultConfig()
docConfig["doc.smiley_format"] = "/images/smilieys/$1.png"
proc rstToHtml(content: string): string =
result = rstgen.rstToHtml(content, {roSupportSmilies,roSupportMarkdown},
docConfig)
var a: string = rstToHtml(".. image:: …
```
=> Fix for inline image in rstgen (nimforum #41)

contributing.rst
The documentation style guide was renamed from `styleguide.rst` to `docstyle.rst` in https://github.com/nim-lang/Nim/commit/a98f609ae215d1fcf9922329b5d87bd1b9242800 but this reference was not updated in that comment.
=> Fix documentation style reference

lib/pure/unittest.nim, tests/stdlib/tunittest.nim
A recent change to the unit test module introduced a local variable to the `require` template. Because `require` is marked as `dirty`, require can no longer be used multiple times in a test. You can see a failed build here:
https://travis-ci.org/Nycto/RBTreeNim/builds/67225776
It look like `require` doesn't need to be dirty, so this change simply removes that pragma and adds a test to ensure this doesn't break again.
=> Unittest module: Fix multiple requires in a test

lib/pure/times.nim
Fills in the missing functionality of decoding Time to TimeInfo and TimeInterval, whilst also adding some procs to work with leap years and to get the day of the week based on a date.
=> Procs to decode Time to TimeInfo & TimeInterval

lib/pure/asynchttpserver.nim
The proc `parseHeader` of asynchttpserver module, parse "GET /path HTTP/1.1\r\Lname\r\L\r\L" will be error.
=> Modify proc asynchttpserver.parseHeader

compiler/ccgstmts.nim, compiler/cgen.nim, lib/nimbase.h, lib/posix/termios.nim, lib/system/debugger.nim
The main reason for this PR is to fix nimgrep test. I'm not sure if --debugger:on works correctly now, but at least it compiles, and nimgrep test succeeds.
Also removed c_line from termios struct. Haven't found it in MacOS and Linux headers, nor in references. If anyone knows what that means, please explain.
=> Fixed --debugger:on option. Removed c_line from termios.

lib/pure/math.nim
The exponentation implementation unnecessarily multiplied the
result with itself at the end if the exponent was an even number.
This led to overflow if result*result > high(int).
=> Fix exponentiation operation to avoid overflow.

compiler/jsgen.nim, compiler/semmagic.nim, lib/system/jssys.nim, tests/js/taddr.nim
Untyped pointers have changed their semantics in JS. Now they are treated as etyBaseIndex, and not as int. This change required to use a different pseudo-type in jssys.nim that has int semantics.
Also addr operation adds sfAddrTaken flag, that fixes another issue, demonstrated in the test.
=> JS: Untyped pointers codegen changed. addr expression fixed.

lib/pure/unittest.nim, tests/stdlib/tunittest.nim
- failed checks cause identifiers and calls to print out their values
- testSetupIMPL and testTeardownIMPL are not awkwardly public anymore while preserving setup and teardown!
=> other unittest pull-request

lib/system.nim, lib/system/sysio.nim
Solves #3084. I ran the tests by @scriptum on my machine:
```
Time [s]
C          0.078
Nim New    0.084
Py2        0.128
Py3        0.271
Nim Old    0.418
```
Problems:
- This drops compatibility with pure CR line endings of old Mac systems.
- When the lines contain '\0' chars, this currently doesn't work properly. Not sure how to fix this, since `fgets` doesn't report the number of bytes read.
=> Improve performance of readLine by using fgets

compiler/sigmatch.nim, tests/metatype/tprocbothmeta.nim
The motivation for this change is to enable ``map(mySeq, x => $(x+1))`` syntax. Unfortunately there is still an outstanding issue for ``auto`` (see https://github.com/nim-lang/Nim/issues/3224) which is used in ``x => $(x+1)``, therefore the expression ``map(mySeq, x => $(x+1))`` still won't work. However, the example below works with generics without providing any types.
I tried not to increase the complexity of the code more than needed.
Thank you, Peter
```nim
proc myFun[A,B](x: A): B =
result = float(x+10)
proc myMap[T,S](sIn: seq[T], f: proc (q: T): S): seq[S] =
result = newSeq[S](sIn.len)
for i in 0..<sIn.len:
result[i] = f(sIn[i])
assert myMap(@[1,2,3], myFun) == @[11.0, 12.0, 13.0]
```
=> extending metatype matching in sigmatch.nim

lib/wrappers/odbcsql.nim
SQLPrepareW and SQLExecDirectW are needed to use unicode as otherwise ODBC only recognises ansi codepages in SQL strings.
=> Add widestring versions of SQLPrepare and SQLExecDirect

lib/system/endb.nim
lib/system/endb.nim
bug fix: Switch state to dbgSkipCurrent for Eval, Local & Global commands.
This avoids stepping into the endb code if previous command was single step.
Other two changes are trailing whitespacespace removed.
=> lib/system/endb.nim bug fix: Switch state to dbgSkipCurrent for Eval, Local & Global

lib/pure/times.nim
Previously countYears & countDays procs were not public, but there were unused,
causing unnecessary warnings generated by standard library.
Since these procs seems to be useful it is better to just export them than
remove them completely. Also turning inline comments into proper documentation.
This is hotfix for PR #3114 which introduced 2 unused private procs, causing warnings generated whenever we use anything related to `times` module.
@dom96 @coffeepots Please have a look at that. Thanks.
=> times: Export & document countLeapYears/Years/Days

compiler/semmacrosanity.nim, compiler/vm.nim, compiler/vmgen.nim, compiler/vmmarshal.nim, compiler/vmops.nim, web/news.txt
VM will now produce nkObjConstr nodes for objects instead of nkPar nodes.
Fixes #3272.
=> VM produces objects.

compiler/msgs.nim
One reference to the old warning DifferentHeaps was missed in dc047931bbde432512053c91d0cb9b8a230a7574.
=> Replace incorrect warning string.

lib/pure/oids.nim
For now Mongo Object IDs cannot be compared directly as values, because all fields are private, and the only way to compare those are comparing their string representation, like:
```
$oid1 == $oid2
```
This PR adds `==` operator that adds compare behaviour to oids
=> Added == operator for comparing two Object IDs

lib/pure/net.nim, lib/pure/rawsockets.nim
This patch implements procedures getLocalAddr() and getPeerAddr() that
return the results of getsockname() and getpeername(), respectively, as
pairs (string, Port) for both Socket and SockedHandle.
Note: this does not currently fully work on Windows, because there's no support in `winlean.nim` for `inet_ntop()` and `getpeername()`.
Also, I am not certain if the procedure names should be changed; they do not reflect the underlying Unix convention, but the Unix names are not all that informative, either.
=> Provide access to getsockname()/getpeername() [WIP]

lib/pure/json.nim
Reasoning: JS doesn't make difference between ints and floats, when float doesn't have fractional part.
```js
JSON.stringify([1.0, 2.5])
// Output: '[1,2.5]'
```
With Nims JSON parser the node types will be [int, float]. That's not really handy.
=> Transparently coerce int to float in JsonNode.getFNum

lib/pure/asyncdispatch.nim
Close file descriptor before `selector.unregister`, therefore `epoll_ctl(s.epollFD, EPOLL_CTL_DEL, fd, nil)` will be failed. When there are large requests, sometimes it will raise an error (assert fail):
**not selectorKey.fd != 0.SocketHandle**
=> Fix proc closeSocket (posix): bad file descriptor error

lib/pure/future.nim, tests/generics/tmap_auto.nim
Made ``map(@[1,2,3], x=>x+10)`` working without TypelessParam warning. Added a simple test.
=> fixing TypelessParam warning in x=>x+1, added test

lib/pure/net.nim, lib/pure/sockets.nim
I'm using OSX 10.11 El Capitan and currently see an error when using `nim`@`devel` with ssl (for example with `nimble`):
```
$ ./nimble
could not import: SSLv2_method
```
OSX 10.11 does not ship with openssl, and I have openssl 1.0.2d installed via homebrew in /usr/local. I guess this version no longer ships with ssl2?
This PR avoids referencing the undefined symbol on OSX, similar to the way it was already being done for linux. I tried to use `defined(SSLv2_method)` but that didn't work.
cc https://github.com/nim-lang/nimble/issues/142
=> Avoid referencing undefined SSLv2_method on MacOSX

lib/pure/memfiles.nim, tests/stdlib/tmemfiles1.nim, tests/stdlib/tmemfiles2.nim
Added extra condition on windows close so if already closed it
doesn't throw an exception.  Identified from #3315
=> bug fix: close() only unmapViewOfFile when fHandle is valid.

lib/posix/kqueue.nim, lib/pure/selectors.nim
This improves networking support for OS X & Free/Open/NetBSD systems usign `kqueue` API, that is somehow similar to epoll - currently present for Linux flavor.
It was tested on OS X 10.10.5 and confirmed to work with `asyncnet` and `asynchttp` examples.
=> kqueue support for OS X and Free/Open/NetBSD

compiler/vm.nim
Previously trying to convert constant of enum type, where this enum type has no
entry with given constant position leaded to "internal error: opConv for enum".
Instead of producing error, now we gracefully convert it to "EnumType position".
This solves internal error in following code:
```nim
import macros
macro dumpNotImm(st: stmt): stmt =
echo st.treeRepr
st
dumpNotImm:
proc clos(x: int): int =
proc addOne: int =
x + 1
addOne()
```
This internal error was caused by `NimNodeKind` containing only "public" node kinds, where helper internal node kinds coming from `TNodeKind` were generated for iterators, but since macros were trying to treat them as `NimNodeKind` it was failing on `nkClosure`.
=> vm: Don't fail on unknown enum position to string

tests/testament/categories.nim, tests/testament/tester.nim
Adds a new `run` option to the tester:
```
Command:
all                         run all tests
c|category <category>       run all the tests of a certain category
r|run <test>                run single test file
```
This makes it much easier to reproduce CI failures and to iterate on a single test/feature during development.
```
$ tests/testament/tester r tests/pragmas/tbitsize.nim
FAIL: tbitsize.nim
Test "tests/pragmas/tbitsize.nim" in category "pragmas"
Failure: reCodegenFailure
Expected:
\i @'unsigned int flag:2;' .*
Gotten:
$ tests/testament/tester r tests/pragmas/tbitsize.nim
PASS: tbitsize.nim
```
=> Allow testament/tester to run single file

compiler/ast.nim, compiler/ccgtypes.nim, compiler/pragmas.nim, compiler/wordrecg.nim, doc/manual/pragmas.txt, tests/pragmas/tbitsize.nim, web/news.txt
cc https://github.com/nim-lang/c2nim/pull/53
``` nim
type
bits* = object
flag* {.bitsize: 1.}: cint
opts* {.bitsize: 4.}: cint
```
``` c
struct  bits95004  {
int flag:1;
int opts:4;
};
```
=> Implement bitsize pragma for bitfields

compiler/extccomp.nim, lib/pure/osproc.nim, tests/testament/tester.nim
This callback also lets us get rid of the "rerun with --parallelBuild:1` error message.
For example, with:
```
$ cat compilefail.nim
{.emit:"invalid".}
```
Before:
```
$ nim c compilefail.nim
Hint: system [Processing]
Hint: compilefail [Processing]
CC: compilefail
Error:  execution of an external program failed; rerun with --parallelBuild:1 to see the error message
$ nim c --parallelBuild:1 compilefail.nim
Hint: system [Processing]
Hint: compilefail [Processing]
/private/tmp/nimcache/compilefail.c:10:1: error: unknown type name 'invalid'
invalid
^
/private/tmp/nimcache/compilefail.c:11:1: error: expected identifier or '('
static N_INLINE(void, initStackBottomWith)(void* locals);
^
2 errors generated.
Error: execution of an external program failed
```
After this patch, `--parallelBuild:1` …
=> Add afterRunEvent callback to execProcesses()

lib/pure/rawsockets.nim
Currently due bug in FreeBSD passing AI_V4MAPPED to addrinfo.ai_flags causes
getaddrinfo to fail with EAI_BADFLAGS ("Invalid value for ai_flags"). That's
why we should disable this flag for now on FreeBSD.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198092
=> rawsockets: Fix getaddrinfo on FreeBSD

bootstrap.sh, install.sh.template, koch.nim
This solves problem where bootstrap was simply copying `./install.sh.template`
into `./install.sh`. Then first call of `./install.sh` was calling `./koch install`
that was running extra compilation and overwriting `./install.sh` with new
content.
This was overcomplicated, and also caused first `sudo ./install.sh DIR` to run
compilation under root account, leaving root owned files in working directory.
Now bootstrap calls `./koch geninstall` that just generates `./install.sh`
without calling it. This `./install.sh` is FINAL one, and running it does not
generate any files aside passed DIR. This makes whole process simpler.
=> Generate install.sh during bootstrap

doc/lib.txt, lib/deprecated/pure/ftpclient.nim, lib/deprecated/pure/rawsockets.nim, lib/deprecated/pure/sockets.nim, lib/pure/asyncdispatch.nim, lib/pure/asyncnet.nim, lib/pure/httpclient.nim, lib/pure/nativesockets.nim, lib/pure/net.nim, tests/async/tasyncawait.nim, tests/async/tasyncconnect.nim, tests/async/tasynceverror.nim, tests/cpp/tnativesockets.nim, tests/macros/tgensym.nim, tests/modules/texport.nim, web/news.txt
This change was done to avoid confusion with TCP/IP raw sockets. Native sockets
module represents handling native system low level socket API in general and is
not just limited anyhow to TCP/IP raw sockets.
=> Rename rawsockets module to nativesockets

lib/pure/strtabs.nim
Not sure if this is the best fix.
It all resolves around the `[]=` proc calling `rawInsert()` 
which is changing the     `data: KeyValuePairSeq`
within the `ref StringTableObj`
```
KeyValuePairSeq = seq[KeyValuePair]
StringTableObj* = object of RootObj
counter: int
data: KeyValuePairSeq
mode: StringTableMode
StringTableRef* = ref StringTableObj ## use this type to declare string tables
```
=> fix #3416 strtabs clear() and []=

examples/maximum.nim, lib/pure/collections/sequtils.nim, lib/system.nim, tests/closure/tclosure4.nim, tests/collections/tapply.nim, tests/collections/tmapit.nim, tests/generics/tinferredgenericprocs.nim, tests/generics/tmap_auto.nim, tests/overload/toverprc.nim, tests/parser/tcommand_as_expr.nim, tests/stdlib/tunittest.nim, tests/template/twrongmapit.nim, web/news.txt
Renamed ``repeat(seq[T], Natural)`` to ``cycle(seq[T], Natural)``.
For example: ``cycle(@[1,2,3], 2) == @[1,2,3,1,2,3]``
Introduced ``repeat(T, Natual)``.
For example: ``repeat(5, 3) == @[5,5,5]``
Moved ``map(...)`` functions to *sequtils.nim*. Fixed tests to include *sequtils.nim*.
Renamed ``map(var seq[T], proc(var T)`` to ``apply(var seq[T], proc(var T))``, and corresponding ``mapIt`` to ``applyIt``.
Introduced ``apply(var seq[T], proc(T): T)``
Simplified ``filter(..)``'s implementation, no extra call of ``accumulateResult``.
Replaced ``seq1[pos] = seq1[i]`` to ``shallowCopy`` in ``keepIf`` and ``keepItIf``, mimicing ``del(...)`` in *system.nim*.
Removed {.immediate.} pragma from ``filterIt`` and ``mapIt`` templates. All test passed (which passed before).
Added length check to …
=> Break sequtils

lib/pure/unittest.nim
Consider the net test suite:
```nim
suite "Test allocation":
setup:
var p = cast[ptr int](alloc(sizeof(int)))
test "test working with manually allocated int":
p[] = 10
check(p[] == 10)
tearDown:
dealloc(p)
```
In case the `tearDown()` is called when it is in a `finally` code block: you will receive an error, because variable `p` cannot be accessed, and we cannot `dealloc` memory for it.
The same problem appears when testing other resources like files/DBs/sockets, etc...
=> Moved teardown call to try block for namespace access reasons

readme.md
Previously clicking on that icon was opening just the icon image in new browser
window, which is default behavior - not very useful in our case.
=> readme.md: Open builder page from its status icon

compiler/importer.nim, lib/pure/collections/critbits.nim, lib/pure/collections/sets.nim, lib/pure/collections/tables.nim, lib/pure/strtabs.nim, lib/pure/xmltree.nim, lib/system/sets.nim, tests/actiontable/tactiontable.nim, tests/collections/ttables.nim, tests/collections/ttablesref.nim, tests/misc/teventemitter.nim, tests/stdlib/tmget.nim, tests/stdlib/tmitems.nim
- In sets, tables, strtabs, critbits, xmltree
- This uses the new var parameter overloading
- mget variants still exist, but are deprecated in favor of `[]`
- Includes tests and fixed tests and usages of mget
- The non-var `[]` now throws an exception instead of returning binary 0 or an empty string
=> Rename mget to `[]`

compiler/installer.ini
Adds a line to the installer's ini file for a new download option: installing support dlls.
=> Added DLL download to installer

lib/pure/concurrency/threadpool.nim
This adds the ``isReady`` procedure which returns ``true`` if the specified ``FlowVarBase`` can be awaited without blocking.
=> Implement isReady procedure in threadpool module.

compiler/msgs.nim, compiler/vm.nim, lib/pure/terminal.nim, tests/testament/tester.nim
Previously we were defaulting to stdout for diagnostics, which could interfere
with scripts or `nim c -r' programs outputting their results to stdout,
possibly mixing their output with compiler messages.
This change makes now Nim to be inline with other compilers emitting
diagnostics to stderr. Also now --stdout option has proper meaning making all
diagnostics to be sent to stdout instead.
The PR also extends terminal module to work with both stderr, stdout (or any other handle on UNIX), making procs assuming stdout deprecated.
=> Extend terminal module, use stderr for Nim compiler diagnostics by default

lib/system/dyncalls.nim
So elif defined(mac) has absolutely no effect, also this block uses some legacy
discouraged NSCreateObjectFileImageFromFile function.
=> system/dyncalls: OS X is already handled as posix

compiler/commands.nim, compiler/main.nim, compiler/msgs.nim, compiler/vm.nim
1. One `msgWriteln` with optional flags instead of `msgWriteln`, `outWriteln` and `stdoutWriteln` doing essentially the same.
2. Always write usage to stdout. Usage is compiler command output, not diagnostics, so we shall output it to stdout. Also this makes: `nim -h | less` or `nim -h | grep ...` working.
=> Simplify msg API and always use stdout for help/usage

lib/pure/json.nim
Javascript uses UTF-16 as its internal representation of strings,
so JSON does so as well. This means that we could have surrogate
pairs, with codepoints above 0xFFFF that take 2 ecape codes to
decode. Also adds tests to detect this in the future.
=> Make sure the json module decodes UTF16 correctly

lib/wrappers/openssl.nim
Currently Nim search only for `libcrypto.so(.10|.1.0.1|.1.0.0|.0.9.9|.0.9.8)` . On gentoo with installed libressl there is created `libssl.so.35.0.0` and `libcrypto.so.35.0.0` with symlinks from `libssl.so` and `libcrypto.so`.
=> Add serach for libssl.so without version suffix.

tools/niminst/buildsh.tmpl
Rather than issuing echo "cmd..." then cmd... itself, we enable shell trace
facility via set -x, which is POSIX shell standard command and is compatible
with all UNIX shells.
This effectively cuts build.sh size twice, since we don't need to double stuff
there, also making it human readable.
We are also setting PS4 (trace prefix) to none, instead final echo "SUCCESS",
we issue : SUCCESS command which outputs its contents in trace.
=> Patch/smaller build.sh using trace

lib/pure/encodings.nim
I am not sure since which version OS X does include the libiconv library without the `lib` prefix. But it seems this is the case for some years now. If there are ways to check for the OS X version at compile time this may be needed to support older OS X versions. But I guess thats not needed for most users working with Nim anyway.
=> Removed libiconv prefix (on OS X) to make encodings compile on OS X.

compiler/installer.ini
Without stdlib.nimble in libs directory Nimscript is not work properly. I.e. switch is not working and maybe other things.
Faced with problem: if i use "nim c file.nim" there is no nimscript effects. But if i use "nim_working_copy/bin/nim c file.nim" all works fine.
So, i found that stdlib.nimble is needed in lib directory for nimscript.
Maybe lib/*.nimble is excessive. Or maybe there is more deep error why .nimble file is needed in lib. But now nimscript works fine for me.
=> Install stdlib.nimble in lib for nimscript fix

lib/pure/osproc.nim
When `startPorcess()` by `poParentStreams`, `close(p: Process)` will close stdin stdout stderr of parent process.
```nim
import os, osproc
if existsEnv("CHILD_ID"):
echo "child process running"
else:
putEnv("CHILD_ID", "1")
var prc = startProcess(paramStr(0), options = {poParentStreams})
echo "child exit ", waitForExit(prc)
close(prc)              # This will close stdin stdout stderr of parent process!
echo "!!! child close"  # Parent stdout has been closed !!!
while true: sleep(1000)
```
=> Fix osproc.close

lib/impure/db_postgres.nim, tests/untestable/tpostgres.nim
The problem #3513 was in wrong `setupQuery` realization: we can't call the same query twice
=> Fixed issue 3513: wrong setupQuery realization

lib/pure/parseopt2.nim
Prevents collisions between those C externalized procedures in parseopt and parseopt2.
=> Prevent Exported C procedure collisions

lib/system/dyncalls.nim
Maintainers of win32 DLLs can opt to provide libraries with
'decorated' function names (Google "stdcall name decoration").  To
pull a function pointer out of one of these DLLs, you have to pass a
decorated name to getProcAddress.  This is painful for the authors
of NIM DLL wrappers - they have to pass manually-decorated strings
to "importc", but only on win32.
This commit adds auto-decoration to nimGetProcAddress.  This function
will probe the DLL for the undecorated name, and if that fails, it
will automatically add decoration and try again.  That way, the author
of the wrapper doesn't have to deal with it.
=> Add 'auto-decoration' to nimGetProcAddr

lib/pure/strutils.nim, tests/stdlib/tstrutil.nim
a, b must both be indexed starting from s after the common
prefix "strip" phase.  This resolves issue 3477:
https://github.com/nim-lang/Nim/issues/3477
=> Fix loop index bug in scan for a[s] in b[s..s+len2-1].

compiler/ccgexprs.nim
If ``slurp`` is used like this:
```nimrod
let s = slurp"test.txt"
```
, the compiler fails with stacktrace:
```
nim.nim(107)             nim
nim.nim(71)              handleCmdLine
main.nim(251)            mainCommand
main.nim(63)             commandCompileToC
modules.nim(221)         compileProject
modules.nim(169)         compileModule
passes.nim(203)          processModule
passes.nim(137)          processTopLevelStmt
cgen.nim(1217)           myProcess
ccgstmts.nim(1116)       genStmts
ccgexprs.nim(2068)       expr
ccgstmts.nim(1116)       genStmts
ccgexprs.nim(2068)       expr
ccgstmts.nim(1116)       genStmts
ccgexprs.nim(2065)       expr
ccgstmts.nim(502)        genBlock
ccgexprs.nim(2068)       expr
ccgstmts.nim(1116)       genStmts …
```
=> Fixed SIGSEGV on wrong slurp usage

doc/tut1.txt
Wrap the code inside a code block. The declaration for ``proc even(n: int): bool`` is present twice. Hence removed one and wrapped it in a separate code block.
=> Wrap the example in a code block

lib/pure/unicode.nim
unicode.validateUtf8() currently does not check for overlong ASCII representations, which start with 0xc0 or 0xc1 and are longer than neccessary
They are illegal according to the standard.
This introduces a simple check if the rune starts with co or c1.
=> validateUtf8: catch overlong ascii

lib/system.nim
The example in the documentation for `low()` uses `high()` where it looks like it was supposed to use `low()`.
=> Using low() instead of high() in example for low() procedure

compiler/ccgexprs.nim
Set operations used "1<<n" style shifts, which led to undefined
behavior if the signed shift overflowed. Similarly, the right-hand
side of the operator sometimes used a mix of signed and unsigned
integers that were combined with "&". This patch attempts to provide
a consistent implementation that uses unsigned integers everywhere.
=> Avoid signed shifts and bit operations for sets.

lib/system/dyncalls.nim
Make Nim give more detailed error messages when compilation fails. This is related to the comment about needing to uncomment `lib/system/dyncalls.nim` to get the error from the compiler:
https://github.com/nim-lang/Nim/issues/2408 . I ran into the same issue while trying to write a wrapper for a C library and that detailed error message helped me figure out quickly what I need to add. 
Unfortunately, I don't run windows so this pull request won't have any effect there. The docs for getting the error message are here: https://msdn.microsoft.com/en-us/library/windows/desktop/ms680582(v=vs.85).aspx 
I'm not really sure how to test this, so any pointers there would be welcome!
=> Print out more detailed error messages when compilation fails

lib/pure/nativesockets.nim
According to `man getaddrinfo`, `AI_V4MAPPED` should be passed along with `AF_INET6` `ai_family`. I suppose invalid use of `AI_V4MAPPED` may lead to platform-dependant behaviour. E.g. on Android `getaddrinfo` would just fail.
=> Fixed getAddrInfo on android

lib/pure/redis.nim
Fixing  too many open files on quit command with an explicit socket close, and importing the net module
=> Explicit socket close, and importing the net module

lib/core/typeinfo.nim, lib/nimbase.h
This is an alternative attempt to fix issue #2841 in a way that does not
rely on non-standard C compiler behavior.
The underlying problem is that the typeinfo module includes
system/hti.nim, but system/hti.nim is also included by system.nim. The
result is that the compiler at any given point has two instances of
TNimType with the same external name and will generate code either for
one or both of them. Code generation for the second version is normally
suppressed by using {.importc.}, but that results in a missing type
declaration for modules that only use the second version. This happens
for modules that import typeinfo, because the the second component of
typeinfo.Any has type PNimType = ptr TNimType, which generates a
"TNimType *" struct member.
The previous solution was to have a …
=> Fix code generation issues with TNimType.

lib/wrappers/mysql.nim
FIELD had the wrong size which made mysql.fetch_fields() useless.
=> Fixing mysql_field.

lib/pure/nativesockets.nim
Based on the comment right above this was just a mistake for OpenBSD. I checked NetBSD and it also doesn't compile with `AI_V4MAPPED`.
=> Fix nativesockets compilation on OpenBSD

lib/pure/osproc.nim
Same as MacOSX and FreeBSD, NetBSD doesn't have execvpe.
=> Fix osproc compilation on NetBSD, use workaround for missing execvpe

compiler/vmdeps.nim
E.g. this is crucial for a macro that generates type ids based on lineinfo.
=> Fixed lineinfo in getType

lib/pure/osproc.nim
`execvpe` is not available on android prior to 5.0
=> osproc fix for Android

lib/pure/times.nim, tests/stdlib/ttime.nim
as per #3609 
added procs to times.nim for TimeInterval add/subtract and helper functions
Is there a better way to do "plural" functions
``hour()``  and ``hours()``, ``day()`` and ``days()``, etc
than
```
proc day*(d: int): TimeInterval {.inline.} = initInterval(0,0,0,0,d)
proc days*(d: int): TimeInterval {.inline.} = initInterval(0,0,0,0,d)
```
=> Times intervals

compiler/evaltempl.nim, compiler/semtempl.nim, tests/generics/tgenerictmpl.nim
Previously it was not possible to use template arguments in template body as
the symbols were not resolved correctly leading to Error: undeclared
identifier: 'XX', eg.:
template defaultOf[T](t: T): expr = (var d: T; d)
echo defaultOf(1) #<- invalid identifier, but should output 0
=> fixes #3498

lib/posix/posix.nim, lib/system.nim
"ioctl (an abbreviation of input/output control) is a system call for device-specific input/output operations and other operations which cannot be expressed by regular system calls."
=> Add support for ioctl.

lib/pure/collections/tables.nim
Fixes #3702  with CountTableRef and getOrDefault:
```{nimrod}
import tables
proc main() =
const testKey = "TESTKEY"
let t: CountTableRef[string] = newCountTable[string]()
#test_counttable.nim(7, 43) template/generic instantiation from here
#lib/pure/collections/tables.nim(117, 21) template/generic instantiation from here
#lib/pure/collections/tableimpl.nim(32, 27) Error: undeclared field: 'hcode'
echo "Count of " & testKey & " is " & $t.getOrDefault(testKey)
t.inc(testKey,3)
echo "Count of " & testKey & " is " & $t.getOrDefault(testKey)
when isMainModule:
main()
```
Previously, `getOrDefault` for CountTableRef objects was calling the
`getOrDefaultImpl` template, which used the t.data.hcode object -
assuming a Table or similar object.  Because CountTableRef didn't have
an hcode in its data …
=> Fix CountTableRef#getOrDefault (#3702)

compiler/jsgen.nim, lib/system/jssys.nim
`cstrToNimstr` will now convert any js unicode string to utf8 bytes array. Because of that jsgen should not encode unicode chars in JS string literals.
=> Fixed unicode handling in JS. Fixes #3714.

lib/pure/streams.nim
As it is very unfriendly to JS.
=> Dont convert string to cstring when writing to stream.

compiler/jsgen.nim, lib/system/jssys.nim, tests/misc/tunsignedinc.nim, tests/testament/categories.nim
Corrected unsigned arithmetics to reflect C behavior. Added a unittest to js category which previously would fail. Removed extra code. Enabled `$``(uint)`.
=> Unsigned arith corrected for JS

compiler/jsgen.nim, lib/system/jssys.nim
Reverts nim-lang/Nim#3733
Introduced problems with arbitrary byte string literals. Will try to fix it differently.
=> Revert "Fixed unicode handling in JS. Fixes #3714."

compiler/jsgen.nim, doc/tut2.txt, tests/misc/tints.nim, tests/testament/categories.nim
Also enabled previously failing tests and added some more.
=> JS: Corrected shift operators. Cast ints like C does.

compiler/jsgen.nim, lib/system/jssys.nim, tests/js/tstringitems.nim
Reimplementation of #3733, which was reverted in #3756.
Some explanation:
- Nim string literals are created the same way it was done previously (before my attempts to fix this), but different magic is used: `makeNimstrLit`.
- cstrToNimstr magic now expects js string to be a utf16 string.
- pure cstring literals are now generated in a new way, introduced in #3733, that is escape only control chars, and let js interpreter do the rest.
Also added more tests.
@vegansk, could you please check it once again? ;)
=> Fixed unicode strings in JS. Second try.

readme.md
GitHub recommends HTTPS for security reasons.
=> Switch git clone URLs to HTTPS

lib/system/gc_common.nim
Usage of ``setupForeignThreadGc`` causes crashes and some more interesting things when ``treads`` option is off or when ``tlsEmulation`` is on. So it's better  produce compilation error for these situations.
=> Disable system.setupForeignThreadGc when it crashes

doc/manual/threads.txt
Spelling mistake fixed `overriden` > `overridden`
=> Fixes typo in doc/manual/threads.txt

lib/pure/json.nim
This used to fail, reported by ldlework:
```nim
import json
var j = %*{}
```
Now works.
=> Fix json.`%*` for empty objects

lib/system/repr.nim
Enable repr() to properly work with custom sized enum type of 1, 2, 4 and 8 bytes.
=> bug fix: repr() of sized enums presentation Issue #3864

lib/windows/winlean.nim
Resolve redefinitions of winsock staff in Microsoft Visual Studio headers, using MSVC
Issue #3879
=> Resolve "redefintion" errors, when using MSVC.

lib/pure/json.nim, tests/closure/tclosure4.nim, tests/stdlib/tmitems.nim, web/news.txt
- Significant speedup for some operations, fixes #3809
- Not tested very well yet
- We have no more order for key,val pairs. Is that fine? According to the JSON standard it is:
> An object is an unordered set of name/value pairs
http://www.json.org/
- Had to implement `hash` for `Table[string, JsonNode]`, wondering if there is a better way
- This also changes the external API of the json module, exposing the table instead of the seq
Edit: This causes a slowdown for this benchmark (from 6 to 9 seconds for me), I'll take another look: https://github.com/kostya/benchmarks#json Probably still worth the 500-times speedup for #3809. Edit2: Don't see anything obvious to optimize this.
=> Use tables instead of seqs for json objects

compiler/syntaxes.nim
Removing this from the compiler makes it possible to use shebang in nim(script) code. This can be useful for editors which support shebang based running of "scripts".
=> Removed `#!` handling (was deprecated long enought)

lib/pure/times.nim
Return timezone in seconds instead of minutes for JS target. See #3905
=> Return timezone in seconds instead of minutes for JS target.

compiler/ccgstmts.nim
PR #3881 was incomplete for `try` statement generation. `genTry` assumed it was working with C backend and so generated `->Sup` for parent field access. Now it is fixed.
=> Fixed try statement generation with --noCppExceptions switch

lib/pure/collections/sets.nim
Changed hashset's `[]` proc to use when compiles($key) like hashtable's. Fixes https://github.com/nim-lang/Nim/issues/3920
=> Don't expect all keys in hashsets to have $ defined

lib/nimbase.h
Fixed issue #3889. The problem was that we declared TLS variable in VC style for all the compilers on windows. 
This PR is based on the solution described here: http://stackoverflow.com/questions/18298280/how-to-declare-a-variable-as-thread-local-portably
=> Fixed NIM_THREADVAR definition in nimbase.h

lib/pure/uri.nim
This is a small modification of the document.
`/` Implementation:
```
proc `/` (x: Uri; path: string): Uri {.raises: [], tags: [].}
```
However, Examples are connecting the Uri and Uri.
This examples does not work.
=>  Fixed an wrong example of the uri module doc.

lib/pure/collections/sets.nim
Due to import of `os` modules sets didn't compile for js target. It seems like os module is not used in sets module at all for now.
=> Removed unused import of 'os' module from module 'sets'

lib/pure/json.nim
This is the nicest way I found to support `null` directly in `%*`. It's nice being able to directly paste json into Nim code, otherwise we could just use `nil`. This PR fixes that `nil` used to create a string `""`, which is now a `null`.
=> Support json null in %*

compiler/jsgen.nim
Using a procvar as parameter did not work. This fixes it.
@araq said that there could be done more (regarding LL and closure support).
=> Fix for PHP function pointer implementation.

compiler/jsgen.nim
Codegen used JS version for PHP which fails badly.
=> Fix for integer division in PHP codegen.

lib/system/mmdisp.nim
the other newObj's use alloc0, no reason the one in nogc shouldn't..
=> newObj can clear memory, even when using malloc and nogc

lib/system/alloc.nim
munmap returns a c int on posix.. posix.nim gets it right but system/alloc.nim does not, which causes some confusion when both are used (for nlvm at least)
=> Munmap ret fix

compiler/jsgen.nim
Integer modulo was also broken in PHP codegen.
=> Fix für PHP codegen integer modulo calculation.

lib/pure/collections/sequtils.nim
This fixes the (potential) multi-evaluation of the sequence parameter in foldl() and foldr().
It also adds a foldl() version which gets a start parameter. This allows for creating a result with a different type than the elements of the sequence.
=> Fixes foldl() and foldr() + foldl() with start parameter

compiler/jsgen.nim
I spent some time to make the PHP backend compile this:
```nim
import strutils
proc foo(s: ptr string) =
s[0] = 'y'
proc bar(s: ptr char) =
s[] = 'z'
var s = "12345"
s[0]='x'
echo s
foo (s.addr)
echo s
echo addr(s[1]) # C Backend echos: 2345 .. but see below?
bar addr(s[1]) # it is a ptr char here.
echo s
```
I got ptr string and ptr char (and ref and pointer) to work by making them PHP references but I beliefe that addr string[x] can't be supported without using etyBaseIndex as it is used in JS.
Note: In addition see the `Backend: 2345 .. see below?` comment. It differs between JS and C backend. I believe it is kinda wrong in the JS implementation (as is in the PHP implementation)
=> Try to fix addr() ref and pointer for PHP

lib/pure/ropes.nim
Ropes can be handy in code-generating macros (i.e. ones that .emit code). As shown in #3956 they cannot be used in VM context right now, because of few global variables related to cache. I have not found a clean way to make those variables available in any context, and, as a simple workaround, made exception appear if cache-related methods are called in static context.
I'm open to other suggestions on how to make ropes available to macro code.
=> Make ropes usable in VM context

lib/pure/math.nim, tests/manyloc/keineschweine/lib/sg_assets.nim
Tau (= 2 * Pi) is much more commonly used than Pi itself and should therefore be included in the standard library. Fore more details on the rationale behind Tau, see: http://tauday.com/
=> Added TAU constant.

lib/pure/rationals.nim
Fixed a bug which caused this:
```nim
2 - 1//2  # returns -3/2
```
to return incorrect result.
Also, I wonder if `reduce(result)` should be added to every overloaded operator proc in rationals.nim?
=> Fixed a typo in rational number subtraction proc

lib/pure/collections/tableimpl.nim
I don't quite understand the reason, but this code resulted in occasional duplication of KeyValuePair tuple within data seq.
=> Fixed Table::del in JS

compiler/lexer.nim
if it wasn't for bug #3978, assignment from getNumber would overwrite
tok.indent (which is set at top of rawGetTok, but not in getNumber)
=> avoid overwriting tok.indent in lexer.getNumber

lib/system/sysio.nim
Right now, at least on Linux, you can call a directory `foo.nim` and compile the directory, which is interpreted as an empty file. This is rather strange, so I think it should be disabled.
=> Don't try to read directories as files

lib/pure/strutils.nim
Still uses the optimized version for when the array consists of strings. Not sure if this is wanted. Also removed the version without `sep` and added a default value instead. Also, is there a better way than speciyfing `T: not string`?
=> Make strutils.join with with generic openarrays

lib/impure/db_odbc.nim
Repair using the "db_odbc" module to query the Oracle database, the program compiled in the release mode, the return of the field value is null.
The affected functions are getRow (), getAllRows (), fastRows (), instantRows ().
Has been tested Oracle and Firebird, are very normal!
Since #3865 submitted multiple COMMIT, I do not know how to merge them into one, so shut down the #3865, to re submit.
=> Repair using the "db_odbc" module to query the Oracle database, the program compiled in the release mode, the return of the field value is null.

tests/seq/tshallowseq.nim
currently looks like it's not covered (was useful when working on nlvm)
=> add test for shallow seq copy

lib/system/dyncalls.nim
Fixes #3987
Hooray for bugtracker items tagged 'Easy'. Also I happened to notice this one earlier today anyway, conveniently enough.
I ran ./koch test c dll before and after these changes and verified that they build (also introduced a trivial stupid error to dyncalls.nim to verify the build failed in that case). Note that on my box I saw some failures with the following two configurations both before and after this patch:
* client.nim --gc:boehm -d:useNimRtl
* client.nim -d:release --gc:boehm -d:useNimRtl
Both failed expecting rc 0 (got 1). I'm assuming these are environmental or otherwise broken just on my box, for now.
=> Makes dyncall errors report to stderr.

lib/pure/json.nim
Changed the JSON object hashing procedure to use a symmetric operator to disregard key order in object hashes as discussed under issue #3972
=> Changed the JSON object hashing procedure (fixing #3972)

lib/system/dyncalls.nim
Replacement of csprintf() with pure nim's implementation in nimGetProcAddr.
=> Replace csprintf() in windows version of nimGetProcAddr

lib/pure/mersenne.nim, web/news.txt
Current implementation of Mersenne Twister internally works with `uint32`, but its public procedures accept/produce `int` which is confusing and wrong - it leads to different behaviour on different platforms.
The main modification in this PR is change of `int` to `uint32` in `newMersenneTwister` and `getNum` proc signatures. Other changes are cosmetic - fixing formatting and style.
=> mersenne.nim public procs are no longer platform-dependent

lib/posix/posix.nim
Compiler could not be built in **Solaris** because:
hstrerror() declared in posix.nim and used in nativesockets.nim [getHostByAddr()]
On **Solaris** this function lives in **libresolv.so**.
On **Linux** timer_{create, delete, settime, gettime} and clock_{getcpuclockid, getres, gettime, nanosleep, settime} are in **librt.so**.
=> Add missed library dependencies on Linux and Solaris.

lib/pure/net.nim
SSLv3 is no longer secure and has been removed from OpenSSL since 1.0.2.
Disabling this will enable Nim programs to run against OpenSSL 1.0.2.
=> net: disable SSLv3

lib/system/gc_ms.nim
Without this change, a user's Nim code won't compile if they're using both threads & the mark-and-sweep GC:
```
lib/system/gc_ms.nim(75, 18) Error: undeclared identifier: 'SharedList'
toDispose: SharedList[pointer]
^
```
This small code block addition was copied from `lib/system/gc.nim` (where it appears directly after a `when defined(memProfiler)` block also).
=> Add `import sharedlist` when `hasThreadSupport`

lib/pure/os.nim, lib/pure/times.nim
initTime allows creating times from strings. initTimeFromStr offers a default format string compatible with $Time.
timeToTimeInterval changed to work properly.
=> depreciate timeToTimeInfo, add str->time procs

lib/core/macros.nim
The child order in unpackSomething procedures was messed up. Operator always goes first in the AST, but those procs assumed it goes second.
=> Fixed macros unpackX procedured to return values correctly

lib/windows/winlean.nim
**winlean's** definition of **GetOverlappedResult** was a little bit wrong.
[GetOverlappedResult function](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683209(v=vs.85).aspx)
=> Correct getOverlappedResult() definition

compiler/transf.nim
else you end up with for example an int64-sized value with an int32
type, when checking int32 -> Natural
=> fix type used for chckRange node boundaries

lib/pure/smtp.nim
Fixes the smtp examples so that they compile at least. I still couldn't get them to actually do something useful though:
```
S:220 kundenserver.de (mreue104) Nemesis ESMTP Service ready
C:HELO smtp.1und1.de
S:250 kundenserver.de Hello smtp.1und1.de [31.186.251.128]
C:AUTH LOGIN
S:503 Bad sequence of commands
C:QUIT
send.nim(7)              send
smtp.nim(112)            auth
smtp.nim(77)             checkReply
smtp.nim(72)             quitExcpt
Error: unhandled exception: Expected 334 reply, got: 503 Bad sequence of commands [ReplyError]
```
=> Make SMTP example compile

lib/system/syslocks.nim
Fixes https://github.com/dom96/jester/issues/65
Simpler steps to reproduce:
```nim
import locks
{.push stacktrace:on.}
proc someProc*() =
raise newException(Exception, "")
{.pop.}
proc serve() =
try:
echo 1
someProc()
except:
echo 2
try:
echo 3
someProc()
echo 4
except:
echo 5
serve()
```
This code hangs.
=> Fixed stacktrace error

lib/pure/asyncdispatch.nim, lib/windows/winlean.nim
CompletionKey parameter for functions CreateIoCompletionPort and
GetQueuedCompletionStatus must be 64bit size on amd64 and 32bit size on x86.
=> Proper definitions for functions СreateIoCompletionPort and GetQueuedCompletionStatus

lib/pure/asyncdispatch.nim, lib/pure/collections/heapqueue.nim
=> Added heapqueue collection. Fixed timers in asyncdispatch.

lib/pure/logging.nim
This is a very easy commit to pure/logging.nim. It adds the NOTICE level (between INFO and WARN) and some opinionated explanatory text snippets on what the individual levels could/should be used for.
My idea is to publish a package later on that adds a syslog logger, both for windows (over udp/tcp) and over the native syslog.h api on linux and osx. I don't think that kind of stuff needs to be in a lean core library for the rare usecases it would see.
As a consequence, this is a variant of my idea to make #3701 work as a nimble package instead of pulling in all that syslog crap into upstream.
In the same vein, I've decided not to add alert and emerg, since those levels are used mostly for systems/kernel programming and would confuse the average nim user, who only needs fatal.
Feedback …
=> pure/logging: add notice level, suggest usecases

lib/system/jssys.nim
Because of PHP can't have refs for literal function parameters I
needed to come up with a hack such that the following code compiles with
PHP target.
```nim
type Foo = tuple[a: string, b: int]
var foo: array [0..2, Foo]
foo[0] = ("Test", 1)
foo[1] = ("Me", 2)
for x in foo:
echo x.a
echo x.b
```
=> PHP codegen array constructor hack (!!!) for demo purpose only I guess

doc/gc.txt, lib/system/gc.nim, lib/system/gc2.nim
The use case for this came up when integrating Nim with a foreign environment (UE4). The place where `GC_step` is called there is quite far from the stack bottom, but it is guaranteed that the current stack doesn't contain Nim references, because it is foreign. Addition of this flag helped to reduce `GC_step` time on my laptop from ~15ms to fractions of millisecond - the whole duration was being wasted on traversing the 80 KB stack.
=> Added stackSize parameter to GC_step

lib/pure/collections/LockFreeHash.nim
otherwise nim can't parse the file.
Introduced in https://github.com/nim-lang/Nim/commit/192ba3bbc0ae7f570c1277c9211d24eeea2cf48a#diff-1a01187da2fad29f03da8ce36ffe1f91
the way I ran into this was by running `for file in $(find path/to/nim/lib -iname "*.nim"); do nim jsondoc "$file"; done` which will fail on that file.
=> Fix missing `]`

lib/pure/collections/LockFreeHash.nim
* type mismatch in range (line 55)
* invalid indentation (line 249)
Not sure if this solve rthe root cause but with patch it compiles fine with threads on
=> Fix 2 compile errors in LockFreeHash.nim

lib/impure/nre.nim
This function was in the original ``re`` module and it's a nice convenient thing to have.
=> Stdlib: nre: Convenience proc ``contains`` added.

lib/system/sysstr.nim
Fixes #4117
This implementation of **nimParseBiggestFloat** attempt to parse floats without using arbitrary precision.
If it can't, it reduce the float to its integer and exponent form:
`integer` * 10^ `exponent`
For example, 0.0926 would be written as 926 x 10^-4
then pass the string to **strtod**.
this bypass the locality problem (decimal character) and seems to works for all cases I tested.
=> fixes issue #4117 and make float parsing locale independent.

tests/enum/tenum.nim
This PR fixes #4066, but seems somewhat wrong to me. If I return `n.typ` always (not only for tyEnum), I will fail some tests, specifically compilation fails where closures are passed to calls, e.g:
```
Test "tests/closure/tfutclosure2138.nim" in category "closure"
Failure: reNimcCrash
Expected:
Gotten:
tests/closure/tfutclosure2138.nim(10, 6) Error: type mismatch: got (varargs[string], proc (word: GenericParam): untyped)
but expected one of:
tfutclosure2138.any(list: varargs[T], pred: typedesc[proc (i0: T): bool{.closure.}])
sequtils.any(seq1: seq[T], pred: proc (item: T): bool{.closure.})
```
=> Added test for #4066

lib/system/jssys.nim, tests/js/testtojsstr.nim
fixes #4190 .
Add leading zero to encoded character if it is less than 0x10.
Add regression test.
=> Fix toJSStr for control characters

lib/pure/osproc.nim
Resolve #4200
Resolve [Deprecated] warning for raiseOsError at line 878
Tested in Linux, OpenBSD, FreeBSD, NetBSD and Solaris.
MacOS testing needed.
=> Make waitForExit() to use timeout.

.gitignore
I added `.*/`, `~*` and `*.log` to GIT ignore list.
Using different IDEs for the Nim compiler I am constantly running into the problem that my global gitignore is not working for the Nim directory. This is caused by the `*` / `!*.*` like rules, which reset all other rules. So I thought a bit about a sensible filtering of common IDE special files and added that to the .gitignore.
=> Extending .gitignore to skip common IDE files and directories

lib/pure/ropes.nim
Apparently, there's a typo in `[]` proc. Before the fix, extracting characters by index didn't work:
```nim
import ropes
var r: Rope
r = rope("foo")
assert r[0] == 'f'
assert r[3] == '\0'
```
=> Stdlib: ropes: Fix character extraction by index.

lib/system/sysstr.nim, tests/float/tfloat4.nim
Here is a better fix for #4212, I think.
I think 835bd9aef23 will need to be reverted, but I not sure what is usually done in this situation for this repo.
=> fixes issue 4212 && add test for various valid zero floats.

lib/impure/nre.nim
This should make `nre` more user friendly. See https://github.com/nim-lang/Nim/issues/4158
=> Stdlib: nre: Add `export options`

compiler/pragmas.nim, tests/pragmas/thintoff.nim
The bug was in processNote, module pragmas. The code assumed that a nkBracketExpr AST node always had two children (without testing this), and tried to access elements with index 0 and 1 in the sons array of the nkBracketExpr node.
The code that triggered the bug was just {. hint[]: off .} by itself in a module; in this case the nkBracketExpr has only one children in the sons array, so the code in processNote caused an out-of-bounds array access.
This commit also adds a test to guarantee that this pragma is rejected, as is.
=> Fix issue #4001: invalid pragma {. hint[]: off .}

lib/pure/httpclient.nim
When using `httpclient`, viewing HTTP headers is impossible without importing `strtabs`, which is very much _not_ obvious; it's impossible to know without deep diving into the docs.
Dealing with headers is an essential part of working with HTTP in general, so I propose this change. The situation is analogous to this one with `nre` and `options`: https://github.com/nim-lang/Nim/issues/4158
=> Stdlib: httpclient: `export strtabs` added.

compiler/vm.nim, compiler/vmdeps.nim, compiler/vmgen.nim, lib/core/macros.nim, tests/macros/tgettypeinst.nim
This adds a variant of getType that also includes the generic arguments.  It was inspired by getType2/getTypeImpl in https://github.com/nim-lang/Nim/pull/3709 but doesn't add any new magics.  The name was chosen since the major difference from getType is in the handling of the tyGenericInst node.  The intention is also to make the output resemble a syntactically correct declaration of the type, though it wouldn't typically work in a declaration since it doesn't use the correct symbols for the generic types (and I couldn't find a symbol that would work).  The output doesn't handle all cases correctly yet, but I wanted to check that it is suitable for inclusion before finishing the rest.
```nimrod
import macros
type
Foo[N:static[int],T] = object
bar:T
var
a:Foo[1,float] …
```
=> getTypeInst

lib/pure/strutils.nim
This implements a `maxsplit` argument to `strutils.split` that limits the number of splits to at most `maxsplits`, yielding `maxsplit+1` substrings. This feature is something I've had the need for when working with csv files and similar, when only the first couple of fields are of interest. The behaviour should be (if implemented correctly!) be identical to that of `str.split` in Python.
I'm not sure if the tests are sufficient - there were no tests for `split` to start with.
=> Add maxsplit argument to strutils.split

lib/impure/db_odbc.nim
Fix row reading procs to not use SQLRowCount, but SQLFetch/SqlGetData until returns SQL_NO_DATA
change SqlCheck() and SqlGetDBMS() to sqlCheck() and sqlGetDBMS() (camelCase consistency)
=> db_odbc - row reading bug fix

compiler/semdata.nim, compiler/semexprs.nim, tests/generics/tgenerictmpl2.nim
The problem comes from the fact that macroOrTmpl[...] is transformed by
semSubscript which is trying to evaluate macroOrTmpl identifier in place. This
is okay for non-generic macros or templates, but wrong for generic ones, that
do not have a chance to receive their generic arguments explicitly specified in
brackets.
Solution:
1. macroOrTmpl[...] where macroOrTmpl is non-generic macro or template, then
macroOrTmpl is evaluated before applying brackets. (as before)
2. macroOrTmpl[...] where macroOrTmpl is generic macro or template, then if:
a. It comes from macroOrTmpl[...](...) call expr (efInCall), then macroOrTmpl
is turned into a symbol (efNoEvaluate) rather than evaluating it in place,
then whole bracket expr is returned to semIndirectOp which transforms it
to proper generic macro or …
=> fixes #3496

lib/pure/math.nim
When a proc is `importc`-ed, made explicit. Otherwise, used `[T: float32|float64]`. For some reason, the indentations look weird. If that's the case, I'll go through and fix them
EDIT: that was the case. fixed
=> Rewrote procs for float32/float64

lib/pure/times.nim
Resolve #3059
Make getTimezone() to work properly on FreeBSD and NetBSD.
=> Let getTimezone() to work properly on BSD

lib/pure/times.nim, tests/testament/categories.nim
This fixes randomize() function on JS. Time, being a value type was broken anyway. A nicer wrapper should be invented eventually if anyone cares... Also added times and random to js tests.
=> Time has now reference semantics on js

lib/pure/strutils.nim, web/news.txt
This is the last PR in my little series implementing formatEng - this is the one that actually does it (and I'll now delete PR#4211).
I've tried to take into account all the comments from the previous review, with one exception: I've left the `trim` argument with the default as `true`.  I tried lots of different alternatives for `precision` and `trim`, and none of them gave a very satisfactory result for an engineering format.  I did wonder about a default of `precision=3` and `trim=true` as I think that is probably closer to what most engineers would be interested in, but with precision being the second argument it should be easy to tweak.  As an engineer, if I try to format a capacitance of 63e-3 I would expect it to be displayed as `63 mF`, not as `63.0000000000 mF` or even `63.000 …
=> Implemented string formatting functions for engineering format

examples/ssl/extradata.nim, examples/ssl/pskclient.nim, examples/ssl/pskserver.nim, lib/pure/net.nim, lib/wrappers/openssl.nim
From Wikipedia:
> Transport Layer Security pre-shared key ciphersuites (TLS-PSK) is a set of cryptographic protocols that provide secure communication based on pre-shared keys (PSKs). These pre-shared keys are symmetric keys shared in advance among the communicating parties.
=> Add support for TLS-PSK ciphersuites to net.nim

lib/pure/unicode.nim
I just found this old work I did for adding more optimized rune "position" access. Please no discussion about how it does not support precomposed characters. They are always something pretty special. My goal was to make simple ISO-xxxx-xx > UTF-8 working painlessly. Like having ISO-8859-1 "like" UTF-8 texts and simply working with them.
May still need some work .. esp. an example and probably renaming stuff.
=> Add unicode rune offsets

lib/posix/posix.nim
Fix compile error on android ndk:
" undefined reference 'sigtimedwait' "
=> Fix android compile time error

web/news/2016_06_07_version_0_14_0_released.rst
Sorry: I didn't realise I'd made this mistake until the release notes for 0.14.0 were published.
=> Corrected typo in earlier release note addition.

lib/pure/asyncfile.nim, tests/async/tasynceverror.nim
asyncfile.nim's close() must unregister fd from async dispatcher too.
tasynceverror.nim must close acceptor socket with async close, but not system one.
=> Make some proper closes.

compiler/commands.nim, compiler/msgs.nim, compiler/options.nim
As discussed in #4307.
Add flag to display absolute file path in error messages.
=> adds --excessiveStackTrace:on|off flag for nim

lib/pure/parsecsv.nim, web/news/version_0_15_released.rst
Python's `csv` module has the `csv.reader` and `csv.DictReader`.  The latter automatically reads the headers from a CSV file.  Rows are then returned as dictionaries with the header strings as keys.  For a lot of CSV files, this is quite a convenient way of accessing them as the columns can be rearranged (e.g. extra ones inserted) but the data is still accessible in the same manner.
Tables seem to be Nim's closest equivalent to dictionaries, but I didn't want to use them as it would be an additional module to import into `parsecsv` (which currently only imports `lexbase` and `streams`).  Therefore, I've implemented a much simpler version that assumes the user will manually request header reading and then will call a function to carry out the lookup process.
To keep it nice and …
=> Improvements to parsecsv to include a minimalist DictReader #4285

lib/pure/asyncdispatch.nim, lib/windows/winlean.nim, tests/async/twinasyncrw.nim
I have found a `little bit hacky way` to have addRead()/addWrite() functions on asyncdispatch.nim windows IOCP implementation.
Mostly this functions are not needed for implementation of asynchronous programs in Windows, but sometimes, when you trying to use some other libraries (which has their own socket working code inside) this functions will help to adopt this library for windows.
For real world example its a libpq.dll (PostgreSQL C API library), which has support for select/poll functions only. But IOCP dont support polling by itself.
=> addRead/addWrite for Windows IOCP.

lib/impure/nre.nim
Importing `options` is no longer necessary.
=> Stdlib: nre: Docstring improved.

lib/system/ansi_c.nim
Checked systems OpenBSD, NetBSD, FreeBSD, Solaris.
=> Resolve bug with ansi_c.nim signals declaration

lib/pure/asyncdispatch.nim
Just because RegisterWaitForSingleObject() performs waiting in other thread GC can free our callbacks' environment data. So we need to use "brand new and undocumented" methods "system.protect() and system.dispose()" from @Araq, to protect our callback environment from angry GC.
=> Implement protection on callback environment.

lib/pure/asyncdispatch.nim, lib/windows/winlean.nim, tests/async/tnewasyncudp.nim
After failure of my previous "Async UDP support" PR i have made decision to not make any utility functions anymore, so only hardcore functions from now. I think you can easily wrap this functions to make your functions more convenient.
So representing only 2 functions for each platform:
1. sendTo() which accepts data as (pointer, size) and address as (SockAddr, SockLen).
2. recvFromInto() which returns data to user defined (pointer, size) variables and address to user defined (SockAddr, SockLen).
As you can see IPv6 is supported, because you can pass IPv6 address with SockAddr object easily.
Also there small test (you can use it as example of usage) under "tests/async/tnewasyncudp.nim"
All this functions can work on Linux, Windows, FreeBSD, OpenBSD, NetBSD and MacOS (tested on all of …
=> Async UDP support (hardcore version)

lib/pure/os.nim
Files were not properly checked to actually be files after globbing.
=> Fix #4280: os.walkFiles yields directories on Unix systems

lib/impure/db_mysql.nim
Currently, inserting a string with backslashes results in a broken input. This patch replaces a single `\` with `\\`.
=> Expand dbQuote to handle backslashes

lib/pure/json.nim
JSON itself uses table/seq semantics for nodes and arrays, so it is naturally to have `in` operator supported for it, so the next code is possible:
```nim
import json
let x: JsonNode = %*{
"a": 1,
"b": 2,
"c": ["hello", "world", "found", "in", "here"]
}
echo "a" in x                # true 
echo "d" in x                # false
echo %"found" in x["c"]      # true
echo %"not-found" in x["c"]  # false
```
=> Implemented `in` operator support for JsonNode objects

lib/pure/math.nim
Microsoft Visual C++ compilers prior to 2012 do not implement the 'round', 'roundl' or 'roundf' functions.
This change fixes this. Tested it with MSVC 2010.
Please review.
=> Windows MSVC < 2012 'round' function update

lib/pure/collections/queues.nim
This pull request is the result of a user asking for random access for queues, I implemented it as the underlying data structure supports that efficiently. Along the way I made many more changes (see commit messages).
Still, there are those salient points:
The `{.noinit.}` that I put in the `add()` proc probably does not do what I wanted it to do (skip the zeroing of sequence contents). I probably should remove it or correctly optimize.
Now I'm not using the `low()` and `high()` anymore, so they may be removed as the manual says they can't be overloaded. However, we then don't have that functionality and when I try to use it on a queue object I get: `Error: invalid argument for 'high'`
I'm not sure if I should remove `back()`, or should add `popBack()` to have a more orthogonal feature …
=> Enchanced random access support for queues among other changes

compiler/commands.nim, compiler/msgs.nim
This patch fixes not being able to completely disable Processing hint via command line with --hint[Processing]:off
=> Fix disabling hintProcessing

lib/pure/os.nim, tests/stdlib/tos.nim, tools/niminst/niminst.nim, web/news/version_0_15_released.rst
This change is to supplement #4352.
I also added a `walkDirs` proc that only walks directories because I thought it might be useful. I changed `niminst.nim` to use `walkPattern` to get both files and directories.
=> Add walkPattern to list both directories and files

doc/manual/procs.txt
I briefly considered moving instead to the end of the sentence, but looking at the manual it seems to favor leading with instead in lines such as these:
> instead a helper distinct or object type has to be used
> and instead the generated code should contain an #include
> to instead refer to the imported name via the namespace::identifier notation
It only seems to end with instead when the sentence can't easily be reworked to move it to the beginning, for example:
> However, depending on the use case new Foo can also be wrapped like this instead:
=> Fix a small typo in the manual

lib/core/macros.nim
When using the findChild template you get a warning about shadowed result variable. This is easily fixed by naming it differently. Which I did.
=> Fix a warning about result reused in macros.nim.

bootstrap.sh
Explicit `exit 0` in `bootstrap.sh` creates a nuisance to start it with `source` command without `chmod` changing. It kills terminal session. I've fix it. Don't find a reason to keep explicit exit here.
=> Remove explicit exit from bootstrap.sh

compiler/sigmatch.nim, tests/generics/t88.nim
This doesn't finally fix #88. But now we can use inheritance with generics like this:
```nim
type
BaseClass[V] = object of RootObj
b: V
proc new[V](t: typedesc[BaseClass], v: V): BaseClass[V] =
BaseClass[V](b: v)
proc baseMethod[V](v: BaseClass[V]): V = v.b
proc overridedMethod[V](v: BaseClass[V]): V = v.baseMethod
type
ChildClass[V] = object of BaseClass[V]
c: V
proc new[V](t: typedesc[ChildClass], v1, v2: V): ChildClass[V] =
ChildClass[V](b: v1, c: v2)
proc overridedMethod[V](v: ChildClass[V]): V = v.c
let c = ChildClass[string].new("Base", "Child")
assert c.baseMethod == "Base"
assert c.overridedMethod == "Child"
```
=> Fix generics inheritance issues

lib/pure/terminal.nim, lib/windows/winlean.nim
Implemented Windows version of `getch` proc for module `terminal`.
The only issue I have is that for some reason dynamic linkage for `readConsoleInput` proc doesn't work. When this proc gets called several times program just crashes without any message, with static linkage everything works great. I guess there are problem with [INPUT_RECORD](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683499(v=vs.85).aspx) struct which is actually an union. I didn't get how to properly handle unions, so I did it same way as it being done in sdl2 module.
=> Implemented terminal.getch() for Windows

lib/pure/strutils.nim, tests/stdlib/tstrutil.nim
As discussed in #4184, this patch adds `isNilOrEmpty` and
`isNilOrWhitespace` to `strutils`. This should close #4019.
It also modifies the existing `isSpace` proc slightly to exit early
rather than looping through all characters in a string.
=> Adding isNilOrEmpty and isNilOrWhitespace

lib/pure/os.nim
Before:
```
Error: unhandled exception: The system cannot find the file specified.
[OSError]
```
After:
```
Error: unhandled exception: The system cannot find the file specified.  [OSError]
```
=> Remove line breaks in OSError messages (Windows)

lib/pure/strutils.nim, tests/stdlib/tsplit.nim, web/news/version_0_15_released.rst
Make `split` with `set[char]` proc behave similarly to other split procs. I updated the news v0.15.0 release rst to reflect the breaking change. Let me know if there are other places that need doc updates.
=> Fix #4305: Make split proc for set[char] consistent

lib/pure/parsexml.nim
Added additional documentation for parsexml.nim to describe the assertions that are used to check the parser's current status when accessing parser data.
=> Add doc to parsexml.nim for template assertions

compiler/ast.nim, compiler/commands.nim, compiler/condsyms.nim, compiler/pragmas.nim, compiler/semfold.nim, compiler/wordrecg.nim, doc/basicopt.txt, doc/manual/pragmas.txt, doc/nimc.rst, lib/system/osalloc.nim, web/news/version_0_15_released.rst
This allows the end user to use the {.intdefine/strdefine.}
pragmas to pass values into code at compile time.  This has a nice side
effect of also allowing/requiring a default value to be assigned in the
code (see osalloc.nim/StandaloneHeapSize for an example)
=> Add the ability to pass a value with the -d flag

compiler/ccgcalls.nim
Varargs is now supported, though the check still occurs at the call, not the definition.
The drawbacks I can see are: (1) slightly greater overhead due to repeated notin checks, (2) error is reported at callsite, which is potentially misleading.
Is this okay for now, or should I find a way to check at the definition?
Note: This PR supercedes https://github.com/nim-lang/Nim/pull/4355
=> Fix #4275: Argument count not checked in importcpp

lib/system/repr.nim
Current implementation of reprEnum fails to work on 32-bit systems.
This version fixes it.
Bad reprEnum behaviour is only observed when there are negative enum values.
Here's an example to reproduce:
```nim
type asda = enum
ffa = -1
ffb
ffc
asda_len
let vv = asda_len
echo vv
```
The output is:
```bash
ffb
```
but has to be:
```bash
asda_len
```
=> Fixed reprEnum() function on 32-bit systems

compiler/jsgen.nim
Repr for enums with holes still doesn't work.
=> JS: Repr now works for enums starting with non-zero.

lib/pure/json.nim
Fix "Error: string literal as key expected expected"
=> Fix "string literal as key expected" error

lib/pure/collections/queues.nim
Fixes https://github.com/nim-lang/Nim/issues/4422.
Uses `default` proc from https://github.com/nim-lang/Nim/commit/5f83e869fa000598ab38866485dc8e58dd7d90d0. Redefined here. Maybe this should be an exported/reused library function?
=> Fix #4422: Reset queue element on pop. Prevent NimVM confusion. Help GC.

compiler/semstmts.nim, tests/types/tassignemptytuple.nim
Fixes https://github.com/nim-lang/Nim/issues/3516.
=> Recursively check literals for tyEmpty.

lib/system/gc.nim
`fileName` and `line` of PCell is not initialized when `leakDetector` and `hasThreadSupport`.
=> Fixed crash with leakDetector and threads enabled.

compiler/options.nim, lib/pure/ospaths.nim
`findExe()` now resolves symlinks on default. This is not supported in nimscript so far (when `ospath` is included instead of `os`)
The reason to change this is that the compiler normally looks into `bin/nim/../lib` for libraries (nim being the executable in this fake path notation). So if the compiler is linked somewhere else (like `~/bin/` it had some code to resolve this. But that code just followed one symlink and was only in the compiler. There are other tools which utilize the compiler. Nimsuggest as such did not have this symlink following. That caused strange problems, mostly because nimsuggest runs "invisible" which makes it hard to see what is happening.
By changing `findExe()` to resolve the path to the real binary file those problems can be circumvented. Resulting in a more …
=> findExe() now by default follows symlinks.

lib/pure/collections/tables.nim
With previous code, the compiler deduced that equalsImpl may raise
a KeyError. While this could only actually happen in a nasty
multi-threaded environment, I fixed the code so that it will never happen.
Example code:
```nim
import tables
proc tablesAreEqual(left, right: Table[string, string]): bool {.raises: [].} =
left == right
let
a = {"a": "b"}.newTable()
b = {"c": "d"}.newTable()
echo tablesAreEqual(a, b)
```
Did not work previously, but works now.
=> `==` in tables should not raise KeyError

lib/pure/osproc.nim, lib/system/widestrs.nim, tests/osproc/passenv.nim
Previous implementation used newWideCString, which doesn't
handle strings with \0 characters.
Fixes #4499 .
=> Fix passing environment in startProcess (win)

lib/pure/ospaths.nim
FindExe is broken after last fix on Linux.
The problem is that symlinks can have relative paths, e.g.:
```bash
krolik@krolik-nb:~/Projects/nim$ which firefox
/usr/bin/firefox
krolik@krolik-nb:~/Projects/nim$ ll /usr/bin/firefox 
lrwxrwxrwx 1 root root 25 чер  6 15:43 /usr/bin/firefox -> ../lib/firefox/firefox.sh*
```
In this case symlink's source node is defined by relative path. This fix though does not populate normalized path to symlink's source, still fixes the issue.
=> Fixed findExe behaviour on Linux with symlinks relative paths

lib/system/threads.nim
Exposes SysThread type and introduces the function "handle" to return GcThread.sys (although the GcThread type is not exposed so the param is Thread, it's descendant).
This is a minor tweak to #3375 because I'm not sure how to add a commit to an existing PR!
=> Add handle function to Thread type

lib/pure/htmlparser.nim, tests/stdlib/thtmlparser2814.nim
This fixes https://github.com/nim-lang/Nim/issues/4064 by allowing paragraphs inside lists which is pretty common. This [w3 site](http://www.w3schools.com/tags/tag_dd.asp) explicity allows for: paragraphs, line breaks, images, links, lists, etc.
=> htmlparser: Allow <p> as children of <dd> and <li> Fixes #4064 

lib/pure/httpclient.nim
`httpclient.request` opens a socket with `s = newSocket()` and closes it when done. However, if an error occurs (e.g. when name resolution fails and OSError is thrown from `nativesockets.nim:getAddrInfo`) the socket is not closed, resulting in "Too many open files" errors after a while.
This PR wraps everything in a `try...catch` block and closes the socket `finally`.
=> make httpclient close opened Socket on error

lib/system/sysstr.nim
$ on a cstring(nil) now is translated to a string(nil)
=> Fix for cstring nil to string nil conversion with `$`

compiler/ccgtrav.nim
this commit will fix visual studio family warning in #4459. but not VS2010 compiler error
=> fix visual studio family warning

.travis.yml, tests/testament/categories.nim, tests/testament/tester.nim
* Disable fasm usage on Travis CI
* Enable support of disabled modules in stdlib for tester.
=> Disable fasm usage on Travis CI

lib/pure/httpclient.nim
This change refactors `request` slightly to sent an HTTP `CONNECT` to the HTTP proxy (when present) and when making an SSL request. It's a bit of hack, as clearly the procedure for socket construction should be moved out of request. There's already a `TODO` marker to change how the headers are constructed as well. But it works!
I would add a test, but it appears the tests are not ran with `-d:ssl`, so I'm unsure how to do this. I'm also a little confused why -d:ssl isn't a default option, as SSL support seems pretty standard these days. I imagine it has something to do with linking to OpenSSL?
This fixes #4520
=> Adds support for HTTPS over proxy

compiler/sigmatch.nim, tests/distinct/tnil.nim
This should do what we talked about. Are the tests ok like that or better "`assert()`" or output checks instead of the `doAssert()` ?
=> Allowing `nil` for distinct types where the base type is nilable

compiler/semmagic.nim, compiler/types.nim
Fixes https://github.com/nim-lang/Nim/issues/3658.
=> Fix #3658. Types derived from ordinals are ordinal. Code cleanup.

lib/upcoming/asyncdispatch.nim
Two changes to upcoming asyncdispatch here:
1. Renamed Windows proc `newEvent` to `newAsyncEvent` for it to be compatible with posix platforms naming (those platforms already have `newAsyncEvent` proc).
2. Exported `AsyncEvent` type on non-Windows platforms (previously it was only exported on Windows).
I haven't tested if everything is fine on Windows with the second change. Shouldn't be any problems though.
/cc @cheatfate
=> AsyncEvent compatible between Windows and non-Windows platforms

lib/system.nim
Otherwise the compile complains that result might not be initialized.
=> Get rid of initialization warning

lib/pure/algorithm.nim, lib/pure/collections/sequtils.nim
.gensym is the default, so no need to specify it explicitly.
=> Removed the use of .gensym pragma from stdlib templates

lib/upcoming/asyncdispatch.nim
In non-windows systems `AsyncEvent` is defined as an alias for `SelectEvent`. This lead to infinite recursion when calling `setEvent` or `close`, despite the conversion. I changed the procs to use fully qualified name.
=> Fixed infinite recursion in setEvent and close procs in new asyncdispatch

lib/pure/unittest.nim, tests/js/tunittests.nim, tests/stdlib/tnet_ll.nim, tests/stdlib/tparseuints.nim
* if `suite` is used, write its name to the output
* indent child tests of the suite and their error output
* empty line before `[Suite]` so that multiple suites are separated from each other. Also makes a nice separation from the compilation output if run with `nim c -r`
Output of the example code of the unittest documentation:
```
[OK] essential truths
test1.nim(11,12): Check failed: 1 != 1
[FAILED] slightly less obvious stuff
[OK] out of bounds error is thrown on bad access
```
```
[Suite] description for this stuff
[OK] essential truths
test1.nim(11,12): Check failed: 1 != 1
[FAILED] slightly less obvious stuff
[OK] out of bounds error is thrown on bad access
```
=> Nicer output formatting for unittest

lib/pure/times.nim, tests/stdlib/ttime.nim
`yearday` has not been set at all. Fixed that.
=> Calculate correct yearday in times.parse

lib/pure/collections/tableimpl.nim, lib/pure/collections/tables.nim, tests/collections/ttables.nim, tests/collections/ttablesref.nim
Fixes tables.clear() for all six table types, and adds tests for it to prevent regressions.
=> Improvements to tables.clear()

compiler/jsgen.nim, lib/system/jssys.nim, tests/exception/tunhandledexc.nim, tests/testament/categories.nim, tests/testament/tester.nim, web/news/version_0_15_released.rst
Code:
```nim
proc test() = raise newException(Exception, "hi")
test()
```
Output before:
```
/Users/yglukhov/nimcache/test.js:175
throw e_12605;}
^
Exception: 104,105,0
```
Output after:
```
/Users/yglukhov/nimcache/test.js:363
throw new Error(cbuf_12401);
^
Error: Error: unhandled exception: hi [Exception]
test.test, line: 2528
at unhandledException (/Users/yglukhov/nimcache/test.js:363:11)
at raiseException (/Users/yglukhov/nimcache/test.js:212:1)
at test_23003 (/Users/yglukhov/nimcache/test.js:393:1)
at Object.<anonymous> (/Users/yglukhov/nimcache/test.js:396:1)
at Module._compile (module.js:556:32)
at Object.Module._extensions..js (module.js:565:10)
at Module.load (module.js:473:32)
at tryModuleLoad (module.js:432:12)
at Function.Module._load …
```
=> Uncaught exceptions in JS now always propagate with better stack trace. Fixed codegen bug.

lib/posix/termios.nim, lib/pure/terminal.nim
Hey...So, for most nice formatting for terminal like output, it is usually helpful to know at least the current terminal width.  This PR adds that proc to the standard lib.  It should compile/run/work on Windows, though it would be best for someone with a commonly used Windows Nim build environment to double-check that.
=> Add terminal.terminalWidth for windows & posix/unix-like

lib/pure/asyncdispatch.nim, lib/upcoming/asyncdispatch.nim
> A pointer to an array of WSABUF structures. Each WSABUF structure contains a pointer to a buffer and the length, in bytes, of the buffer. For a Winsock application, once the WSASend function is called, the system owns these buffers and the application may not access them. This array must remain valid for the duration of the send operation.
[WSASend documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms742203(v=vs.85).aspx)
So we need to protect ``data`` argument from being freed by GC.
=> async: protect data argument in windows send operation.

lib/pure/logging.nim, tests/testament/categories.nim
1. Moved js-incompatible stuff under `when not defined(js)`.
2. ConsoleLogger will actually do `console.log` in js.
=> Logging compatible with js

tests/async/config.nims, tests/testament/categories.nim
1. New category `async` added to testament.
2. `tests/async` now has `config.nims` which allow to run async tests with `upcoming/asyncdispatch.nim` too.
=> Add upcoming/asyncdispatch.nim to tests.

lib/upcoming/asyncdispatch.nim
Before this fix `addRead` would remove listening for write events, and vice versa.
/cc @cheatfate
=> Async read/write procedures no longer conflict in upcoming/asyncdispatch

lib/upcoming/asyncdispatch.nim, tests/async/tupcoming_async.nim
Fix windows issues with newly added `addTimer()`.
Fix semantic of `AsyncEvent` close/unregister operations #4694.
Fix type declaration error with `type AsyncEvent = SelectEvent`.
Fix #4697.
Added first test.
=> upcoming_async: Fix multiple issues and add test.

lib/pure/asyncdispatch.nim, lib/pure/asyncfile.nim, lib/pure/asyncnet.nim, lib/upcoming/asyncdispatch.nim
Sometimes it's better to use read/write operations on buffers. Syncronous IO already had that functions (for example http://nim-lang.org/docs/system.html#readBuffer,File,pointer,Natural). This PR adds them to asynchronous IO.
=> Add async IO operations with buffers on files and sockets

compiler/sem.nim
In the manual:
> Top level defer statements are not supported since it's unclear what such a statement should refer to.
Currently, compiling a module containing a defer statement at top level, such as:
```nim
defer: echo "deferred"
echo "hello, world!"
```
causes the compiler to crash with the following traceback:
```
test.nim(1, 1) Error: internal error: expr(nkDefer); unknown node kind
nim.nim(115)             nim
nim.nim(71)              handleCmdLine
main.nim(254)            mainCommand
main.nim(65)             commandCompileToC
modules.nim(238)         compileProject
system.nim(1103)         compileModule
passes.nim(198)          processModule
passes.nim(131)          processTopLevelStmt
cgen.nim(1215)           myProcess
ccgstmts.nim(1121) …
```
=> Display error message if defer statement is used at top level

lib/pure/collections/sharedtables.nim
tableimpl uses {.oldimmediate.}, which is defined in system/inclrtl.
=> Allow compilation of sharedtables.nim

lib/pure/asyncdispatch.nim, tests/async/tasyncsend4757.nim
Fixes #4757.
The intermediate `Future` was already finished when returned, so `cb` was never called.
=> Fix AsyncFD send

bootstrap.sh, doc/tut2.rst, lib/pure/algorithm.nim, lib/pure/os.nim, lib/system.nim, tests/manyloc/keineschweine/README.md, web/download.rst
Minor doc fixes for a few issues I noticed while reading the docs. The first one changes git urls to always use https, not only in docs but also in a few scripts.
I'm not sure if "doc: tut2: simplify debug macro example" is entirely correct as I have no experience with nim's macros. But the result seems to work fine.
=> Misc minor (doc) fixes

lib/pure/asyncftpclient.nim
I am trying to fix issue #4681 with the missing procvar on the defaultOnProgressChanged proc. After adding the pragma the problem went away.
=> fix missing procvar in asyncftpclient

lib/pure/marshal.nim, tests/stdlib/tmarshal.nim
Now it's backward compatible and handles binary data at the cost of additional traversal to validate UTF-8. @Araq @dom96 thoughts?
=> Use array encoding for non-UTF-8 strings in marshal

tests/async/tnewasyncudp.nim
Fix #4777.
Because `sendTo()` operation is cheap, it completes immediately (so no call to poll() performed). It causes to overflow system network buffer, so when 5000 messages sent, only 700+ was received.
Now client and server talks to each other and waiting for answers.
=> Fix tnewasyncudp test

lib/posix/posix.nim, tests/async/tnewasyncudp.nim
If there's a reason why this was changed to an int instead of using the constant, please document and ignore this pull request.
=> tests: tnewasyncudp: use constant

lib/system/mmdisp.nim
With this PR, new defined value will be added `nimBurnFree` which allows memory manager to fill memory with 0xFF before actually freeing it.
This is useful for debugging and security purposes.
=> add define nimBurnFree

config/nim.cfg
On BSD systems there some paths, where shared libraries can be placed after installations from `ports` or from `packages`.
Nim don't use `implicit linking` so `dlopen()` could not find libraries which are not installed in `/lib` or `/usr/lib`. To resolve this we need to create dynamic section of ELF file (called `RPATH`) with some default locations for shared libraries.
=> RPATH locations for OpenBSD,NetBSD and FreeBSD.

lib/pure/ioselectors.nim, lib/pure/ioselects/ioselectors_kqueue.nim, tests/async/tioselectors.nim
Add support of kqueue's `EVFILT_VNODE` events for ioselectors.nim.
Add test.
This changes affecting only FreeBSD, OpenBSD, NetBSD and MacOS.
=> EVFILT_VNODE events support for ioselectors

lib/system/osalloc.nim
Change caused MAP_ANONYMOUS to have an incorrect value when compiling
for mipsel.
Fixes #4852.
=> Revert change to osalloc.nim from commit 8d7a45f.

lib/system.nim, lib/system/gc2.nim
Some tweaks to make gcv2 compile with `--threads:on`.
=> Make gc v2 compile with --threads:on

lib/pure/httpclient.nim
i struggled to figure out how to post json content with nim's http client. this is a fundamental capability in many web apps, we don't always need to send data as multipart form data (e.g. when communicating via json apis) so frankly i'm surprised it isn't part of the "post" and "postContent" procs
=> Add example for posting json content

lib/pure/times.nim, tests/stdlib/ttime.nim
`initInterval` had logic to calculate and carry overflowed fields (65 seconds
turns into 5 seconds and carries 1 minute). However, we were not including that
carried value when we recalculate the carry over for the next period of time.So
if you had, for example, 3600 seconds, we carried 60 minutes into the minutes
calculation, but when we calculated how much we should carry into the hours
value we only considered what the user originally supplied for the minutes
field, and forgot to include those 60 carried minute.
So, for example, with the previous implementation this was true:
`seconds(60 * 60 * 24) == seconds(0)`
Or, as failing tests:
```nimrod
import times
assert seconds(60 * 60 * 24) != seconds(0)
assert seconds(60 * 60 * 24) == days(1)
```
=> Bugfix for times.initInterval (issue #4889)

lib/system/gc_stack.nim
Fix for #4892, also added size getter procs for MemRegion objects.
=> Gc stack fix

tools/niminst/buildsh.tmpl
'nuf said....
Mingw's Nim currently has a .patch file that patches the csources build.sh directly, but I figured it would just be nicer if it was officially supported. Of course, the csources repo would need to be updated afterwards.
=> Add Mingw build support for build.sh

lib/pure/asyncdispatch.nim, lib/upcoming/asyncdispatch.nim
In some cases, **epoll** or **kqueue** can return error on descriptor without specifying Read or Write events. To handle such case i propose to call all available descriptor callbacks so they can handle this errors via calls to appropriate read/recv and/or write/send operation.
=> asyncdispatch: Fix handle of error only events.

lib/wrappers/openssl.nim
1.0.2 is a current OpenSSL stable release. Related to #254
There is also 1.1.0 around but it could be added in a different commit.
=> Support OpenSSL 1.0.2

lib/pure/times.nim, tests/stdlib/ttime.nim
There may still be edge cases around dates that fall in the zones of ambiguity immediately before and after DST starts or ends, but I believe this is a step towards more correct date parsing.
=> Fix #4922, bug in times.parse, mishandling DST.

lib/pure/unittest.nim
The ability to nest tests and override setup can be unintended. If so, we should advice not to use it.
Overriding teardown is not working as expected.
=> Improve unittest docs

lib/pure/collections/tables.nim, tests/collections/ttables.nim
* added `==` for OrderedTable, CountTable and the *Ref types
* added missing documentation to all `==` procs
* fixed clear() for OrderedTables, which did not work because `var`
does not work well with `|`
* added tests
=> Table fixes. fixes #4901

lib/js/jsconsole.nim, tests/js/tconsole.nim
Added the js console object, which is available in most javascript environments (Node, browsers, Gnome etc.). Note that `echo` is not a substitute for this because it stringifies its arguments while browsers, for instance, output a navigable representation of objects
=> Added js console object

lib/core/macros.nim, lib/pure/future.nim, tests/macros/tdump.nim
I am adding here a couple of general purpose macros which are very useful but I could not find in the standard library. Since they are used for debugging purposes, I do not feel they belong to an external library.
The first one (included here) is used to dump an expression (tree + value), so that for example
```nim
import future
let
x = 10
y = 20
dump(x + y)
```
prints `x + y = 30`.
The second one (not here yet, coming in another commit) would be a `expandMacros` macro that expands (one level of) macro, useful for debug when writing macros
=> Some useful macros

lib/impure/nre.nim, lib/impure/re.nim
Regular expressions in Nim are slow because they are not using JIT feature of PCRE. Idea of using JIT in pcre_study based on grep source. Performance impact is **huge**.
There is still bottleneck in `nre`, it is 2-3 times slower than `re`.
=> Enable JIT in PCRE to improve regular expressions performance

compiler/cgen.nim
This PR allow easily setup breakpoint in GDB, and start debugging module code, but not system.nim specific code.
```
break NimMainModule
```
=> Generate `NimMainModule` name for main module.

doc/manual/types.txt
Not sure where to add this, gives some background for #3130 so that it's a clear that a `ptr T` is implicitly convertible to a `pointer`.
=> (minor) Doc change for #3130

lib/pure/asynchttpserver.nim, lib/pure/httpclient.nim
Fixes #4969 
1. More robust request parsing in accordance with https://tools.ietf.org/html/rfc7230#section-3.5 .
2. Add `overrideHeaders` parameter to `request` procs for headers that shouldn't persist between requests.
=> Fix problems with persistent HTTP connections

lib/pure/includes/asyncfutures.nim, tests/async/tasyncall.nim
Before this patch the returned future never completed with empty arg.
=> async all() now immediately completes if arg is empty

lib/pure/strutils.nim
isUpperAscii and isLowerAscii is very slow on long lines, that is because they scan all the characters in string
this patch makes them stop scanning as soon as possible
=> [enh] isUpperAscii*, isLowerAscii* speedup execution by stopping

lib/pure/times.nim, tests/stdlib/ttime.nim, web/news/e029_version_0_16_0.rst
* mktime always interprets its input as local time even on systems where
gmtoff is present, so using it is utterly useless for anything but getting
the local timezone. Removed all other usage of gmtoff to avoid confusion.
* Properly handle timezone offset in toTime()
* Properly handle timezone offset in `$` because asctime also interprets its
input as local time
* Also tried to fix the JavaScript implementation
I tested this on OSX and Linux.
**Edit:** Things I want to do before merging:
=> Fixed timezone handling

lib/pure/times.nim, tests/stdlib/ttime.nim
I've added 'noSideEffect' pragma for [proc `-`](https://github.com/nim-lang/Nim/blob/0f3419685fecc554f6ce28dee3e4630480358c3b/lib/pure/times.nim#L219) and comparison operators.
I have not removed 'noSideEffect' from [generic `==` for seq[T]](https://github.com/nim-lang/Nim/blob/0f3419685fecc554f6ce28dee3e4630480358c3b/lib/system.nim#L2179) as suggested here https://github.com/nim-lang/Nim/issues/4981#issuecomment-257648687 because I do not fully understand how to do it properly. There are other procedures for seq[T] with this pragma and this pragma probably should be removed from them too. And personally I think that having 'noSideEffect' on `==` is generally not a bad idea.
So this PR only fixes #4981.
=> Add 'noSideEffect' pragma for Time type's operators. Fixes #4981

.gitignore
When using `./koch tools`, the directory `dist/` is generated (it contains the `nimble` sources).
The `dist` directory was added to .gitignore.
=> added dist/ to .gitignore

lib/pure/times.nim, tests/stdlib/ttime.nim
* The format strings `z`, `zz` and `zzz` parse a `Z` character, which is a special case that represents UTC.
* Removed a buggy line in parsing `M`
* Improved implementation of ``proc `-` ``
* Fixed problems with DST
** Do not assume DST if a timezone offset has explicitly been given
** Calculate the DST offset into the timezone offset when formatting the timezone
* Added tests & updated documentation
* Fixes #5004
=> Improvements to times.nim

compiler/commands.nim
make excessiveStackTrace option available for testing, as in:
```nim
const useFullPaths = compileOption("excessiveStackTrace")
```
=> make 'excessivestacktrace' option available for testing.

lib/pure/collections/tables.nim
Changed `del` algorithm. Does almost what `enlarge` does except filters for the deleted key and does not actually change seq size.
=> Fixes #5057

lib/pure/collections/tables.nim
The keys in the test were accidentaly changed during experiments. Changed them back so that they actually reproduce the original case. Also a typo corrected.
=> Corrected test case for #5057.

compiler/docgen.nim, compiler/nim.cfg
`compiler/docgen.nim` relied heavily on `$lib/packages/docutils` being in `path` at compile-time. While this works fine when building Nim itself, things start breaking when using `compiler` as a nimble package.
=> Remove docgen.nim's dependency on things being in path

compiler/cgen.nim, compiler/commands.nim, compiler/options.nim, lib/pure/dynlib.nim, lib/pure/net.nim, lib/wrappers/openssl.nim
* Don't try to link and call some OpenSSL functions if not available.
* Support `dynlibOverride` flag in `compileOption`.
* `libCandidates` moved to library from compiler.
* `loadLibPattern` introduced.
=> Fixed dynlink with OpenSSL >1.1.0. Added loadLibPattern.

lib/posix/termios.nim
* All symbols were hardcoded using Linux specific values, using
imports now (because of this, the module was broken on OS X, for example)
* There were many non-POSIX (Linux specific) symbols and
functions included, these have been removed
=> Use imported symbols & remove non-POSIX stuff

lib/pure/times.nim
This is based on @endragor's commit.
On Windows keeps the previous implementation (using `mktime`). `mktime` in Windows seems to be using the same logic for determining the timezone that the existing implementation is using (using current timezone data instead of historical), so this works. `_mkgmtime` approach doesn't work with 32-bit mingw, since the function is not present in the old msvcrt.dll.
On other systems uses `timegm` to remove the need for historical timezone data. This is non-ANSI-compliant, but seems to be supported at least by Linux (tested), FreeBSD, OpenBSD, and OS X.
Fixes #4690.
=> Fix 4690 (WIP)

lib/pure/osproc.nim, tests/osproc/texitcode.nim
This fixes a race with parallelBuild on DragonFly BSD.
Also fixes #5092.
=> check waitpid() return value before setting exitStatus

lib/pure/collections/tables.nim
This is a fix for `CountTable`'s `smallest` description, erroneously stating that it returns largest element.
=> Fix description of CountTable's smallest

compiler/extccomp.nim
I think that the compiler should use ``out`` switch when building static library, as it does when building executable or dynamic library
=> Use ``out`` compiler option when linking static library

lib/pure/xmldom.nim
Currently `getAttribute` and `getAttributeNS` are defined on a `PElement`. This makes getting attributes from anything returning a `seq[PNode]` annoying (it requires a cast). One prime example of this is `getElementsByTagName(NS)`
Considering the fact that the attributes are actually defined on the `Node` type and not on the `Element` type, it makes more sense to define the methods on a `PNode` instead.
For example the code which triggered this PR:
```
let operations = doc.getElementsByTagNameNS(wsdl_ns, "operation").map(proc (x: PNode) : string = PElement(x).getAttribute("name")).deduplicate.join(", ")
``` 
Will not need the cast anymore:
```
let operations = doc.getElementsByTagNameNS(wsdl_ns, "operation").map(proc (x: PNode) : string = x.getAttribute("name")).deduplicate.join(", ")
``` …
=> Define getAttributes(NS) on PNode instead of PElement.

lib/pure/asyncdispatch.nim, lib/upcoming/asyncdispatch.nim, tests/async/tpendingcheck.nim
First I wanted to add ``proc len(p: PDispatcher): int``, but then I realized that there is no public API for PDispatcher, see #5162
=> Adds pending operations presence check function to asyncdispatch, fixes #5155

lib/pure/os.nim
posix dynamic libraries doesn't have ``cmdCount`` and ``cmdLine``
=> Disables ``paramCount``, ``paramStr`` when building posix dynlib. Fixes #4775

lib/pure/endians.nim
This is a tentative pull request to add support for GCC, CLANG, ICC & VCC builtins for faster byte-swapping.
It should compile to a single assembly instruction on x86 & x64, no idea on ARM. (Checked output assembler with gcc & clang on x64).
It is tentative, because there may be memory alignment issues since **swapEndianXX** takes a pointer to arbitrary memory and not, as is usually done a **uint16**, **uint32**, **uint64** integer.
=> optimize byte-swapping in endians.nim

lib/pure/times.nim
toTime(): Use the Windows-specific part for every OS, because it gives correct results on Linux too. The removed code for Linux gives wrong results.
=> fixes #4804

doc/tut1.rst, doc/tut2.rst
Please check that the replacement description text for ``expr`` & ``stmt`` are correct.
tut1: added multiline comments
tut2: replaced expr/stmt with untyped/typed
added some more template/macro examples
=> Further tutorial updates

compiler/transf.nim
```
iterator iter: tuple[i, j: int] =
yield (i: 1, j: 2)
for x, y in iter():
echo x, y
```
expands to:
```
x = i: 1
y = j: 2
echo x, y
```
since it does a literal copy.
=> Remove colon when unpacking yielded tuples. Fixes #5173

lib/system/threads.nim, lib/system/timers.nim
This would be a simple way to fix #5192 
Not sure if you would prefer to use different names though.
=> Naive work-around for time redefinition

lib/pure/asynchttpserver.nim
Fix the example code for asynchttpserver to import the JSON package. Without that, it can be confusing to newbies:
http://forum.nim-lang.org/t/2711
=> Async json example fix

lib/system/repr.nim, tests/system/tenum_array_repr.nim
Currently `repr` assumes that enums have the size of int. When they aren't, it produces incorrect output. This fixes #5045.
=> Handle different enum sizes in reprAux

compiler/ccgcalls.nim, tests/ccgbugs/tret_arg_init.nim
For code like `expr = foo()` where the generated function for `foo` returns by argument, `expr` needs to be reset before `foo` is called. The code generator does this when `expr` is a variable, but not when it is an array access, field access, or dereference.
I'm not sure it makes sense that these locations have kind `locExpr`, as opposed to e.g. `locField`, but this fix handles all the above cases. I don't think it overreaches, since if an expression appears on the LHS of an assignment, then it must be an l-value and should be cleared.
=> Reset locExprs before arg return. Fixes #5098

lib/pure/coro.nim
Take a look at MWE of the issue:
```Nim
when defined(mycoro):
from mycoro import run, start, suspend
else:
from coro import run, start, suspend
proc test_routine() =
while true:
suspend(1)
start(test_routine)
start(test_routine)
run()
```
`mycoro` is a `coro` version from this PR.
This code was compiled on GNU/Linux 4.8.13-1-ARCH by Nim compiler 0.15.0 (exact git hash: 8ec28552bc2d6271ad70eb21ed1d59b00078df16)
```
nim c -d:nimCoroutines -d:mycoro -o:mytest test.nim
nim c -d:nimCoroutines -o:test test.nim
```
After running both of `test` and `mytest` executables for a 10 seconds with measurement of cpu usage by `time`, I've got the following results:
```
$ time ./test                                
^CTraceback (most recent call last)
test.nim(12)             test
coro.nim(74) …
```
=> Workaround for the high cpu usage issue in coroutines on linux

compiler/ccgexprs.nim, tests/ccgbugs/tdeepcopy_addr_rval.nim
Here's a bit of an issue: the C generator seems to sometimes call `addrLoc` without checking whether the location is an lvalue. This is a problem because `genCast` (for example) doesn't always produce an lvalue when it should. I don't think this problem can be solved easily, because afaik there's no way right now to differentiate a regular variable from a manifest constant, since nim library code imports constants using `var`.
This PR fixes #5166, regarding `deepCopy`. It handles the case where the r-value is of kind `locExpr`, but that might not be sufficient for the same reason as above. Also this same bug might exist in other places. I haven't been able to find any.
=> Create temp var in deepcopy if needed

lib/pure/mersenne.nim
There is a bug in current implementation of Mersenne Twister algorithm - ``7'u32 shl result`` in line 39, where should be ``result shl 7'u32`` and the same thing in line 40.
This causes incorrect result and also leads to undefined behavior since ``result`` is too large to use it as second operand of ``shl``.
=> Fixed Mersenne Twister

lib/pure/ioselectors.nim, lib/pure/ioselects/ioselectors_epoll.nim, lib/pure/ioselects/ioselectors_kqueue.nim, lib/pure/ioselects/ioselectors_poll.nim, lib/pure/ioselects/ioselectors_select.nim, lib/upcoming/asyncdispatch.nim, tests/async/tioselectors.nim, tests/async/tupcoming_async.nim
Fix #5128.
Fix #5184.
Removed flush() procedure from ioselectors.nim.
Changed methods of work with application-driven data.
Changed all `discard` to proper error checks.
=> Fix #5128, #5184.

lib/impure/re.nim, lib/pure/collections/rtarrays.nim
These changes are to enable RE procs to work on cstring/array[..., char] without converting to strings first.
This also makes it easier to use RE's with memfile char data
=> re additions for buffer (cstring) RE matching

compiler/jsgen.nim, tests/js/tmangle.nim
This implements the changes discussed in relation to pull request #5213, and removes the need to excessively annotate object fields with `exportc` when interfacing to JavaScript.
=> Removed mangling of object fields for the js target only.

lib/pure/os.nim, lib/pure/ospaths.nim
This fixes linker errors when `import ospaths` and `import os` end up in one project.
=> Import ospaths instead of include

lib/pure/random.nim
fixed bug when the first random(max: float) call is the same value, regardless of randomize()
=> fixed bug when the first random(max: float) call is the same value

lib/pure/httpclient.nim, tests/stdlib/thttpclient.nim
=> Use onThreadCreation to set default SSL context for each thread

lib/system.nim
=> Fix a typo in system's staticExec procedure description

lib/pure/volatile.nim
Add volatile load/store
Adds volatile load/store capability to the impure part of the standard
library.  Note that this currently only supports numerical types.
Should resolve https://github.com/nim-lang/Nim/issues/3382
=> Add volatile load/store

lib/core/typeinfo.nim, lib/system/assign.nim, lib/system/deepcopy.nim, lib/system/hti.nim, lib/system/repr.nim
Seems there are some upconverting issues when using ranges to denote
array capacity on 16 bit targets. This seems to get the majority of the
ones that embedded folks might hit (though there are many other examples
in the stdlib)
=> Fix compilation for 16 bit targets

lib/pure/asyncdispatch.nim, lib/pure/ioselects/ioselectors_epoll.nim, lib/pure/ioselects/ioselectors_kqueue.nim, lib/pure/ioselects/ioselectors_poll.nim, lib/pure/ioselects/ioselectors_select.nim, lib/upcoming/asyncdispatch.nim
1. Fix memory leaks on exceptions in ioselectors.
2. Fix memory leaks on exceptions in upcoming/asyncdispatch.nim
3. Fix some error handlers to obtain more reliable error codes.
4. Fix for asyncdispatch to remove duplicate `osLastError()` calls.
5. Fix checks on return values for posix functions.
=> Fix: upcoming asyncdispatch memory leaks on exceptions.

tools/nimweb.nim
* Name is irritating; nonstopmode stops execution if an
error occurs instead of asking the user for input.
=> execute pdflatex in nonstopmode

config/nim.cfg
... to enable building of koch on Linux again
=> revert nim.cfg to version before b26e6e3

compiler/commands.nim, compiler/extccomp.nim
This fixes issue https://github.com/nim-lang/Nim/issues/5307
This commit change the way passC/passL cmdline arg and setting in config
files are parsed.
They are added to a separate linkOptionsCmd/compileOptionsCmd and are
inserted when compile/linking command list are requested.
=> fixes compiler ignoring passC/passL args when setting --cc:compiler.

lib/pure/ioselects/ioselectors_epoll.nim, lib/pure/ioselects/ioselectors_kqueue.nim, lib/pure/ioselects/ioselectors_poll.nim, lib/pure/ioselects/ioselectors_select.nim, lib/upcoming/asyncdispatch.nim, tests/async/tupcoming_async.nim
Fix `ioselectors_kqueue.nim` leaking FD.
Fix `asyncdispatch` do not unregisters AsyncEvents properly in posix branch.
Fix `asyncdispatch` do not unregisters AsyncEvents properly in windows, when no poll() was called.
Fix unregistering AsyncEvent twice is now generates `AssertionError` on windows and posix systems.
Fix some asserts and exceptions messages.
Added tests for #5304, #5298.
=> Fixes for upcoming asyncdispatch and ioselectors.

lib/pure/collections/tables.nim, tests/collections/ttables.nim
I saw a disabled test, enabled it, and fixed the problem with it.
https://github.com/nim-lang/Nim/issues/4448 should not prevent tables from working.
=> reenabled clear test, made clear working

lib/system/threads.nim
This fixes compilation error on Android as SYS_gettid is not consistently defined across all platforms. Also corrected `syscall` signature.
=> Use __NR_gettid instead of SYS_gettid

tools/nimweb.nim
If an external command fails, its output is now shown to facilitate debugging.
=> nimweb: Show output of failed external command

lib/impure/rdstdin.nim
according to the documentation here: https://github.com/antirez/linenoise
`linenoise` is supposed to return a `nil` and the end of the file. No reason to raise an exception, just return false.
=> fix in using the linenoise function

doc/backends.txt, lib/system/gc_common.nim, lib/system/threads.nim, tests/gc/foreign_thr.nim, tests/testament/categories.nim
The problem is that if we initialized GC using ``setupForeignThreadGc``, we get memory leaks on thread's exit. This PR adds function that should be used to avoid this.
=> Add ``tearDownForeignThreadGc`` function

lib/pure/algorithm.nim
Reversing an empty `openArray` would raise a RangeError. For instance for `a: seq[int] = @[]`, we have `a.high` return `-1` but `-1` is not a `Natural`. Leaving the array as-is is the expected behaviour. Another way to go about it: 
```
proc reverse*[T](a: var openArray[T]) =
if a.len > 0: reverse(a, 0, a.high) else: discard
```
=> Fix reverse on empty openArray

compiler/pragmas.nim, doc/manual/locking.txt, tests/pragmas/tlocks.nim
This is an attempt to address #3074. This would allow to write:
```nim
type SomeBase* = ref object of RootObj
type SomeDerived* = ref object of SomeBase
memberProc*: proc () # preferred solution here: {.locks: 0.}
method testMethod(g: SomeBase) {.base, locks: nil.} = discard
method testMethod(g: SomeDerived) =
if g.memberProc != nil:
g.memberProc()
```
In other words, it would allow to propagate the "assume the worst" from the procvar explicitly back to the base. Obviously the nicer solution in this example would be to mark the procvar as benign/non-locking. But maybe it makes sense to support the general case of an unknown lock level, and it can serve as a work around in cases where the compiler can't be easily convinced that something is benign (I failed to make it work in the …
=> Enabled explicitly unknown lock levels

lib/pure/json.nim
I have a case were I need to exchange signed JSON serializations with NodeJS and I've noticed the two diverge.
This PR changes formatting from 
```
{
"foo":
{
"bar": null
}
}
```
to
```
{
"foo": {
"bar": null
}
}
```
=> match json.toPretty style with NodeJS's stringify

lib/pure/asyncdispatch.nim, lib/upcoming/asyncdispatch.nim
Execute just part of timers at a time. To prevent infinite loops.
just do to make this happen.
while true:
//check something, should happen from different async.
//Not use await since need to perform some complex logic.
await sleepAsync(0) # Allow to next async to be executed.
=> Fix async timers execution.

lib/pure/nativesockets.nim, lib/windows/winlean.nim, tests/stdlib/tnativesockets.nim
Support Posix and Windows.
Add a simple functional test.
The hostname length is documented at:
https://tools.ietf.org/html/rfc1035#section-2.3.1
https://tools.ietf.org/html/rfc2181#section-11
https://en.wikipedia.org/wiki/Hostname
https://technet.microsoft.com/en-us/library/cc959336.aspx
=> Add gethostname to nativesockets

lib/pure/base64.nim
StdLib base64 encodeInternal crashes with out of bound exception
=> Fixes #5457 - StdLib base64 encodeInternal crashes with out of bound exception

lib/impure/nre.nim, tests/stdlib/nre/find.nim
nre.findIter keeps on searching when it's never matched until it reaches the end of the input. The function keeps incrementing the offset by one and searches again until len of input is reached. The function should bail early when never matched instead of searching for the next match boundary.
=> fixes #5444 - nre.findIter keeps searching when no match is possible

lib/pure/coro.nim, tests/coroutines/twait.nim, tests/coroutines/twait.nim.cfg
@cheatfate pointed out show `wait()` implementation which mistakenly assumes that coroutine can be identified by it's function pointer. Running multiple coroutines of same proc naturally would not let us wait on specific instance of coroutine. This PR fixes the issue by returning `CoroutineRef` object on which public API operates. Reference is valid even when coroutine exits and is deallocated. Now that API operates on specific coroutine reference object waiting costs O(1) instead of O(N).
Also `Coroutine` object is allocated and managed manually. This paves way for easy coroutine migration between threads should anyone decide to implement it.
=> Fix waiting on coroutines

lib/system/gc_common.nim
Introduced by #5317. `regAddr` is not used. @rokups, need your comment, or later fixup.
=> Fixed compilation error

compiler/vmdeps.nim, tests/macros/tgettypeinst.nim
This should solve #4862. The cause of the issue is that the node pointer of an unnamed tuple is `nil`, so `t.n.sons` results in a sigsegv.
Things to consider:
- Is this actually the right place to handle the issue, or should `t.n` in fact be non-nil for a unnamed tuple? Since it does not make much sense for an unnamed tuple to refer to node, I assume the node has to be nil.
- Design question: How should the type AST look like for an unnamed tuple anyway? 
- Should it be just a pure list of types? Drawback: Client code would have to handle named and unnamed tuple ASTs quite differently.
- Or should it use `IdentDefs` and follow the convention from `instFieldBodyLoop` in `semfields.nim`, which would name the fields `Field0`, `Field1`, .... Drawback: Client code may want to find out if a …
=> Fix sigsegv in getTypeImpl for unnamed tuple

tests/stdlib/nre/find.nim
Ensure we are measuring the early bailout and not the performance of the PCRE engine itself. We anchor the expression at the beginning so we can ensure  the regexp fails fast.  Scale tolerance based on result for `smallData` and add some leeway for latency.
=> More robust tests for #5453

lib/packages/docutils/rstgen.nim, lib/pure/strutils.nim, tests/manyloc/keineschweine/lib/sg_gui.nim
The result of countLines() is now increased by 1 compared to the old
version.
Fixes #5460.
=> Make countLines() the same as len(splitLines(s))

lib/pure/httpclient.nim
If condition, for not removing the scheme when proxied connection isn't a TLS request ("http://...").
=> Only remove scheme when there's a TLS request ("https")

tests/stdlib/tnre.nim
nre tests were just being compiled - changed so that a failure causes exit code to differ from expected causing `tester` to report it as a failure
=> close #5472 nre tests should be run

readme.md
The package is called `build-essential`, not `build-essentials`.
=> Fix typo in readme.md (there is no "build-essentials" package in Debian)

lib/pure/smtp.nim
Deduplicate synchronous and asynchronous code with the multisync pragma.
Pass address and port at connect rather than ``new(Async)Smtp``.
I needed to use the smtp library and found the API a bit confusing because the synchronous and asynchronous client diverge, so I converted it to multisync. This may break a few things but overall I think the interface is more intuitive and consistent with the current Nim standards.
I left debugging as a run-time option, but I would be happy to convert it to a compile time switch, I have been using ``when not defined(release)`` in my other email related projects.
=> SMTP sync/async deduplication

doc/tut1.rst
In a code example I think it best to either use full names (index, item) or abbreviated names where that's common (i, item) but not non-standard abbreviations (indx, itm). So I've changed it to index, item since it is a tutorial, although i, item would be just as good.
=> Suggested small change to code

doc/tut1.rst
Line 1264: A sequence may be passed to an openarray parameter.
This is not explained until a bit further on so should be deleted or should provide a cross-ref for openarray.
Line 1389: b[11..^2] = "useful"
This deserves some explanation. I'm guessing "Replace in be from position 11 to length-2"?
I see you are using British (European) English, e.g., "behaviour"; that's nice.
Line 1576: proc `*` *(a, b: seq[int]): seq[int] =
My guess is that the `*` is the function name and the second * is marking it for export. Seems strange that the export * isn't after the return type (e.g., to be like var x*: int). But anyway, given the use of two *s I think you should at least say explictly which is which in the text that follows it.
Line 1580: for i in 0..len(a)-1: result[i] = a[i] * b[i]
Why isn't …
=> Nicer English

doc/tut1.rst
I also suggest that you change line 406
OLD: for i in 0..<s.len:
NEW: for i in 0..^s.len:
So that readers can see that < and ^ are synonyms in this context (since that's what the text above implies).
=> Fixed typo

lib/pure/memfiles.nim, tests/stdlib/tmemfiles2.nim, web/news/e031_version_0_16_2.rst
Fix 2 problems.  First, 0 is a valid fd on Unix (easily gotten if user first
closes all fds and then starts using memfiles).  Use -1 instead for an invalid
fd.  Second, it is best practice to conserve open fds on Unix and file handles
on Windows.  These handles are not needed unless the user wants to remap the
memory with ``mapMem`` (or a hypothetical future ``proc resize``).  Adding a
new bool param ``allowRemap=false`` to ``memfiles.open`` solves this cleanly
in a "mostly" backward compatible way.  This is only "mostly" because the
default ``false`` case does not keep unneeded resources allocated, but that
most sensible default means that any ``mapMem`` callers need to fix all their
open calls to have allowRemap=true, as this PR also does for tmemfiles2.nim.
=> Fixes incorrect fd==0 test on Unix; Conserves handles by default.

doc/manual/procs.txt
I deleted it because it came across as arrogant. It is also contentious so IMO has no place in a manual.
=> Deleted parenthetical phrase

tests/async/tasyncrecursion.nim
In order to avoid unreasoned attempts to modify/remove `callSoon()` in the future.
=> asyncdispatch recursion test

compiler/jsgen.nim, compiler/jstypes.nim, tests/enum/tbasicenum.nim, tests/enum/tenumhole.nim, tests/enum/tenumoffset.nim, tests/js/tbasicenum.nim, tests/js/tenumhole.nim, tests/js/tenumnegkey.nim, tests/js/tenumoffset.nim
Change enums from js arrays to js object, using the offset of each element as index.  
This fixes  #5062, I also added some basic tests for enums with holes and offsets.
The behaviour should be the same, as non-holed enums simply have offsets starting from 0, but
the set of tests for the js target is a bit small, so I'd like some more validation.
=> Fixes #5062

lib/pure/collections/sets.nim, tests/collections/tsets.nim
Same as the clear function in collections/tables.  The implementation is pretty much the same as the tables implementation modulo field name differences.
=> Add clear() function for OrderedSet and HashSet.

lib/pure/logging.nim
Process can have no stderr/stdout. In that case, attempt to log something with console hanlder will fail with Unknown IO error.
=> Fix console logger issue #5546

lib/pure/unittest.nim
Implement ConsoleOutputFormatter that is backward compatible with the previous implementation.
Implement JUnitOutputFormatter which can be added externally.
=> Add support for custom test report formatters

compiler/vmdeps.nim, web/news/e031_version_0_16_2.rst
Currently getTypeImpl for an enum returns something like:
```nim
EnumTy
EnumTy
Sym "valueA"
Sym "valueB"
Sym "valueC"
```
This changes the result to
```nim
EnumTy
Empty
Sym "valueA"
Sym "valueB"
Sym "valueC"
```
which is what the AST that creates the type looks like.  This does not change getType, which currently returns the first version with the double ```EnumTy```.  I can change that too if desired.
=> fix getTypeImpl for tyEnum
