lib/pure/asynchttpserver.nim
=> Add imports to asynchttpserver example

doc/tut1.txt
This is likely a remainder of the name change from "Nimrod" to "Nim".
=> Tutorial: Fixed slices example code.

lib/pure/md5.nim
Fixes the bug that files > 256 MB get wrong md5 sum calculated: http://forum.nimrod-lang.org/t/716/
=> Translate md5 module to unsigned numbers

lib/pure/httpclient.nim
=> Remove debug messages

tools/niminst/nsis.tmpl
Untested, but I believe it fixes #1804.
=> fix NSIS uninstaller filename

compiler/docgen.nim, config/nimdoc.cfg, tools/nimweb.nim, tools/website.tmpl
use `./koch web --googleAnalytics:UA-48159761-1` to build with it
=> Add google analytics to docs

compiler/ast.nim, compiler/evaltempl.nim, compiler/semcall.nim, compiler/seminst.nim, compiler/vm.nim, compiler/vmgen.nim
This reverts the work by @zah however, there is a conflict in vmgen.nim that still needs to be resolved. Please help in identifying the correct implementation of the beginning to `getTemp`
=> Revert 5e4ae8d

lib/pure/future.nim
As suggested: https://github.com/Araq/Nim/issues/1920
=> Remove unnecessary check in list comprehensions

lib/pure/unittest.nim
=> Fix named argument handling

doc/docgen.txt, doc/filters.txt, doc/idetools.txt, doc/manual/effects.txt, doc/manual/ffi.txt, doc/manual/generics.txt, doc/manual/lexing.txt, doc/manual/modules.txt, doc/manual/pragmas.txt, doc/manual/procs.txt, doc/manual/stmts.txt, doc/manual/templates.txt, doc/manual/trmacros.txt, doc/manual/type_bound_ops.txt, doc/manual/type_sections.txt, doc/manual/typedesc.txt, doc/manual/types.txt, doc/nimc.txt, doc/pegdocs.txt, doc/sets_fragment.txt, doc/tut1.txt, doc/tut2.txt, lib/pure/pegs.nim, lib/pure/pegs.nimfix, tests/stdlib/tpegs.nim
Just the ones I could find quickly. Made sure that the examples still work when I wasn't sure.
=> More renames

compiler/vm.nim, tests/vm/tldconst.nim
This is a testcase and proposed fix for issue #1946
All tests pass. But I can't say I have a good understanding of the VM as a whole yet, so review the change carefully.
=> Test and fix for VM issue

compiler/extccomp.nim, tests/misc/tspace in filename.nim
Fixes #1955 by quoting the input filenames *once*
=> Custom merge of Zielmicha devel

lib/pure/httpclient.nim
=> Fixes #1962

lib/pure/complex.nim
Also removed inline indentation in unit tests
=> Added complex conjugate

lib/system/gc.nim, lib/system/profiler.nim
Pragma positions by Araq. Fixes #1983
=> Make ESTP compile

tests/testament/caasdriver.nim
Wanted to do more, but now Araq wants to fix idetools himself, which will probably work better than me doing it anyway.
=> Make caasdriver compile

lib/core/macros.nim
I added 3 new shortcuts for ASTs I find myself constructing a lot: `newPar`, `newConstStmt` and `newColonExpr`. The change list is pretty noisy because my editor chopped off a lot of the trailing whitespace in the file; I'll make sure to turn this off in the future.
=> Added a few AST-construction shortcuts.

lib/pure/collections/lists.nim, lib/pure/collections/queues.nim, lib/pure/json.nim, lib/pure/poly.nim, lib/pure/xmltree.nim, lib/system.nim, tests/stdlib/tmitems.nim
I added them where they seemed reasonable.
I also added iterators for cstrings, but I'm not sure how to easily create cstrings. To test I had to use:
```nimrod
var x = "foobar"
var y = cast[cstring](addr x[0])
for c in y.mitems:
inc c
echo x
```
=> mitems and mpairs

lib/pure/collections/lists.nim, tests/stdlib/tsinglylinkedring.nim
Fixes #2034
- SinglyLinkedRing's prepend was broken
- needed a tail so that prepend can work properly
- now append works as well, so I added it too
- simple testcase added as well
=> Fix SinglyLinkedRing in lists module

lib/pure/unittest.nim, tests/assert/tfailedassert.nim, tests/bind/tnicerrorforsymchoice.nim, tests/clearmsg/ta.nim, tests/cpp/trawsockets.nim, tests/cpp/ttypeinfo.nim, tests/effects/teffects1.nim, tests/iter/tconcat.nim, tests/manyloc/keineschweine/dependencies/chipmunk/chipmunk.nim, tests/manyloc/keineschweine/dependencies/enet/enet.nim, tests/manyloc/keineschweine/dependencies/genpacket/genpacket_enet.nim, tests/manyloc/keineschweine/dependencies/sfml/sfml.nim, tests/manyloc/keineschweine/dependencies/sfml/sfml_audio.nim, tests/manyloc/keineschweine/enet_server/enet_client.nim, tests/manyloc/keineschweine/keineschweine.nim, tests/manyloc/keineschweine/lib/game_objects.nim, tests/manyloc/keineschweine/lib/gl.nim, tests/manyloc/keineschweine/lib/map_filter.nim, tests/manyloc/keineschweine/lib/sg_assets.nim, tests/manyloc/keineschweine/lib/sg_packets.nim, tests/manyloc/keineschweine/lib/vehicles.nim, tests/modules/tmismatchedvisibility.nim, tests/osproc/tstdin.nim, tests/static/tmatrix.nim, tests/stdlib/tdialogs.nim, tests/stdlib/tgetfileinfo.nim, tests/stdlib/tircbot.nim, tests/template/tscope.nim, tests/testament/categories.nim, tests/testament/tester.nim
Ended up with more commits than I expected. I can squash them if it's wanted.
The remaining failing tests mostly look like actual bugs. Some other tests I couldn't get running, like the `dll` one.
=> Tests stuff

lib/pure/logging.nim
=> Revert "newRollingFileLogger - fmtStr is always set to defaultFmtStr"

lib/impure/rdstdin.nim, lib/posix/termios.nim
Example usage:
```nim
import rdstdin
let pass = readPasswordFromStdin "What is the password? "
echo pass
```
Only tested on Linux. Code adapted from this one by Apollo: http://forum.nim-lang.org/t/758
=> Rdstdin pass

compiler/msgs.nim
After ~1 year of Nim, I finally realized it doesn't refer to dynamic memory
=> Clarify "instantiation from here"

compiler/msgs.nim, lib/system/excpt.nim
How do I get access to the initial command string?
=> report how to create a compiler stacktrace #1280

lib/impure/rdstdin.nim
I believe that's how it should be, would still appreciate someone with Windows to actually test it.
=> Fix readPasswordFromStdin for Windows

lib/pure/matchers.nim
Just tripped over this and did the trivial fix.
=> Fixed non exhaustive case by adding else

compiler/nimfix/nimfix.nim.cfg
I "fixed" https://github.com/Araq/Nim/issues/1801 by adding the paths which are most likely working on any systen. I do not understand how the paths which where in there did work in the past. For me they did not!
=> Changed paths so that it nimfix compiles from prominent dirs.

lib/js/dom.nim
Missing functions and fields for various dom elements/events.
=> Some additions to dom.nim

compiler/main.nim, compiler/modules.nim, compiler/nim.nim, compiler/passes.nim, compiler/service.nim
=> Make compiler read files from stdin

lib/pure/complex.nim
Filled out some of the hyperbolic functions with their principal value definitions, along with some asserts to make sure they work. They seem to :smiley:
=> Addition of some complex hyperbolic functions

compiler/llstream.nim, compiler/passes.nim
Bootstrapping tested on Linux from csources.
=> Make reading from stdin work again.

lib/impure/re.nim
I fixed the examples of the pocs replace and replacef in module re.
=> Fixed examples in the documentation of module re 

tests/testament/tester.nim
Removes some abstraction, but generates better messages for tests with `nimout`.
=> better messages for nimout

lib/pure/collections/sequtils.nim
I thought that it would be nice to have this available for seq. I am unsure how to document the proc with changed parameter order.
=> Adding repeat(s, n) to sequtils.

lib/nimbase.h, tools/niminst/buildsh.tmpl
Thanks to http://forum.nim-lang.org/t/936 for showing how to fix the compile errors on freebsd.
=> compile nim on freebsd

readme.md
Move bot url to botbuild 
See https://github.com/Araq/Nim/issues/2293
and https://github.com/Araq/Nim/issues/1765
=> Move bot url to botbuild

tests/testament/tester.nim
=> fixed tester back up

lib/pure/asyncfile.nim
Not sure if this is the best way, but I've seen it in other async* modules. Right now the documentation didn't build. Trying with this command: `nim doc2 --hint\[Conf\]:off --hint\[Path\]:off --hint\[Processing\]:off --putenv:nimversion=0.10.3 --docSeeSrcUrl:https://github.com/Araq/Nim/tree/master/lib/pure -o:web/upload/asyncfile.html --index:on lib/pure/asyncfile.nim`
=> Fix doc for asyncfile

compiler/semstmts.nim
=> do not warn about gensym'd results

lib/pure/redis.nim
Added implementation for Redis SCAN command overloaded for different set of parameters.
=> Added implementation for Redis SCAN command

compiler/semtypes.nim, tests/types/tinfiniterecursion.nim
=> Fix infinite recursion in semtypes with recursive types

compiler/extccomp.nim, config/nim.cfg
=> Fix linking errors with basic Objective-C FFI.

lib/pure/collections/tables.nim, tests/collections/ttablesref.nim
See: https://github.com/Araq/Nim/issues/2126
=> Making tuples anonymous (so far... not finished).

lib/core/macros.nim, lib/pure/asyncdispatch.nim, lib/pure/future.nim, lib/pure/htmlgen.nim, lib/pure/json.nim, lib/pure/unittest.nim, lib/pure/xmltree.nim, lib/system.nim, tests/caas/idetools_api.nim, tests/generics/tunique_type.nim, tests/macros/tbugs.nim, tests/macros/tdumpast.nim, tests/macros/tdumpast2.nim, tests/macros/tgensym.nim, tests/macros/tgentemplates.nim, tests/macros/tmacro1.nim, tests/macros/tmacro3.nim, tests/macros/tmacro4.nim, tests/macros/tmacro5.nim, tests/macros/tmacros1.nim, tests/macros/tnimnode_for_runtime.nim, tests/macros/tstringinterp.nim, tests/macros/tvarnimnode.nim, tests/manyloc/keineschweine/dependencies/genpacket/genpacket.nim, tests/manyloc/keineschweine/dependencies/genpacket/genpacket_enet.nim, tests/manyloc/keineschweine/dependencies/genpacket/macro_dsl.nim, tests/showoff/tdrdobbs_examples.nim, tests/template/t_otemplates.nim, tests/usingstmt/tusingstatement.nim, tests/vm/tstringnil.nim
Csources have to be rebuilt for this.
=> Rename PNimrodNode to NimNode

lib/system/atomics.nim
I believe this should fix #2376, but don't have a machine to test.
=> Add cpuRelax asm for other platforms

compiler/docgen.nim
No idea how this got in, I'm not sure if it's ever worked.
=> Fix segfault in jsondoc

lib/impure/re.nim
Fixes https://github.com/Araq/Nim/issues/2354. I believe `pegs` has the same issue, should I fix it in a similar matter too?
=> re.match returns true on zero-length match #2354

lib/pure/pegs.nim
Follow up from https://github.com/Araq/Nim/pull/2357
I also fixed a few tests to assert instead of writing to stdout.
=> fixes match on empty peg match, #2354

lib/wrappers/iup.nim
Tested with the iupex1 and still works.
=> Make iup wrapper work with iup 3.1

compiler/ropes.nim, lib/pure/ropes.nim
A few more lib_ropes <-> compiler_ropes fixes, no deprecation warnings this time :)
=> More comp ropes

lib/impure/re.nim
I also slightly rearranged the line splits to fit in 80 chars.
=> Deprecate constant regular expression strings

lib/pure/pegs.nim
=> Revert "Corrected code example in pegs"

lib/system.nim
Inspired by https://stackoverflow.com/questions/29428702/nim-how-to-iterate-over-a-slice/
=> Add items iterator for slices

lib/pure/json.nim
Fix for #2431 
- Note now returns nil if users try to index into a non-object. Old behaviour was to throw a runtime error, but unlike other object access methods, there was no assertion check that you were looking at an object in the first place, so this looks to me like oversight not design.
- Also s/transverse/traverse/
=> {} returns nested results in json & standardise on 'key' not 'name'

lib/pure/collections/tables.nim
For starters, according to #1680. Should I go ahead and implement it for all other collections too?
=> merge for CountTable, see #1680

web/question.txt
=> Revert "New Editor (LiClipse)"

lib/pure/asyncdispatch.nim, lib/pure/asynchttpserver.nim, lib/pure/asyncnet.nim, lib/pure/strtabs.nim, lib/pure/uri.nim
These changes improve the performance of asynchttpserver significantly. See each commit for a detailed description.
See this for the progress: https://github.com/def-/nim-http-speedup
=> Speed up asynchttpserver and everything surrounding it

compiler/nimfix/nimfix.nim.cfg, compiler/nimsuggest/nimsuggest.nim.cfg
I made a mistake in the previous commit for nimfix, and I also didn't include nimsuggest to be consistent.
=> Fixed the paths of nimfix and nimsuggest to be relative.

web/assets/style.css
The slideshow now has its controls on the bottom left. It makes it more apparent that it is in fact a slideshow and there is controls for it... which wasn't really apparent before.
preview here: http://i.imgur.com/L2SmCtv.png?1
=> Moved frontpage slideshow controls

lib/impure/zipfiles.nim
Also adds an example usage to the module
=> Make zipfiles module work again

lib/impure/re.nim
findBounds returns both starting and ending position of the match.
=> Fix comment in re

lib/pure/math.nim
=> Generalize mean to other types

lib/pure/strutils.nim
Tests pass for the strutils module.
=> Add arbitrary char support to the strutils  proc.  Issue #2626

lib/pure/times.nim
Instead it's an int now. Fixes the failing test in the same module.
=> Year shouldn't be arbitrarily limited to -10_000 .. 10_000

lib/pure/algorithm.nim
=> Corrected sortedByIt example

doc/lib.txt, web/news.txt
See https://github.com/Araq/Nim/pull/2680#issuecomment-102104757
=> added documentation about sexp

lib/pure/json.nim
```
Current Standard Library
time: 3.064078 s
New Json Renderer
time: 2.634936 s
```
=> Improved performance of json rendering with `$`

compiler/nimsuggest/nimsuggest.nim
=> Nimsuggest fix

doc/manual/trmacros.txt
See IRC logs around Sun May 24 22:06:26 EDT 2015 for details
=> Fix typo in manual

doc/manual/trmacros.txt
=> Revert "Fix typo in manual"

lib/pure/streams.nim
@Araq if you don't like 'Remove trailing spaces' commit, I can remove it
=> Fix streams peekline

doc/manual/about.txt, doc/manual/definitions.txt, doc/manual/effects.txt, doc/manual/lexing.txt, doc/manual/modules.txt, doc/manual/pragmas.txt, doc/manual/procs.txt, doc/manual/stmts.txt, doc/manual/trmacros.txt, doc/manual/type_rel.txt, doc/manual/types.txt
I changed the intro wording a little to make it sound less apologetic, and more of a feature, without sweeping under the carpet.
The change under "move optimization", I admit to not understand, but took verbatim via IRC, since I had already begun editing it.
Some more changes in places where I at first read through found things unclear.
Fixed some typos while I saw them, haven't actively looked for it.
=> Change wording in some parts. Fix some typos.

compiler/jsgen.nim, tests/js/tobjfieldbyvar.nim
=> Fixes #2798. Passing arguments by var in certain cases leads to invalid JS.

tests/js/taddr.nim, tests/js/testobjs.nim
Funny thing. Turns out, these tests were never run.
=> Enabled taddr and testobjs tests

doc/manual/lexing.txt
- Please check that I got the BNF right - I'm not 1000% on the syntax
- Changed wording slightly regarding operators
=> Fix doc for #2523, regarding numeric literals.

lib/pure/logging.nim, web/news.txt
This is a breaking change! This PR removes formatting from logging module, so that logging is more consistent with echo and easier to use. More details here: #2827.
=> Removed formatting from logging.

doc/manual/procs.txt
=> Fixed code indentation in procs.txt

lib/impure/zipfiles.nim, lib/pure/fsmonitor.nim, lib/wrappers/libffi/libffi.nim, lib/wrappers/readline/readline.nim, lib/wrappers/sdl/sdl.nim, tools/niminst/niminst.nim
Fixes issues in https://github.com/Araq/Nim/issues/2876 as well as `zipfiles.nim`.
=> Some fixes from the recent `T` renaming

lib/pure/algorithm.nim
Just shorten a function and remove an unused assignment at the beginning. (var pos = result)
=> shorten lowerBound in algorithm.nim

lib/impure/db_mysql.nim, lib/impure/db_postgres.nim, lib/impure/db_sqlite.nim
It is drop-in replacement for `Row` and `fastRows`, however `instantRows` returns a
handle, not `seq[string]`, so no Nim string is created until `[]` operator is
called on the given handle. Also there is a `len()` proc returning number of
columns in the handle.
In some situations, when we iterate through many rows, but later we just read
few columns this solution will be quicker than converting all column to Nim
`seq[string]` on each iteration.
=> db: InstantRow and instantRows

compiler/installer.ini
=> Add missing nre dependency to installer

lib/pure/logging.nim
Motivation
----------
Current implementation does not allow to specify any formatting. It
even cannot output log level, because `writeln()` accepts
`varags[string]` and silently ignores everything before last argument.
Modification
------------
Perform formatting in the single place during substitution. Make log
level optional as all other substitution variables. Also make verbose
logging more informative and parseable.
Result
------
Correct handling formatting and substitutions. Machine-friendly default
output of verbose logger.
=> Fix logger formatting

lib/system/jssys.nim
=> Fixes #2917

doc/astspec.txt
[This question on SO](http://stackoverflow.com/questions/30311110/how-to-create-a-nnkuint16lit-nimnode) made me realized these weren't in there
=> Added uints to Leaf nodes

lib/system/jssys.nim
Follow up of #2945. This doesn't change the overall result, but it's a slight logic fix. Hopefully it should also increase performance a tiny bit.
=> Fixed fix of #2917

compiler/jsgen.nim
Two fixes here: one for #2617. One for genAddr of object downcast.
=> Fixes #2617, fixes addr of obj downcast.

doc/astspec.txt
Closing parenthesis. Couple of indentation fixes.
=> Minor fixes to astspec

lib/impure/nre.nim, tests/stdlib/nre/split.nim
=> Fix nre issue #20

lib/pure/math.nim
Error function (and complementary) and gamma function (and truncated). Also cubic root
=> Added some C99 funcs

doc/manual/ffi.txt, doc/tut1.txt, lib/system/alloc.nim, lib/system/hti.nim
Gender neutral language as proposed here: https://twitter.com/velartrill/status/612693665316761600
=> Neutral language

doc/manual/syntax.txt
Hopefully this change makes this neat feature more apparent
=> Added example for associativity

doc/manual/types.txt
Another assertion and clarification
=> Minor object documentation additions

lib/pure/math.nim
provides a new constant for conversion (not public, but that can be changed if it's wanted). the functions are pretty simple, honestly. top-level comment so documentation for each function could remain. Fixes #2881
=> Conversion between radians and degrees.Fixes #2881

lib/system.nim
Added a few type explanations
Also docs for `==` and some examples.
I'm not sure my explanation of `Ordinal[T]` is correct. It sounds the same as `SomeOrdinal` would be.
PR against devel as fix to #2986
=> Slight documentation addition Ref #2986

lib/pure/hashes.nim
ordinal hash was using ``THash``. switched to ``Hash``
=> THash -> Hash correction

lib/pure/algorithm.nim
Explained that the sort is a merge sort (I didn't check, just looked at the name). And corrected a little typo
=> Updated some example code in algorithm

lib/system.nim
Just to be a little more in style with the rest of Nim
=> Updated `&` parameters

lib/pure/asyncdispatch.nim
``TOVERLAPPED`` -> ``OVERLAPPED``
``TGUID`` -> ``GUID``
=> Fixed some deprecation warnings

doc/sets_fragment.txt
To clarify that sets should only be a certain size.
=> Update sets documentation. Fixes #3058

lib/pure/math.nim
I think I remember reading that the documentation is generated from the normal targets (not javascript), so that's where I put the docs
=> Added some documentation and examples

config/nimdoc.cfg, doc/nep1.txt, doc/nimdoc.css, doc/tut1.txt, web/documentation.txt, web/website.ini
Changes:
- Added NEP 1 to the documentation set.
- Modified nimdoc's css to add additional spacing between list entries, as well as between code blocks.
- Added a warning to nimdoc.css for future developers.
=> Add NEP1 to documentation.

lib/system.nim
=> Added safeAdd documentation

lib/pure/unittest.nim
=> Remove access modifiers from inner templates

compiler/platform.nim, lib/system.nim, lib/system/platforms.nim
=> Add Mipsel CPU support (untested)

compiler/installer.ini, compiler/platform.nim, lib/system.nim, lib/system/platforms.nim
As suggested in https://github.com/nim-lang/Nim/issues/3162
Not sure if we want them in the installer.ini as well.
=> Add powerpc64el and arm64 support

lib/pure/httpclient.nim
=> Revert "Set correct Host in request header"

doc/manual/types.txt, lib/system.nim
It's very hard to find this feature without knowing its name now.
=> Improve discoverability of 'of' operator

lib/system.nim
=> Workaround for #3179.

contributing.rst
The blocks were not showing up correctly.
=> Fix contributing guide rST

lib/pure/strutils.nim, tests/stdlib/tstrutil.nim
Note: I haven't figured out the rsu____ pragma pattern yet. I tried blindly adding it and compiling, but that did not work. If there is a link to where I can learn more about the pragmas I'd be happy to learn.
Feel free to reject this request if you want stylistic changes to the code. I'm still new to the Nim language :)
=> Create chomp proc and tests

web/question.txt
https://github.com/nilnor/howl/pull/65
=> Mention Howl's Nim support

lib/system/widestrs.nim, tests/stdlib/twchartoutf8.nim
the source of problem for issue #3228
=> fixed UTF-16 to UTF-8 conversion in widestrs.nim

lib/system.nim, lib/system/sysio.nim
=> When reading files, check if the eof flag is set before throwing.

compiler/jsgen.nim, tests/js/tbyvar.nim
The problem is demonstrated in the test. I'm not sure if it should be fixed in the backend though.
=> JS: Fixed passing byvar

lib/wrappers/iup.nim
Add link button for IUP wrapper
=> Add link button for IUP wrapper

lib/pure/coro.nim
We did away with the type prefixes a while back, let's not introduce new ones.
=> removed coro prefixes from coro.nim

lib/system/sysio.nim
Fix readLine handling of long lines.
=> Fix readLine handling of long lines.

lib/impure/db_mysql.nim
mysql connector "command out of sync" error 
due to breaking the fastRows iterator loop
=> fixes #3220 lib/impure/db_mysql.nim getValue()

lib/system/jssys.nim
Sometimes nimCopy is called with dest=undefined. E.g. in seq.insert function. Handle it properly.
=> Fixed JS copying.

lib/pure/osproc.nim
Previously startProcessAuxFork was defined even when it was unused, also the
compile time condition to select spawn vs fork was not always the same for
definitions and calls.
This change just defines the condition in one place as constant, then in other
places we just check for `when useProcessAuxSpawn`.
=> osproc: Define and select spawn/fork same way

lib/pure/httpclient.nim
Created this with reference to https://github.com/nim-lang/Nim/issues/3267
Wasn't entirely sure how to test this, let me know if something is wrong
=> Include port in host header as expected

lib/impure/db_mysql.nim
First attempt at adding an example.
Should probably be same or similar added to the other db_xxxxxx modules,
hopefully as similar as possible.  I haven't attempted this.
Also, an update to fastRows() iterator to describe what happens if you break 
the iterator - just trying to be clearer on what you had about it being dangerous.
=> db_mysql example and doco updates

compiler/semexprs.nim, compiler/semfold.nim, lib/system.nim
Prevent transformation of nimvm magic in generic code.
=> Fixed when nimvm in generics.

compiler/types.nim
Previously `not nil` flag was not shown on `cstring or nil` or `PType not nil`,
where `type PType = ref Type`, eg. when showing compiler diagnostics.
FYI: Added extra `addTypeFlags` helper instead moving case block into `else:` which would basically produce much bigger diff.
~~~nim
proc wantCString(arg: cstring not nil): bool = true
wantCstring(1)
#
~~~
=> typeToString: Fix shared/not nil on complex types

lib/pure/xmltree.nim
Hi,
It would be nice to have these two methods in xmltree.
Thanks,
Andrey.
=> Improve xmltree

contributors.txt, lib/pure/collections/sequtils.nim, lib/pure/events.nim
This PR fixes my name in a few files that it is in.
=> Fixed my name.

lib/pure/times.nim
add examples block to top of times module
bug fix: initInterval()  `+` and `-`  handle GM and Local time correctly
test added to bottom of module for initInterval()
=> times module examples & bug fix

compiler/vm.nim, lib/system/repr.nim
As a result, VM can now convert uint64 to string.
=> Uint64 to string in pure nim. array[char] to string fixed in vm.

web/question.txt
Given that Nim compiles to JS, limits of the JVM is not really a fair point ;)
=> Changed arguable statements about JVM/CLR.

install.txt, web/community.txt, web/news.txt, web/website.ini
=> Fix capitalization of GitHub

lib/pure/options.nim
This adds a few convenience methods to the `options` module:
* `get` with a default value
* `each`
* `map`
* `filter`
* `$`
=> Extend options module

tests/stdlib/tmemfiles1.nim, tests/stdlib/tmemfiles2.nim
Remove comments so koch test doesn't complain
=> tmemfiles minor fix 

lib/pure/streams.nim, tests/stdlib/tstreams2.nim
add examples to top of module for stringStream and fileStream	
add default file mode to newFileStream()
add test for newFileStream() opening a missing file
=> Streams examples & default newFileStream() file mode

.travis.yml
Adds a very basic travis to build nim and run tests on a linux machine.
=> Run tests on TravisCI

lib/pure/streams.nim
Create a const to handle magic number.
=> Move magic numbers to const

lib/system/alloc.nim
When compiling with '-d:nimAllocNoUnmap', the allocator will not
attempt to return large chunks to the OS. For certain allocation
behaviors, this can be a significant speedup.
=> Add option to disable munmap() use in the allocator.

lib/pure/rationals.nim, tests/rational/trat_float.nim, tests/rational/trat_init.nim
added `tests/rational` directory with 2 tests.
Both tests are failure tests (run-time assertion and compile).  
Checked via  `kock test c rational` on win7 machine
Can someone testthis on linux/Mac ??
=> Rationals - add checks and tests

lib/pure/ospaths.nim
On my system (OSX) I got multiple: `Error: can have an unlisted effect: ReadIOEffect` which are fixed by this change.
=> Added ReadIOEffect because thats what happens on OSX.

lib/pure/rationals.nim
add toRational(float) conversion from any float to closest approx for specified precision,
uses method based on farley sequences
=> rationals add toRational(float) conversion

lib/pure/xmltree.nim
In real life project of xml modification often need to change xml node tag and insert child nodes in existed xml node.
=> Add proc to change an element tag and proc to insert xmlnode child

lib/pure/hashes.nim
added hash procs for handling portions of strings/arrays/seqs.
added tests at bottom of file
changed some doco layout
Makes hashing iteratively through buffers faster when you
don't have to pass copied portions of the buffer to the
hash function
=> added hash procs for handling portions of strings/arrays/seqs.

lib/pure/strutils.nim
Added procs:
isAlpha
isAlphaNumeric
isDigit
isSpace
isUpper
isLower
=> Added useful procs to strutils for string testing.

lib/pure/logging.nim
Allow Nim users to create their own loggers
=> Export substituteLog

lib/pure/strutils.nim
add {.pop.} for {.push debugger:off.} to balance push/pop
=> fix #3343  strutils.nim  balance {.push.} with {.pop.}

lib/system.nim
system.nim add example to proc headings for 
`addr, and, or, xor, div, mod, shl, cmp, setLen`
=> system.nim add example to a few proc headings

.travis.yml, tests/manyloc/nake/nakefile.nim, tests/testament/categories.nim
Please, don't merge until travis succeeds.
=> Fixed tests for TravisCI.

lib/system.nim
Changed apparent typo, to reflect intended behavior.
=> fixed shr documentation

doc/tools.txt
Fix "Documentation generator" link in Tools page.
=> fix docgen link

lib/pure/xmlparser.nim, tests/testdata/doc1.xml
I threw up a test at the last minute so it may not be up to snuff. I hijacked the apparently unused doc1.xml file for the test.
=> Create entity nodes with xmlparser, add a test to xmlparser

lib/system/jssys.nim, web/news.txt
Subj. Note that this is a breaking change.
=> Removed Node, NodeType and Document definitions from jssys.

lib/js/dom.nim
Another pass of dom refactoring, including more renaming/deprecations and rewriting imported procs in a more correct way, that is importcpp.
=> Dom refactoring

lib/pure/nativesockets.nim
=> OpenBSD doesn't support AI_V4MAPPED

lib/system.nim
=> 7 div 5 == 1

lib/impure/db_odbc.nim, lib/wrappers/odbcsql.nim
Add SQLErr()
Add some SQLGetInfo const values
Fix SQLSetEnvAttr() parameter type
add this module
=> odbcsql.nim  and  db_odbc.nim

compiler/vm.nim, tests/vm/texcl.nim
little typo mistake that causes segfaults
=> fixed compile time `excl ` cause SIGSEGV #3639

compiler/cgmeth.nim, tests/method/tmultim8.nim
Fix multimethods issue #3550
Added test case
=> Fix multimethods issue #3550

compiler/ccgcalls.nim, tests/openarray/tptrarrayderef.nim
#2240 and #3586 are the same bug
=> fixed #2240 and #3586

lib/pure/lexbase.nim
This effectively enables `parsexml` on JS.
=> Lexbase compatible with JS

config/nimdoc.cfg, lib/packages/docutils/rstgen.nim
Changed rstgen and default nimdoc config to emit valid XML, to make postprocessing the result easier.
=> Made docgen emit valid XML by default

lib/system/repr.nim
=> add support for uint32 and uint64 in repr

examples/statcsv.nim, lib/pure/math.nim, lib/pure/stats.nim
As discussed in issue #3512
Removal of RunningStat stuff from pure lib math.nim
Addition of new pure lib stat.nim
Extended RunningStat
Added RunningRegress for linear regression and correlation of two data sets
=> stats.nim pure library (moved from math lib to new lib)

web/community.txt
The Nim BR Meetup (http://www.meetup.com/pt-BR/nim-br) is a brazilian user group about Nim where they are having discussions, talks or workshops about Nim programming language.
=> Add Nim Meetup

compiler/msgs.nim, compiler/vm.nim, compiler/vmgen.nim, lib/impure/rdstdin.nim, lib/pure/nativesockets.nim, lib/pure/net.nim, lib/pure/securehash.nim
I just removed unsigned and changed a writeLn() call to writeLine() to
avoid the remaining deprecation warnings.
=> Fixed deprecation warnings while Nim compiles.

web/community.txt
Just one more but very nice option to talk about Nim.
=> I added the Gitter Chatroom for Nim which is really nice actually!

lib/pure/nimprof.nim
=> Improve warning msg when -d:profiler not passed

lib/windows/winlean.nim, tests/stdlib/tnet_ll.nim
Fixes #3539, detects the presence of ``inet_ntop`` dynamically at startup.
Instead of multicommit PR https://github.com/nim-lang/Nim/pull/3776.
=> Fixed issue #3539 - could not import inet_ntop on XP/2003 - 3rd try

lib/pure/os.nim, lib/system.nim
=> Use defer in iterator to avoid possible leaks

lib/packages/docutils/rstgen.nim
If `.. image::` links to an SVG file, output an `<object>` tag instead of an `<img>` tag for HTML output. This enables interactive elements (e.g. hyperlinks) in linked SVG. Afaik, browser support is identical to using  `<img>`.
Only drawback is that `scale` is not supported on `<object>`, but when using SVGs, you should scale them inside the SVG anyway.
=> RST: Output <object> for SVG images in HTML

lib/pure/net.nim
just rearrange few procs to make it gc-safe
=> [net/httpclient] make it gc-safe #2692

compiler/jsgen.nim
This is an optimization to generate JS typed arrays for arrays without initializer. Low hanging fruit.
=> Prefer JS typed arrays for arrays.

compiler/jsgen.nim
- Fixed index checking
- Fixed shr.
- Fixed Tuple "field" access.
- Fixed uint32 (tints.nim at least)
=> Some fixes for the PHP CodeGen

lib/nimbase.h
=> Added -Wpragmas ignore

lib/pure/httpclient.nim
As reported in https://github.com/nim-lang/Nim/issues/3895
=> Fix redirection in httpclient (fixes #3895)

compiler/semmagic.nim
Removed error that disallows slices with negative indexes
~~Added template `..-` to allow avoiding space in 1..-1~~
=> Removed error that disallows slices with negative indexes

compiler/ast.nim, compiler/canonicalizer.nim, compiler/sem.nim, compiler/transf.nim, lib/impure/nre.nim, lib/pure/net.nim, lib/pure/parsecfg.nim, lib/pure/poly.nim, lib/pure/securehash.nim, lib/pure/streams.nim, lib/pure/times.nim, lib/system/gc_common.nim, lib/system/nimscript.nim, tests/stdlib/nre/init.nim, tests/tuples/tuple_with_nil.nim
=> Spellcheck

compiler/jsgen.nim
I think this "partly" fixes defer for the php codegen. It is pretty ugly though and will not work if you have a return in the proc :( .. but at least it does not break all of the remaining code and compiles for now.
=> Fix for defer in PHP Codegen.

lib/pure/concurrency/threadpool.nim
iOS will BAD_ACCESS (ARM bad alignment) when working with pthread primitives that were initialized on the stack and later copied to elsewhere.
=> Fixed semaphore on iOS.

lib/system/repr.nim
Let repr() properly show **uint** type values.
=> Fix for #3939 issue

lib/system/jssys.nim
It was creating an array before.
=> Fix for PHP mnewString()

lib/nimbase.h, lib/system.nim, lib/system/atomics.nim
The code compiles again with tcc backend.
=> Fix some threading issues with tcc backend

lib/posix/kqueue.nim, lib/pure/os.nim, lib/system/sysio.nim
As reported in https://github.com/nim-lang/Nim/issues/3945
Edit: Now fixing a few other BSD bugs I find.
=> Support IOFBF and IONBF on all systems

lib/posix/kqueue.nim
This file was made according to FreeBSD/OpenBSD/NetBSD and MacOS X headers. Have been tested on 64 bit platforms of this OSes.
=> Modified and more reliable kqueue.nim

lib/pure/parseutils.nim, lib/pure/strutils.nim, tests/stdlib/tparseuints.nim
``parseUInt`` and ``parseBiggestUInt`` functions was added  to ``parseutils`` and ``strutils`` modules
=> parseUInt and parseBiggestUInt functions

doc/backends.txt
=> triggering yourself -> yourself triggering

lib/posix/posix.nim
This is proper declarations:
int timer_delete(timer_t timerid);
int timer_create(clockid_t clockid, struct sigevent *sevp, timer_t *timerid);
=> Patch timer_create and timer_delete to have proper declaration.

lib/pure/json.nim
=> Added json.getOrDefault along with {singleKey} tr optimization.

lib/pure/base64.nim
This fixes latest nimble 502 issue.
=> Fixed base64 encode

lib/posix/posix.nim
A signal handler to run some code when Unix signals are received
=> Add signal handler

lib/pure/asyncfile.nim
Correct errors was made by #4080
=> Correct proper usage of getOverlappedResult()

lib/pure/pegs.nim
I was missing a nice way to use pegs with a more specialized replace functionality. Here my try to create a universal and versatile version of replace for that.
At first I just had the "caps" as argument for the callback but I decided that adding some more information does not hurt and gives a surplus in uses cases.
P.S.: Originally it used to be just called replace() and uses overloading which is not possible with the pramas the other functions in peg use. So I came up with `replacecb()`.
=> Added a replace() with callback to pegs.

lib/packages/docutils/highlite.nim, tests/stdlib/trstgen.nim
A simple YAML lexer for syntax highlighting. Tries not to parse indentation unless absolutely necessary.
=> YAML highlighting support for doctools/highlite

lib/pure/json.nim, web/news.txt
Revamp of #4014 with some bonus.
=> Json serialization for openarrays and objects

lib/system/sysstr.nim, tests/float/tfloat5.nim
Fix issue #4181 also add a testfile.
=> fix issue #4181. add testcase.

lib/pure/asyncdispatch.nim, tests/async/tasyncdiscard.nim, tests/async/tasynctry.nim, tests/ccgbugs/twrong_string_asgn.nim
Introduce callSoon() implementation
Resolve #3919
Resolve #4160
Patch some async tests.
=> Resolve bugs with `deep recursion` of asyncdispatch.

lib/system/sysstr.nim, tests/float/tfloat6.nim, tests/float/tfloat7.nim
fixes some potential issues with underscores in float literals.
adds more checks for badly positioned underscores in float literals.
adds more test files.
EDIT: travis check seems to fail but I don't this commit is at fault. The test  "tests/types/typeof_produces_alias.nim" also fail  on clean devel on my computer.
=> fixes some issues with underscores in float literals. add more tests.

lib/system/osalloc.nim
I am working in that file but my editor chokes on the pragmas ending without the dot. Not sure if they are mandatory but I guess it does not harm anyway.
=> Fixing pragmas (so syntax highligthing works).

compiler/vmops.nim, lib/system.nim
There is a ``writeFile`` function, but no ``readFile``, but it's very usefull, in build scripts for example
=> Add ``readFile`` implementation for nimvm

lib/system/gc_stack.nim, lib/system/threads.nim
Should be what we talked about!
=> Made nimphpext work with gc:stack.

lib/pure/collections/sharedtables.nim
Template withValue() allow to thread safe modification of value in scope of withValue block.
**P.S.** I'm not very good in english, so maybe documentation needs improvement.
=> Introduce template withValue()

lib/pure/collections/tables.nim
This is same template withValue() like in #4208, but for tables.nim now.
=> Introduce template withValue() for tables.nim too.

lib/pure/json.nim
JSON generation can be a bit tricky, another example might help
=> Add another JSON example

examples/unix_socket/client.nim, examples/unix_socket/server.nim, lib/posix/posix.nim, lib/pure/nativesockets.nim, lib/pure/net.nim
Adds support for Unix sockets.
=> net.nim: add support for Unix sockets

examples/unix_socket/client.nim, examples/unix_socket/server.nim, lib/posix/posix.nim, lib/pure/nativesockets.nim, lib/pure/net.nim
Updating @zielmicha's excellent Unix socket pull-request #3488 with `nimdoc` comments as per @dom96's comments
=> net.nim: add support for Unix sockets (with nimdoc comments)

lib/pure/asyncdispatch.nim
Based on this discussion: http://forum.nim-lang.org/t/2262
There's a couple points wrt to this proc:
- `and` and `or` procs do not return any result and thus don't need to be discarded. This one returns the sequence of all incoming procs. This creates an inconsistency:
```
waitFor req1 and req2       # doesn't return any values
waitFor all(@[req1, req2]) # has to be discarded
```
An expert opinion is required here. Is it ok to keep it this way? Should I replace `all` with `waitForAll`? Should `all` not return values?
- I wanted `all` to accepts varargs[Future[A]] instead of seq[Future[A]], but doing so raises an `Illegal capture`` error. Why is that?
- As far as I understand, all incoming futures must be of the same type A. Is this correct? Is there a way to wait on futures of different …
=> Stdlib: asyncdispatch: Add proc `all`.

lib/pure/strutils.nim, web/news.txt
=> Reimplementation of formatSize to return a more meaningful value

lib/pure/strutils.nim
Just realised I missed the nosideeffect pragma of my previous PR.
=> Added missing noSideEffect pragma

lib/pure/unittest.nim
Here's my implementation for #4266 .
@dom96 Could you please review it?
=> Implemented SKIPPED test status

lib/pure/httpclient.nim
=> Use passed user agent in `newAsyncHttpClient`

.travis.yml, tests/test_nimscript.nims
Test the officially supported modules and few other ones.
Some useful but unsupported modules are commented out.
=> Add nimscript test and run it in Travis CI

lib/nimbase.h, lib/pure/memfiles.nim, lib/pure/os.nim, lib/pure/streams.nim, lib/system.nim, lib/system/alloc.nim, lib/system/ansi_c.nim, lib/system/chcks.nim, lib/system/debugger.nim, lib/system/deepcopy.nim, lib/system/dyncalls.nim, lib/system/endb.nim, lib/system/excpt.nim, lib/system/gc.nim, lib/system/gc_stack.nim, lib/system/mmdisp.nim, lib/system/osalloc.nim, lib/system/sysio.nim, lib/system/sysstr.nim, lib/system/threads.nim, lib/system/timers.nim, lib/system/widestrs.nim
a bunch of small changes that cleans up function declarations and constants in system, so that nim and c actually agree on types and other ABI details.
=> System c cleanup

lib/pure/xmldom.nim
Correct xml namespace reserved prefix xml: use, see https://www.w3.org/XML/1998/namespace.
=> xmldom fix

lib/pure/collections/tables.nim
=> Implement clear() for CountTableRef. Fixes #4325.

lib/pure/httpclient.nim
HTTP/1.0 does not send `Connection: close`. Thus we have to read till the end of the response in order to catch the whole body.
As discussed with @dom96 on IRC we now pass `httpVersion` to `parseBody`.
=> Fix empty body on HTTP/1.0 connections

lib/pure/asyncdispatch.nim
Function useful for creating a future that completes once future completes or after a timeout, as discussed in #4368
=> Add withTimeout proc for futures

lib/pure/math.nim
I could have sworn I fixed this in the original pull request... sorry!
=> Corrected comment in maths library.

doc/nep1.rst
Not sure if any lines became too long... Maybe softwrap would be easier for contributors?
=> Fix punctuation

lib/deprecated/pure/sockets.nim, lib/posix/posix.nim, lib/pure/nativesockets.nim
Fixes #4376.
Where should this be documented?
=> Added 'android4' define that declares a different gethostbyaddr

lib/pure/htmlparser.nim, lib/pure/pegs.nim, lib/pure/strutils.nim, lib/pure/unicode.nim, web/news/version_0_15_released.rst
This adds unicode procs that are useful for string manipulation.
=> Add unicode procs

doc/manual/procs.txt, lib/system.nim, tests/assert/tunittests.nim, tests/closure/uclosures.nim
This template comes in handy when creating closures in loops. It has already been used quite for a while in our projects. Also its documentation will make newcomers more aware of loop-closure specifics.
=> Added closureScope template

lib/pure/collections/tables.nim
Added an explanation and two examples to the documentation of tables.nim.
=> explain difference between Table and TableRef in tables.nim

web/question.rst
=> Added Visual Studio Code editor support to FAQ

compiler/semexprs.nim, tests/tuples/tconver_tuple.nim
Fixes https://github.com/nim-lang/Nim/issues/4346.
=> Use target field types in tuple conversions.

lib/pure/random.nim
Edit: Remove reference to issue not completely addressed by this PR.
=> Random module: fix links, improve header.

lib/pure/unicode.nim
Well... that could be written much more performant but better than nothing if you ask me!
=> Added iterator for utf8 strings

lib/pure/os.nim, lib/system.nim
Just added some text to make it easier to find on searches.
=> Small changes to the docs to make it easier to find stuff.

compiler/ast.nim, compiler/ccgexprs.nim, compiler/ccgstmts.nim, compiler/semfold.nim, compiler/transf.nim
never being set - leftover from an older version?
=> remove sfFakeConst

compiler/commands.nim, lib/system.nim, web/news/version_0_15_released.rst
same as #4536 but without crap
=> fix #4417 (new)

.travis.yml, tests/testament/tester.nim
* Use fasm from nim-lang.org.
* Enable coroutines test again.
=> Enable coroutines again

doc/manual/type_rel.txt, lib/system/nimscript.nim, readme.md
Fixes few broken links I have encountered.
=> Fix several broken links in docs and readme

lib/pure/nimprof.nim, lib/system/profiler.nim
Hi guys,
It would be nice to display filenames using embedded profiler in profile_results.txt file.
Thanks,
Andrey.
=> Enable embedded profiler to display filenames.

lib/pure/memfiles.nim
Add doco on mapMem(), extend doco on open(), and add extra blank doco lines for readability
=> memfiles doc additions

compiler/jsgen.nim
I suddenly got ReferenceError exceptions for some of my code which is using ptr seq[T] (etyBaseIndex ptr). Initialising the xxx_Idx part of the variable in advance fixes this problem and looks like what needs to be done to me anyway. It does not really make sense to initialize the "sequence" with `var foo = [null, 0]`  and then assign to `foo_Idx` without to initialize this too.
I am not sure why the same code works in some javascript engines but not in others. For Screeps the exact same javascript which worked in the real world server did not work in the simulation. I believe later one is running in the browser JS engine while the world servers use nodejs.
=> Fix using ptr to seq in js backend.

lib/pure/ioselects/ioselectors_kqueue.nim, tests/async/tioselectors.nim
Fix issue #4606 
Fix some new deprecation warnings in tioselectors.nim test.
=> Fix issue #4606

compiler/types.nim
A concrete result of [this discussion](https://github.com/nim-lang/Nim/pull/4602).
=> Add comments to clarify the roles of abstractX and typedescX types.

compiler/semcall.nim
Instead of constructing a seq of overload candidates, the symbols are compared as they're generated. To avoid https://github.com/nim-lang/Nim/issues/2229, we restart the process whenever the symbol table is modified. Not terribly expensive, and doesn't happen often. (When building Nim devel, it only occurs in `guards`, `lowerings`, and `semparallel`).
Some benchmarks follow.
command (executed in `Nim/compiler`):
> nim c -f -c --hint[Processing]:off --hint[Conf]:off nim
Results (user + sys) for [recent vanilla Nim](https://github.com/nim-lang/Nim/tree/b0d9c11e5395b4cb3c1f1294b6dfbaf3f5c1f678):
> 5.514 5.509 5.524 5.513 5.556 5.517
Results (user + sys) for (the same) [recent vanilla Nim](https://github.com/nim-lang/Nim/tree/b0d9c11e5395b4cb3c1f1294b6dfbaf3f5c1f678) + this PR:
> 5.464 5.456 …
=> Optimise pickBestCandidate: reduce heap allocations.

lib/pure/concurrency/threadpool.nim
Partial solution for https://github.com/nim-lang/Nim/issues/4597 .
Only solves the third case (recursion with cpu load). However it still deadlocks if all the slave threads are blocked in recursion and the pool is full. What should be done in this situation?
=> Add a workaround for threadpool deadlocks on recursion

lib/pure/ioselects/ioselectors_epoll.nim, lib/pure/ioselects/ioselectors_poll.nim, lib/pure/ioselects/ioselectors_select.nim
Fix integer size for SelectEvent handling, problem appears on 32bit architectures.
=> Fix 32bit architecture problems with SelectEvent.

compiler/semcall.nim, tests/overload/importA.nim, tests/overload/importB.nim, tests/overload/timport.nim
Fixes https://github.com/nim-lang/Nim/issues/4675 while keeping the benefits of https://github.com/nim-lang/Nim/commit/b0c12a7dc4065372960a696907947812b4c01e0d.
=> pickBestCandidate: pre-calculate candidates when symbol table modified

lib/upcoming/asyncdispatch.nim
This PR was created by manual diff with current version of `asyncdispatch.nim`.
=> async: make upcoming version to be up to date with current version.

doc/manual/types.txt
Added compact documentation for the cstring type.
=> cstring doc

lib/pure/xmltree.nim
=> xmltree: separate escaping for attributes

.gitignore
[Reference](https://github.com/nim-lang/Nim/blob/083b31b47314c1aa70b2726a9b7d0a3c942c2bd8/koch.nim#L248)
=> Ignore new nimcache folders

doc/manual/lexing.txt, doc/manual/procs.txt, doc/manual/stmts.txt, doc/manual/syntax.txt, doc/manual/templates.txt, doc/manual/type_sections.txt, doc/manual/types.txt, doc/sets_fragment.txt, lib/system.nim
Please tell me if you don't like some of these changes and I'll adapt them and update the pull request.
=> Misc documentation fixes

lib/pure/os.nim
Only the OS-specific case in walkDir() handled that correctly. Adapt the
general case and handle it in getFileInfo().
I tried to pass nil instead of "" but then nim complained:
```
Error: ambiguous call; both system.==(x: pointer, y: pointer) and system.==(x: seq[T], y: seq[T]) match for: (nil, nil)
```
I don't know enough nim to fix this so I passed "" instead.
=> os: always use pcLinkToDir as kind for links to directories

lib/pure/osproc.nim
=> reset p.exitCode in peekExitCode on Posix when process did not exit

lib/pure/httpcore.nim
Added the HTTP method PATCH, which was added in RFC 5789
=> Added PATCH HTTP method

lib/pure/asyncftpclient.nim
proc for renaming files and/or directories via ftp
=> Asyncftpclient: adding rename proc

lib/pure/asyncftpclient.nim
proc for removing a file on the remote ftp server
=> Asyncftpclient: add remove file

lib/pure/asyncftpclient.nim
adding a proc for deleting a directory
=> Asyncftpclient: adding removeDir proc

tests/async/tupcoming_async.nim
This test causes problems on VMs.
=> tupcoming_async: Disable real time test comparison

lib/upcoming/asyncdispatch.nim
Fix upcoming asyncdispatch to pass test tpolltimeouts.nim on Windows.
=> Fix upcoming to pass tpolltimeouts

config/nim.cfg
=> Haiku supporting code in nim.cfg. We don't have -ldl.

doc/astspec.txt
=> Fix a table in macros documentation

lib/pure/httpclient.nim
Not sure why else the client is created in the line above.
=> Update httpclient documentation

lib/pure/ospaths.nim
=> Fix isAbsolute for Windows root directories

lib/pure/os.nim
Windows and Posix systems can have path longer then MAX_PATH constants.
http://insanecoding.blogspot.com/2007/11/pathmax-simply-isnt.html.
Current version of getCurrentDir() will truncate current path for Windows if it exceeds size of 512 bytes,   and raise exception on Posix operation systems.
Current version of expandFilename() on Windows systems has same issue with long pathnames, but now size is limited to 3072 bytes.
On Posix systems expandFilename() uses pretty old variant of realpath(3) with preallocated buffer, which can cause heap overflow.
Windows version of getAppFilename() has same issue with long pathname, with size limited to 256 bytes.
FreeBSD version is broken, because FreeBSD from version 8 drops support of `/proc` filesystem.
As alternative i propose to use FreeBSD …
=> Some changes to os.nim

lib/pure/httpclient.nim
=> Reset HttpClient if new URL has different port

compiler/vm.nim, compiler/vmdeps.nim, tests/vm/tgorge.bat, tests/vm/tgorge.nim, tests/vm/tgorge.sh
Please review Windows test, I am not sure that it's working.
=> Fixes #4871

tests/stdlib/tgetfileinfo.nim
Not sure if this will work on Windows as I have to create symlinks. Does the travis-build check windows?
=> tests: add more tests for getFileInfo()

lib/pure/asynchttpserver.nim
Add an example for the respond proc demonstration JSON response.
=> Add respond proc example

lib/pure/os.nim, tests/stdlib/tos.nim
=> Make createDir return discardable bool

tools/vccenv.nim, tools/vccexe.nim, tools/vcclinkerexe.nim
Enables automatic loading of Visual Studio C/C++ Build Tools
=> Add VCC wrappers

lib/system/osalloc.nim
=> add MAP_ANONYMOUS const for amd64, fix MAP_PRIVATE on mips etc

lib/pure/collections/tables.nim
Also made documentation more consistent.
=> Fixes #4974

lib/pure/times.nim, tests/stdlib/ttime.nim
This was introduced in recent "cosmetic" fix for previous PR. Not so cosmetic after all…
=> Fixed timezone sign error

lib/pure/asyncfile.nim
=> Fix asyncfile in Windows Server 2003

lib/pure/unittest.nim
=> Use default colors for test and suite names

lib/pure/logging.nim
=> Add newFileLogger overload accepting file descriptor

lib/pure/collections/tableimpl.nim, lib/pure/collections/tables.nim, tests/collections/ttables.nim
Did some minor cleanup while I was at it (duplicate template)
=> Fixes #5035

lib/upcoming/asyncdispatch.nim
To conform latest changes to current version of asyncdispatch.
=> upcoming_asyncdispatch, make it compatible again

lib/pure/terminal.nim
* setStyle did not take the current color flags into account on Windows, this
is fixed now
* refactoring to get rid of magic constants
=> Fix setStyle for Windows

lib/pure/smtp.nim
Test both sync and async email delivery
=> Improve SMTP testing

lib/pure/asyncdispatch.nim, lib/upcoming/asyncdispatch.nim
One more place with latest bug fixed for both versions of `asyncdispatch`.
Added comments for latest @Araq fixes.
Removed some old artifacts with `never happen` branch of code.
=> async: some fixes more.

lib/pure/xmltree.nim, tests/stdlib/txmltree.nim
=> Make xmltree.innerText recursive, define for all node kinds

lib/pure/collections/tableimpl.nim
Also removed redundant zeroing.
=> Workaround for #5098

lib/pure/strscans.nim
=> strscans: Fix examples

lib/pure/concurrency/cpuload.nim
=> Fix overflow when casting int64 to int in cpuload.nim

lib/core/macros.nim
Cleanup following the change in `TTypeKind`
=> NimTypeKind - replace ntyArrayConstr with ntyAlias

tools/trimcc.nim
Added libgdi32.a and libcomdlg32.a to list of essential files
=> fixes #2723

doc/tut1.rst
Add extra For Statement stuff
Add Distinct Types
=> Tutorial1 additions

lib/pure/memfiles.nim
Seems to me like stdlib memfiles is a good place for this proc.
=> Add a proc `==` for MemSlice.

lib/pure/htmlgen.nim
=> get rid of immediate macros in htmlgen module

lib/pure/strutils.nim, tests/stdlib/tstrutil.nim
build fail on **tests/generics/tlateboundstatic.nim** but appear to be unrelated to the pull request
=> Improve & optimize strutils 'find' procs

lib/windows/winlean.nim
Make SockAddr.sa_data public, coherently with its Posix counterpart.
=> Make SockAddr.sa_data public

compiler/modules.nim, tests/modules/tnotuniquename.nim, tests/modules/tnotuniquename2.nim
Fix error messages raised when multiple modules have the same original name as the following.
files:
a.nim
a2.nim
b.nim (empty)
dir/b.nim (empty)
a.nim:
import b
import dir/b as c    
a2.nim
import b
import dir/b
compile:
nim c a.nim
raise error:
Error: module names need to be unique per Nimble package; ...
compile:
nim c a2.nim
raise error:
Error: module names need to be unique per Nimble package; ...
=> Fixes #5112 (Fix error messages raised when multiple modules have the same original name)

lib/pure/nativesockets.nim
rename nativesockets.select() into nativesockets.selectRead()
=> Fix nativesockets.select()

compiler/ast.nim, compiler/vm.nim, tests/vm/tnimnode.nim
At the current state this is still expected to fail. 
This should also fix this issue: https://github.com/nim-lang/Nim/issues/4821
=> make quote ast a ref type

compiler/ast.nim, compiler/vm.nim, tests/vm/tnimnode.nim
fixes https://github.com/nim-lang/Nim/issues/4821
=> fix seq add for nim node in VM

compiler/jsgen.nim, tests/js/tmangle.nim
My bad. #5234 should now work.
=> fixes #5234

lib/pure/httpclient.nim, web/news.rst, web/news/e031_version_0_16_2.rst
=> Redirects support in request proc

compiler/jsgen.nim
Dot notation was not fully reverted to.
=> Fixup #5240

compiler/jsgen.nim, tests/js/tderef.nim
fix "invalid left-hand side in assignment" in js backend.
about error case, please look tderef test.
=> fix genderef of jsgen

appveyor.yml
Appveyor integration for x64 Windows. 
Win32 version is commented.
=> Appveyor integration.

lib/system.nim, tests/stdlib/tstring.nim
fixes https://github.com/nim-lang/Nim/issues/4636
primary code fix courtesy of @memophen
added test file for edge cases.
=> fix string slice & splice

compiler/vm.nim
fixes missing  lineinfo in issue https://github.com/nim-lang/Nim/issues/4992
copy lineinfo from instanciation point.
=> tentative fix for missing lineinfo:  ???(???, 0) Error:

tools/nimweb.nim
Also check for incorrect parallelBuild values
=> Use the correct parallelBuild value. fixes #5328

compiler/scriptconfig.nim
=> Don't prepend project path to absolute filenames passed to setCommand

lib/posix/posix.nim
Inspired by some discussion on this forum thread:
https://forum.nim-lang.org/t/2786
There is not much to this PR besides just mirroring the way the C works with st_?tim primary data fields and st_?time accessor inline functions.
=> Update Stat to work with modern Unix impls

lib/pure/parseutils.nim, lib/pure/strutils.nim, lib/system.nim
* new type BiggestUInt in system
* made strutils and parseutils use new type
* results in parseBiggestUInt being usable in JS
=> Added BiggestUInt

lib/pure/asynchttpserver.nim
This enables ipv6 support for asynchttpserver. ipv4 still works.
=> Listen on ipv6

lib/pure/hashes.nim, tests/collections/thashes.nim
=> added hash for uints

lib/pure/httpclient.nim
I've changed the semantics of `nil` value for `sslContext` in `newHttpClient` and `newAsyncHttpClient` procs to mean "default SSL context" instead of "no SSL context". This should not be a problem, since before this fix making HTTPS request with "no SSL context" (nil) produced segfault.
=> Ensure default SSL context is always initialized

lib/pure/asynchttpserver.nim
Reverts nim-lang/Nim#5433
Unfortunately this breaks windows. Reverting for now.
=> Revert "Listen on ipv6"

lib/pure/asynchttpserver.nim
Handle bad request rather than crashing =)
=> Dont assert on malformed requests

lib/pure/encodings.nim
=> Fix iconv import on freebsd and netbsd

lib/system.nim
=> Fix links to manual

doc/tut1.rst
On line 1135 I suggest changing Subrange to, say, MyRange (and in the following para), otherwise it is slightly confusing with the subrange terminology.
I also softened "wrong" to unwise.
=> Nicer English

lib/pure/collections/critbits.nim
And hopefully now in the right branch!
=> Minor doc fix as per issue #5523

lib/pure/bitops.nim, tests/stdlib/tbitops.nim, tests/stdlib/tbitops.nim.cfg, tests/stdlib/tbitops2.nim, tests/stdlib/tbitops2.nim.cfg
This module implements reasonably optimized proc for bit manipulation/operation and optionally make uses of compiler intrinsics for improved performance.
It also support non-compiler backend with default implementation
=> add bitops module for optimized bit manipulation.

lib/nimbase.h, lib/system/gc.nim
adding initial support for ASAN, in my own testing i was only able to isolate this one function that needed to be ignored; there may be more but it should be trivial to add support as necessary.
=> adding support for using llvm ASAN

lib/pure/unittest.nim, tests/stdlib/tunittest.nim
=> Reduce the scope of stackTrace var

compiler/extccomp.nim
The json file created with ``nim --compileOnly`` is missing the object files to link.
Blocks #5560.
=> fix empty link file list during external compilation

lib/system/alloc.nim, lib/system/threads.nim, tests/threads/tmanyjoin.nim, tests/threads/treusetvar.nim
Fix #4719.
Allow reuse of Thread[TArg] object.
Added 2 tests.
=> Fix for #4719.

compiler/semcall.nim
=> Fixed issue #5638

lib/pure/parsecfg.nim, tests/stdlib/tparscfg.nim
Working just with files is often not enough
=> parsecfg: handle streams and strings when saving or loading configuration

compiler/extccomp.nim
The calls to the compiler and linker backend have been wrapped in try-blocks to provide an error message like the following:
> Error: invocation of external compiler program failed. The system cannot find the file specified.
>
>Additional info: Requested command not found: 'gcc.exe -c -w  -ID:\Source\GitHub\nim-lang\Nim\lib -o D:\Source\GitHub\nim-lang\Nim\nimcache\compiler_koch.o D:\Source\GitHub\nim-lang\Nim\nimcache\compiler_koch.c'. OS error: 2
This represents the `msg` and `errorCode` of the `OSError` that is raised when `execCmd` fails.
After the error has been printed, the OSError is reraised, since the compile command still should fail.
Fixes #2770, #2135
=> Error Message if CC invocation fails

compiler/ccgtypes.nim, lib/posix/epoll.nim, lib/posix/termios.nim, lib/pure/times.nim, lib/system/ansi_c.nim, lib/system/syslocks.nim, lib/system/threads.nim
#5656 and #5674, without posix.nim changes
=> Linux abi take 3

lib/pure/cookies.nim
See https://tools.ietf.org/html/rfc6265
=> Fix "secure" capitalization

lib/pure/cookies.nim
See https://tools.ietf.org/html/rfc6265
=> Fix cookie timestamp format #5718

lib/pure/asyncnet.nim, lib/pure/httpclient.nim, lib/pure/net.nim
=> Add 'hostname' param to wrapConnectedSocket

compiler/cgmeth.nim
=> fixes multiple nil-checks for methods

lib/system/atomics.nim
Also, fixed inconsistent behaviour of atomicInc on vcc. Previously
it would return the old value, while it must return the new value.
Fixes: #5808
=> Fix atomicInc under vcc, C++, amd64

tests/testament/specs.nim, tests/testament/tester.nim
to compare two compilers (or run nlvm instead)
=> compiler option for testament

lib/posix/posix.nim, lib/posix/posix_linux_amd64.nim, lib/posix/posix_linux_amd64_consts.nim, lib/posix/posix_other.nim, lib/posix/posix_other_consts.nim, tools/detect/detect.nim
accidentally wiped by ce86b4ad78aae11f62c50e4f46e8ab2a124356b4
see also  #5783 (@cdunn2001)
=> add back SIG_IGN, SIG_DFL and friends to posix.nim

lib/pure/osproc.nim
posix_spawn doesn't set errno - it returns the error code.
=> Fix posix_spawn error handling

lib/system/syslocks.nim
=> Fixup #5804

readme.md
Revised Readme to reflect that nimsuggest now is part of the main Nim repo again
=> Fixed nimsuggest in readme

lib/system.nim
=> Add len for Slice[T] where T is ordinal

compiler/vm.nim, doc/astspec.txt, tests/vm/tnimnode.nim
Changes as suggested by @Araq on [IRC](https://irclogs.nim-lang.org/19-05-2017.html#11:53:43).
=> Creating and setting comment nodes in macros

lib/pure/collections/tables.nim, tests/stdlib/torderedtable.nim
This fixes issue #5917 
This is a temporary fix until a faster OrderedTable can be  implemented.
=> fix orderedtable enlarge proc.

lib/pure/concurrency/cpuinfo.nim
=> fix countProcessors error return value.

compiler/vmgen.nim, tests/arithm/tshr.nim
=> fix logical right shift in VM.

lib/pure/parseopt.nim, lib/pure/parseopt2.nim, tests/misc/tparseopt.nim
=> Fix parseopt custom arguments

compiler/msgs.nim, lib/pure/json.nim, lib/pure/pegs.nim, lib/pure/strutils.nim, lib/system/repr.nim, lib/system/reprjs.nim
=> Ascii character code 127 (DEL) is not printable and must be quoted.

tests/types/t1252.nim
In case we want a test case for #1252
=> added test case for #1252

lib/pure/math.nim, lib/pure/random.nim, tests/stdlib/tmath.nim
=> Simple fix for power issue

lib/pure/times.nim
=> Fix documentation for subtracting TimeInterval from Time

lib/system.nim
=> system.nim: Fix documentation ( 7 div 5 == 1 )

lib/pure/asyncnet.nim, tests/async/tasyncRecvLine.nim
As requested by @dom96, this fixes an issue seen here: https://github.com/nim-lang/redis/pull/4#issuecomment-312713921
=> Wait for reads to finish before reading the result

lib/pure/asyncfile.nim
Allows to create `AsyncFile` with a previously opened `fd`.
=> Added newAsyncFile proc

doc/nimc.rst
Small usage inconsistency I noticed on the page.
=> Make option usage more consistent in doc

lib/pure/asynchttpserver.nim
Add more suitable error code and reason phrase for required Content-Length request.
=> Correct "Length required" response status code and phrase

lib/pure/strscans.nim
This example parses a string for ip addresses.
=> Docs: add one more example in strscans module

lib/system/atomics.nim
don't know how to make a test, but I already test it with MSVC 2010 & MSVC 2015
=> fixes #6196

lib/pure/collections/tables.nim
=> fixes #6250

lib/pure/times.nim
The output can be surprising - better provide examples.
=> Improve docs around subtracting times

lib/pure/json.nim, lib/system/jssys.nim
=> Fixed handling of surrogate pairs

lib/pure/json.nim
=> Update doc for json.to() with limitation

lib/pure/times.nim
=> Improve TimeInterval docs #6135

tests/objvariant/tconstructionorder.nim
=> Add test for objvariant construction order

readme.md
I just think that it gets annoying after the fact I have removed the prefixing dollar signs whenever I setup Nim on a new machine.
=> Wouldn't it be less of a hassle like this?

lib/pure/asynchttpserver.nim
=> Handle failed uri parsing in asynchttpserver

lib/pure/collections/critbits.nim, lib/pure/collections/intsets.nim, lib/pure/collections/sets.nim, lib/system/cellsets.nim, tests/sets/tsets2.nim
=> Add counterpart to containsOrIncl for excl

compiler/ast.nim, compiler/vm.nim, compiler/vmdef.nim, compiler/vmgen.nim, tests/vm/tstring_openarray.nim
=> Fix operations on string as openarray in VM.

doc/manual/types.txt, doc/tut1.rst
=> Update docs on assignment operator

tests/vm/tvmmisc.nim
Added test-cases for these 3 issues
=> Closes #6083, closes #6086, closes #6379

lib/pure/options.nim
Adds the monadic bind operator to the options module.
=> Add flatMap operator to Options

lib/pure/json.nim
=> Fix deprecated json procs

lib/pure/times.nim, tests/stdlib/ttimes.nim
Fixes https://github.com/nim-lang/Nim/issues/6178
=> Fix countLeapYears

readme.md
=> improved wording style

changelog.md, lib/impure/re.nim
This catches out way too many people (including myself).
=> Remove reExtended from re constructor. Fixes #5627.

lib/pure/collections/sequtils.nim
Based on `strutils.count`.
This is my first PR and I tried to copy the style of other functions in `sequtils`, but if something needs to be changed/improved, let me know.
=> add `count` to sequtils

doc/manual/locking.txt
Solves [this](https://forum.nim-lang.org/t/3275) issue, brought up on Nim forum, which is also #6575.
=> fixes #6575

lib/pure/collections/sequtils.nim
- one letter parameter names
- parameter types are openArray where possible
- added missing tests and new tests for arrays as parameters
=> Sequtils improvements

readme.md
Felt the paragraph about contributing was grammatically awkward.
¯\_(ツ)_/¯
=> Updates to readme.

doc/manual/ffi.txt, doc/manual/locking.txt, doc/manual/modules.txt, doc/manual/pragmas.txt, doc/manual/procs.txt, doc/manual/templates.txt, doc/manual/threads.txt, doc/manual/type_bound_ops.txt, doc/manual/type_rel.txt, doc/manual/types.txt
Fixes broken links and typos.
Closes #4397
=> Tweeks in the manual

lib/system.nim
Add "Existing files will be cleared!" like in fmReadWriteExisting. 
Behavior tested under Linux.
=> Extend description of fmWrite

doc/manual/pragmas.txt
Haven't built the html locally but rst syntax is probably ok.
=> fix broken link in manual

compiler/parser.nim, doc/grammar.txt, tests/parser/tletcolon.nim
Curious to see if that already fixes #3827.
=> Block expressions

lib/pure/collections/heapqueue.nim, web/website.ini
Add copyright header to heapqueue modlue
=> Add heapqueue module to doc index

lib/system/atomics.nim
and use the correct interlocked exchange for bool
=> Fix cas when using vcc + cpp 

lib/system/sysstr.nim
fixes https://github.com/nim-lang/Nim/issues/6244
=> appending float to string now works on the VM

tools/niminst/makefile.tmpl
improves compatibility with cross compilation systems
=> use more make conventions

lib/pure/ospaths.nim, lib/pure/osproc.nim
Enables quoteShell on nimscript
as requested by @Araq on [IRC](https://irclogs.nim-lang.org/24-11-2017.html#12:23:22).
=> Move quoteShell to ospaths

lib/pure/net.nim, lib/windows/winlean.nim
Add OptNoDelay and usage example.
=> Add TCP_NODELAY support #6795

lib/pure/cgi.nim, lib/pure/uri.nim
=> Moved encodeUrl and decodeUrl from cgi to url

config/nimdoc.cfg
Related to #4219
This is a basic example. In future docgen could understand links between pages and allow users to easily add new ones.
=> Add links to documentation

lib/system.nim
programResult wasn't being honored by node backend.
I am not sure if there are tests for exit code?
=> Exit node with programResult

changelog.md, lib/pure/htmlgen.nim, lib/pure/strutils.nim
This is in line with Python.
Added some nice runnable examples to the ``split`` proc docs as well.
=> Fixes #4377.

config/nimdoc.cfg
Switch to Lato font for better readability
Make text darker
Make spacing between paragraph and pre block consistent
Example: https://cdn.rawgit.com/FedericoCeratto/db002f193d0f8ba311aab883adf7e9d3/raw/184a941377338094e82942c8f84631775bf1e4c3/httpclient.html
=> Update docgen style

lib/pure/json.nim, tests/stdlib/tjsonmacro.nim, tests/stdlib/tjsonmacro_reject.nim, tests/stdlib/tjsonmacro_reject2.nim
Please don't squash.
This fixes all the reported issues with the json.to macro.
=> Json to fixes

lib/pure/osproc.nim, tests/osproc/texecps.nim
This version uses much less syscalls and cpu, when multi core/cpu available.
=> Refactored version of osproc.execProcesses with test.

compiler/jsgen.nim, tests/js/tcodegendeclproc.nim, tests/js/tcodegendeclvar.nim
I am not sure how to test the output with regex in discard.
(I don't know if names are deterministic)
=> Implement codegenDecl for js

compiler/vmdeps.nim, tests/macros/tgettypeinst.nim
=> fix getTypeInst for tyGenericInst

lib/system/sysstr.nim
inline the call to setLengthSeq and avoid decref for types if ntfNoRefs
closes #6721 
This is my first attempted contribution to Nim so I especially appreciate any feedback. I think the check before the `forAllChildrenAux` is valid, but not positive.
with this code:
```Nim
import times
var N = 100000
var size = 200000
var a = newSeq[int](size)
var s:int
var t = cpuTime()
for i in 0..N:
a.set_len(size)
for k in 0..10:
a.set_len(0)
s += 1
s += a.len
echo cpuTime() - t
echo s
```
I get:
```
$ nim c -d:release --gc:v2 -r seqbench.nim
3.158566
1100011
$ nim c -d:release --gc:refc -r seqbench.nim
3.16616
1100011
$ nim c -d:release --gc:boehm -r seqbench.nim
3.202457
1100011
```
before this change, I get:
```
$ nim c -d:release --gc:v2 -r seqbench.nim
16.951686
1100011
$ nim c -d:release …
```
=> optimize setLen

tests/testament/tester.nim
=> Tester: added test duration output

lib/pure/parsecsv.nim
Name error, example didn't compile .
=> Name error in example

koch.nim, tests/testament/categories.nim, tests/testament/tester.nim
This is now failing the same set of tests on my machine as vanilla devel. If anything new fails in CI I'll fix it.
=> Prep for tester parallel: private nimcache for each test

lib/pure/unittest.nim, tests/stdlib/tunittest.nim
Support simple globbing.
Related to #5114
=> Add unittest suite/test name filters

compiler/extccomp.nim
=> add support for building GUI applications with TCC

lib/posix/posix_other.nim
My attempt at fixing this. No idea if it's valid.
=> Fixes `times` module compilation on cpp backend.

lib/pure/terminal.nim
If this PR will be merged then #6966 can be closed.
=> Windows: fix getch bug

lib/pure/net.nim, lib/wrappers/openssl.nim, tests/untestable/tssl.nim
Add methods for backward compatibility, to detect the running version, and simple online test.
Closes #5000
=> Add OpenSSL 1.1.0 support

lib/js/dom.nim
Hello,
I've found missing methods in JS backend.
Have a nice day.
=> add missing methods in js backend

readme.md
https://gratipay.news/the-end-cbfba8f50981
=> Gratipay is dead

lib/pure/strutils.nim, tests/stdlib/tstrutil.nim
Add parseHexStr and toHex and tests.
=> Add string-to-hex and back conversions

compiler/jsgen.nim, compiler/rodutils.nim, compiler/semfold.nim, tests/ccgbugs/t7079.nim
Turns out it wasn't a VM bug, but a codegen bug.
=> Fixes codegen bug with literal negative zero, fixes #7079

compiler/sempass2.nim
Noticed that breaksBlock is  unnecessary recursive.
Also previous version was checking every statement in statement lists.
It should be enough just to check only last statements.
=> Small performance improvement in sempass2

compiler/ccgstmts.nim, tests/exception/tfinally.nim
Looks like there is more exception bugs to be found #7204
Test is included
=> Nested finally bug fix. Fixes #7204
