nim-lang/Nim

- tests/types/taliasinequality.nim
previously the test comparing typedesc vs typedesc, and that is not what this test meant to.
now it is fixed, instance of tyenum vs tyenum
> fix taliasinequality test case

- lib/system.nim
Originally this procedure just said "oh it is so unsafe to use this" without actually mentioning what needs to be taken care of when using it. I put some information the programmer needs to take care of.
> Added few documentation lines for the unsafeAddr operator.

- lib/pure/collections/deques.nim
- tests/collections/tdeques.nim
Fixes compilation error when the `[]` operator is used on Deque object.
The error:
> lib/nim/pure/collections/deques.nim(83, 23) Error: undeclared field: 'first'
> Deques compilation error fix

- lib/impure/db_mysql.nim
The previous implementation of db_mysql fastRows had a bug - if a row in the query result had a null field, and the next row had a non-null field in the same column, a segfault would occur here:
```nimrod
setLen(result[i], 0)  # segfaults if result[i] == nil from previous row
```
I would like very much to avoid allocating the strings after nulls, but so far I haven't found any way in Nim to assign a string inside a seq without copying it.
If that would be possible we could just:
```nimrod
var
result = newRow(L)
backup = newRow(L)
if row[i] == nil:
backup[i] = result[i]  # somehow, copy only the reference here
result[i] = nil
```
and use the backup seq as a repository of strings to reuse.
> Fix segfault in db_mysql fastRows

- config/nimdoc.cfg
Should fix the issues mentioned here: https://forum.nim-lang.org/t/2877
There is also the question of why we're using xhtml rather than just HTML5, but that's out of the scope of this PR.
> Make fonts load from https rather than http

- tests/async/tioselectors.nim
Increasing timeouts 10x times, maybe it helps AppVeyor to perform simple operations in reasonable time.
> Fix tioselectors.nim test for appveyor.

- lib/pure/times.nim
- tests/js/ttimes.nim
Yearday 0 has no sense and contradicts the behaviour under C backend, where yearday is an int from 1 to 365, i.e. cannot be 0 even theoretically.
> Add yearday calculation to getLocalTime and getGMTime, so that yearday is not 0 for TimeInfo instances under JS backend.

- compiler/jsgen.nim
- compiler/jstypes.nim
- lib/system/reprjs.nim
- tests/js/trepr.nim
~~**THIS IS NOT COMPLETE YET**~~
I have been working on implementing `repr` for the js backend, to close [#343](https://github.com/nim-lang/Nim/issues/343).  
I open this pr before finishing, to allow for feedback on the way I implemented this, as I am sure there are other ways to implement this that may be better/easier. I'm also not so sure about my approach here, as C made use of a lot of pointers arithmetic that I couldn't get to replicate in JS
I tried to match the output of `repr` in the C backend, but I took some liberties:
- strings aren't prefixed by a pointer
- seqs are prefixed by a `@` instead of a pointer
- `nil` strings are represented as `nil` instead of `""`. This is because strings in an empty array are represented as `nil` ( in C backend ), and also because I think an …
> Implementing `repr` for JS

- lib/posix/posix.nim
Fix `sigtimedwait` to use direct syscall to **__NR_rt_sigtimedwait** (available since Android SDK L3).
Testing needed...
> Proper fix for osproc.nim on Android

- lib/genode_cpp/threads.h
- lib/system/threads.nim
While PR #5560 was open the allocation of some thread metadata changed at 254fbcc548247865cf15200a200436024258e647.
> fix thread metadata allocation for genode

- lib/system.nim
Documentation for proc compiles showed a broken/unintuitive example (unless i missed something)
> Update 'compiles' documentation to remove not

- lib/pure/asyncfile.nim
- lib/system.nim
- lib/system/sysio.nim
- tests/async/tasyncfile.nim
Platform independent procedure to set a file length. Useful when
replacing file content.
> asyncfile: setLen procedure for files

- compiler/semexprs.nim
- tests/tuples/tuple_subscript.nim
The fix turned out to be rather simple to make. semArrayAccess already does overloaded subscript if semSubscript returns nil, so the only required change was to make semSubscript return nil instead of throwing exception
> Fix for #5695 make subscript operator overloadable for tuples

- lib/pure/base64.nim
Changed `var` to `let` in some places, changed deprecated `stmt` and `expr`, put variables declaration into one block, removed `{.immediate.}` pragma
> Small base64.nim refactor

- lib/pure/asyncdispatch.nim
- lib/pure/asyncnet.nim
- lib/pure/httpclient.nim
- lib/pure/includes/asynccommon.nim
- lib/pure/nativesockets.nim
- lib/pure/net.nim
- lib/pure/uri.nim
- lib/upcoming/asyncdispatch.nim
- lib/windows/winlean.nim
- tests/async/tasyncdial.nim
- tests/stdlib/thttpclient.nim
- tests/stdlib/tnetdial.nim
- web/news/e031_version_0_16_2.rst
Added ``dial`` procedure to networking modules: ``net``, ``asyncdispatch``,
``asyncnet``. It merges socket creation, address resolution, and connection
into single step. When using ``dial``, you don't have to worry about
IPv4 vs IPv6 problem.
Fixed addrInfo loop in connect to behave properly.
Previously it would stop on first non-immediate failure, instead of
continuing and trying the remaining addresses.
Fixed newAsyncNativeSocket to raise proper error if socket creation
fails.
Fixes: #3811
> Implement dial, support IPv6 in httpclient

- lib/pure/parseutils.nim
The documentation for the `parseutils` module's `captureBetween` procedure isn't rendering properly, as can [be seen in the docs][1]. Adding the missing space character fixes it.
[1]: https://nim-lang.org/docs/parseutils.html#captureBetween
> Add space to fix RST in captureBetween docs

- lib/pure/asyncdispatch.nim
- lib/upcoming/asyncdispatch.nim
This can be abused. It is important to deregister all file-descriptors and exhaust all events *before* calling this. But it works fine. Not urgent, but this makes it possible to run `posix.fork()` after using (and cleaning up) asyncdispatch.
re: #5717
> setGlobalDispatcher()

- compiler/jsgen.nim
- compiler/jstypes.nim
2 bugs:
* `SetConstr` changed to `setConstr`
* Don't reset `global.unique` because otherwise `ConstSet`s from different modules share common identifiers in the resulting JS and thus overwrite each other.
> Fixed const sets in JS

- lib/system/syslocks.nim
Reimplemented #5803 in a way that should be impossible to misuse.
> Fixed syslocks for ios

- lib/pure/strutils.nim
Added line: "If ``precision == 0``, it tries to format it nicely." (copied from formatBiggestFloat())
> Extend documentation of formatFloat()

- lib/pure/parsecfg.nim
Fixes #5816 
This works for me.
> Use writeable file in parsecfg.writeConfig()

- lib/pure/ospaths.nim
- web/news/e031_version_0_16_2.rst
I added a check for the `XDG_CONFIG_DIR` environment variable to meet the [freedesktop XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).
> Modified ospath's getConfigDir to meet XDG spec

- lib/pure/asyncdispatch.nim
- tests/async/tasyncall.nim
waitFor can now wait on a sequence of async procedures
waitAll waits on all existing async procs
runningAsyncProcedures and showRunningAsyncProcedures are helpers
Switch tasyncall.nim to unittest, speed it up and add new tests
> Add waitFor on seq[Future], waitAll and more

- compiler/cgen.nim
This avoids a -Wstrict-prototypes warning in the generated C file.
> Create correct C protoypes in genMainProc.

- compiler/semstmts.nim
- lib/pure/asyncmacro.nim
- tests/async/tasync_forward.nim
- Fixed pragma handling. Line 380. Previously proc body was used as pragma.
- Cosmetics. Replaced indexed proc subnodes access to named access for better readability.
- Added `gcsafe` pragma to the iterator to make gc unsafety errors more informative.
Please review carefully :)
> Async macro fixes

- tools/niminst/niminst.nim
Right now the nim-0.17.0.tar.xz is 24 MB. After this change it should be 4 MB. On my local machine time to extract improves from 2.3 s to 0.9 s.
> Invoke xz -9 explicitly instead of trusting tar to interpret XZ_OPT

- lib/core/macros.nim
- tests/macros/tnewlit.nim
Improved the type correctness of ``newLit``. The resulting literal has the exact same type as the argument value. Also made newLit work for object tuple array and seq types. That does not allow newLit correct and implemented for all types (no ref types or ptr types) but it allows it for a big majority of value types. The reason I changed the implementation of newLit for integer types is, without the change a value of ``int8`` would be translated in a normal ``int`` literal and that is not correct. It causes problems when the first element of an array is translated from ``1'i8`` to a normal integer literal ``1``.
> more and improved newLit procs in macros module

- doc/nims.rst
Whilst reading the docs I thought there must be a way to run them with a portable shebang line - I discovered that this did exists and was mentioned in #3301 but not documented anywhere.
I find it a little weird it doesn't work with non `.nims` filenames, this stops nimscript from replacing some kinds of scripts where the filename is fixed. Using `#!/usr/bin/env nim e` isn't possible as not all implementations of `env` allow extra arguments.
> Documented shebang execution of Nimscripts

- lib/pure/parsecfg.nim
File is already being closed by defer: file.close() closing it twice causes crash.
Fixes #5906
> Remove redundant filestream.close, causes crash

- compiler/ccgexprs.nim
- tests/arithm/tshr.nim
fixes last issue in #5915 
signed int must first be cast as unsigned before converting to larger
integer.
C compiler will auto convert operands to largest type.
> fix right shift c codegen bug.

- compiler/trees.nim
- compiler/vm.nim
- lib/core/macros.nim
- tests/macros/tnodecompare.nim
It was already possible to get the comment of a ``nnkCommentStmt`` node with ``strVal``, now it is also possible to compare such nodes, set their value with ``strVal=``, and create such a node with ``newCommentStmtNode``.
> improved comment satement support in macros

- compiler/semexprs.nim
- tests/misc/tcast.nim
This commit forbid casting a closure to anything other than another
closure. use rawEnv/rawProc to access underlaying pointers.
This solve issue #5742
> restrict casting for closure.

- lib/system/mmdisp.nim
Back in October 13 2016, gccgo changed the struct "mstats" when importing code from the Go 1.7 runtime. This broke our getFreeMem() and related functions.
> support libgo from GCC 6.3

- compiler/cgen.nim
This is a followup to issue #5171.
I've recently built a number of linux-musl-gcc-6.3.0 cross toolchains,
and by inspecting the output of each compiler's "gcc -E -dM - < /dev/null"
and "g++ -E -dM - < /dev/null" I have found that the following
non-underscored symbols are predefined in some configurations:
#define LANGUAGE_C 1
#define MIPSEB 1
#define MIPSEL 1
#define PPC 1
#define R3000 1
#define R4000 1
#define i386 1
#define linux 1
#define mips 1
#define powerpc 1
#define unix 1
> cgen: #undef some more predefined symbols.

- lib/pure/asynchttpserver.nim
A empty (http response) headers should be a valid (empty) newline.
```nim
HTTP/1.1 400 Bad Request\c\L
\c\L
```
> Fix bad tail for status response

- lib/system.nim
`y` was undocumented and `x` is the destination not the source as the documentation suggested.
> Fix `deepCopy` incorrect argument description.

- tools/niminst/makefile.tmpl
This changes the indentation of all non-recipe lines from tabs to 2 spaces. While this doesn't fix anything, it avoids either make or someone interpreting those lines as a make recipe.
This also fixes the error handling by using make's $(error) function instead. Previously make gave this syntax error whenever it hit the error handling code:
```
*** recipe commences before first target.  Stop.
```
---
Discovered this while adding mips64 support to makefile.tmpl. One other issue I noticed was this on line 48:
```
ifeq ($HOSTTYPE,x86_64)
```
This is clearly wrong because `$HOSTTYPE` = `$(H)OSTYPE` so the condition can never be true. I'm not sure what it should be instead though since `HOSTTYPE` doesn't seem to be defined anywhere.
> makefile.tmpl: fix error handling and cleanups

- lib/pure/os.nim
- lib/windows/winlean.nim
Added `moveDir` which is mostly a copy-paste of `moveFile`, but falls back to `copyDir/removeDir` on `EXDEV` error.
Removed extra `include ospaths`
> Added moveDir

- tests/async/tioselectors.nim
This is one more attempt to fix annoying tioselectors.nim test.
In this variant we will switch to kernel with calls to `sleep()`, so windows kernel will be able to handle both sockets properly.
> One more attempt to fix tioselectors.nim test

- lib/core/macros.nim
- tests/macros/tnewlit.nim
newLit on an empty seq does not loose type information anymore.
```Nim
var s = newSeq[string](0)
newLit(s)
> newLit emty seq fix

- lib/pure/parsecfg.nim
- tests/stdlib/tparsecfg.nim
this patch allow for something like
```text
bar=-1
name=-abc
```
> fixes #6046 parsecfg failed to parse negative int

- lib/posix/posix_other.nim
- lib/pure/os.nim
The Genode readdir is inherited from then FreeBSD libc.
> Genode readdir fix

- lib/pure/asyncdispatch.nim
- lib/pure/asyncfutures.nim
- lib/pure/asyncstreams.nim
- lib/upcoming/asyncdispatch.nim
- tests/async/tasyncrecursion.nim
- tests/async/tcallbacks.nim
(For issue #5731)
This slightly changes behaviour of callSoon - before loop is initialized, callSoon will call the function immediately.
> [WIP] Better Future

- lib/system/threads.nim
Cache threadId to not perform syscalls all the time
Use syscall to get threadId for FreeBSD and MacOS
> Cache threadId to not perform syscalls all the time in threads.nim

- compiler/msgs.nim
- compiler/vm.nim
- compiler/vmdef.nim
- compiler/vmgen.nim
- lib/core/macros.nim
- test.nim
- tests/method/tmapper.nim
- tests/modules/tmismatchedvisibility.nim
- tests/pragmas/tused.nim
- tests/showoff/tquasiquote.nim
lineInfoObj now return an object with fields that were perviously contained in the lineinfo string. This is more flexible in case the lines need to be processed further in a macro.
> Lineinfo change

- lib/pure/concurrency/threadpool.nim
This reverts commit bdb653c4156af099814df2e21b9878cdb1591190.
Unfortunately my initial implementation turned out to be completely incorrect. `pinnedSpawn` has nothing to do with previously spawned threads. I'll try to redo it, but it may take some time.
> Revert "GC_fullCollect on sync threadpool (#6107)"

- lib/core/locks.nim
This allows using locks without `--threads:on`. Otherwise weird things happen.
> Disable stacktrace in locks

- lib/core/macros.nim
- tests/macros/tdumpastgen.nim
This allows those writing macros to write examples, get the code to generate the AST for that example, and then modify that code to be dynamic with the macro function.
> Added codeRepr and dumpCode to the macros module.

- lib/pure/random.nim
Critical bug. On 32bit targets randomize did not have any effect.
> Fixed randomize for 32bit target

- compiler/vm.nim
- compiler/vmdef.nim
- compiler/vmgen.nim
- tests/vm/tzero_extend.nim
This should fix the remaining issues with those proc in the VM.
For fixing ``toUXX``, I had to create a new opcode opcToNarrowInt for this.
the algorithm is fairly simple: 
```
-((i8 and 0xFF) xor 0x7F) + 0x7F # for uint8
```
I tried to generate the relevant instructions in vmgen, but it was slow and buggy.
> Vm fix zero extend proc ze/ze64 && toU32/toU16/toU8

- compiler/installer.ini
- compiler/platform.nim
- lib/posix/posix_other.nim
- lib/system.nim
- lib/system/platforms.nim
- tools/niminst/buildsh.tmpl
- tools/niminst/makefile.tmpl
This PR is based on #5830, so that must be merged before this one.
---
This adds the definitions for mips64 and mips64el cpu platforms (using the n64 MIPS ABI). It then adjusts the niminst templates to correctly detect the right mips platform using the C compiler. Unfortunately there isn't really another good way to do this which works reliably.
I've run the testsuite on mips64el and the majority of tests pass except for the dll tests. I'm still looking at this but I'm not yet sure who is to blame for it yet - it might be a toolchain bug.
> Add mips64 and mips64el CPU platforms

- lib/system/threads.nim
We went past the default boundary in our application.
> Allow to configure tls size

- tests/arithm/tshr.nim
the first assert in `tests/arithm/tshr.nim` checks against a nim `int` literal and then assumes that an `int` in Nim is always 64-bit. This breaks the test on platforms that are not 64-bit.
E.g. this causes #5772 test runs on Android ARMv7 systems to fail, since they use a 32-bit OS.
> Removed platform-specific arithm test cases

- readme.md
Fixed link to github contributors page
Without it contributors image would point to https://github.com/nim-lang/Nim/blob/devel/graphs/contributors which isn't a correct link
> Small fix to README

- config/nim.cfg
VCC, aka. `Microsoft (R) C/C++ Optimizing Compiler` uses nearly identical command-lines for both C and C++.
For C++, all compiler options pass the `/EHsc` option to the compiler for C++ exception handling.  
From [MSDN - /EH (Exception Handling Model)](https://msdn.microsoft.com/en-us/library/1deeycx5.aspx):
> **`/EHsc`**: catches C++ exceptions only and tells the compiler to assume that functions declared as `extern "C"` never throw a C++ exception.
> Added missing C++ options for VCC

- lib/pure/ospaths.nim
when using nimscipt `createDir` is not declared in `ospaths`
Disabled implcit creation of a temporay directory when `os` is not declared.
> fixed createDir undeclared error on Android

- compiler/vmgen.nim
This PR fixes issue #6197 as well a few others concerning differences in hashing between VM and compiled code. 
This commit change the default behaviour of VM from int/uint always being
64bits to make int/uint on VM behave identically to compiled code.
This insert 'opcNarrowU' or 'opcNarrow' opcode on Int/Uint operations
when needed to simulate smaller Int/Uint on VM.
> fix VM intsize for 32bits and smaller targetOS.

- compiler/ccgtypes.nim
before this it was just "TY". This is for easier debugger integration, but also more meaningful names for generated type names.
solves: https://github.com/nim-lang/Nim/issues/6202
> type kind is now part of the generated name for types

- compiler/semexprs.nim
- tests/vm/tmitems.nim
this discard any implicit conversion on iterator return value.
the previous behaviour was to return a reference to a converted copy and
thus not modifying the original value.
This  PR fixes issues #4741 & #5013
This is probably not the desired fix , but I didn't see any issue running the tests.
> fixes mitems iterator on vm. (issue with returning tuple value)

- compiler/semtypes.nim
This fixes issue platform dependant type alignment issue https://github.com/nim-lang/Nim/issues/6094 in order to make PR https://github.com/nim-lang/Nim/pull/5664 usable.
An additional hurdle (only gcc-like compiler)  is passing (via passC) -malign-double to the C compiler which force 64bits type (int and float) alignment to 8bytes (this is the default on x64_86)
This would make the code return a different alignment value from the c compiled code.
It's probably not a particularly important issue, since it's pretty dangerous to use on i386 (ABI compatibility issues, etc...) and not used often, but its better to warn in advance.
> fixes 64bits type alignement issue on i386 platform.

- config/nim.cfg
Instead of having duplicate settings for all platforms, use `%=` instead to avoid redundencies
> Nim Configuration cleanup for VCC

- doc/lib.rst
Per [this](https://github.com/nim-lang/Nim/blob/d4e766c8dca5ebe6a11f8f60b93c8126166fbfc0/web/news/e017_version_0_12_0.rst) version - libcurl isn't in stdlib and the nim web page (obviously) doesn't go anywhere useful given that libcurl isn't in stdlib anymore
> libcurl is available via nimble, doc isn't in stdlib any more

- compiler/ccgexprs.nim
- compiler/vm.nim
- tests/vm/tseq_badinit.nim
This fixes issue #6083 
seq.setLen in VM now correctly initialize elements to their default value.
(ptr and ref object are not supported yet in VM)
This also fixes an issue with c code generation for partially initialized array of closure at compile time.
> Fix seq.setLen initialisation in VM

- tools/niminst/buildsh.tmpl
It turns out that `uname -o` which should return the operating system name is a non-standardized addition to `uname` and thus is not guaranteed to be supported on all POSIX systems. E.g.: Usage of `uname -o` breaks the build on Mac OSX.
**Workaround:** Call `build.sh` with command-line arguments like shown in the following example for android:
``` bash
sh ./build.sh --osname android
```
> Revert usage of non-standard `uname -o` command in build.sh

- lib/pure/json.nim
New versions of closure compiler are complaining about this:
```
ERROR - variable property is undeclared
for (property in x_780603) {
^^^^^^^^
```
> Fixed closure compiler incompatibility

- doc/manual/lexing.txt
- Clarified that identifiers are only case insensitive for ASCII characters
- Removed mention of dash-style, since it has been removed
> Corrected manual (Identifier equality)

- lib/pure/strutils.nim
- tests/stdlib/tstrutil.nim
I'm sorry, I introduced a bug in https://github.com/nim-lang/Nim/pull/5470 when I wanted to make it equal to ``len(splitLines(s))``.
Did nobody notice this?
Addition: test cases added
> Fix wrong result of countLines()

- lib/system.nim
Add missing doc for slice functions. I think this is sufficient to close this out given the docs that now exist in the manual for this: https://nim-lang.org/docs/tut1.html#advanced-types-slices. 
Fixes #1917
> Document inclusiveness of Slices

- lib/pure/json.nim
- tests/stdlib/tmarshal.nim
This PR makes JSON output nicer by preserving UTF8 char sequences, according to [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf), except for `/` char for aesthetical reasons.
> Changed JSON stringification to preserve UTF

- lib/genode_cpp/threads.h
- lib/system.nim
- lib/system/threads.nim
The Genode OS permanently pins every thread to a CPU, the scheduler does not move threads around to load balance. This patch pins new threads in a round-robin manner. It also defines ``paramCount`` and ``paramStr`` for Genode.
> balance Genode CPU pinning, deadlock at Genode exit

- lib/pure/collections/sets.nim
- Added excl(key) to OrderedSet
- Added pairs() iterator to OrderedSet
I noticed that `proc incl*[A](s: var HashSet[A], other: OrderedSet[A])` is a bit strange, since it takes one of each set type instead of two of the same like `proc incl*[A](s: var HashSet[A], other: HashSet[A])`. The doc-comment implies that the first is incorrect.
> Sets enhancements, fixes #2467

- lib/pure/nativesockets.nim
Test them by:
```nim
import nativesockets, net
var sock = newSocket(AF_INET6)
sock.bindAddr(Port(0), "::1")
assert sock.getLocalAddr()[0] == "::1"
```
> Fix `getPeerAddr()` `getPeerAddr()`: +`sin6_addr`

- lib/system.nim
Currently `quit(x)` emits `exit(x)` for node, which is incorrect. Emit process.exit instead
> Fix node quit

- lib/pure/json.nim
Reason: Someone might think that `parseJson*(s: Stream, filename: string): JsonNode` is only for files. Whereas it can be also used with `resp.bodyStream`.
This way calling `bodyStream.readAll()` and then `newStringStream(buffer)` is avoided.
Another way would be to overload it with `parseJson*(s: Stream): JsonNode`.
> Add default value for filename in parseJson proc

- lib/pure/unittest.nim
- tests/stdlib/tunittest.nim
- `check` no longer attempts to break out expressions from `or` & `and` to avoid messing up short circuiting (fixes #5784)
- checkpoints are generated for more expression types (e.g `foo.len == 3` and `foo[0] == 3` will now generate checkpoints)
- some general cleanup (prefer `let` over `var`, prefer returning a tuple over mutating outer variables, prefere `quote do` over `getAst(tmpl(...))`)
`check a.isNil or a.field == 3` is still not very useful, since it won't generate a checkpoint for `a.field`'s value. I don't think it's a good idea to attempt to generate checkpoints for that case, because it would make an already complex macro much more complex.
Perhaps there should be a different template/macro for running some checks iff an expression evaluates to true, and otherwise fail …
> Improved unittest check macro, fixes #5784

- compiler/commands.nim
Closes #6298 
This makes the Nim CLI conform with the majority of other tools' `version` commands.
> direct `nim --version` to stdout rather than stderr

- lib/pure/times.nim
Seems like [tzset](http://man7.org/linux/man-pages/man3/tzset.3.html) must be called to initialize the timezone variable.
> Fixes #6450

- lib/pure/times.nim
- lib/system.nim
- lib/system/ansi_c.nim
- lib/system/sysio.nim
- lib/windows/winlean.nim
clang can parse the windows headers from the windows kits and link aganst the MS C runtime. There are some places in nim that use when defined(vcc) instead of when defined(windows). I think these should be switched over, and I think these symbols exist in the mingw headers as well.
Do not merge yet, we should run the test suite on all supported windows toolchains first.
> [RFC] [Patch] Allow clang with msvc abi and headers

- compiler/commands.nim
- doc/basicopt.txt
- tools/nim.zsh-completion
This adds the missing nilChecks option when compiling as mentioned in #6479
Question nil checks are on by default even in release mode, I didn't change nim cfg, but isn't supposed to be turned off there in release builds?
> Add missing nilChecks compiling option closes #6479

- lib/system/assign.nim
This is roughly an idea, work must be reviewed.
Test case is the same in #6433
```Nim
import times, sequtils
proc newSeqUninitialized[T](len: Natural): seq[T] {.noSideEffect,inline.}=
result = newSeqOfCap[T](len)
result.setLen(len)
let size = 1000000
var data = newSeqWith(size, -3.67'f32)
var s1, s2 : seq[float32]
var start: float
start = cpuTime()
for i in 0..<10000:
s1 = newSeqUninitialized[float32](size)
copyMem(s1[0].addr, data[0].addr, size*sizeof(float32))
echo "copymem ", cpuTime() - start
start = cpuTime()
for i in 0..<10000:
s2 = data
echo "assignment ", cpuTime() - start
assert s1[0] == s2[0]
assert s1[size-1] == s2[size-1]
```
Before this patch:
```
copymem 2.427948
assignment 4.052885
```
After this patch:
```
copymem 2.575448
assignment 2.451823
```
> Futher improve seq assingment speed #6433 by 2x factor

- tests/stdlib/ttimes.nim
Added tests for formatting timezones with DST. Closes #3199. #3200 already had a test, so it can also be closed.
I commented out one of the tests because it's failing appveyor (https://github.com/nim-lang/Nim/pull/6459). I can't reproduce it on my machine. It didn't fail before because the test was only compiled, not executed.
> Add dst formatting tests

- compiler/ccgexprs.nim
- compiler/rodutils.nim
- lib/pure/nativesockets.nim
- lib/pure/os.nim
- lib/system.nim
- lib/system/repr.nim
- tests/async/tnewasyncudp.nim
- tests/gc/gctest.nim
- tests/misc/treadx.nim
- tests/system/toString.nim
fixes https://github.com/nim-lang/Nim/issues/5828
```
echo([1,2,3])
```
The result of ``$`` on array of char is now something that might need some discussion. Because by thefault `$` on `char` creates a string of one unescaped character, the resulting string might be of length 1, but with the `'\0'` as only character. If this string is concatenated into the result, the result is literally a string with a terminating `\0` in the middle.
> arrays can now be printed

- lib/pure/collections/lists.nim
This is subjective of course, but I dislike how many `{.dirty.}` templates are used in the standard library. I made an attempt to refactor the lists module to use type classes instead (where possible). It's less code, less duplicated doc comments, and (imo) more readable.
> Refac of lists module

- lib/pure/collections/sequtils.nim
As per discussion in #6558, the names of seqs are changed to `list`.
Other than that, some small cosmetic changes - update dead links, space around `..`.
> `sequtils` - change parameter name to `list`

- lib/pure/strutils.nim
Add the alignLeft proc to mirror the already existing align proc (which does right-alignment)
*Moved here into its own seperate PR from [original PR #6023](https://github.com/nim-lang/Nim/pull/6023)*
*Includes changes from https://github.com/nim-lang/Nim/pull/6023#pullrequestreview-46885169 by @euantorano*
> Add left-aligning string proc to strutils

- lib/pure/strutils.nim
`removeSuffix` code blocks where missing a newline before them so they weren't highlighted,  
eg. https://nim-lang.org/docs/strutils.html#removeSuffix,string,set[char]
> Highlight `removeSuffix` code blocks in docs

- lib/pure/strutils.nim
- tests/stdlib/tstrutil.nim
if we encounter a character that does not satisfy the proc, we return immediately, without continuing to loop over the rest of the chars in the string.
> isAlphaNumberic and isDigit improvement + tests

- compiler/cgen.nim
- lib/pure/unittest.nim
- lib/system.nim
Genode components do not quit by default, they must persist after the main procedure to serve RPC requests. I would also like to define a Genode only effect in system.nim to mark procedures that invoke RPC as a client.
Finally, unittest uses paramCount not as indicated.
> No implicit quit for Genode

- koch.nim
While trying to fix another bug the 'koch temp' command failed to build the freshly checkedout devel branch because my installed nim didn't know a procedure used in the development standard lib. This enables 'koch temp' to use a version of nim generated by 'koch boot'
> Use findNim() in koch temp()

- lib/pure/strutils.nim
The find function with a precalculated table is useful for repeating the substring search.
Some benchmarks on my PC (ArchLinux x64, gcc 7.2):
Call | Current implementation | With this PR
------------ | -------------|----------
find("1234567890abcdef", "abc") | 19915.0 | 12176.0
find("1234567890abcdef", "a") | 15121.0 | 675.0
find("abc", "1234567890abcdef") | 9987.9 | 325.0
> strutils.find enhancements

- compiler/commands.nim
- tests/testament/categories.nim
- tools/nimresolve.nim
If the length of ``NIMBLE_DIR`` is larger than zero, the nimblepath
will be set to ``$NIMBLE_DIR/pkgs``, only when ``passPP``.
See nim-lang/nimble#340
> Let the environment variable NIMBLE_DIR overrides nimblepath in cfg file

- lib/pure/strutils.nim
Note: The [solutions suggested on StackOverflow](https://stackoverflow.com/a/31332367/1804173) (using `_set_output_format`) are probably not a good idea, because the function is obsolete and has been removed in the latest Visual Studio Compile. Thus, the simple post-processing should be the easiest fix.
> fixes #6589

- lib/pure/algorithm.nim
This is a reimplementation of `std::rotate` from c++. It should make c++ developers feel more at home. It is just a port of the reference implementation shown in the c++ docs here: http://www.cplusplus.com/reference/algorithm/rotate/
The reason I implemented this, was that I thought several times a rotate function would be the thing to solve the current problem, but I couldn't find it in algorithm.
I am not 100% happy with the API yet. It does copy the c++ api, but with indices instead of iterators. The problem is that the API has exclusive upper bounds, and that is not in sync with the rest of the nim API.
The only solution that I can think of, is to change the arguments to `first`, `last`, `offset`. But then I would also rather call it rotateLeft, so that the offset cannot be …
> added rotate in algorithm

- lib/system.nim
- tests/system/tsystem_misc.nim
For generic functions which operate on both integers or floats it would be nice to have a definition of `high` and `low` for floats as well. This would make the [Q/A I've posted on StackOverflow today](https://stackoverflow.com/q/46875488/1804173) even more simple.
Note: The procs cannot be moved easily at the top where the other `high`/`low` procs are defined, because it depends on `Inf` and `NegInf`, which in turn depends on the definition of `/` => too much re-ordering required.
> Implementation of high/low for SomeReal

- lib/pure/strutils.nim
- tests/stdlib/tstrutil.nim
Ref #6473 ([specific comment](https://github.com/nim-lang/Nim/pull/6473#discussion_r143852016))
`char` and `set[char]` versions now remove all occurrences of the `char`(s) at the end of a string, matching the implementations used in the new `removePrefix` proc.
> Update `removeSuffix` implementations to match `removePrefix`

- lib/pure/rationals.nim
Hey thanks for merging my previous PR. However when I tried to translate the C source I made some errors, because I was inexperienced. I tried [here](https://gist.github.com/konqoro/1c9717abdea5d3a6eb79f088cb54fd76) again using the proper C types.
Though in this PR, the matrices are of type  `int ` in order to return `Rational[int]`. I kept the range checks to `high(int32)`, in an effort to prevent overflows. Something like `toRational(high(int).float)` can still crash it.
> Make toRational proc to loop through integers

- lib/pure/net.nim
If `SSLShutdown` returns an error, we're freeing `sslHandle`, and calling `socketError` which tries to use the nil handle and crashes.
> Fixed crash in case of error in SSLShutdown

- config/nim.cfg
`vcc.options.debug` is not automatically triggered for non-release builds. Therefore, move the `/Zi` (create Program Database) and `/FS` serialize PDB output compiler flags to a more general case.
`vcc.options.debug` now only affects the VCC code optimizer by specifying `/Od` (no optimization).
This change enables easy step-by-step debugging through the generated C code, while incurring no additional size to the resulting binary (as all debug information is stored in a separate .pdb file). This will be the first step to enable full Nim-PDB support for the Windows Native Debugger.
Next, replace `/Zi /FS` with `/Z7` (see [/Z7, /Zi, /ZI (Debug Information Format)](https://msdn.microsoft.com/en-us/library/958x11bc.aspx)) to store the debug information in the generated `.obj` instead of a …
> VCC always creates debug symbols when not in release

- tests/testament/categories.nim
With this change it's possible to run a single JS test file instead of always running the entire category.
> Always compile tests in the JS category with the JS backend

- config/nim.cfg
- lib/pure/osproc.nim
`system/bin/sh` is the correct path for `sh` on Android regardless of termux.
> Fix path for sh on Android

- lib/pure/strutils.nim
Implements #6503:
Adds optional `maxsplit` parameter `splitWhitespace` iterator and proc.
Also adds a few simple tests for this functionality
> Adds optional maxsplit parameter to splitWhitespace (#6503)

- lib/pure/httpclient.nim
This version fixes proxy support for SSL connections by moving all proxy interactions into the ```newConnection()``` proc instead of in ```requestAux()```.
Tested both HTTP and HTTPS sites directly and thru proxy to verify nothing broke. Ran against hundreds of sites using the following test code. Compile and run with a starter URL which program will search for URLs. 
```> nim c -r -d:ssl --threads:on test.nim http://reddit.com```
```nim
import htmlparser, httpclient, ospaths, os, re, streams, strtabs, strutils, threadpool, xmltree
proc getU(url: string): string =
try:
let proxystr = getenv("http_proxy")
let proxy = if proxystr != "": newProxy(proxystr) else: nil
let cl = newHttpClient(proxy=proxy)
result = cl.getContent(url)
echo "PASS: " & url
except:
result = ""
echo …
```
> Fix for #6685

- compiler/cgen.nim
This fixes linker error when building [glut_example.nim](https://github.com/nim-lang/opengl/blob/master/examples/glut_example.nim) with cpp backend (using `dynlib` mechanism).  Definition of `nimLoadProcs0` requires C linkage since declaraction of [`nimLoadProcs0`](https://github.com/nim-lang/opengl/blob/e1283c7800b00372ee0e218a42212370adc37593/src/opengl/private/prelude.nim#L83) uses `{.importc.}`
> Fix definition of nimLoadProcs when using cpp backend

- lib/packages/docutils/rstgen.nim
Add the possibility to add a class `lang<Name>` to code listings.
Needed for restricting `run` to nim code (see https://github.com/nim-lang/nimforum/pull/111 )
> Add possibility to get language class in listings

- lib/system/excpt.nim
When using `-d:useNimRtl`, stack traces are useless ("No stack traceback available").
This can be verified when compiling this example program in addition to `libnimrtl.so`:
```nim
template fuzzy(x) =
echo x[] != 9
var p: ptr int
fuzzy p       # will segfault on purpose, however "no stack traceback is available"
```
Compile with `nim c -d:useNimRtl test_segfault.nim`  and `nim c -o:libnimrtl.so nim-repo/lib/nimrtl.nim`.
Start (on linux) with `LD_LIBRARY_PATH=/path/to/libnimrtl.so  ./test_segfault`
This happens because two instances of `framePtr` exist at the same time: one from `libnimrtl.so`, and one from the test program (I ended up seeing this when `printf`ing my way around and checking the generated c files). There is also two `signalHandler` present, the one from test_segfault is the …
> Fix missing stacktraces when using -d:useNimRtl

- lib/pure/os.nim
Related to #6066 
Also puts argv and argc in theindex.html to make paramStr and paramCount easier to discover when searching the index.
> Clarify paramStr / paramCount use and availability

- tests/async/tasyncsend4757.nim
This test depends on example.com site to be reachable, and fails when
there is no internet connection.
> Tests should not rely on external services

- tests/stdlib/thttpclient.nim
- tests/testament/specs.nim
The `thttpclient` causes AppVeyor tests to fail. Disabling that test when running on AppVeyor.
For that a new value for the test-spec disabled key is introduced: `appveyor`. Similar to `travis` it checks for the existance of the `APPVEYOR` environment variable.
> Appveyor thttpclient

- doc/manual/generics.txt
- doc/manual/pragmas.txt
- doc/manual/type_sections.txt
- doc/tut1.rst
- doc/tut2.rst
I've update all codes that uses the following:
```Nim
type
Node = ref NodeObj
NodeObj = object
le, ri: Node
data: int
```
to this simpler syntax
```Nim
type
Node = ref object
le, ri: Node
data: int
```
I also updated the non-working generics example in the manual to something that works in tut2:
Manual:
```Nim
type
BinaryTreeObj[T] = object    # BinaryTreeObj is a generic type with
le, ri: BinaryTree[T]      # left and right subtrees; may be nil
data: T                    # the data stored in a node
BinaryTree[T] = ref BinaryTreeObj[T] # a shorthand for notational convenience
proc newNode[T](data: T): BinaryTree[T] = # constructor for a node
new(result)
result.data = data
proc add[T](root: var BinaryTree[T], n: BinaryTree[T]) =
if root == nil:
root = n
else:
var it = root
while it != nil: …
```
> Documentation: directly use ref object + fields

- lib/pure/uri.nim
When the hostname and path fields are set, handle missing or extra
slashes to generate valid URLs.
> Make Uri rendering more lenient. Closes #6652

- lib/pure/strutils.nim
It looks like the issue with #6589 is not VCC specific, but a general Windows runtime problem.
> Fixes #6589 again

- compiler/sigmatch.nim
- tests/overload/tstatic_with_converter.nim
Fix compiler crash on complicated use case with overloaded functions with static arguments, converters and imported from c incomplete types.
As far as tell: aOrig.n.typ is nil because aOrig.n has incomplete type after autoconverter from float to vfloat. Multiple procs required to trigger overload resolution.
Test cases included
> Fix compiler crash (#6773)

- doc/lib.rst
Update to list Distros module in the manual
I was updating some nim packages that I needed for Mac compatibility, and it took me a long time to find the correct way to write platform specific #ifdef code. I figured it out by looking at other nim projects like the nim-glfw project.
I tracked down the ```macosx``` constant to the ```distros``` module, but I didn't find it easily listed in the docs anywhere.
This is my attempt to add the ```distros``` module to the main docs page to make it easier to find for other people.
I hope my description and placement of the module is correct.
Thanks,
Ray
> Update to list Distros module in the manual

- lib/pure/browsers.nim
All these utilities where replaced by xdg-open from package xdg-utils in Linux and the BSDs.
Checked: CentOS,  Solaris,  NetBSD,  OpenBSD,  FreeBSD' they all have it in their repos.
Testing done: Run it at a Linux system works.
> Don't run "kde-open" and "gnome-open" under Unix

- tools/niminst/makefile.tmpl
also interested in proposing switching to some other make defaults for termux cross compilation (and other types of cross compilation in general), let me know if there's any interest/problems/something that i'm not thinking of
> use make default linker naming convention

- lib/system/mmdisp.nim
__go_free() was removed from gcc-7.2.0 so we stop trying to help the
garbage collector by marking no longer used memory regions
> Go GC: remove goFree() in order to support gcc-7.2.0

- compiler/scriptconfig.nim
Example:
Hint: used config file '/Users/../Nim/config/nim.cfg' [Conf]
_**Hint: used config file '/Users/../project/test/config.nims' [Conf]**_
> List nimscript configuration files used during compilation like cfg files

- compiler/extccomp.nim
This fixes an inconsistency in genscript. Previously object file paths in the linker command were absolute, while in compilation command they were relative. Now they are relative in the linker command.
> Emit relative object file paths in genScript

- lib/pure/ioselects/ioselectors_select.nim
- lib/pure/selectors.nim
The 'poll' of the Genode C runtime is a wrapper over 'select'.
I had to touch-up `ioselect_select` a bit to get it to compile.
> favor 'select' over 'poll' on Genode

- nimsuggest/nimsuggest.nim
This outputs nimsuggest usage on 'nimsuggest --help'
and fixes #6854 and #5841.
Although, the usage line
> "In addition, all command line options of Nim that do not affect code generation
are supported."
would no longer be true for '--help'
> Fixed printing nimsuggest commandline help message

- compiler/commands.nim
- compiler/options.nim
- doc/advopt.txt
add the dynlibOverrideAll switch to avoid nim loading any dynlibs at all. The idea here is to use this if you have some build system you need to integrate with, or you  need to link in some special-sauce platform specific way. I wager it could also be handy if you want to build a program with gcc's `-static` switch.
> add dynlibOverrideAll switch

- lib/pure/asyncdispatch.nim
- lib/pure/asyncfutures.nim
- tests/async/tasyncall.nim
Addresses part of #6849 
I tried doing a wider sweep of callback= but that caused some tests to fail and I didn't have time or experience to really dig into them.
> Use addCallback rather than callback= in asyncfutures.all()

- compiler/vmdeps.nim
- tests/macros/tgettypeinst.nim
Fixed getTypeImpl for second part of #5788.
This changes the behavior so that it will recurse and give the final implementation for a recursively defined type.
> modify getTypeImpl to reduce result to final implementation

- lib/pure/logging.nim
- A `newRollingFileLogger` opened in mode `fmAppend` tries to read the existing file to get the number of lines already present in the file. But a file opened in append mode can't be read. Nim currently has no way to open a file in mode "a+". So in `countLogLines`  i open the file again in mode `fmRead`to count the number of lines.
- the `countFiles` procedure doesn't find any files if the filename passed to `newRollingFileLogger` has no directory component. So i check if `splitFile(filename)` gives an empty directory and replace that by "."
- a file opened in mode `fmReadWrite` is truncated on open. So if you want to append to the current rolling log, you have to open it in mode `fmAppend`.
> fix #6264 and #6141

- lib/pure/collections/tables.nim
Previously `.smallest` would always give (0, 0) unless the first element in `data` contained something.
> Fix counttable smallest

- lib/system/genodealloc.nim
- lib/system/osalloc.nim
Genode software components all start with an explicit RAM resource quota
which may or may not be upgraded during runtime by the parent process.
With this patch `osTryAllocPages` will fail if allocation exceeds quotas
set by the parent and the `osAllocPages` procedure will trigger a
blocking request to the parent to increase quotas. The previous behavior
could potentially block both procedures indefinitely for a quota upgrade
rather than fail and trigger garbage collection.
This patch also adds proper management of Genode dataspace mappings into
the component address space.
> Genode: constrain `osTryAllocPages` to RAM quota

- compiler/extccomp.nim
Passing `--cc:icc` was not working on linux, this fixes it.
> Fix icc compiler on linux

- compiler/renderer.nim
This should makes documentation easier to read for people who haven't
committed the ascii table to memory.
I found docs like https://nim-lang.org/docs/memfiles.html#lines.i,MemFile,Char,Char hard to read because of this. I locally rendered the docs with this change and confirmed that it uses the '\c' and '\L' escape sequences.
My plan for testing was to add coverage to whatever test failed from this change, but no (new) tests failed on my machine. Where is a good place to add testing for this?
> Use escape sequences rather than hex in string/char literals

- changelog.md
- doc/lib.rst
- lib/js/asyncjs.nim
- tests/js/tasync.nim
- web/website.ini
Yesterday we had a discussion in the chat with @Araq , @dom96 and others about implementing some async support for the Nim's js target mapping to modern JS's async/await. (and eventually integrating an existing solution for compiling to older versions of js for people who need nim async in older js)
I've already done something like this for a project of mine, so I open this PR to see if people agree with this approach.
It was easiest to just introduce an asyncjs module, which defines a js variant of`async`. 
It replaces `return/result` inside with `return jsResolve(#) / result = jsResolve(#)` in order to satisfy the Future type (jsResolve(#) is generated as #, so no overhead).
It defines a function `await` in each body:
that seemed easier than the asyncmacro solution, because I didn't …
> A demonstration of my approach for JS async

- lib/js/asyncjs.nim
- tests/js/tasync.nim
```nim
import jsffi
proc e: js {.discardable.} =
proc a {.async.} =
e()
```
should work correctly now
> Make asyncjs Future[void] play nicely with last line discardable calls & forward declaration

- compiler/main.nim
The "genDepend" command was previously taught how to generate a "deps"
file in 4910a87 (gendepend improvements; refs #5144). Such a deps file
is useful in integrating the Nim compiler with an external build system
or watch daemon, such that it's possible to only run the Nim compiler
when any of the source files are modified.
It's also useful to generate the deps file in the nimcache directory
during C compilation, without needing to re-run the compilation passes
with "genDepend". This would thus reduce overall project build times.
> Generate deps file during C compilation

- .travis.yml
- lib/pure/times.nim
Add a simple grep to the Travis CI build to detect badly formatted ".. code-block::" entries.
Fix docstrings in two files.
> Add check for broken code-block in docs

- compiler/pragmas.nim
- tests/pragmas/tnoreturn.nim
Based on the feeback on https://github.com/nim-lang/Nim/pull/6954, void type return type should be allowed for noreturn procs
> Allow noreturn procs with void type

- compiler/vmgen.nim
- tests/vm/tcastint.nim
This PR add support for casting between integers of same bitsize in VM (compile time and nimscript).
This allow to among other things to reinterpret signed integers as unsigned.
EDIT: PR now doesn't create a new opcode, but rather generate correct sequence of vm instruction to correctly cast signed <-> unsigned integers.
It also handle new behaviour of VM (VM int now emulate intsize used by target platform)
> add integer casting support to VM

- doc/manual/stmts.txt
Includes a note in the manual entry for case statements clarifying that the branch values must be known at compile time.
> Add compile-time paragraph to manual

- lib/pure/times.nim
I've added warnings about some procedures being deprecated.
Also I can't find what is the replacement for `getTimezone` proc, please help with that
> Add warnings about deprecation to times module

- lib/pure/collections/sharedlist.nim
- lib/pure/collections/sharedtables.nim
- lib/system/gc.nim
- lib/system/gc2.nim
- lib/system/gc_ms.nim
- tests/collections/ttables.nim
Ok, so it's another bug because of mutexes are copied. Related: #5803, #3936.
Here's a man: https://linux.die.net/man/3/pthread_mutex_init
Note the following:
> Only mutex itself may be used for performing synchronization. The result of referring to copies of mutex in calls to pthread_mutex_lock(), pthread_mutex_trylock(), pthread_mutex_unlock(), and pthread_mutex_destroy() is undefined.
> Fixed mutex usage in SharedList and SharedTable. Closes #6988

- tests/testament/tester.nim
After the change, when stacktraces rendered in reversed order (most recent
call first), this method removed all stacktraces in the test failures.
> Remove obsolete method analyzeAndConsolidateOutput

- compiler/jsgen.nim
now in case of bool genConv generates boolean values instead of numeric
> fix in jsgen

- lib/pure/rationals.nim
Current limit `high(int32)` is not safe for 32-bit platforms
and it will overflow (even when running its own test suite).
Similar behaviour would be when try to set limit to `high(int64)`
on 64-bit platforms.
This change selects safe maximum value based on platform
size of int. Safe maximum considered half of int size (for
backward compatiblity).
> Use safe limit for toRational(float, int)

- koch.nim
- tools/nimgrep.nim
This also fixes a correctness issue where reExtended and reStudy weren't always being passed to re()
> Faster nimgrep

- lib/system.nim
This is useful as mentioned in the issue #6401 
Note that this is only implemented for seq of numbers. I'm not sure if this is the correct implementation, however testing using this method I do see random numbers when initializing and no zeros anymore.
Please review.
> Add newSeqUninitialized, closes #6401

- lib/pure/times.nim
Hopefully this isn't to late to undo... I think it was a mistake to export these two procs in #6552. The reason is that they use a primitive `tuple[monthday: MonthdayRange, month: Month, year: int]` type due to the current lack of a proper `Date` type.
The procs are useful, but it would be sad to be stuck with this stupid return type for `fromEpochDay`. They can be exported again when the `times` module is more complete.
> Unexport epochday procs

- lib/system/mmdisp.nim
From the man page: "Unlike the standard implementations of malloc, GC_malloc
clears the newly allocated storage. GC_malloc_atomic does not."
> Don't zeroMem result of boehmAlloc()

- .gitlab-ci.yml
- .travis.yml
- ci/build.sh
- ci/deps.sh
- koch.nim
- tests/testament/categories.nim
Empty paths in a colon separated list would be considered as the current
directory, so have to ensure $PATH and $LD_LIBRARY_PATH are not empty
before separating it with :
> Fix lists of paths in posix environment

- doc/astspec.txt
Change variable name to a from v, to match the ast and other examples.
> Ast and concrete syntax different.

- lib/pure/terminal.nim
```nim
import terminal
echo "123"
echo "456"
cursorUp(2)
eraseLine()
```
> Windows: fix a eraseLine bug

- lib/pure/strformat.nim
- tests/stdlib/tstrformat.nim
Since `fmt"{someObjWithStringifier}"` is accepted, `fmt"{someObjWithStringifier:10}"` should be accepted.
> Add additional $ fallback to fmt

- compiler/ccgtypes.nim
"#pragma pack(1)" sets current alligment without pushing into stack,
so "#pragma pack(pop)" causing stack underflow.
> Fix struct packing for VCC.

- lib/pure/times.nim
- tests/stdlib/ttimes.nim
The proc fields in `Timezone` must be closures to allow for creating timezones dynamically, which is usually necessary.
> Allow timezone procs to be closures

- lib/pure/asyncfutures.nim
- lib/pure/asyncmacro.nim
- tests/async/t6100.nim
- tests/async/tfuturestream.nim
Yet another way to fix #6100, replaces #6915 and #6614 (I guess as well?).
The speeds are as follows for the test added in this PR:
* This PR: 0.12s
* #6915: 0.07s
* #6614: 1.2s
I think there is more to #6614 than just #6100 though. Thoughts welcome.
> Fixes #6100.

- lib/pure/httpclient.nim
This code crashes without this PR:
```nim
import httpclient
discard newHttpClient().request("https://specially-crafted-https-server/", "GET", "")
```
If the server response doesn't have `Content-Length`.
Also added some checks to `parseChunks` to make sure that doesn't happen there.
`recvFull` closes the client when the response is read. If called again, it would crash in `sslRead` because the `sslHandle` of the socket is already nil. This PR prevents `recvFull` from being called on the closed client.
> Fixed crash in ssl httpclient

- doc/tut1.rst
Seems like these two class ids on the page were renamed to reflect their hierarchy but the tutorial links weren't pointing to them, this fixes that so the links lead to the right section
> Update two links in tutorial to point to correct section

- lib/pure/asyncnet.nim
- lib/pure/net.nim
This is something that me and @yglukhov discussed.
The old semantics were:
* For non-ssl sockets:
* calling ``recv`` on a closed socket gives "Bad file descriptor" OS error.
* For ssl sockets:
* calling ``recv`` on a closed socket gives a SIGSEGV because sslHandle is nil.
I was initially under the false impression that ``recv`` would return ``0`` in that case. Seeing as that's not true this isn't a breaking change so there shouldn't be any issues with this PR.
This PR also makes a small fix to net.recv() which affected @subsetpark
> Assert on closed sockets

- compiler/ast.nim
- compiler/pragmas.nim
- compiler/semstmts.nim
- tests/pragmas/tcustom_pragma.nim
Found that pragmas with new call syntax don't work in proc annotations, because I haven't patched `semProcAnnotation` to use `nkPragmaCallKinds`
> Custom pragmas in procs bug fix

- changelog.md
- lib/wrappers/openssl.nim
This commit basically returns the code that was removed in
a78d7a31f780c6cf1e421f820d9ed19a5db64ca7, but under 'openssl102'
define symbol. OpenSSL 1.0.2 is still actively maintained, so there is
no point in dropping support of it.
> Allow static linking with OpenSSL 1.0.2

- config/nim.cfg
In most distros (Ubuntu, Debian, Arch Linux) the only available Linux ARM toolchain uses arm-linux-gnueabihf- prefix. That's also the correct compiler for cross-compiling code for Raspberry Pi, which is what most people will probably want.
> Change default ARM compiler name

- tests/realtimeGC/cmain.c
- tests/realtimeGC/readme.txt
- tests/testament/categories.nim
`testC` command already has "gcc" as command, second "gcc" as option
generates "file not found error", and terminates the compiler with
error code
> Fix longgc category tests

- lib/pure/uri.nim
Allows parsing of URIs without authority.
For example, `file:///foo/bar/baz.txt`.
> Allow parsing URIs without authority

- compiler/transf.nim
- tests/exception/texcas.nim
fix for ICE in the `transformExceptBranch`:
Snippet to reproduce a crash
```
let x = try: 10    
except ValueError as ex:
echo(ex.msg)
-1
```
> Fix compiler crash on try expression with infix as (Fixes #7116)

- lib/system/sysio.nim
- tests/system/io.nim
Fixes #7121: Windows was unable to report file sizes > 2Gb, and incorrectly for >4Gb.
When tested on linux (Arch, x64), clong was of size 8, which allowed ftell to correctly report filesize, but it seems appropriate to switch to ftello anyway.
Replace ftell and fseek with (windows) _ftelli64, _fseeki64 and (posix) ftello, fseeko
> Fixes #7121

- doc/manual/types.txt
When trying to write them as they were that would cause error:
`Error: attempting to call undeclared routine: 'NaNChecks'`
> Fix the names of the float checks pragmas.

- compiler/sigmatch.nim
- tests/array/tarray.nim
Fixes empty array don't compile problem. The logic to handle empty array was already present in `tyOpenArray` part of `typeRel`, just taken it from there.
> Fixes #6853

- lib/pure/json.nim
- tests/stdlib/tjsonmacro.nim
I noticed that `json.to` couldn't convert directly into types with generic parameters, e.g a table. I think this fix is correct.
> Fix `json.to` for types with generic parameters

- lib/pure/collections/intsets.nim
This pull request fills out `intsets` with most of the missing functionality from `sets`. The following procs are added:
```
incl*(s: var IntSet, other: IntSet)
excl*(s: var IntSet, other: IntSet)
union*(s1, s2: IntSet): IntSet
intersection*(s1, s2: IntSet): IntSet
difference*(s1, s2: IntSet): IntSet
symmetricDifference*(s1, s2: IntSet): IntSet
`+`*(s1, s2: IntSet): IntSet
`*`*(s1, s2: IntSet): IntSet
`-`*(s1, s2: IntSet): IntSet
`-+-`*(s1, s2: IntSet): IntSet
disjoint*(s1, s2: IntSet): bool
len*(s: IntSet): int
card*(s: IntSet): int
`<=`*(s1, s2: IntSet): bool
`<`*(s1, s2: IntSet): bool
`==`*(s1, s2: IntSet): bool
```
Tests for all methods are included.
Possibly missing are checks for whether `intsets` are initialized.
> add more functionality from sets to intsets

- compiler/ccgstmts.nim
- tests/cpp/tcppraise.nim
I had to get rid of gotos to make exception rethrowing work, the exception branch bodies are repeated if multiple types are specified. On the good side of things, ``genTryCpp`` became much simplier and easlier to follow.
> genTryCpp codegen. Fixes #7232. Fixes #7239

- lib/js/asyncjs.nim
- tests/js/tasync.nim
early `return` without arg in js async functions was resulting in wrong expanded code
> Fix return for js async

- changelog.md
- lib/impure/rdstdin.nim
- lib/pure/terminal.nim
Moves the `readPasswordFromStdin` proc from the `rdstdin` to the `terminal` module. This way the proc is not dependent on `linenoise` anymore, which it does not use anyways.
I had to convert the `password` variable (`TaintedString` argument of the proc) manually to a string, before `setLen` is called. Otherwise the call fails in taint mode.
> move `readPasswordFromStdin` from rdstdin to terminal

- compiler/ccgstmts.nim
- tests/cpp/temitlist.nim
Simple fix not to generate empty parenthesis if there are no arguments for constructors
> Fixes #6837

- lib/pure/streams.nim
- tests/stdlib/tstreams3.nim
This is the ``openFileStream`` proc proposed in the RFC, along with a new test to go with it. As mentioned on the issue discussion, I did not yet deprecate ``newFileStream()``, but I did update the docs to warn users about the possibility of ``nil``.
> Resolves #5588: adds openFileStream proc that throws on failure

- lib/js/asyncjs.nim
- tests/js/tasync_pragma.nim
Uh, that was nasty, I should have seen it earlier.
Maybe we need some kind of `addPragma` helpers in macros, as it's seems easy to make such a mistake again?
> Stop replacing all pragmas of a function with asyncjs

- compiler/scriptconfig.nim
- lib/system/nimscript.nim
- tests/newconfig/tfoo.nims
I have described our use cases in #7283.
We do need ``putEnv`` in nimscript to migrate from config files.
> putEnv for nimscript. Fixes 7283

- lib/system/dyncalls.nim
When platform is Windows and app type is GUI, an error about missing DLL file is displayed as message box in addition to the console output, which is usually not visible.
> Fixes #7212, now with better code

- lib/impure/re.nim
Spotted the typo on https://nim-lang.org/docs/re.html
> Fix typo in re module: PRCE -> PCRE

- lib/pure/parseopt.nim
- tests/misc/tparseopt.nim
non-empty partial symbol table.  Behavior should be identical to the
old behavior if empty partial symbol tables are passed.  "Partialness"
of the symbol table refers to the fact that one need only specify
option keys that are toggles/booleans/do not take arguments, hence
the "NoArg" suffixes in shortNoArg and longNoArg.
commandLineParams() returns seq[TaintedString], so use that consistently
in getopt() and initOptParser(seq[TaintedString]) dropping the taint at
the quoting stage just as with the paramStr() logic.
Fix capitalization inconsistency of cmdLongOption.
Export OptParser.cmd and OptParser.pos so that, at least *in principle*,
users of this API can handle "--" option processing termination or some
"git-like" sub-command stop word with a separate option sub-syntax.
{ Eg., ``case …
> Add ability for users to elide ':' or '=' when CLI authors pass a

- changelog.md
- compiler/main.nim
- doc/advopt.txt
- doc/docgen.rst
- tools/nim.bash-completion
- tools/nim.zsh-completion
Manual was missing information about jsondoc2 which made it seem like
it didn't exist at all. This commit adds mention of the jsondoc2
command along with an example.
> Renamed jsondoc2 to jsondoc, similar to doc2

- compiler/vm.nim
Compile times for codes creating lots of idents grew very large due to repeatedly creating an ident with the same string.  Since it seems this isn't intended to be used in correct macros, it is most efficient to just reuse the same ident each time.
> reuse default ident in opcNNewNimNode (performance regression)

- compiler/ccgexprs.nim
- compiler/ccgtypes.nim
- tests/ccgbugs/mymodule.nim
- tests/ccgbugs/tforward_decl_only.nim
I have described the use case in #7339
Summary of changes:
- ``getTypeDescAux`` no longer pushes type to be defined at finalization step if type's ptr/ref encountered
- All operations dereferencing the pointer/reference now need to call getTypeDesc for the derefed type, however it is already done in most of cases. I have found only 2 extra places where adding ``getTypeDesc`` was required: ``genOf`` and ``downConv``
> Codegen: use type forward declarations more aggresively. Fixes #7339

- lib/pure/algorithm.nim
This allows to find lower bound of objects by their attribute. E.g.:
```nim
type Foo = object
name: string
var s: seq[Foo]
echo lowerBound(s, "hello") do(a: Foo, b: string) -> int:
cmp(a.name, b)
```
Otherwise a pseudo key of `Foo` has to be created.
> More flexible lowerBound interface

- lib/pure/xmlparser.nim
Like #7198, but for `xmlparser`. Also fixed some documentation errors.
> Add string overload for parseXml

- config/nimdoc.cfg
Don't assume, that the default background-color is white.
My default background-color is dark, which makes the documentation hardly readable: https://i.imgur.com/xN0UjWz.png
The reason is the transparency of the existing color (rgba(252, 248, 244, 0.45);) 
Fixed by removing the transparency.
> Fix background-color in nimdoc.cfg

- doc/lib.rst
`basic2d` and `basic3d` has been moved to nimble packages
> Remove basic2d & 3d from module list

- compiler/ccgstmts.nim
- tests/ccgbugs/tbug1081.nim
- tests/ccgbugs/tforward_decl_only.nim
> Fixes #7363

- lib/wrappers/openssl.nim
LibreSSL 2.6.4 provides libssl.so.44
> LibreSSL 2.6.4 linking fix

- lib/pure/dynlib.nim
Following a question on Gitter about loading libraries dynamically based upon some runtime parameter, I noticed there's no documentation on the `dynlib` module for something that's quite common.
> Add an example to the `dynlib` module doc

- compiler/ast.nim
- compiler/ccgtypes.nim
- compiler/lookups.nim
- compiler/semexprs.nim
- compiler/seminst.nim
- compiler/semtypes.nim
- compiler/semtypinst.nim
- compiler/sigmatch.nim
- compiler/types.nim
- tests/concepts/tseqofconcept.nim
- tests/cpp/tcovariancerules.nim
- tests/cpp/tvector_iterator.nim
- tests/metatype/tstaticparammacro.nim
- tests/metatype/ttypeselectors.nim
- tests/metatype/typeclassinference.nim
- tests/misc/tidentconcatenations.nim
- tests/statictypes/tcryptodigest.nim
- tests/statictypes/tstaticimportcpp.nim
These are some `static[T]` fixes for problems discovered while wrapping and authoring fixed-size message digest cryptographic libraries at Status.
> Static[T] fixes

- lib/pure/net.nim
Under Linux (probably POSIX), the current code tests for timeout, but
does not test for connection failure. connectAsync() returns successfully
upon an EINPROGRESS result; but at this point, the connection state is
still unknown. After selectWrite() is done, we need to test the socket
for errors again.
> net.connect (with timeout), raise error on connect failure

- lib/pure/unittest.nim
Add a method with which you can disable param filtering for a certain file: I wanted to change the logic, so testsFilters just ignore params with `arg:value`, but it seems that can be a pattern..
> Unittest param filtering 

- compiler/renderer.nim
It doesn't change behavior or fix a problem. All it does it it causes fewer temporary string objects to be allocated on the heap.
> fewer temporary string allocations

- changelog.md
- lib/core/macros.nim
- tests/parser/tpostexprblocks.nim
- tests/vm/tnimnode.nim
the output of the example in https://github.com/nim-lang/Nim/issues/7473:
```
============================================================
"  \L  \c  \t  \\  "
StrLit("  \L  \c  \t  \\  ")
StrLit "  \L  \c  \t  \\  "
newLit("  \L  \c  \t  \\  ")
============================================================
"  \L  \c  \t  \\  "
StrLit("  \L  \c  \t  \\  ")
StrLit "  \L  \c  \t  \\  "
newLit("  \L  \c  \t  \\  ")
============================================================
"  \L  \c  \t  \\  "
StrLit("  \L  \c  \t  \\  ")
StrLit "  \L  \c  \t  \\  "
newLit("  \L  \c  \t  \\  ")
============================================================
"""  \n  \r  \t  \\  """
TripleStrLit("  \\n  \\r  \\t  \\\\  ")
TripleStrLit "  \\n  \\r  \\t  \\\\  "
newLit("  \\n  \\r  \\t  \\\\  ") …
```
> Fix for #7473

- lib/pure/json.nim
- tests/stdlib/tjsonmacro.nim
Part of #6902 ( j1 example) was fixed in this [PR](https://github.com/nim-lang/Nim/commit/9c2cdc94a2f7292a1872a8a24c0d9aed87e424c5). This PR addresses the issue of identifying "null" values correctly. 
ping @enthus1ast @dom96
> Fixes #6902

- changelog.md
- lib/pure/cookies.nim
Now that the `times` module can handle timezones properly there's no reason to assume UTC in `setCookie`.
> Don't assume UTC in cookies.setCookie

- doc/advopt.txt
previous wording was a bit ambiguous since compile can mean both compile Nim sources and generated C/CPP/etc sources
> [trivial] [doc] cmd line help: clarify compileOnly vs noLinking

- nimsuggest/nimsuggest.nim
In [PR 6863](https://github.com/nim-lang/Nim/pull/6863) only the interpretation of --help was added to `processCmdLine` of nimsuggest , -h still displays the standard Nim compiler help. (see #7514)
> include help short option in processCmdLine of nimsuggest

- lib/pure/collections/sequtils.nim
oh oh, the dangers of single letter identifiers ...
issues #6986 and #7501 were both introduced by the following:
```
commit 71c5c0a47f1b733a3978236ac2f3be67547f2988
Author: narimiran <narimiran@users.noreply.github.com>
Date:   Wed Oct 25 13:41:42 2017 +0200
Sequtils improvements (#6574)
```
interestingly there exists a relation between these two issues and #7187 (my proposed fix there is inspired by mapIt, but i didn't see that mapIt itself was buggy).
> fix issues #6986 and #7501

- compiler/platform.nim
- lib/system.nim
- lib/system/platforms.nim
Tested by crosscompiling using GCC 8.0.1 from 20180321 (devel version) running koch tests under qemu-riscv64 version 2.11.50 (v2.11.0-2256-g819fd4699c-dirty).
Some tests failed due to missing libraries; The threadpool module failed to compile due to an unrecognized opcode `pause'.
This PR could be merged as a first step to add RISC-V support and more testing can be performed once real hardware is available.
Closes #7147
> Add RISC-V "riscv64" support

- compiler/bitsets.nim
- compiler/nimsets.nim
- tests/sets/tsets.nim
The issue was that duplicates in set literals are never discarded, so just counting the elements gives the wrong result.
Fixes #7555
> Fix compile time set cardinality

- lib/pure/options.nim
an option on a pointer type does not need an additional ``has`` field. This is an optimization that is built into the language rust and they advertise with that optimization. In Nim it is easy to implement, too.
> option optimization

- compiler/ccgstmts.nim
Quick and slightly dirty fix for #7574 to unblock cpp backend users. Fixes #7574.
It doesn't cover case when Exception object is created, but neither raised nor caught (uncommon).
In order to cover it as well I will need to add a delayed emit queue for symbols similar to BModule.typeStack for types to resolve circular dependency for Exception <-> PopCurrentExceptionEx().
> cpp regression bug fix. Fixes #7574.

- lib/pure/asyncmacro.nim
- lib/pure/htmlgen.nim
just a few changes to remove deprecation messages. In my opinion it also removes visual noise from the code.
> fix deprecation warnings in asyncmacro and htmlgen

- lib/pure/parsesql.nim
- tests/stdlib/tparsesql.nim
* Created new `nkQuotedIdent` node type. 
* Fixed warning related to `toUpperAscii` and `toLowerAscii`.
* Moved stream related methods under when not js block.
* Fix order by limit by parsing.
> Added count(*) support to sql parser. Fixed warnings in sql parser.

- changelog.md
- compiler/semmagic.nim
- lib/system.nim
- tests/assert/tfailedassert.nim
Instantiation info left out column number for no good reason. This adds it in as the third element of the tuple.
> Add column number to instantiation info

- tools/nimgrep.nim
partially addresses https://github.com/nim-lang/Nim/issues/7428
eg usage:
```
./bin/nimgrep '\bfields\b' --ext:nim --recursive --oneline | grep let
/Users/timothee/git_clone/nim/Nim/tests/js/tmangle.nim:69: # Test codegen for fields with uppercase letters:
/Users/timothee/git_clone/nim/Nim/tests/niminaction/Chapter9/configurator/configurator.nim:63:   let identDefs = toIdentDefs(fields)
/Users/timothee/git_clone/nim/Nim/tests/vm/meta.nim:174:   let fields = typedef.fields.render()
/Users/timothee/git_clone/nim/Nim/tests/vm/meta.nim:174:   let fields = typedef.fields.render()
/Users/timothee/git_clone/nim/Nim/lib/core/macros.nim:947:   let enumBody = newNimNode(nnkEnumTy).add(newEmptyNode()).add(fields)
/Users/timothee/git_clone/nim/Nim/compiler/semobjconstr.nim:148:       let fields = …
```
> [nimgrep] add option --oneline to keep file:line info when piping through grep

- compiler/lambdalifting.nim
- lib/pure/asyncmacro.nim
- tests/async/tgeneric_async.nim
This also fixes a compilation error in modules, based only on the
new async module (i.e. not importing the full asyncdispatch)
> Fix some usages of typedesc in async procs

- tools/nimweb.nim
a small attempt to "make tests green again" after: 
[introduce nkTupleConstr AST node for unary tuple construction; breaking change](https://github.com/nim-lang/Nim/commit/47335aab4148b2cd5b28cd3012d6d6e0a0c82db7)
> make tools/nimweb.nim compileable with latest Nim

- lib/pure/nativesockets.nim
In issue #7314 @jaco60 complains that:
> addrList field of Hostent in nativesockets is unusable as is.
This is an attempt to make this addrList field (as returned by ` gethostbyname` and `gethostbyaddr`) readable in the case of ipv4 af_inet addresses.
> make nativesockets.Hostent.addrlist readable (#7314)

- lib/system/jssys.nim
- tests/js/tstringitems.nim
Fixing: https://github.com/nim-lang/Nim/issues/7603
> Fix cmpStrings in js mode

- changelog.md
- lib/js/jscore.nim
- lib/pure/lenientops.nim
- lib/pure/strformat.nim
- lib/system.nim
- tests/tuples/tuple_with_nil.nim
The `SomeReal` types were the superset of all `Float` types. That is not only inconsistent with the names, but it is also wrong. Here is a list of reasons why calling floating point numebrs `real`  (ℝ) is wrong.
∞ ∈ Float
∞ ∉ ℝ
NaN ∈ Float
NaN ∉ ℝ
ℚ ⊂ ℝ
Float \ {NaN, ∞, -∞} ⊂ ℚ
Float ∩ ℝ ⊂ ℚ
In words:
* _infinity_ is a valid floating point value, but it is not a real number
* _nan_ is a valuid floating point value, but again it is not not even a number at all, especially not a real number.
* Leaving out the special values of float, all that is left is a subset of the rational numbers.
Or in other words, if you take all floating point numbers that are also real numbers, there is not a single value left, that would justify to call this number type "real numbers".
Thanks to deprecation …
> rename SomeReal to SomeFloat

- compiler/condsyms.nim
- compiler/idents.nim
- compiler/vm.nim
- lib/core/macros.nim
- lib/pure/cstrutils.nim
- lib/pure/strutils.nim
- tests/macros/tmacro1.nim
This actually adds a test for identifier equality. Then it almost removes one instance of the many duplicates of `cmpIgnoreStyle`. Really copy pasting that function everywhere and then ensuring that the only central version in strutils.nim remains broken doesn't help at all.
The main motivation for this change is that `eqIdent` is called at lot in macros. I will also generate a lot of it form the ast pattern matching library that I am currently working on. I just wanted it to be fast.
> move eqIdent to vm.nim

- lib/pure/times.nim
- tests/stdlib/ttimes.nim
This is an optimization for `TimeInterval`'s which doesn't contain any timezone dependent time units (years/months/weeks/days). Those intervals can be evaluated without using the local timezone, which is expensive. Benchmark:
```nim
import times
let before = getTime()
var sum = 0'i64
for i in 0..100_000:
sum += (toUnix(fromUnix(0) + 5.seconds))
let after = getTime()
echo sum
echo after - before
```
I also fixed a small typo in `$` for `Duration`.
> Timeinterval optimization

- lib/core/macros.nim
@Araq @krux02 
https://github.com/nim-lang/Nim/pull/7598 seemed inaccurate eg for NLineInfo there's `mNLineInfo` but no opcNLineInfo
> [doc] update macros.nim: followup on pull #7598

- lib/pure/osproc.nim
- tests/osproc/tclose.nim
Calling close() in some cases issued two close() syscalls to one FD, which is incorrect in multithreaded programs.
> osproc: fix double close on POSIX

- compiler/bitsets.nim
> Generate populationCount const at compile time

- lib/pure/terminal.nim
Setting the option to true, then to false would not turn off bright attribute.
> Fix bright option in Terminal

- lib/core/macros.nim
- tests/pragmas/tcustom_pragma.nim
sorry, I forgot add a check whether a type has any pragma at all.
Passing a type without a pragma to `hasCustomPragma` or `getCustomPragmaVal`, without this fix, results in an index error.
> hasCustomPragma/getCustomPragmaVal: small fix

- lib/pure/os.nim
- lib/pure/times.nim
- tests/stdlib/ttimes.nim
- Fix `toWinTime` so that nanoseconds are included
- Add `fromWinTime` which is the inverse of `toWinTime`
- Deprecate `winTimeToUnixTime` & `unixTimeToWinTime` since they are now replaced
> Add `fromWinTime` and deprecate `unixTimeToWinTime`/`winTimeToUnixTime`

- compiler/semfold.nim
Fixes issue #7644 more elegantly, given SOURCE_DATE_EPOCH constraint. Imposes no necessary runtime cost or environment checking except for Compile{Date,Time} nodes specifically.
> https://reproducible-builds.org/ support via SOURCE_DATE_EPOCH (#7644)

- doc/manual.rst
Nothing really world changing, but now the opening sentence at least tries to explain a bit how macros work and what they actually do.
In the debug example I updated the comment, and then I removed _visual noise_ for the most part. But it is still the same example.
> macro manual improvements

- compiler/renderer.nim
- lib/pure/strutils.nim
- lib/system.nim
- tests/collections/tcollections_to_string.nim
- `addQuoted` and `strutils.escape` no longer escapes multibyte UTF-8 characters
- Use `addQuoted`/`addEscapedChar` in `renderer.nim` instead of custom procs
- Change escaping scheme used by `addEscapedChar` to match the one previously implemented in `renderer.nim` (except that `'\n'` is now escaped as `"\\n"` instead of `"\\L"`). `strutils.unescape` has been updated to match this as well.
Fixes #7559
Fixes #3056
> Don't escape multibyte characters

- lib/pure/random.nim
- lib/pure/times.nim
- tests/stdlib/ttimes.nim
I realized that I made a mistake in #6978 :( 
`Time.nanoseconds` should be named `Time.nanosecond` for consistency with `DateTime.nanosecond` (note that even though the field isn't exported, it's exported by a getter proc with the same name).
> Rename `Time.nanoseconds` to `nanosecond`

- compiler/commands.nim
- compiler/extccomp.nim
- doc/advopt.txt
- tests/flags/tgenscript.nim
- tests/testament/backend.nim
- tests/testament/categories.nim
- tests/testament/htmlgen.nim
- tests/testament/tester.nim
Fixes #802 - moved compile script into the `nimcache` directory - makes most sense since the idea is to take this `nimcache` directory onto the target machine to build so having the script together with the code makes sense. Also easy since the `.c` file paths don't need any adjustments in the generated script.
Fixes #803 - copies `nimbase.h` into the `nimcache` directory since it is required for build on the target machine.
Fixes #3775 - `--genscript` means `noAbsolutePaths()` so compile commands all failed due to bad paths. But there's no reason to compile anything on this machine, so `--genscript` should imply `--compileOnly`.
> Fixes #802, #803 and #3775 - genscript issues

- compiler/vmdeps.nim
Before, when getType was given an expression of of a type 'var T', it returned a bracket expression. Now it works like the other ref and ptr nodes.
> Fix the return value of GetType and friends when given a `var T` type.

- compiler/semfold.nim
- compiler/types.nim
- tests/misc/tsemfold.nim
- tests/typerel/ttypelessemptyset.nim
An attempt fix an old compiler issue...
Currently, saturated arithmetic is used to implement constant folding. This means that arithmetic operations behaves differently when evaluated by the constant folder compared to when they are evaluated during run time or by the VM, since saturated arithmetic hides overflows:
```nim
static:
var x = high(int8)
echo x + 1 # Error
var x = high(int8)
echo x + 1 # Error
echo high(int8) + 1 # Prints 128
```
This PR changes the behavior of constant folding so that folding only occurs when the arithmetic operation is safe (no over-/underflow or division by zero). When the operation is not safe, no folding is performed, which results in a run time error. Note that it's not a good idea to give a compile time error, because it might catch errors that logically …
> Don't hide overflow/underflow/divbyzero in semfold 

- lib/wrappers/openssl.nim
libressl 2.7 provides `libssl.so.45`
> link against libssl.so.45

- compiler/cgen.nim
- lib/system.nim
Compiling Nim for the Genode OS target always requires compiling to C++, but Std C++ is unacceptably complex and too bulky for us to link with by default. This also means avoiding the `new` keyword, as our C++ runtime lacks an implicit allocator backend (a feature, not an omission).
> Optionally disable std C++

- lib/pure/terminal.nim
- lib/windows/winlean.nim
Change getch() implementation on Windows to only return the result of the target key, for instance SHIFT+'a' return 'A'. Current behaviour would return '0x0' and then 'A'.
> Fixes #7764

- compiler/cgen.nim
Sample:
```nim
import random
echo rand(5)
```
Compile:
```
nim c -d:release --passC:-flto --passL:-flto ~/test.nim
```
Env:
```
clang --version
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Binary size before: 38988
Binary size after: 38764
> Allow better optimisations by removing NOINLINE from module init procs

- changelog.md
- lib/pure/collections/critbits.nim
Also added the parameter ```val``` and tests.
N. B.
This proc was added in version 0.12.
It's strange that during this time this bug wasn't discovered.
> Fixes CritBitTree.inc's bug

- changelog.md
- lib/pure/math.nim
This might just be a pointless breaking change, but it annoys me that modulus for floats uses floor division, when `div` and `mod` for integers uses truncating division.
> Use truncation division in mod for floats

- lib/std/sha1.nim
I propose adding a note to the sha1 module documentation to articulate the "import std/sha1" requirement for the time being
> Add note to import "std/sha1" to sha1.nim (doc)

- lib/posix/posix.nim
- lib/posix/posix_other.nim
- lib/pure/os.nim
- tests/stdlib/tos.nim
This PR adds support for nanosecond resolution on posix for some procs in os.nim:
- getLastModificationTime
- setLastModificationTime (only microsecond resolution)
- getLastAccessTime
- getCreationTime
- getFileInfo
[futimens](https://linux.die.net/man/3/futimens) can be used to suport nanosecond resolution in `setLastModificationTime`, but I don't know if it's available on all of posix
> Use higher time resolution when available in os.nim

- changelog.md
- lib/pure/math.nim
Rename `tgamma` (means true gamma) to `gamma`. Deprecate `tgamma`.
http://pubs.opengroup.org/onlinepubs/009695399/functions/tgamma.html
*This function is named tgamma() in order to avoid conflicts with the historical gamma() and lgamma() functions.*
There are no need to use the name `tgamma` in Nim.
> Rename tgamma to gamma

- lib/pure/json.nim
Last PR was for master branch instead of devel, thanks @Yardanico
> Allow `%` overloading in `%*` macro in json (again)

- changelog.md
- lib/pure/strutils.nim
- lib/pure/unicode.nim
The other variants are isLower, isUpperAscii and isLowerAscii
Fixes https://github.com/nim-lang/Nim/issues/7963.
This commit changes the behavior and signatures of:
- isUpper, isLower in the unicode module
- isUpperAscii, isLowerAscii in the strutils module
A second mandatory parameter skipNonAlpha is added to these 4 procs.
(This change affects only for the case where the input is a *string*.)
---
With skipNonAlpha set to true, the behavior mimics the Python isupper and
islower behavior i.e. non-alphabetic chars/runes are ignored when checking if
the string is upper-case or lower-case.
Before this commit:
doAssert(not isUpper("A B"))
After this commit:
doAssert(not isUpper("A B", false))    <-- old behavior
doAssert isUpper("A B", true)
Below two are equivalent:
isUpper("A B", true) …
> Make isUpper (and variants) work for strings with non-alpha chars

- compiler/cgen.nim
- lib/genode/alloc.nim
- lib/genode/env.nim
- lib/genode_cpp/threads.h
- lib/nimbase.h
- lib/pure/concurrency/cpuinfo.nim
- lib/pure/os.nim
- lib/system.nim
- lib/system/osalloc.nim
- lib/system/threads.nim
- lib/wrappers/openssl.nim
This patch adds a hook for application level code to receive the initial operating system environment. This environment interface object makes it is possible to cleanly implement native Genode IPC clients and servers.
The environment is just a typed pointer to an external C++ class, I plan to export no more Genode specifics from the standard library, but instead add a Genode system library package to Nimble. However I do plan to later add some more internal Genode specific code to the standard library such as bypassing the POSIX runtime layer to access the RTC and timers directly, for example.
> Native access to Genode environment

- lib/pure/asyncfile.nim
Made a simple clarification in the comment for asyncfile.nim openAsync.
It was not self evident to me when working through the code in the Nim In Action book that I was passing a FileMode enum into the openAsync method. The code did not work as I expected and I could not find the documentation desired during simple read of the source. Maybe this change would have helped.
Accept / Reject. I am good either way. It is something simple.
> Added FileMode to comment on asyncfile openAsync

- compiler/vmgen.nim
This typo (?) caused out of range exception when `dest` was `-1`. Unfortunately I could not come up with a nice reproducible sample.
> Fixed uncaught exception in vm gen

- changelog.md
- lib/pure/parseutils.nim
- lib/pure/strutils.nim
- tests/stdlib/tstrutil.nim
I agree with #8018 that it would be nice to offer such a proc. So I just took the implementation of parseutil `parseBin` and removed the parts related to the return value.
I also added some simple test cases for all three parse*Int procs. 
One question: when I saw the implementation for `parseHexInt` and `parseOctInt`. Is there a specific reason, why they don't simply wrap `parseHex` and `parseOct`? For efficiency reasons?
> Add parse bin int, fixes #8018

- compiler/ccgexprs.nim
As a side note: why does `reserved` have to contain the length (for both strings and seqs)?
> Added NIM_STRLIT_FLAG to seq literals

- compiler/pragmas.nim
- compiler/semstmts.nim
- tests/overflw/toverflw.nim
Slightly refactored pragmas to allow pragmas affect particular symbol options instead of global options. This new behavior is used to apply `stacktrace` and `linetrace` pragmas directly on proc symbols, instead of messing with global options which proved to be error prone (e.g. a macro pragma applying another pragma).
> Fixed stacktrace/linetrace proc pragmas when appended by macro pragma

- lib/pure/terminal.nim
\e[3m -> italic
\e[9m -> strikethrough
Ref: https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters
I have tested italics and strikethrough to work on xterm on RHEL 6.6.
I am aware that these ANSI escapes are not supported by all terminals, and probably not in Windows too. But it's useful to have these enums defined so that people wanting to use them can..
- On terminals not supporting italics, the italic ANSI code renders as reverse.
> Add support for italic and strikethrough ANSI escape codes

- doc/tut1.rst
In reading the tutorial, there were a couple places where the word 'constant' was used in a colloquial sense. Since Nim defines constants in a technical sense to be values which must be known at compile time, I believe it would be more accurate to use the term 'immutable' in these places.
> Changed tutorial documentation referring to 'constant' to 'immutable'

- lib/pure/terminal.nim
Also:
- Move the tests block to the end of the file
- Fix the older tests
- Convert styledEcho from a macro to a template, add tests for that.
- Convert styledWriteLine from a macro to a template, add more tests for that.
- Add new tests for styledWrite
Fixes https://github.com/nim-lang/Nim/issues/8046.
---
This commit works, but I don't understand the macro syntax, and would like `styledWriteLine` to reuse `styledWrite` that I added. 
Let me know if that optimization needs to be made before this can be committed.. or if someone can optimize that after this gets committed.
Also, need to fix these warnings:
> terminal.nim(706, 11) Warning: use varargs[untyped] in the macro prototype instead; callsite is deprecated [Deprecated]
> terminal.nim(740, 11) Warning: use varargs[untyped] in the …
> Add styledWrite macro

- changelog.md
- lib/pure/pegs.nim
- tests/stdlib/tpegs.nim
The ``peg`` proc of the pegs module already creates a complete AST of a parsed PEG definition. This PR makes the fields of the AST nodes readable from other modules. A possible application is a PEG parser generator which takes a PEG AST as input.
> Pegs AST read access

- compiler/semfold.nim
- tests/arithm/tnot.nim
- tests/arithm/tshl.nim
Since the source and destination types are the same the result should be
trimmed to fit.
> Fix constant folding for shl/not

- lib/pure/terminal.nim
- Adds `fgDefault` to ForegroundColor and `bgDefault` to BackgroundColor
enums.
- Also adds the `fg8Bit` and `bg8Bit` enum values to fix the "enum with holes" error. The 8-bit color implementation is left unsupported for this PR.. will leave that for my future self or someone else :)
**Windows Console fg defaulted to white, bg defaulted to black.**
/cc @dom96 @Araq 
---
With this PR, now:
```nim
import terminal
stdout.styledWriteLine(fgRed, "red text ", styleBright, "bold red", fgDefault, " bold text")
stdout.styledWriteLine(bgYellow, "text in yellow bg", styleBright, " bold text in yellow bg", bgDefault, " bold text")
```
outputs:
**On RHEL 6.6, XTerm (default fg = white, default bg = black)**
**On RHEL 6.6, XTerm (default fg = black, default bg = green)**
> Support setting foreground/background colors to terminal defaults

- compiler/sighashes.nim
- tests/types/t7905.nim
The root cause of #7905 lies in the codegen phase. The two template
instantiations generate two different MyType types with different
members but same t.sym.name leading the caching mechanism to confuse
the two.
By throwing the type id in the mix we make sure this ambiguity is
solved.
Fixes #7905
> Discriminate gensym'd type names in sigHash

- compiler/extccomp.nim
- compiler/pragmas.nim
Changing source filenames to object filenames sometimes removes the extension and then changes it again, probably assuming it doesn't contain dots. This changes `foo.bar.cpp` to `foo.o` instead of `foo.bar.o`.
> Don't remove extension of source files twice, if filenames contain dots

- compiler/vm.nim
- compiler/vmdef.nim
- tests/vm/tnilref.nim
- tests/vm/tref.nim
Changes with motivations:
- Don't use `putIntoNode` to implement `opcWrDeref`. `putIntoNode` was used for to many things, which made it hard to make it correct for all cases. This change also means that `putIntoNode` doesn't need to handle a bunch of edge cases that are only relevant to `opcWrDefef`.
- Rename `putIntoNode` to `writeField`. This change reflects that the proc is now only used in `opcWrObj`/`opcWrArr`, and it probably shouldn't be used anywhere else.
- Don't allow dereferencing `nil` (see test case in `tests/vm/tnilref.nim`).
- Add `nfIsRef` flag to `sym` nodes (generated by `opcNBindSym` and `opcGenSym`).
Fixes #6081
> VM fix for nil assignment

- compiler/semstmts.nim
- tests/global/t5958.nim
- tests/pragmas/treorder.nim
- tests/vm/tnimnode.nim
- tests/vm/tvmmisc.nim
Treat the static block as a normal block, don't leak any identifier in
the outer scope.
Fixes #5958
I'm quoting @zah on the matter:
> This code is not valid - static blocks introduce their own scope, so there should be a proper compile-time error here. To introduce a global compile-time variable, you can use the compileTime pragma.
> Make `static` blocks introduce their own scope

- compiler/astalgo.nim
- compiler/msgs.nim
- koch.nim
the debug procs once in the past did not need a config object. Now they don't need it anymore. And by default it is set to nil. This doesn't work as well as if it is set, but it won't crash anymore on nil. Also the order of the arguments is reversed so that the old way to use the debug proc will just work.
I also added debug information to the debug build of the compiler. 
With these changes basic debugging of the compiler is now possible. Still a long road ahead to make debugging a better experience. But these steps are absolutely necessary.
> make basic debugging possible

- compiler/cgen.nim
- tests/concepts/tmisc_issues.nim
Fixes #7125
CC @zah since I'm not 100% sure this is sound for every case
> Don't consider concept types as non-complex during codegen

- doc/manual.rst
Fixes https://github.com/nim-lang/Nim/issues/8131.
> Clarify use of special `:` for passing a block of stmts to template

- compiler/semtypes.nim
- tests/types/t6456.nim
Do this during the semantic pass to avoid tripping the following passes.
Fixes #6454
> Reject ptr/ref void types

- compiler/sem.nim
- tests/macros/t7454.nim
Return an error symbol if the macro output has no type and a typedesc
is expected.
Fixes #7454
I added a `localError` to make this case a bit more symmetric wrt the `fitNode` path.
> Return an error symbol as macro output if needed

- compiler/lexer.nim
An attempt to improve the error message if a literal ends with an underscore (fixes #8113), e.g.
```nim
echo 123_
```
will now produce:
```
Error: token must not end with an underscore: ...0_ is invalid
```
Maybe the `...` is ugly, not sure if I like it. Wanted to include the last digit before the underscore and somehow clarify that the shown digit may not cover the whole literal.
> improve error message if literal ends with an underscore, fix #8113

- lib/pure/strformat.nim
I looked for a less hacky way to check if a proc returns void, but couldn't find any. Related: #7397
> Fixes #8100

- compiler/vm.nim
- tests/vm/tvmmisc.nim
I'm not happy about calling `copyValue` in `writeField`, since in most cases `vmgen.nim` will generate a separate instruction for copying anyway. But maybe that should be changed so that only `vm.nim` is responsible for making copies at assignment.
Fixes #8142
Fixes #8125
Fixes #7871
> VM regression fixes

- compiler/semexprs.nim
With the help of @LemonBoy an attempt to fix #8129.
> fix #8129 by calling `semExpr` in `semIs` if node is `strLit`

- lib/pure/osproc.nim
this addresses https://github.com/nim-lang/Nim/issues/8160
```nim
import osproc
proc test_execCmdEx*()=
block:
var options: set[ProcessOption] = {}
options.incl poStdErrToStdOut
let output=execCmdEx("echo foo && unexistant", options)
echo output
block:
var options: set[ProcessOption] = {}
let output=execCmdEx("echo foo && unexistant", options)
echo output
#[
output:
(output: "foo\n/bin/sh: unexistant: command not found\n", exitCode: 127)
/bin/sh: unexistant: command not found
(output: "foo\n", exitCode: 127)
]#
test_execCmdEx()
```
> address #8160 when poStdErrToStdOut not set, stderr disappears

- lib/pure/times.nim
IMO `stringifyUnit` should never have been exported, since the functionality is already available with a more powerful API:
```nim
doAssert $initDuration(hours = 1) == stringifyUnit(1, "Hours")
```
The times module already has a large large amount of exported symbols, so we should avoid introducing overlapping functionality.
I also changed `stringifyUnit` to only work with `TimeUnit` since it doesn't work with arbitrary units anyway (not all units are pluralized the same way).
> Unexport times.stringifyUnit

- compiler/semtypes.nim
- tests/statictypes/tstatictypes.nim
The test case hits the path with this comment:
`# This happens with anonymous proc types appearing in signatures`
it should be safe to avoid the crash like this.
Fixes #6077
> Fix crash with static and anonymous procs

- lib/pure/ospaths.nim
- tests/stdlib/tospaths.nim
This fix was tested on windows PC but not tested on macos.
> Fix os.unixToNativePath proc returns wrong result(#8179)

- lib/pure/asyncftpclient.nim
I'm no async expert, but this solved my issue: #8184
> asyncftpclient: add missing file.close to retrFile

- changelog.md
- compiler/lexer.nim
- doc/manual.rst
- lib/posix/posix.nim
- tests/lexer/tintegerliterals.nim
- tests/lexer/tinvalidintegerliteral3.nim
- tests/misc/tunsignedmisc.nim
Fixes #8082 by on the one hand removing the previously allowed `0c` and `0C` prefixes for otcals from the compiler and the specs. On the other hand adds `0O` as an allowed literal for octals. 
Mainly to make the compiler behave in the same way as e.g. `parseOct` from parseutils.
I also had to change a few occurrences of `0c` oct literals in the `posix` module as well as one test case.
> Deprecate 'c', 'C' prefix for octal literals, fixes #8082

- lib/pure/typetraits.nim
/cc @Araq since you authored 9565da11e5014583a9afe0da6c4e2b83980a3e20
really not sure why newStringStream was used instead of this simpler alternative
also /cc @cdunn2001 bc of https://github.com/nim-lang/Nim/pull/5839
> simplify typetraits.nim test

- compiler/sigmatch.nim
- tests/typerel/t8172.nim
Fixes #8172 
Let's see if the CI likes it, I don't really like how the error message is worded though.
> Error out if vararg match isn't an exact one

- lib/nintendoswitch/switch_memory.nim
- lib/system/osalloc.nim
The first implementation was naive and did not account for multiple
memory allocations. However, this implementation may still be
incomplete. Currently, when running applications, the code runs fine.
When the application is exited via code (the end of the program is
reached or quit() is called), the Switch will crash. Not sure why this
happens, but I suspect it is from Nim memory allocations.
I suspect the memory allocations because when I compile the helloworld
application without any Nim allocations (just C function calls) and use
`--gc:none` as a compile option, the application exits fine.
If anyone has any tips on embedded memory allocation/deallocation issues, I would love
to hear them. I would also love to hear how Nim allocates stack memory if it's any different from C.
> Rewrite the memory management code for Nintendo Switch

- lib/pure/os.nim
- tests/stdlib/tos.nim
> Add normalizePath and tests

- lib/system.nim
was wrongly deleted in https://github.com/nim-lang/Nim/commit/c7298561c199255facc562402700322360408179
> Put back deprecation path for SomeReal

- compiler/sigmatch.nim
- tests/typerel/t7734.nim
As shown in #7734 and #7733 the logic in typerel fails to determine that `type Foo` and `type Foo` are indeed equal.
The simple solution is to check whether `a` and `f` are indeed equal, I don't know if the `==` check is enough though.
> Fix comparison of tyGenericBody in typerel

- lib/system.nim
this fixes this issue so code can now use `doAssertRaises ` without breaking nim doc.
Another PR would be needed to fix the underlying root cause, but that's less urgent
> workaround issue #8223 nim doc fails with doAssertRaises

- compiler/cgmeth.nim
Using getSysSym made the compiler pick a random `and` symbol: if the
symbol table is shuffled we may end up selecting one of the wrong
overloads.
Fixes #8246
> Pick the `and` symbol we need explicitly

- compiler/cgen.nim
- tests/cpp/t8241.nim
In order not to trip the optimization in genInfixCall we have to do so.
The same trick is also used in setExternName.
Fixes #8241
> Generate dynlib strings as a single rope

- lib/pure/json.nim
- lib/pure/strutils.nim
- tests/gc/cyclecollector.nim
- tests/js/tvarargs.nim
- tests/testament/tester.nim
Started with #5626 where test was never run, only compiled, since no action, output or exitCode check was defined in test case.
Per discussion on [IRC](https://irclogs.nim-lang.org/04-07-2018.html#20:11:26), decision to make testament run tests if no action specified.
Fixed a few test cases which now break since they never ran before. Please review to confirm I made the right assumptions.
Also opened #8231 and commented out that test case until it gets fixed.
> Testament should run tests with no action

- compiler/sigmatch.nim
- tests/generics/t7794.nim
The flag should not be carried out across different parameters.
Fixes #7794
> Reset typedescMatched before paramTypesMatch

- lib/pure/strformat.nim
- lib/pure/times.nim
- tests/js/ttimes.nim
- tests/stdlib/ttimes.nim
This PR contains new improved implementations of `times.parse` and `times.format`.
- More powerful mini-language
- Better performance
- Uses `static[string]` to validate layout at compile time when possible
- More consistent error handling, should now always raise a `ValueError` when something goes wrong
- Several minor bugs/limitations fixed
- All z* patterns now output 'Z' for UTC
- Added `g` pattern for era (AD or BC)
- Added `zzzz` pattern for UTC offset including seconds
- Added `uuuu` pattern for astronomical year padded to four digits
- Added `UUUU` pattern for astronomical year without padding
- Added `YYYY` pattern for year without padding
- Deprecated `y`, `yyy` and `yyyyy`. These patterns are not useful and complicate the mini-language for no good reason.
The `uuuu`/`yyyy` …
> New implementations of times.parse & times.format

- compiler/sigmatch.nim
- tests/converter/t7098.nim
The other (cleaner and saner looking) alternative I see is calling `paramTypesMatchAux` on the parameter to handle all the remaining corner cases but I was afraid of any potential side-effect.
Fixes #7098
> Handle subtype relations for converter parameters

- lib/pure/os.nim
fixes https://github.com/nim-lang/Nim/issues/8174
NOTE: see https://github.com/nim-lang/Nim/issues/8174 and  https://forum.nim-lang.org/t/4004 for prior discussion.
`absolutePath` would be best put in `ospaths` but nim doesn't support circular dependencies (yet...).
An alternative would've been to split in 2:
```
proc absolutePath*(path: string, base: string)
proc absolutePath*(path: string)
```
but that's uglier (and less DRY).
Another alternative would've been to add fwd reference of `getCurrentDir` in ospaths but that causes link errors in case user doesn't explicitly call `getCurrentDir`but just calls `absolutePath` in his code  (something nim could improve on IMO )
> add os.absolutePath; fixes #8174

- doc/astspec.txt
The example has the pragmas, reserved slot, and body parts of the `nnkProcDef` incorrectly inside of the `nnkFormalParams`.
> Fixed a wrong AST example

- lib/pure/options.nim
Previously, for some
```nim
type T = object
name: string
```
`$none(T)` would throw a type error. This is fixed, and the first test is added to show so.
The second test was never an issue but is included for good measure to ensure that a similar issue never happens in the future for a `proc(x: T): Whatever`
> Fixed $ on None[T] for T with .name

- lib/pure/terminal.nim
The Style enum needs to be an Ordinal so that it can be used in sets.
Ref: https://github.com/nim-lang/Nim/pull/8264
> Make the Style enum a proper Ordinal (no holes)

- lib/deprecated/pure/asyncio.nim
When ssl is defined, the PObject object reference causes a compiler error. It was replaced with RootRef in other places, so this seems logical.
Fixes #8261.
> Fix undefined PObject reference

- compiler/sighashes.nim
- tests/concepts/t8280.nim
We don't really want to hash the tyInferred container since that'd make
the "real" type and its inferred counterpart produce different hashes
and types for the very same type.
Fixes #8280
> Correctly hash inferred types

- compiler/semmagic.nim
- compiler/types.nim
- lib/system.nim
Make the compiler behave consistently with respect to what's written in
the manual.
Fixes #1239
> Do not consider enums with holes as ordinals

- compiler/extccomp.nim
Prevent some nasty linker errors if the user switches between c and cpp
backends.
> Give different names to objects coming from cpp files

- compiler/ccgexprs.nim
- compiler/cgen.nim
- lib/pure/memfiles.nim
- lib/system.nim
- lib/system/alloc.nim
- lib/system/ansi_c.nim
- lib/system/memory.nim
- lib/system/sysio.nim
- lib/system/sysstr.nim
From my experiments the assembly code remains the same, tested with "clang -O3". The implementations of memory functions are provided in `system/memory.nim`. They are very simple, but clang recognizes them enough to optimize to `mem*` intrinsics.
> Dont depend on string.h in codegen

- lib/wrappers/openssl.nim
SSL_set_SSL_CTX is required to implement [SNI(Server Name Indication)](https://en.wikipedia.org/wiki/Server_Name_Indication).
Implementation of SNI on the server side is not difficult, and it is possible by replacing SslCtx with the target SslCtx in the callback that acquires the server name.
However, this function is said to be a bad idea and may be abolished.
Well... at that time I will submit a new pull request 👍
> add SSL_set_SSL_CTX for SNI(Server Name Indication)

- compiler/sigmatch.nim
- tests/generics/t8270.nim
> Do not crash while instantiating a generic outside a call

- config/nim.cfg
- doc/nimc.rst
This was bad to put in here, so my bad. It doesn't work on anything except platforms with shell support. Users can use `--passC` and `--passL` options for customization.
> Remove cross-compile breaking env var in Nintendo Switch config

- compiler/ccgstmts.nim
- compiler/lineinfos.nim
- compiler/semexprs.nim
- compiler/semstmts.nim
fix https://github.com/nim-lang/Nim/issues/8195
fix https://github.com/nim-lang/Nim/issues/7405
NOTE: to fix these I ran:
```
(cd $git_clone_D/nim/Nim/  && ./koch temp)
$git_clone_D/nim/Nim/bin/nim_temp c -r test.nim
```
then looked at the stack trace to see a good insertion point for adding context via pushInfoContext that wasn't already covered by pushInfoContext
EG:
after this:
```
$git_clone_D/nim/Nim/bin/nim_temp c -r bugs/t01_error_context.nim
/Users/timothee/git_clone/nim/timn/bugs/t01_error_context.nim(14, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/Nim/lib/system/sysio.nim(351, 20) Error: cannot 'importc' variable at compile time
var p: pointer = fopen(filename, FormatOpen[mode])
^
$git_clone_D/nim/Nim/bin/nim_temp c -r …
```
> fix #7405 and #8195

- lib/pure/times.nim
This fixes https://github.com/nim-lang/Nim/issues/8273 + other issues
/cc @GULPF  just curious whether in your PR, https://github.com/nim-lang/Nim/pull/8094/files#diff-91d68bf578ea4bbef60621e73245f542R2073 was a conscious choice or an oversight: you introduced this overload:
```nim
proc format*(f: TimeFormat, dt: DateTime): string {.raises: [].} =
```
all other format overloads have the time first and format second. So I'm also fixing this in this PR (breaking change shouldn't matter since it's in devel branch, not master branch; and also since it's a very recent PR anyway)
> fix #8273 times format regression, and fix inconsistent ordering in 1 format overload

- lib/posix/termios.nim
115200 is really common.  I'd like to get support in nimserial, but
I'm guessing it would help to have support in the stdlib first.
> Add extended baud rates to posix/termios

- changelog.md
- lib/pure/terminal.nim
* The top-left corner of the terminal is position (1,1) on POSIX
> Fix setCursorPos and setCursorXPos on POSIX

- compiler/docgen.nim
- config/nimdoc.cfg
Hopefully I found the right file!
In documentation, the clickable `{..}` pragmas currently don't look clickable. They look like normal code and, given that it's not unreasonable to think that `{..}` is valid (if superfluous) code, that's what some users might think. I sure did.
> Make pragmas look clickable in docs

- compiler/sempass2.nim
- tests/init/t8314.nim
How do I check for the absence of warnings in the test?
Fixes #8314
> Extend init variable tracking to tuple assignments

- compiler/docgen.nim
let's see if my simple attempt to let `runnableExamples` start on a new line in the html docs is good enough...
might fix #8121,  #8346
> let runnableExamples start in a new paragraph

- doc/tut1.rst
Was going through the tutorial and noticed that this link just goes to the top of the page. The line got kind of long, so if we want the link to go on the next line let me know.
> Fix link to first class iterator docs

- compiler/semexprs.nim
currently all imports in runnableExamples disappear in the html docs generated via `nim doc`. This PR tries to keep imports visible in the generated html files.
> Keep imports in runnable examples visible in generated html docs

- lib/packages/docutils/rstgen.nim
- tools/dochack/dochack.nim
- tools/dochack/fuzzysearch.nim
**Motivation**:
The currently implemented doc search is subjectively not great.
It uses a basic regex search that is limited and misses relevant results.
It only searches exposed symbols from the standard lib, even though the manual consists of lots of other potentially useful documents, that can be exposed through `theindex.html`.
It is really odd, especially to new users, that on the main Nim language manual page, the search results do not show results from that page, but instead show results from the standard library.
A prime example of new user issues that might be helped by this is this forum post:
https://forum.nim-lang.org/t/3990
Searching for "exec" with the current search implementation does not even show `OS.execShellCmd`.
The main result is `nimscript : exec(command: string)`, …
> Better doc search

- compiler/extccomp.nim
See https://forum.nim-lang.org/t/4062.
The summary is that there are warnings printed when compiling and that causes a deadlock, likely due to output buffers being filled up. With the `-w` flag, the compiler outputs no warnings and the compilation is allowed to finish.
> Add -w flag to Switch compilation to prevent deadlock

- lib/pure/mimetypes.nim
Suggesting adding wasm | application/wasm as a mimetype to the mimedb.
This comes from emscripten docs - 
```
To serve wasm in the most efficient way over the network, make sure your web server has the proper MIME time for .wasm files, which is application/wasm. That will allow streaming compilation, where the browser can start to compile code as it downloads.
```
http://kripken.github.io/emscripten-site/docs/compiling/WebAssembly.html#web-server-setup
Jester relies on this mimedb and if you try to serve up files with wasm extensions via Jester, it will generate errors in firefox / chrome as well.
> Add application/wasm to mimetypes.nim

- lib/pure/times.nim
Removed two enum stringification procs in favor of declaring the string values directly in the type definition.
> Small times.nim refac

- lib/pure/ioselects/ioselectors_epoll.nim
- lib/pure/ioselects/ioselectors_kqueue.nim
- lib/pure/ioselects/ioselectors_poll.nim
- lib/pure/ioselects/ioselectors_select.nim
- lib/pure/selectors.nim
Use `-1` as an invalid FD. Treat `0` as valid FD. Useful for async stdin.
> Allow async stdin

- lib/system.nim
The HTML anchor IDs were changed, which made those links not link to the appropriate section anymore.
> Fix links to manual.html in the system module documentation

- lib/system.nim
/cc @Yardanico 
before this PR, ` {.line: instantiationInfo().}` was wrong, it actually created a new file instead of recognizing an existing file in
```
proc pragmaLine(c: PContext, n: PNode) =
=>
n.info.fileIndex = msgs.fileInfoIdx(c.config, x.strVal)
```
and after that, the stacktrace would show weirdly for this entry as shown in #7492
After PR, these problems go away, and stack traces show up correctly
(full or not full depending on`--excessiveStackTrace` )
/cc @Araq you wrote this comment:
`# XXX this produces weird paths which are not properly resolved:`
I wonder whether that comment was due to that bug being fixed here
> fix #7492 excessiveStackTrace:on shows non-absolute file in stacktrace

- compiler/lambdalifting.nim
- tests/iter/t338.nim
Reuse the existing machinery, most of the changes are only needed to
handle the `result = result` node in nkReturnStmt produced by the
closure iterator transform.
Fixes #338
> Access implicit `result` trough envP in closures

- compiler/modulepaths.nim
- compiler/options.nim
Probably not the cleanest fix. The issue was that module paths are resolved recursively, and the `std` logic is applied in the last iteration. So for `std / times / datetime` the special handling of `std` was applied to `std / times`.
I noticed that the dot style for imports (e.g `import path.to.module`) doesn't support the std namespace. Is that intentional?
Refs https://github.com/nim-lang/Nim/issues/8382#issuecomment-406783739
> Fix path resolution of submodules in the std namespace

- lib/pure/random.nim
Previously, calling `rand` with negatives would result in a SIGFPE or a hanging program.
> Add checks for random.rand()

- compiler/sem.nim
* simpler fix for #8323 : avoid polluting git satus after `nim doc foo`
(after feedback from https://github.com/nim-lang/Nim/pull/8392)
foo_nimcache,foo_examples.nim, foo_examples will be generated under nimcache/runnableExamples/
* fixes bug: was missing conf in renderModule(c.runnableExamples, inp, outp, conf = c.config)
> simpler fix for #8323 : avoid polluting git satus after `nim doc foo`

- lib/system/ansi_c.nim
Useful for debugging low-level stuff like GC.
> Added c_abort to ansi_c

- lib/pure/encodings.nim
- tests/stdlib/tencoding.nim
I'm not using `newString` but `newStringOfCap + setLen`.
This is done intentionally to anticipate future v2 string,
v2 newString use alloc0 while newStringOfCap use alloc, so it is probably faster.
> fixes #8468, stdlib.encodings.convert not crash anymore on windows

- compiler/docgen.nim
- compiler/options.nim
- config/nimdoc.cfg
- koch.nim
- tools/nimweb.nim
/cc @Varriount  
* fix #8419
* fix #8420
* workaround #6071
* workaround https://github.com/nim-lang/website/issues/98
* Abroken: fixes fact that locally built website points to broken urls
* new nim doc flag: `--git.devel` to override hardcoded `devel` in config/nimdoc.cfg ; useful for git repos in which the development branch is not devel (it usually is `master`, not `devel`)
* some minor code cleanups
eg usage:
```
./koch web --output:/tmp/d20
open /tmp/d20/index.html # see website and docs, with non-broken links
./koch web --output:/tmp/d20 --git.commit:devel
./koch web --output:/tmp/d20 --git.commit:myfeaturebranch --git.url:https://github.com/timotheecour/Nim
#NOTE: can use --git.commit:`git rev-parse --abbrev-ref HEAD` to get current branch
./koch web --output:/tmp/d20 --onlyDocs …
```
> fix #8419 fix #8420 ; workaround #6071 workaround nim-lang/website#98

- compiler/vm.nim
- compiler/vmgen.nim
- tests/vm/tref.nim
Also some related refactorings:
- Replaced the old `TGenFlag` values with new values that are more descriptive. `{gfNode}` is equivalent to `{gfAddrOf, gfFieldAccess}` and `{gfNodeAddr}` is equivalent to `{gfAddrOf}`.
- Split `genAddrDeref` in two - `genAddr` and `genDeref`
Fixes #8402 (the actual fix is line 581 and line 1398 in `vmgen.nim`).
> Fix ref bug in vmgen

- changelog.md
- compiler/vm.nim
- lib/core/macros.nim
/cc @Varriount 
before PR:
check 1==2 would return project path regardless of --listFullPaths
(inconsistent with other logging)
after PR:
check 1==2 would return absolute path when --listFullPaths is provided
(consistent with other logging)
likewise with require.
Note: this fixes https://github.com/nim-lang/Nim/issues/7429 (item A_lineInfoObj)
**EDIT**
/cc @Araq 
new behavior after feedback from @araq is to always return absolute path instead of previous behavior which was to always return project path. New behavior is better because project path can be ambiguous for users when printed out as it depends on cmd line args (it found the first path, via `-p` cmd line, where file is found and prints the path relative to that)
> `lineInfoObj` (and `check`, `expect`) now return absolute paths

- tests/fragmentation/tfragment_alloc.nim
/cc @araq since you introduced that test in 6d4107b
* fixes tfragment_alloc.nim (which allocates 4GB) often makes appveyor fail with out of memory #8509
> fix #8509 disable 4GB allocating test on windows that crashed appveyor

- lib/pure/unittest.nim
this works without checking for nil:
```
var checkpoints {.threadvar.}: seq[string]
proc test()=
echo checkpoints
echo checkpoints == nil
checkpoints.add("hi")
echo checkpoints
```
> remove redundant test for nil before `add`

- lib/system/gc_common.nim
I heard you like structured data output, so I structed the heap dump.
Actually I had a leak and wanted to get the dump as XML on Genode.
https://github.com/ehmry/nim-genode/blob/8c5f0fa1447a28bdd85f1915be1acabca0c28341/src/genode/diagnostics.nim
> Structured alternative to `dumpNumberOfInstances`

- compiler/rodutils.nim
- lib/pure/math.nim
- lib/windows/winlean.nim
tested with MSVC
* 2010 32-bit, a C89 compiler
* 2015 x86, a C99 compiler
* 2015 x64, a C99 compiler
> fixes #8421, fixes #7968, Nim compiler compiles with MSVC C89 version

- lib/system.nim
Since countup/countdown only works with a positive step, it should be enforced in the signature.
> Stricter signature for countdown/countup

- compiler/lineinfos.nim
- compiler/sem.nim
code still removes generated binary and nimcache, but now keeps generated `foo_examples.nim` file around in case of success (and prints that file)
benefits:
* useful in case user wants to see generated file
* doesn't cause any harm as it's inside a gitignore'd directory (since a previous commit) and tiny (compared to nimcache and exe)
* makes it clear to user that a runnableExamples file was generated and run (otherwise user may think it is generated when in fact it's not, because of https://github.com/nim-lang/Nim/issues/7280)
my previous workaround was to insert a `doAssert false` to make the test fail just to see what's inside or to make sure the file was generated.
> runnableExamples: keep (gitignored) generated foo_examples.nim for inspection even on success

- lib/pure/collections/sequtils.nim
Don't try to be too smart and limit the use of `evalOnce` where strictly
needed as not every value can be assigned with a `let`.
Fixes #8566
> Fix regression for mapIt

- build_all.sh
keeping the `nim` build from csources is useful to avoid having to rebuild it via `csources/build.sh`  whn it's needed; 
it's needed  eg to make sure bootstrap still works, see for eg https://github.com/nim-lang/Nim/issues/8577 where problem only occurs during bootstrap, not once a bin/nim is already bootstrapped)
it also makes it more efficient to rerun `sh build_all.sh` if user wants to rebuild nim+toosl after hacking on compiler
> save a backup of csources-built nim to bin/nim_csources to avoid recompiling from csources

- doc/manual.rst
- lib/pure/sugar.nim
- tests/stdlib/tsugar.nim
> fix #8519 T.distinctBase to reverse T = distinct A

- tests/testament/categories.nim
Sometimes I mistype the category name and spend way too much time wondering why there's no output at all.
> Preliminary check for test category folder existence

- config/nim.cfg
- lib/deprecated/pure/sockets.nim
- lib/posix/posix_other.nim
- lib/pure/concurrency/cpuinfo.nim
- lib/pure/coro.nim
- lib/pure/distros.nim
- lib/pure/encodings.nim
- lib/pure/fenv.nim
- lib/pure/math.nim
- lib/pure/nativesockets.nim
- lib/pure/os.nim
- lib/pure/times.nim
- lib/system.nim
- lib/system/ansi_c.nim
- lib/system/osalloc.nim
- lib/system/threads.nim
- tests/osproc/texitsignal.nim
- tests/osproc/tworkingdir.nim
- tests/testament/categories.nim
~~Currently still WIP, please don't merge,~~ but any help is welcome!
This PR brings support inline with current Haiku (hrev52165), as well as fixing some POSIX quirks in Nim.
Only C and C++ backends are being tested so far.
Failing tests (23 tests, 1.47%):
- async
- Due to [Haiku #14312](https://dev.haiku-os.org/ticket/14312)
- tacceptcloserace
- tasyncawait
- tasyncconnect
- tasyncdial
- tasyncsend4757
- tasyncssl
- Hangs: Could be due to `ioselectors_poll` being buggy, as crash can be reproduced with Linux
- tasyncRecvLine
- tnewasyncudp
- cpp
- tasync_cpp (`cannot open file: jester`)
- dll
- client: crash on `SIGSEGV`, for all variations of the test
- fragmentation
- tfragment_alloc (`out of memory`, my test system only have 2G of RAM)
- tfragment_gc
<details>
```
occupied ok: true …
```
> Haiku support for Nim

- lib/pure/collections/sequtils.nim
/c @Araq @LemonBoy more fixes coming after this PR, eg: https://github.com/nim-lang/Nim/pull/8586 (+ 2 others) which depend on this to be merged first ; so can we merge this sooner rather than later?
* fixes #8577
* builds on and improves https://github.com/nim-lang/Nim/pull/8578 (from @LemonBoy) to also fix these:
* fixes #8580
* fixes https://github.com/nim-lang/Nim/pull/8578#issuecomment-411614711 
* avoids duplicate initialization of `result` in `mapIt`
* adds more test cases
> fixes #8577, #8580, other bug fixes

- doc/nimc.rst
Fixes https://github.com/nim-lang/Nim/issues/7586
Not sure about what all the hints mean, I've added them nonetheless so users can experiment on their own, it at least saves them from greping the compiler sources. But anyhow, if there are some that should be considered as private to the compiler I can remove them. And of course, please feel free to provide the missing explanations :)
> Fixes #7586: Adds documentation for hints

- compiler/ast.nim
- compiler/astalgo.nim
- compiler/transf.nim
- tests/ccgbugs/topenarraycast.nim
When a `var openArray[T]` function parameter goes trough the
`transformAddrDeref` pass we may lose the `var` specifier, leading to
nasty crashes at runtime.
> Fix unsound transform pass

- tests/testament/tester.nim
* `getCurrentExceptionMsg()` was added in this block:
```
except IOError:
given.err = reCodeNotFound
```
to provide useful diagnostics when `IOError` occur; otherwise looking at logs is not helpful:
example from a failed travis job: https://travis-ci.org/nim-lang/Nim/jobs/416117242 
with this PR we get the useful line "cannot open: nimcache/tests/pragmas/tnoreturn.nim_0d61f8370cad1d412f80b84d143e1257/.tests.pragmas.tnoreturn.c" :
```
PASS: tcopying.nim JS -d:nodejs -d:release                         (1.76057816 secs)
cannot open: nimcache/tests/pragmas/tnoreturn.nim_0d61f8370cad1d412f80b84d143e1257/.tests.pragmas.tnoreturn.c
FAIL: tnoreturn.nim C
Test "tests/pragmas/tnoreturn.nim" in category "pragmas"
Failure: reCodeNotFound
Expected:
Gotten:
```
without this PR, all we get is the …
> [trivial] tester.nim add more diagnostics

- lib/pure/ospaths.nim
same as:
* in D: [escapeShellCommand](https://dlang.org/library/std/process/escape_shell_command.html)
* in C#: [QuoteArguments](http://gfxmonk.net/2014/04/25/escaping-an-array-of-command-line-arguments-in-csharp.html)
* in perl: [String::ShellQuote](https://metacpan.org/pod/String::ShellQuote)
* in node: [quote](https://github.com/substack/node-shell-quote)
* in ruby: [shelljoin](https://ruby-doc.org/stdlib-2.3.0/libdoc/shellwords/rdoc/Shellwords.html)
* in go: [shellquote](https://github.com/kballard/go-shellquote)
> add quoteShellCommand

- appveyor.yml
- compiler/ccgexprs.nim
- config/nim.cfg
- lib/nimbase.h
- lib/pure/ioselects/ioselectors_select.nim
- lib/pure/os.nim
- lib/system.nim
- lib/system/ansi_c.nim
- lib/system/excpt.nim
- wrap strings in "Genode::Cstring" when logging
- define SIGABRT for Genode
- disable GCC -fstack-protector
> Genode fixes

- lib/js/jscore.nim
The `push` pragma caused issues because apparently it overrides existing `importcpp` pragmas, which meant that none of the `newDate` overloads could be used.
> Remove broken push pragma from jscore

- changelog.md
- lib/pure/times.nim
- tests/js/ttimes.nim
- tests/stdlib/ttimes.nim
This PR makes some changes to the `times.Timezone`/`times.ZonedTime` types:
- `times.Timezone` is now a `ref` type.
- `times.Timezone` is now immutable. Initialization is done with an explicit constructor: `newTimezone`.
- Subsequent calls to `utc()` and `local()` returns the same instance, avoiding additional allocations.
- Changed `times.ZonedTime` to store the `Time` instead of the adjusted `Time`.
I also made some small correction in doc comments, and started using `math.floorDiv` instead of inlining the logic.
Timezones are currently copied to every `DateTime` object, which is wasteful and bloats the `DateTime` type. The old implementation also caused a string allocation every time `utc()` or `local()` was called. This new implementation will hopefully make more sense.
The changes in …
> times.Timezone changes

- compiler/semcall.nim
- tests/proc/t8683.nim
The old implementation relied on the (now?) wrong assumption that
default-valued parameters can only be placed after the required ones.
Fixes #8683
> Update all the default parameters after an instantiation

- compiler/lookups.nim
- tests/modules/t8665.nim
Take this into account while searching for undefined forward references.
Fixes #8665
This `sf...` flag reuse is an endless source of silly problems like this.
> sfForward is also sfReorder for skModule symbols

- compiler/pragmas.nim
- compiler/suggest.nim
- tests/deprecated/importme.nim
- tests/deprecated/tmodule1.nim
- tests/deprecated/tnoannot.nim
Prevent `deprecated` annotations to "slip" up to the parent module and
warn about unsupported annotations.
Accidentally fixes #7867
> More robust handling of deprecated pragmas

- tests/testament/htmlgen.nim
Fallout from the nil-str patch. Nothing to see here, move along.
> HTML generation in testament works again

- compiler/semexprs.nim
- compiler/semfold.nim
- compiler/types.nim
- tests/magics/t8693.nim
`containsGenericType` was too shallow and didn't check all the branches.
The resulting half-processed nodes are often simplified by the constant
folding pass but when that's not possible we get a nasty error during
codegen.
Fixes #8693
I also found out that trying to use `not <type>` often yields a stack overflow in `typerel` but didn't investigate much.
> Don't consider tyAnd/tyNot/tyOr/tyAnything as generic

- compiler/rodutils.nim
- lib/pure/math.nim
partially reverts https://github.com/nim-lang/Nim/commit/c3d5ec8eadf3aa887f34231c2d7b5818923818d4
fixes #8594
> fixes 8594

- compiler/semtypes.nim
- tests/proc/t8357.nim
Fixes #8357
Despite what the ticket says this has nothing to do with concepts (for once)
> Pick skParam symbols when resolving type idents

- compiler/semfold.nim
- tests/misc/tsemfold.nim
abs was incorrectly implemented, and unary sub didn't prevent against overflows.
Fixes #7814 (this PR doesn't fix the the fact that `Inf.int` is allowed, but it fixes `-low(int)` which is the cause of #7814).
> Fix abs & unary sub in semfold

- compiler/docgen.nim
/cc @Araq 
* fix: `nim doc2 --project -o:doc/ ` cannot find files in subdirectories https://github.com/nim-lang/Nim/issues/8218
* the error msg was super confusing, since it referred to a file that existed (filename) instead of the file to be created (outfile)
* fixed error by calling `createDir(outfile.parentDir)`
> fix #8218: `nim doc --project` was failing

- lib/pure/times.nim
Workaround until #6668 is fixed by someone. I don't have a Windows machine to test this on (and it's not possible to test it with testament), so somebody needs to verify that this fixes #8743 manually.
Fixes #8743
> Fix for #8743

- compiler/commands.nim
- compiler/nimconf.nim
- lib/system/nimscript.nim
/cc @Araq 
* fix #8739 allow --hint:foo:on --warning:bar:off
* partially address: nim command line should be nested instead of flat (cf git command line) #8216
NOTE: `--hint.foo:on` was not a good option:
eg, passing --hint.foo:on on a compile BEFORE this PR would silently accept it via `setConfigVar` (and not process the flag!) instead of given an error
* I made as few changes as possible while keeping sane semantics
processSpecificNote accepts either `[key]:val` or `key:val`
previously, it accepted only `key]:val` which made it awkward to work with both `--hint:foo:on` and `--hint[foo]:on` syntaxes without introducing ambiguities; so I made sure all code paths include the leading `[` when the form `[key]:val` is provided, to lift this ambiguity.
> fix #8739 allow --hint:foo:on --warning:bar:off; ref #8216

- compiler/pragmas.nim
- tests/pragmas/t8741.nim
We're not interested in custom pragmas attached to certain node kinds so
the compiler silently ignored them.
> More checks for custom pragmas placement

- lib/core/macros.nim
- lib/system.nim
- lib/system/helpers.nim
- tests/assert/testhelper.nim
- tests/assert/tfailedassert.nim
- tests/assert/tfaileddoassert.nim
/cc @Araq 
before PR:
* when assert fails, no line context was shown;
* when doAssert fails, project path was shown (can be ambiguous), via `file(line)`
after PR: 
* doAssert, assert now print full path of failing line on error: `file(line, col)` (same rationale as https://github.com/nim-lang/Nim/pull/8466)
* refactoring so lib/core/macros.nim can reuse code to print Lineinfo
> doAssert, assert now print full path of failing line on error

- .gitignore
a better fix would be to output `foo.html` in nimcache when running `nim doc foo.nim`, as it would also apply to other repos without having to add a line to gitignore and would be easier to clean up in bulk mode, but that can be done in subsequent PR
NOTE: `nim doc foo.nim` is useful for both running runnableExamples and inspecting output of html when working on a PR. it shouldn't affect `git status`
> gitignore html output of nim doc foo

- lib/system.nim
New strings/seqs make the idea of a variant of `len()`- i.e. `xlen()` - that does not check for `nil` as opposed to our standard `len()` useless.
> Deprecate xlen() for strings and seqs

- lib/pure/ospaths.nim
* fixes #8491 (which is actually still broken: `XDG_CONFIG_HOME` was being happily ignored due to a bug in nim:when #8681), see [1]
* adds (private) normalizePathEnd which is needed here and in other upcoming PR's to ensure we have exactly 0 or 1 trailing dir separators (taking care of special cases on windows); the previous coded didn't guarantee that (on top of the main bug)
[1] here's the bug: `XDG_CONFIG_HOME` is ignored:
XDG_CONFIG_HOME=FOO rnim bugs/compiler/t20_XDG_CONFIG_HOME.nim
nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r bugs/compiler/t20_XDG_CONFIG_HOME.nim
getConfigDir()=/Users/timothee/.config/
bugs/compiler/t20_XDG_CONFIG_HOME.nim:
```nim
import ospaths
echo "getConfigDir()=", getConfigDir()
```
> [ospaths] fix #8491: XDG_CONFIG_HOME was being ignored due to #8681 + private normalizePathEnd

- compiler/vm.nim
- compiler/vmgen.nim
- lib/core/macros.nim
- tests/macros/tmsginfo.nim
Let's bring those to feature-parity with `error`.
> Allow `hint` and `warning` to specify its loc info

- compiler/cmdlinehelper.nim
- compiler/commands.nim
- compiler/nim.nim
- compiler/nimconf.nim
- compiler/options.nim
- compiler/scriptconfig.nim
- nimsuggest/nimsuggest.nim
/cc @Araq 
* run $systemConfigPath/config.nims if it exists
* run ~/.config/nim/config.nims if it exists
* run parendDir/config.nims if exists for each parendDir
* run project config.nims if exists
* run inputfile.nims if exists
these are controlled by `optSkip<XXX>ConfigFile 
* makes config.nims behave like nim.cfg
* supersides https://github.com/nim-lang/Nim/pull/8233
* fixes: config.nims should apply to subdirectories recursively, like nim.cfg does #8217
* refactors duplicate/out of sync code between nim.nim and nimsuggest.nim
> make config.nims behave like nim.cfg in terms of where these scripts are searched / run

- lib/pure/coro.nim
fixes these tests on OSX:
tests/coroutines/texceptions.nim
tests/coroutines/tgc.nim
tests/coroutines/titerators.nim
before PR:
```
Test "tests/coroutines/tgc.nim" in category "coroutines"
Failure: reNimcCrash
Expected:
Gotten:
Hint: used config file '/Users/timothee/git_clone/nim/Nim/config/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/git_clone/nim/Nim/tests/coroutines/tgc.nim.cfg' [Conf]
CC: stdlib_coro
CC: stdlib_lists
Error: execution of an external compiler program 'clang -c  -w -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0  -I/Users/timothee/git_clone/nim/Nim/lib -o /Users/timothee/git_clone/nim/Nim/nimcache/tests/coroutines/tgc.nim_0d61f8370cad1d412f80b84d143e1257/stdlib_lists.c.o /Users/timothee/git_clone/nim/Nim/nimcache/tests/coroutines/tgc.nim_0d61f8370cad1d412f80b84d143e1257/ …
```
> fix 3 tests on OSX: "The deprecated ucontext routines require _XOPEN_SOURCE to be defined"

- doc/manual.rst
After discussion in irc about issue #8818 (https://irclogs.nim-lang.org/30-08-2018.html#15:54:55), the experimental `enumerate` macro was proposed as a workaround.
This PR wraps the example macro in the manual in a block to create a new scope to avoid polluting the calling scope with a bunch of (to be reused) variable names.
I left the test case untouched and also fixed the line breaks for the case statement macro in the manual below, which previously (for me locally anyways) wouldn't produce a code block.
> Improve enumerate macro

- lib/pure/htmlgen.nim
Continuation of #8788. Follows the HTML spec here: https://www.w3.org/TR/html50/dom.html#elements
- 1 obsolete element removed: `<acronym>`
- 36 elements added: `<abbr>, <article>, <aside>, <audio>, <bdi>, <bdo>, <canvas>, <data>, <datalist>, <embed>, <figure>, <figcaption>, <footer>, <header>, <iframe>, <keygen>, <main>, <mark>, <meter>, <nav>, <output>, <progress>, <rb>, <rp>, <rt>, <rtc>, <ruby>, <s>, <section>, <source>, <template>, <time>, <track>, <u>, <video>, <wbr>`
- All elements now have `commonAttr` ("global attributes" in spec)
- A number of obsolete attributes removed: `accesskey, align, charset, longdesc, profile, valign, classid, codebase, declare, codetype, archive, standby`
- 1 typo fixed: `encype` is now `enctype`
- Move some attributes that are not required to optional.
> Update html elements to current html spec

- compiler/sigmatch.nim
- tests/macros/t8706.nim
When an empty nkArgList `varargs[untyped]` is passed around it is now
reused for efficiency sake and to prevent the introduction of a spurious
element: before this commit we'd pass the caller a
nkArgList[nkHiddenStdConv[nkBracket]] node instead of just an empty
nkArgList.
Fixes #8706
> Do not materialize empty varargs[untyped] arrays

- compiler/closureiters.nim
Fixes #8773
You can find a before/after comparison of the AST below.
I hope the C compiler is smart enough to shake out the dead branches, otherwise we'll have to get smarter and drop the empty branches when the final `nkElse` is introduced.
No idea about how to test this tho.
<details>
<summary>Broken AST</summary>
```nim
while true:
var :state
block :stateLoop:
goto :state6
state 0:
{.push, warning[resultshadowed]: false.}
var result: ResponseData
{.pop.}
block allRoutes:
result.action = TCActionNothing
result.code = 200
result.content = ""
var request = request
block routesList:
block routesList:
case reqMethod(request)
of HttpGet:
block outerRoute:
if pathInfo(request) == "/sendFile":
block route:
echo(["This doesn\'t get called"])
var future515441 = foobar()
:state = 1
return result …
```
> Make sure addGotoOut always inserts its node

- compiler/jsgen.nim
- tests/js/tjsffi.nim
- tests/js/tthismangle.nim
As shown in pragmagic/karax#67 using `this` as parameter name made the
codegen output wrong code (and the user didn't notice the errors in the
browser console).
> Correctly mangle `this` in the JS backend

- lib/pure/memfiles.nim
and more recently indexing past the Nim-logical end has become
illegal making this line cause a crash.
Not much more to say.
> This has been unnecessary as long as rawNewObj has called zeroMem,

- lib/pure/strscans.nim
Just some typos I stumbled across...
> [DOC] fix typos in `strscans` documentation

- lib/js/asyncjs.nim
- lib/pure/asyncmacro.nim
Mark internal procedures as used
Allow .async. for more node kinds
Make .async. work for nkStmtList
Fixes #6971
> Minor fixes for asyncjs

- compiler/transf.nim
- tests/js/t7534.nim
Fixes #7534
The C backend gets away without this by ignoring the `nkIfExpr` type altogether and uses the `nkCaseStmt` one instead.
> Fix AST generation for case statements

- compiler/jsgen.nim
- lib/system.nim
- lib/system/jssys.nim
As requested by @Araq.
Fixes #6163 by accident.
A couple of notes:
- JS strings are immutable while Nim's `cstring` are mutable, trying to modify one gives a codegen error.
- Some places expect strings/seqs to be `null`, other will happily crash at runtime.
- The concatenation shortcut when the LHS is null is wrong given JS semantic wrt strings.
- Strings may get a performance boost by using JS typedarrays.
> JS strings have no trailing zero

- lib/system/hti.nim
- tests/ccgbugs/thtiobj.nim
The compiler is now smart enough to emit types only if needed without
all the importc tricks. This also fixes a codegen bug where, if all the
stars align correctly, typeinfo doesn't include any definition of
`TNimType` but uses it.
Found by @skilchen in #8938
> Always emit hti object types if needed

- lib/system.nim
- tests/js/taddnilstr.nim
The conversion makes no sense but it doesn't crash anymore.
> Fix add(string, cstring) when the lhs is null

- compiler/sighashes.nim
- lib/system/hti.nim
- tests/ccgbugs/t8964.nim
Since the name mangling is inhibited we should take the user-supplied
name during the sighash computation.
Fixes #8964
CC @sinkingsugar
> Fix hashing for codegenProc (sic) types

- doc/manual.rst
Closes #8699.
Might also for #8822. (depends on if {.reorder.} needs new impl)
> [Docs] Added {.experimental: "codeReordering".} to manual

- compiler/ccgexprs.nim
- compiler/ccgtypes.nim
- tests/ccgbugs/t8967.nim
Sometimes sets are materialized as arrays and we must treat them as
such: the CPP backend is pickier than the C one and would sometimes
produce invalid code.
Fixes #8967
>  we treat set[char] in getParamTypeDesc
Yeah, sure, heh.
> Fix codegen for set[T] parameters

- lib/system/sysio.nim
see discussions in #8961 and https://github.com/nim-lang/Nim/commit/4ab99537875a763e0540fbbe48d69cad454ca792
I am taking 
```
sp = cint(cast[PGenericSeq](line.string).space)
```
literally from the old implementation. I don't know if this is a good solution.
> more efficient fix for #8961

- compiler/cgen.nim
- compiler/commands.nim
- compiler/options.nim
- doc/advopt.txt
- lib/nimbase.h
Until now the option `cppCompileToNamespace` was using a hard coded "Nim" namespace, this PR makes it possible to specify a custom namespace.
This is very useful when building dynamic libraries and plugins where we want different Nim modules compiled with different options to completely use different linked code. (requires `--noMain`, `cpp`)
This PR also removes the need to link nimRtl which is currently very well broken. (at the cost of every module having a GC or regions etc.)
> Improve the compiler option cppCompileToNamespace

- lib/posix/posix_other.nim
- lib/pure/net.nim
The only way to make this work for both abstract and non-abstract
sockets is to send the kernel an incomplete structure.
Reported by Epictek on the forum.
> Fix connectUnix/bindUnix with abstract socket paths

- lib/posix/posix_other.nim
The change is technically correct but requires too much type juggling
and the effort outweighs the gains.
> Fix regression due to type change

- lib/pure/strscans.nim
- tests/stdlib/t8925.nim
The error in #8925 is a result from `getType `being used on a non base type. Using `getTypeInst` we get the named type instead, which should be more helpful as an error message (and won't let us crash in `macros.nim`).
Of course in this case e.g. `HourRange` can actually be converted using `parseInt`, but allowing `ntyRange` in https://github.com/nim-lang/Nim/blob/54d22d7cdc53c8b700d717c5924e0c588d56748e/lib/pure/strscans.nim#L359 seems wrong, if we don't check the base type of the range. At least in principle it doesn't have to contain `SomeInteger`, yes?
Does this warrant a test case?
> fix #8925 by using `getTypeInst` instead of `getType`

- compiler/vm.nim
- tests/vm/t4952.nim
Tuple constructors can't have nkExprColonExpr but may contain NimNodes
of that kind.
Fixes #4952
> Fix error during field access in VM

- lib/system.nim
This definition has already appeared 5 times across our codebase. 
Even though the `system` module has operators for `array` and `seq`, these are not sufficient inside functions having `openarray` parameters.
> Implements the equals operator for openarray

- .travis.yml
To make this PR functional, @Araq or anyone who has admin rights to this repo will need to get the GitHub API token for **repo** level permissions from https://github.com/settings/tokens. The token will be visible only once. So once you get it, copy it.
Now go to Travis CI settings in a different browser tab, and create an env var named **GITHUB_OAUTH_TOKEN** ([as that's what this PR uses][1]) and paste that copied token value there. *Ensure that this env var value is not made public (by default, it's not public).*
/cc @LemonBoy 
[1]: https://github.com/nim-lang/Nim/pull/8992/files#diff-354f30a63fb0907d4ad57269548329e3R74
> Deploy devel build of docs to https://nim-lang.github.io/Nim

- lib/system/hti.nim
- tests/cpp/t9013.nim
Declare the root symbol only once and have the other modules depending
on it emit an `extern` declaration.
Fixes #9013
> Fix linking issue in cpp codegen

- compiler/pragmas.nim
#8765 disabled custom pragmas on most symbols. Until now I [was using them extensively](https://github.com/fragcolor-xyz/nim2spirv) on variables, etc.
Is the set of allowed locations specified somewhere? Would we need anything else to extend it again?
> Allow custom pragmas on more symbols again

- compiler/plugins/locals.nim
- tests/misc/tlocals.nim
Follow the same logic as semTupleFieldsConstr and only skip skVar since
we're gonna add a nkDefer anyway.
Fixes #8985
> Fix locals() interaction with generic types

- lib/pure/ioselects/ioselectors_poll.nim
`pollAdd()` is called only if the events set isn't empty. This fixes some tests on Haiku.
> ioselectors_poll: don't pollRemove() if not needed

- doc/nims.rst
- Use "\<myproject\>" instead of "myproject" so that it looks more like
a project name placeholder.
- Add macros module to the list of modules that can be imported in
.nims files.
- Fix typo: nim.cfg -\> \<myproject\>.nims.
> Minor edits to NimScript (nims) docs

- lib/posix/posix.nim
Fixes the code example for `posix.onSignal` for the docs and also injects the currently handled signal as `s` into the calling scope. 
For the latter maybe I'm missing something obvious and this isn't even necessary? If so, I can take that out again. Accessing `sig` in the body doesn't work.
> fix `posix.onSignal` example, inject current signal as `s`

- lib/wrappers/openssl.nim
Prevent spurious segfaults when OpenSSL is used in multithreaded
environments since the library isn't able to handle thread-local memory.
Fixes #9016
> Allocate OpenSSL memory outside of the thread heap

- compiler/ccgexprs.nim
- tests/ccgbugs/t9098.nim
Taking the LHS type when a temporary result value was needed lead to bad
code being generated if we get a tyRef.
Fixes #9098
> Fix codegen for some set operations

- doc/nimc.rst
User config file path on Nim Compiler User Guide was not updated after PR #8662.
> Nim Compiler User Guide: Fix how user config file is searched

- tools/dochack/fuzzysearch.nim
https://irclogs.nim-lang.org/28-09-2018.html#19:43:52
Was a stupid one liner 😿 for a fairly common edge case. IDK why it wasn't caught before. I think some browser versions were more lenient about the error.
> Bugfix for fuzzysearch found by Zevv

- config/nimdoc.cfg
- lib/packages/docutils/rstgen.nim
- lib/pure/uri.nim
- nimdoc/testproject/expected/subdir/subdir_b/utils.html
- nimdoc/testproject/expected/testproject.html
- nimdoc/testproject/expected/theindex.html
Use $itemSymOrIDEnc instead of $itemSymOrID in the id and href attr in
a tags.
Fixes https://github.com/nim-lang/Nim/issues/9097.
Thanks to @LemonBoy for helping with this commit.
> Encode non-alphanum chars like %, + in URLs in the docs

- tests/async/tasyncfilewrite.nim
/cc @Araq 
fixes a bug where ./koch tests would leave a test_async.txt, making git status not clean
> remove test_async.txt after test to keep git status clean

- compiler/semgnrc.nim
- tests/generics/t8694.nim
- tests/generics/t9130.nim
The examples should not enter the generic analysis at all.
The regression was introduced in 4cf704bb as a fix for #8694.
Fixes #9130
Fixes #8694
> Fix regression with runnableExamples in generic expr

- install_nimble.nims
- install_tools.nims
It looks like these are deprecated scripts, and #4934 wanted them removed from the repo root as well. Been having a lot of fun using Nim over the last year.
> Remove install_nimble.nims, install_tools.nims as per #4934

- lib/pure/json.nim
Added a demo of `{}` for safely acquiring `JsonNode`s.  
The docs didn't quite flow right after air-dropping that in, so I divided it up into sections.  Hope that's ok.
Lemme know if there's a documentation style/tone-guide I should consult if this needs revisions.  I didn't see one after searching for a grand total of 12 seconds.
Closes #6531
> [docs/json]: expands existing examples + shows {} operator in action

- lib/nimbase.h
/cc @Araq
(references https://github.com/nim-lang/Nim/commit/9bd23b2d4cc94f6b31d7c45eb9dd20dcb64ccebe)
nullptr is safer because: https://www.geeksforgeeks.org/understanding-nullptr-c/ `Unlike NULL, it is not implicitly convertible or comparable to integral types.` so could remove some potential future codegen bugs.
> use 0 instead of nullptr because travis' C++ compiler doesn't know nullptr
weird that C++ doesn't know about nullptr since it was introduced in c++11, is `-std=c++11` passed in travis?
* could we use NULL instead of 0 in the else branch?
```
/* consider using NULL if comment below for NIM_NIL doesn't apply to C++ */
```
not sure if this comment applied only to C or also C++ (also, details or references would help...) …
> define NIM_NIL nullptr when __cplusplus >= 201103L

- lib/std/sha1.nim
As #9239 points out the old implementation had some serious flaws.
The new implementation is a port of the MIT-licensed one used by
Chromium OS and has been tested against the FIPS-provided vectors and by
generating huge files like the ones mentioned in the issue above.
While I tried my best to take into account the existence of BE machines
the code has only been tested on a LE one.
> Replace the sha1 implementation w/ a working one

- lib/pure/htmlgen.nim
Added some missing HTML Tags, some HTML5 tags, some HTML4 tags.
- center https://developer.mozilla.org/en/docs/Web/HTML/Element/center
- details https://developer.mozilla.org/en/docs/Web/HTML/Element/details
- dialog https://developer.mozilla.org/en/docs/Web/HTML/Element/dialog
- marquee https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee
- picture https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture
- slot https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot
- summary https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary
Some are super useful like `<details>` and `<picture>`.
:cat:
> HTMLGen Update

- compiler/parser.nim
- compiler/semstmts.nim
- tests/errmsgs/tgeneral_excepts.nim
- tests/errmsgs/tmultiple_finally.nim
This PR adds a check for number of general except blocks possible. It counts the number of `nkExceptBranch` nodes with only one son, and if that number exceeds 1 raises an error.
Addresses #9189
> Fix no checks for multiple except blocks

- compiler/docgen.nim
It was just a matter of copying&pasting some code.
```nim
proc foo*() =
##
##
raise newException(Exception, "boo!")
```
> nim doc can run code blocks

- compiler/cgen.nim
- tests/cpp/amodule.nim
- tests/cpp/t8241.nim
The fix is to use a local stack variable instead of global variable to avoid global variable redefinition problem:
```
Hint:  [Link]
C:\nim-devel\nimcache\tests\cpp\t8241.nim\compiler_amodule.cpp.o:compiler_amodule.cpp:(.bss+0x0): multiple definition of `T1_'
C:\nim-devel\nimcache\tests\cpp\t8241.nim\compiler_t8241.cpp.o:compiler_t8241.cpp:(.bss+0x8): first defined here collect2.exe: error: ld returned 1 exit status
```
> Fixes #9222, link time error when multiple dynlib pragmas with function calls used

- lib/pure/algorithm.nim
Fixes the 'koch docs' build failure.
Ref:
https://github.com/nim-lang/Nim/commit/b90b45b01bba1f3fc241a96abd4ae5c8c314bb92
> Fix typo in an algorithm runnableExamples

- lib/pure/os.nim
- tests/stdlib/tos.nim
`removeFile()` behavior should now be consistant between Windows and POSIX
Fixes #9200
> os: use unlink() to remove file

- compiler/vmdeps.nim
- tests/macros/t9194.nim
The `range[X,Y]` representation is wrong, we use `range[X .. Y]`
instead.
Fixes #9194
> Fix range type construction in the VM

- lib/pure/ospaths.nim
- tests/stdlib/tospaths.nim
/cc @araq
* fixes #8341
* no breaking change, added `lastPathPart` that is similar to extractFilename but ignores trailing dir separator, to get behavior found in:
unix cmd line, C, D, node.js
* added tests: tests/stdlib/tospaths.nim
* normalizePathEnd block was moved, no change there
* works well in conjunction with parentDir (which ignores trailing separator); added a note to that effect in parentDir doc comment
Note: pathSuffix would be another naming option...
> fix #8341: add lastPathPart

- lib/pure/math.nim
Decimal rounding on binary numbers doesn't make sense.
fix for #9082
> deprecate decimal rounding in binary floating point math libray

- lib/pure/asyncstreams.nim
- tests/async/tfuturestream.nim
Replaces #9159 and #9003.
See https://github.com/nim-lang/Nim/pull/9159#issuecomment-426871190 for how I arrived at this fix.
> Fixes #8994. FutureStream read procedure data loss no longer occurs.

- compiler/transf.nim
- tests/cnstseq/t2656.nim
What happens here is that the lambda lifting pass "lifts" the loop variables into `envP` slots on the heap while the iteratee is stack-allocated.
This is bad because the compiler assumes that by construction the AST doesn't contain such stack-on-heap moves using `nkFastAsgn`.
But there's more, I've also noticed that `genSeqElem` may compute a wrong `TLoc.storage` under some conditions: if we consider `it2` in the attached test case and the introduced expression `args[:envP.i2]` the compiler states that the resulting C code `args->data[(*colonenvP_).i2]` is `OnStack`. Of course that's wrong because the sequence `args` is not on the stack nor any of the items it contains.
> Fix yield transformation in inline context

- compiler/ast.nim
- compiler/docgen.nim
- compiler/semtempl.nim
@LemonBoy pretty much spelled out the fix, but I would have never gone in there without him doing so. Can't thank you enough for taking the time to do that.
One thing I would like to add is a a regression test. Unfortunately I was unable to figure out how to target `runnableExamples` without running the docs. Any advice?  Would it be an AST only type of test?
Before:
After:
Fixes #9143
> Fixes unexpected transforming of runnableExamples

- config/nimdoc.cfg
- nimdoc/testproject/expected/subdir/subdir_b/utils.html
- nimdoc/testproject/expected/testproject.html
Fixes https://github.com/nim-lang/Nim/issues/9232.
/cc @cup
> Do not encode the anchors in docs (`id` attr in `a` tags)

- lib/pure/algorithm.nim
Improvements:
* fixed style issues (before: small letter at the beginning of the sentence, too long lines, single backticks (italic) denoting code, etc.)
* don't use the word "array" for `openArray` as those can be not only arrays but seqs and strings too
* added the examples for the most of the procs
* made `rotateLeft` procs discardable
* both arguments to `reversed` are now `Natural` (before it was `first: Natural, last: int`), just like it was/is for `fill`
> better docs for `algorithm` module

- lib/pure/collections/tables.nim
Improvements:
* fixed style issues (before: small letter at the beginning of the sentence, too long lines, single backticks (italic) denoting code, etc.)
* added an example of how to use `CountTable` (valuable because I'm sure I'm not the only one who regularly tries to do `inc myTable[key]` and realizes that this is not possible, and `myTable.inc(key)` should be used)
Unlike #9192, here nothing outside of the docs is changed.
> better docs for `tables` module

- compiler/scriptconfig.nim
/cc @araq @LemonBoy 
* fixes https://github.com/nim-lang/Nim/issues/9264
> fix #9264 regression

- compiler/ast.nim
- compiler/ccgexprs.nim
- compiler/ccgtypes.nim
- compiler/condsyms.nim
- compiler/jsgen.nim
- compiler/semasgn.nim
- compiler/semexprs.nim
- compiler/semtypes.nim
- compiler/sigmatch.nim
- compiler/types.nim
- compiler/vmdeps.nim
- compiler/wordrecg.nim
- lib/core/macros.nim
- lib/system.nim
- tests/macros/typesapi.nim
- We have to take out one unused `ty...` member of the enum so that we can make `TTypeKind` fit in a single word again
- The JS backend doesn't know about this but I'm tired now
- It took less effort than expected but...
- ...I'm afraid this may be the second coming of `tyStatic` so please bear with me (and remember that @araq asked me to write this)
- The `.unchecked.` pragma is now useless, isn't it? (Let's deprecate stuff! I love deprecating stuff!)
> Unchecked arrays now have their own type

- tests/async/tioselectors.nim
- tests/async/tupcoming_async.nim
- tests/stdlib/ttimes.nim
#9209
* Replace `/bin/sleep` with just `sleep`, i.e. use environment variable `$PATH` to locate binary.
* Replace `/usr/share/zoneinfo` with `$TZDIR` when it is defined, fallback to hardcoded path otherwise. This is the same behavior that Glibc2 normally have, see [man 3 tzset].
[man 3 tzset]: https://linux.die.net/man/3/tzset
> Fix tests on NixOS

- compiler/cgen.nim
- tests/ccgbugs/t9286.nim
@Araq your heuristic was a bit too eager and removed the reset even though it was needed. The fix should be correct since it uses the informations gathered from all the previous nodes so that if nothing had initialized `result` before the point where the return is we insert a zeroing operation in the function prologue.
> Fix wrong heuristic in codegen

- doc/contributing.rst
- readme.md
/cc @Araq  @dom96  @kaushalmodi @mratsim 
* existing doc/contributing.rst is not very discoverable (I had previously created https://github.com/nim-lang/Nim/pull/8271 as I was previously unaware of its existence); this makes it more discoverable by linking to it from readme.md
* **style guides are useful** ; they save time for reviewers and PR authors and cut down on repetitive debates; oftentimes it's better to have guidelines than no guidelines and inconsistent approaches, so the intent is to keep adding to it over time. Not meant like a bible but more like a guide when in doubt, or for future code / modules.
* I updated it as best I could; there were glaring omissions (eg no runnableExamples ) and omissions; future improvements can just be made in other PR's
> make contributing.rst more up to date; reference it in readme.md to make it more discoverable

- compiler/ast.nim
- compiler/lineinfos.nim
- compiler/msgs.nim
- compiler/sem.nim
- compiler/semexprs.nim
- compiler/seminst.nim
- tests/concepts/t3330.nim
- tests/macros/tmsginfo.nim
- tests/testament/tester.nim
Make `template/generic instantiation from here` messages more specific. Fix #6763.
Not all `pushInfoContext` invocation are covered, but it is enough for cases listed in the issue.
Code: #6677
```
i6677.nim(17, 7) template/generic instantiation of `suite` from here
i6677.nim(18, 8) template/generic instantiation of `test` from here
i6677.nim(19, 5) template/generic instantiation of `check` from here
i6677.nim(20, 48) template/generic instantiation of `check` from here
<long path skipped>/lib/pure/unittest.nim(648, 14) template/generic instantiation of `==` from here
<long path skipped>/lib/system.nim(2496, 3) Error: parallel 'fields' iterator does not work for 'case' objects
```
---
Code: #4628
```
i4628.nim(11, 10) template/generic instantiation of `==` from here
<long path …
```
> compiler: show name of instantiating context in error traces (#6763)

- compiler/nimeval.nim
- tests/compilerapi/tcompilerapi.nim
/cc @araq
* fix #9180
* enables tcompilerapi test which was effectively disabled:
"effectively disable this test as 'nim' is not in the PATH so tcompilerapi cannot find Nim's standard library"
* add `findNimStdLibCompileTime`
* add test case for #9180
~~Note: https://github.com/nim-lang/Nim/issues/9184 is still an issue after this PR (no change before / after this PR regarding that issue)~~
> test case for #9180 and re-enables the disabled tcompilerapi test

- compiler/scriptconfig.nim
- lib/system/nimscript.nim
Mirrors some functionality of `nim.cfg`. Distinction between `Path` and `Full` seemed a bit vague to me so i switched the names. Don't know if this is appropriate solution, but it allows me to use only `config.nims` for global configuration.
>  Add procs to retrieve project name, directory and full path from nimscript

- doc/manual.rst
Fix https://github.com/nim-lang/Nim/issues/9288 https://github.com/nim-lang/Nim/issues/8376 and https://github.com/nim-lang/Nim/issues/2901
> Clarify that term rewriting macros are applied recursively

- compiler/ccgexprs.nim
- compiler/cgen.nim
- compiler/options.nim
- lib/system/mmdisp.nim
- lib/system/sysstr.nim
- Go's write barriers are now plugged-in in all the relevant points
- "gcGo" is correctly classified by usesWriteBarrier()
- some gogc structures and functions now use golib wrappers to keep GCC
version-specific conditions out of the compiler/stdlib code
- we no longer allow mixing the C malloc with Go's
- fix a problem with string copying
> gogc: GCC-8.2.0 compatibility and other improvements

- lib/system/dyncalls.nim
By using `write` instead of `rawWrite` we'd end up asking the compiler
to generate the GC dynlib _while_ we were already generating another
dynlib!
Fixes #9123
@Araq: I think you'd like this better than #9124 :)
> Avoid memory allocation during dynlib loading

- doc/manual.rst
I don't know much about history of Nim, but it seems ``stmt`` and ``expr`` templates are removed and compiler says "Error: undeclared identifier: 'expr'".
So I removed stmt or expr template related text.
> manual: Remove stmt or expr template related text from manual

- lib/pure/strutils.nim
Returns `s.len + 1` when substring `sub` is empty, as proposed in the issue discussion.
> Proposed solution for issue #8919

- compiler/ccgcalls.nim
- lib/system.nim
- tests/system/tsystem_misc.nim
This pull request would let users replace code like this:
```Nim
type MyTypes* {.unchecked.} = ptr array[0, MyType]
get(toOpenArray(myObs[], 0, n), 0).somefield[1]
```
with code like this:
```Nim
type MyTypes* = ptr UncheckedArray[MyType]
echo get(toOpenArray(myObs, 0, n), 0).somefield[1]
```
In both cases, `get` is just some `proc get*[T](x: openArray[T], i: int): T`, `myObs` is some instance of `MyTypes`, and `n` is some length computed at run-time.  I elided those to more starkly show the difference.
I don't know if that improves the ergonomics enough to close https://github.com/nim-lang/Nim/issues/9001, but it is a pretty simple change maybe worth consideration.
> Add `toOpenArray[T](ptr UncheckedArray[T])` for clarity.

- lib/core/typeinfo.nim
- lib/pure/marshal.nim
- tests/stdlib/tmarshal.nim
Fixes https://github.com/nim-lang/Nim/issues/8916.
This PR is partially based on @timotheecour's https://github.com/nim-lang/Nim/pull/8942, but fixes the issue seen in his example.
In `marshal.nim` we must not check for `isNil` of `tySequence` anymore and then in addition make sure we return the length of a sequence in `typeinfo` correctly. If the latter can be done differently, let me know.
> fixes #8916 by fixing typeinfo and marshal.

- lib/pure/strutils.nim
useful in conjunction with things like osproc.execCmdEx, or readline lines of text file (that could've been produced on another platform) for example.
in other languages:
* D: chomp https://dlang.org/library/std/string/chomp.html
* java: chomp https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html
* perl: chomp https://perldoc.perl.org/functions/chomp.html
* ruby: chomp https://ruby-doc.org/core-2.2.0/String.html
* scala: stripLineEnd https://www.scala-lang.org/api/2.7.7/scala/runtime/RichString.html
* node: newline-remove https://www.npmjs.com/package/newline-remove
it's easy to get wrong and common enough to be in stdlib (alongside `removeSuffix`)
Note: as in all (most?) of the above languages, the implementation of `stripLineEnd ` is not OS …
> add strutils. stripLineEnd: removes (at most 1) newline-like suffix

- lib/system.nim
- tests/assert/tfailedassert.nim
- tests/concepts/texplain.nim
/cc @Araq 
* refs #9301: `doAssert foo.bar.type is T` used to render the condition as the not informative `false`; now it correctly renders the condition as `foo.bar.type is T` (likewise with other const foldings)
* it renders `a > 1` as `a > 1` instead of transforming as `1 > a`
* fixes #8518: it now doesn't expand out condition in failed expression if it contains templates, which sometimes used to fill hundreds of lines in error messages
> correctly render AST in doAssert/assert condition: fix #8518; refs #9301

- compiler/ast.nim
- compiler/canonicalizer.nim
- compiler/condsyms.nim
- compiler/jsgen.nim
- compiler/pragmas.nim
- compiler/semexprs.nim
- compiler/semfold.nim
- compiler/semmagic.nim
- compiler/semtypes.nim
- compiler/sigmatch.nim
- compiler/sizealignoffsetimpl.nim
- compiler/types.nim
- compiler/vmgen.nim
- lib/system.nim
- testament/tester.nim
- tests/misc/tsizeof.nim
- tests/misc/tsizeof2.nim
- tests/types/tillegalrecursion3.nim
/cc @araq @krux02 
* this PR manually squashes https://github.com/nim-lang/Nim/pull/5664 to avoid messing git history (so a fast fwd merge can happen); 
* manually squashed + rebased as follows:
```
git fetch origin pull/5664/head:pr_5664
git checkout pr_5664
git merge origin/devel
git checkout pull_5664_3 -b origin/devel
git checkout pr_5664 -- `git diff --name-only pr_5664`
git commit --amend --author="Arne Döring <arne.doering@gmx.net>"
```
> implement sizeof and alignof operator (manually squashed @krux02 's PR  #5664)

- compiler/lexer.nim
- doc/manual.rst
- tests/lexer/tstrlits.nim
Changes:
- `\uHHHH` and `\xHH` must now use exactly four/two hex digits (already documented in the spec)
- `\uHHHH` is no longer allowed in char literals
- Added `\u{H+}`, which is used to escape an arbitrary unicode codepoint
Fixes #7068
> Unicode escape in string literals

- doc/nims.rst
Related: https://github.com/nim-lang/Nim/pull/8682
/cc @timotheecour @Araq
> Update config.nims search path in docs

- changelog.md
- compiler/docgen.nim
- compiler/docgen2.nim
- doc/docgen.rst
This fixes `jsondoc0` so that it has comments in the output as described
by the documentation. It also fixes `jsondoc`/`jsondoc2` as it stored
it's output in a file with an html extension. Along with this it also
adds a new field `moduleDescription` to `jsondoc`/`jsondoc2` which
contains the module description.
> Fix #9364 and add moduleDescription to jsondoc

- doc/filters.rst
As promised in issue #9384. Also gives source code filter an abbreviation, SCF.
> Elaborate on source code filter usage in the documentation.

- tests/async/tfuturestream.nim
- tests/collections/ttables.nim
- tests/generics/trtree.nim
- tests/parallel/tconvexhull.nim
- tests/parallel/twaitany.nim
I've checked the slowest tests on appveyor and tried to see if there is anything that can be improved.
* in `ttables.nim` there was a slow test which was duplicated. I've removed the duplicate, but didn't touch [the original number of iterations](https://github.com/nim-lang/Nim/blob/06a3b63e77a79297a8d91b117d0f6c39d9868f46/tests/collections/ttables.nim#L165)
* changes in other files include decreasing the number of iterations or less `sleep`
I've tried to do the same for the slowest tests on TravisCI, but the results seem very erratic (e.g. tests that should be fast taking more than a minute).
> make some tests faster

- doc/lib.rst
`docs/lib.html` still reads like the entire Nimble package list is included inline on the page but that's no longer the case.
> docs(lib): update Nimble notes since package list is not inline anymore

- lib/pure/endians.nim
The copy to a temporary local variable is often elided by a sufficiently
smart compiler when it can prove the input pointer is aligned.
Refs #9206
> Make the swap procs safe for unaligned input ptrs

- lib/pure/terminal.nim
- tests/stdlib/t9394.nim
Fixes #9394.
Until issue #7632 is fixed, use string append.
> fix #9394 by replacing `fmt` with `strutils.%`

- changelog.md
- lib/core/macros.nim
- tests/macros/tmacro1.nim
I am using this code, and whenever I don't have it I copy past it. So it might be worth to have it in the macros module.
This in an example code piece where I actually use it (it is not constructed to demostrate the or operator and therefore a bit long):
```nim
proc injectTypes(framebuffer, mesh, arg: NimNode): NimNode {.compileTime.} =
arg.expectKind(nnkDo)
let formalParams = arg[3]
formalParams.expectKind(nnkFormalParams)
let vertexTypeExpr = quote do:
`mesh`.type.VertexType
let fragmentTypeExpr = quote do:
`framebuffer`.type.FragmentType
let resultType = formalParams[0] or fragmentTypeExpr
var vertexArg, vertexType, envArg, envType: NimNode
formalParams.matchAst:
of nnkFormalParams(_,nnkIdentDefs(`vertexArgX`, `envArgX`,nnkEmpty,_)):
vertexArg = vertexArgX
vertexType = vertexTypeExpr …
```
> or on NimNode

- doc/contributing.rst
/cc @Araq @mratsim @narimiran @dom96 
I always wished there was a "best practices" section; let's start one and grow it over time, keeping it up to date with language improvements. It saves times for both PR authors and reviewers, we can just refer to this doc in code reviews, using anchors to the specific paragraph. 
There are plenty of posts on forum requesting such best practices section:
* [Lessons learned/idioms - Nim forum](https://forum.nim-lang.org/t/4124#25693)
* https://forum.nim-lang.org/t/4099#25496 "How should I handle testing these examples? ..."
* https://forum.nim-lang.org/t/1978#13958 "what are the best practices?"
* [Zen for NIM? - Nim forum](https://forum.nim-lang.org/t/1377#8593) "What are the recommended Practices between soo many choices? ..."
* …
> [doc] start of best practices section in contributing.rst

- changelogs/changelog_0_18_1.md
- changelogs/changelog_0_19_0.md
- changelogs/changelog_X_XX_X.md
- changelogs/readme.md
* fix https://github.com/nim-lang/Nim/issues/9376
* commands used to revive old changelogs:
- git show 86c3832201d5705463dfd7f33736385402cabdfc^:changelog.md > changelogs/changelog_0_18_1.md
- git show 7f81519f4114dbb49fcd68ca2361920bf374fb1c^:changelog.md > changelogs/changelog_0_19_0.md
(versions older than that were not in git)
* Also added links to changelogs (including older ones) stored in https://github.com/nim-lang/website
> fix #9376: old changelogs should be kept instead of erased

- lib/system/sysio.nim
- tests/stdlib/tissues.nim
Fixes #9456.
We didn't check whether the file pointer was nil before.
> Fixes #9456

- compiler/ccgexprs.nim
- tests/magics/tmagics.nim
This PR introduces a minor change in the semantics of those two operators wrt empty `ref` types: instead of a null-pointer deref we don't do anything.
Fixes #9442
> Don't crash if GC_{un,}ref is called on nil

- lib/windows/winlean.nim
Mingw always comes with a lower case "windows.h".
So I think it would be better to use #include "windows.h", since it works on both linux and windows.
> fixes #9474

- config/nim.cfg
- doc/nimc.rst
- Added a `-d:mingw` flag to enable cross compilation for Windows from Linux/OSX
- Added section to cross-compilation documentation
> Make Windows cross-compilation simpler

- changelog.md
- compiler/ccgstmts.nim
- compiler/semexprs.nim
- lib/system.nim
Tagging @jcosborn as I think he is also a heavy user of OpenMP with [QEX](https://github.com/jcosborn/qex/blob/fc0295a7c920cd84f95f582f4231d698d907ef21/src/base/omp.nim).
This fixes #9490.
- The first commit is the actual fix.
- The second one is to use `static` instead of a custom check in semexprs. I'm not that familiar with the compiler internals so please review that carefully.
Test case:
```Nim
#
import sequtils
when defined(openmp):
{.passC: "-fopenmp".}
{.passL: "-fopenmp".}
{.pragma: omp, header:"omp.h".}
proc omp_set_num_threads*(x: cint) {.omp.}
proc omp_get_num_threads*(): cint {.omp.}
proc omp_get_max_threads*(): cint {.omp.} # This takes hyperthreading into account
proc omp_get_thread_num*(): cint {.omp.}
else:
template omp_set_num_threads*(x: cint) = discard
template …
```
> Openmp parallel iterator improvements

- changelog.md
- lib/core/macros.nim
- tests/vm/tnimnode.nim
- Remove commas from the lisp representation of the AST.
- Make the dumpLisp output "pretty" and indented.
- Improve docs of `dumpTree` and `dumpLisp` macros.
---
- `lispRepr` outputs unindented lisp representation by default (the `indented` arg is `false` by default) as before, but with a comma-less lisp form.
- `dumpLisp` macro now outputs an indented lisp representation, just like `dumpTree` does.
---
With:
dumpLisp:
echo "Hello, World!"
Output before this commit:
StmtList(Command(Ident("echo"), StrLit("Hello, World!")))
Output after this commit:
(StmtList
(Command
(Ident "echo")
(StrLit "Hello, World!")))
`dumpTree` output for reference:
StmtList
Command
Ident "echo"
StrLit "Hello, World!"
Another example: https://irclogs.nim-lang.org/25-10-2018.html#15:01:12, …
> Improve dumpLisp macro

- lib/pure/asyncdispatch.nim
- lib/pure/asyncfutures.nim
Ref #9524 
Small improvement to make users like me aware of the difference between these two procs.
> docs: clarify `asyncCheck` vs `waitFor`

- lib/pure/httpclient.nim
This fixes only the `newHttpClient` based version. 
Should i also fix the deprecated?
Signed-off-by: enthus1ast <david@code0.xyz>
> fixes #7842 if no uri.scheme specified raise ValueError with hint

- lib/pure/strscans.nim
- tests/stdlib/tstrscans.nim
Issue: #9240.
Fix `atom` to emulate 0.18 behavior (matching EOF with `'\0'`).
Also, add some tests that should pass both on 0.18 and after this PR.
Solution to fix `scanp` [proposed][1] by @LemonBoy fails on matching tuple as it assumes there is no EOF after the tuple:
```nim
doAssert scanp("foo", idx,  ('f', 'o', 'o'))
```
I've tried to come up with other solutions to fix `scanp`, but they all introduce regressions on some edge cases involving EOFs or empty matches.
[1]: https://github.com/nim-lang/Nim/issues/9240#issuecomment-428919674
> Fix strscans.scanp

- lib/pure/math.nim
- lib/system.nim
This adds more examples to show the behaviour of `mod`, `div`, `floorMod` and `floorDiv` with negative numbers, which closes #4676.
Also, this fixes the documentation generation by adding an empty line before code blocks introduced in #9266.  
@eqperes, you can run `nim doc lib/pure/math.nim` to see how the generated .html looks like (but also nobody of the rest of us in that thread noticed this ;))
[ci skip]
> more examples for `mod` and `div`, plus corrections (closes #4676)

- lib/pure/htmlparser.nim
- lib/pure/parsexml.nim
- tests/stdlib/thtmlparser.nim
Fix #6154.
Implemented in accordance to https://html.spec.whatwg.org/multipage/syntax.html#unquoted
> Make htmlparser parse unquoted attrib values

- compiler/parser.nim
Quick and hackish, but it's #hacktoberfest season and this works :)
> Maps `out` keyword to an nnkIdent. Fixes #6011.

- lib/pure/logging.nim
Fixes https://github.com/nim-lang/Nim/issues/9547
write all logs to stderr
```nim
import logging
var L* = newConsoleLogger()
addHandler(L)
error("err should go to stderr")
fatal("fatal sholud go to stderr")
warn("warn sholud go to stderr")
info("should go to stderr")
```
```bash
~> bin/nim -r c /tmp/testlogging.nim > stdoutfile.txt 2> stderr.txt
~> cat stdoutfile.txt  
~> cat stderr.txt
Hint: used config file '/home/ahmed/wspace/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: testlogging [Processing]
Hint: logging [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: times [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: …
```
> write logs to stderr instead of stdout fixes #9547

- lib/impure/nre.nim
Integer division is already hard enough on your CPU, using floating
point here is WAY slower and can just as effectively be done using
integers. This is important because matchImpl tends to be in the center
of very hot loops (like split()).
> Eliminate floating point arithmatic in nre

- compiler/docgen.nim
- nimdoc/testproject/expected/subdir/subdir_b/utils.html
- nimdoc/testproject/expected/testproject.html
As proposed [here](https://github.com/nim-lang/Nim/issues/5525#issuecomment-286549519):
> (1) Or we remove the word "module" instead?
> (2) I think the "Imports" word should be changed to "Dependencies" instead.
> Change documentation details (closes #5525)

- lib/pure/math.nim
Alternatively (if there is a problem with `Math.hypot`), I can provide a function which doesn't overflow.
> Fix #9585 hypot in js

- compiler/semexprs.nim
- tests/macros/tquotedo.nim
Previously the useful "quote do" construct had an issue were the result variable would be shadowed by the macros result variable and thus get the wrong return type. These commits fixes this by adding a hidden parameter to the intermediary template and calling the template with an added `newNimNode("result")` argument. This way all results are only resolved after the macro expansion and thus avoids the shadowing of the macros own result variable.
> Quote do now works with result in block

- compiler/msgs.nim
- compiler/options.nim
IDK why `shortenDir` was changed to `relativeTo` in a previous commit - https://github.com/nim-lang/Nim/commit/86556ebfdbbd4b8e9edc9d3085ea21d6c0bae2e2#diff-ec1eedfc292fc296265be60cf35f5188L90, but that was the reason for https://github.com/nim-lang/Nim/issues/9556
> Fixes #9556

- compiler/vmops.nim
- tests/float/tfloatmod.nim
Add a wrapper for `mod`(float, float) to vmops.nim to allow the later removal of `fmod(float, float)` after a reasonable deprecation period. @gulpf showed me how to write this wrapper.
This is an alternative to PR #9584, which was closed by the author.
> make `mod` on floats available in the VM

- lib/pure/times.nim
- tests/stdlib/ttimes.nim
This removes the unneeded negative sign when parsing a datetime with the formats `z` or `zz`.
> times - remove unneeded negative sign when parsing formats z and zz

- koch.nim
- nimsuggest/nimsuggest.nim.cfg
this removes redundant `-p:compiler` from koch.nim ; the compiler files are already imported via `import compiler/foo` instead of `import foo` (the latter being bad style since it can lead to name clashes)
furthermore, having `-p:compiler` led to issues when modules with same name could clash, such as options:
compiler/options.nim
lib/pure/options.nim
(eg, nre has `import options`; so wasn't usable inside for example nimsuggest because that would point to the wrong options module)
(which I ran into while debugging another PR)
> remove redundant `-p:compiler` from koch.nim ; the compiler files are already imported via `import compiler/foo`

- lib/pure/asyncfutures.nim
- tests/async/tcallbacks.nim
Put new callbacks at the end of the `CallbackList`, not in front, so the order of callbacks is not reversed.
Fixes #7197.
> keep the order of the callbacks

- compiler/semfold.nim
- lib/system.nim
the math.nim test failed for me when I built using clang. This fixes the problem.
> NaN fixes for clang backend

- lib/core/macros.nim
- tests/macros/tnewlit.nim
with these changes ``nowLit`` should also work on `enum` and `set` types. This is supposed to help with issue https://github.com/nim-lang/Nim/issues/5844
> newLit works on enum

- koch.nim
Up until now koch fails when it is started from another directory because it contains relative paths to its own location. Now it won't crash anymore.
> change dir when koch starts

- lib/pure/asyncfutures.nim
- tests/async/t8982.nim
Analogous to `and`.
Credits to @k0zmo for proposing the solution.
fixes #8982
> complete future only once in `or` (fixes #8982)

- tools/vccenv/vccenv.nim
I have tested this on Windows. Fix for #6540
> add vs2017 support when run from developer command prompt.

- lib/impure/re.nim
Proc split didn't pass maxsplit argument to split iterator
> Fix split proc in re module ignored maxsplit argument.

- lib/wrappers/openssl.nim
> Add `.46` as supported libssl version

- lib/pure/includes/osenv.nim
The `getEnv` proc calls `findEnvVar`, which tries to find an environment variable's key using case-sensitive search, and, if it is not found, tries to use `c_getenv`.
On Windows, where the environment variable keys are case insensitive, `c_getenv` returns ANSI-encoded string - the returned value is incorrect if it originally contained Unicode characters.
This changes the behavior such that `findEnvVar` proc tries to match the key using case-insensitive search on Windows.
> Make getEnv case insensitive on Windows

- compiler/ccgexprs.nim
- tests/cpp/tcasts.nim
Fixes #9739. Codegen for discard is greatly simplified.
> Fixes discard bug in cpp codegen [backport]

- nimsuggest/nimsuggest.nim
/cc @Araq 
this reopens https://github.com/nim-lang/Nim/pull/9715 as requested by @araq but hides the feature under `--partialRecompilation` so only it's only enabled for users who want to try it out
reference:
this comment from @Araq https://github.com/nim-lang/Nim/pull/9721#issuecomment-439016793
> I liked your previous solution much better and the crashes could have been fixed, I think. The ModuleGraph can have multiple entry points, in theory there is not much to it.
* fixes https://github.com/nim-lang/nimsuggest/issues/96
docs say https://nim-lang.github.io/Nim/nimsuggest.html
> There is some support so that you can throw random .nim files which are not part of myproject at Nimsuggest too, but usually the query refer to modules/files that are part of myproject.
this wasn't true until …
> nimsuggest: fix #96 ; enabled via `--partialRecompilation` since some cases cause crashes

- lib/system.nim
- tests/seq/tseq.nim
Before this change, this code was crashing by SEGV.
So I had append empty check in `shallow`.
```nim
block:
var a: seq[int] = @[]
var b: seq[int]
shallowCopy(b,a) # ok
block:
var a: seq[int] = @[]
var b: seq[int]
shallow(a) # crash here
b = a
```
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
> Empty check in shallow [backport]

- changelog.md
- compiler/ast.nim
- compiler/condsyms.nim
- compiler/vm.nim
- compiler/vmdef.nim
- compiler/vmgen.nim
- lib/core/macros.nim
- tests/macros/tgetimpl.nim
In typed macros we often compare symbols. Comparison often made with the `bindSym` output. However this comparison does not work if a symbol belongs to the generic proc. In the proc bodies we are analysing, we encounter only already resolved instances of generic procs while `bindSym` returns generic proc symbols. These are understandably are different symbols and comparison returns `false`. AFAIK, there is no way at the moment check if proc symbol is the instance of a particular generic proc. This PR adds this functionality.
> Add isInstanceOf for generic procs to the macros module

- lib/pure/collections/sequtils.nim
* current sequtils.toSeq is limited: it can't be used in UFCS, and can't be used in a number of other contexts (eg iterables that are not iterators, or even when calling a proc that returns an iterator)
* this fixes all of this
See test cases for more details but here's the skinny:
```nim
iterator myIter1():auto{.inline.}= ...
iterator myIter2():int {.closure.} = ...
doAssert [1,2].toSeq == @[1,2]
doAssert @[1,2].toSeq == @[1,2]
doAssert myIter1.toSeq == @[1,2]
doAssert toSeq(myIter1) == @[1,2]
doAssert myIter2.toSeq == @[1,2]
doAssert toSeq(myIter2) == @[1,2]
proc myIter3():auto= ... # returns iterator int
proc myIter4(a:int):auto= ... # returns iterator int
doAssert myIter3().toSeq == @[1,2]
doAssert toSeq(myIter3()) == @[1,2]
doAssert myIter4(1).toSeq == @[1,2]
doAssert …
```
> universal toSeq: works with UFCS; works with inline & closure iterators, and with iterables

- lib/system.nim
- tests/system/tnilconcats.nim
shallow() casts its string argument to a seq and then tries to access
its fields. Guess what happens when that string is nil, which seems to
be the representation of an empty string (both the default value and an
explicitly assigned "").
Segfault encountered when running "ntags -R ." on a large project. The relevant line:
https://bitbucket.org/nimcontrib/ntags/src/a1c62c38e539877c105fbe4e08d06b76232f8017/ntags.nim#lines-125
> fix segfault when calling shallow() on an empty string

- compiler/destroyer.nim
- tests/destructor/t6434.nim
- tests/destructor/tmove_objconstr.nim
Destructors are getting more mature. On tuple construction we now move objects into tuple just like for object construction and we move objects out of the tuple during tuple unpacking.
> Destructors: move into nkTupleConstr and move on tuple unpacking

- lib/js/jsffi.nim
- tests/js/tjsffi.nim
We limit JsAssoc keys to types with values that can be mapped 1 to 1 with cstring .
Drop the support for `JsAssoc[string, V]` . Still, one can do `JsAssoc[cstring, string]{a: "e", "b": "e"}` and access cstring keys with string literals.
Convert keys automatically in iterators
> Support only some types as JsAssoc keys, fix #8601

- nimsuggest/nimsuggest.nim
This makes it possible to import nimsuggest as a library to make it easier to use in Nim based plug-ins (like nimlsp). It still has to be imported by a direct path, but I'm not entirely sure what to do to make the importing smoother.
> Made nimsuggest importable as a library and add Nim-path override option

- lib/pure/httpclient.nim
Implement fix as suggested by https://github.com/nim-lang/Nim/issues/8777#issuecomment-433653022
TODO: 
* violates DRY
* no tests: i checked tests/stdlib/httpclient and there don't seem to be any existing tests for different methods. putContent and deleteContent do seem to work with httpbin though.
* documentation not updated
* other methods: HEAD, PATCH, etc
Let me know if any of these are deabreakers and I can fix them
> fix #8777 add missing http methods in httpClient

- compiler/sizealignoffsetimpl.nim
- tests/types/tfinalobj.nim
Bug is rather critical and fix should be backported
> fixes #9794: sizeof tuple is incorrect if contains imported object

- compiler/sigmatch.nim
- tests/converter/tconvert.nim
- tests/converter/tconverter_unique_ptr.nim
I am working on smart pointers using new Nim destructors and they require top quality converter support. I have stumbled upon two more issues:
Fixes #9735  (Converter bug: if converter returns `lent T` it is still possible to pass it as `var T` argument)
Fixes #9736  (Converter bug: if converter returns `var T` and argument expects `var T`,  it may still be rejected if original variable is `let`)
I haven't provided examples in the issue description, but the PR contains extensive test case
P.S.
I guess I can contribute the smart pointer library to stdlib if there is an interest.
> More converter fixes

- compiler/destroyer.nim
- compiler/lowerings.nim
- compiler/sem.nim
- tests/destructor/tmove_objconstr.nim
I have found a couple more use cases where sink is not happening for tuples.
nkStmtListExpr in moveOrCopy is likely going to help not only tuples.
> Destructors: more moves for tuples

- lib/system.nim
/cc @Araq 
this form is often more convenient eg:
```nim
let ai = mc.insert(doc.deepCopy)
var doc2: type(doc)
deepCopy(doc2, doc)
let ai = mc.insert(doc2)
```
> add: proc deepCopy*[T](y: T): T

- nimsuggest/nimsuggest.nim
One of the hooks were set inside the execute procedure which caused nimsuggest to crash when it tried to send something over the uninitialised channel.
> Moved some code around in nimsuggest to avoid crash when run as library

- changelog.md
- lib/pure/os.nim
- lib/pure/osproc.nim
/cc @Araq 
surprising it didn't exist yet
after this is merged maybe nimble/src/nimblepkg/tools.nim can be refactored use that  /cc @dom96 
* [How do I get the process ID of the current program? - Nim forum](https://forum.nim-lang.org/t/946)
> add os.getCurrentProcessId()

- changelog.md
- lib/pure/options.nim
- Removed `ref` from UnpackError
- UnpackError inherits from Defect instead of ValueError
I also removed the examples using `try/except`, since UnpackError should not be catched.
Fixes #9856
> Make options.UnpackError inherit from system.Defect

- compiler/jsgen.nim
Fixes https://github.com/pragmagic/karax/issues/80
> tyProc does not require copying in JS codegen

- compiler/ccgexprs.nim
- compiler/cgen.nim
- compiler/semfold.nim
- lib/pure/collections/sharedstrings.nim
- lib/pure/subexes.nim
- lib/system/chcks.nim
- lib/system/helpers2.nim
- tests/misc/tinvalidarrayaccess.nim
- tests/misc/tinvalidarrayaccess2.nim
/cc @Araq 
* refs #9880 show index and bound in lots of `index out of bounds` errors
there are still a few cases left; these can be done in future PR's
> refs #9880 show index and bound in lots of `index out of bounds` errors

- compiler/main.nim
- doc/advopt.txt
* documents `--dump.format:json`
* adds `out` to json dump, see use cases [1]
* closes https://github.com/nim-lang/Nim/issues/8196  since with this PR we have a more systematic way to access these (hints, warnings) that's both human-readable and machine-readable, via json instead of custom "cute" format in --hints:list and --warnings:list
`dump --dump.format:json` more generally is useful, because it may not always be clear what the compiler sees (eg flags can come from several config files + command line) (eg, could be useful in some bug reports)
one can use `jq` (eg after `brew install jq`) or any other tool to access the json dump, eg:
* pretty print json dump:
`nim dump --dump.format:json main.nim|jq`
or we can postprocess the json dump from cmd line:
* show all the warnings:
`|jq …
> enhance `dump --dump.format:json` : report `out`, `hints`, `warnings`, document it ; closes #9513

- lib/system/excpt.nim
The new error message looks like this:
"Error: call depth limit reached in a debug build (2000 function calls). You can change it with -d:nimCallDepthLimit=\<int\> or switch to a release build with -d:release."
> replace misleading "stack overflow" message when reaching Nim's call depth limit

- compiler/commands.nim
- doc/advopt.txt
/cc @Araq  @citycide 
* refs #9906
editor integrations (eg NimLime /cc @Varriount ) often use `nim check` to report whether input file has any errors; unfortunately `nim check` has inherent limitations (see https://github.com/nim-lang/Nim/issues/9906) in that it's limited to semantic pass and won't report some errors.
Oftentimes what user wants is just "tell me whether this file has any errors" regardless of whether it's in semantic pass or in backend, or in subsequent stages (eg linking).
This PR fixes this problem by adding a flag , eg `--errorMax:10` will stop after 10 errors instead of the usual 1 error 
* the default is actually 0 but 0 is rather meaningless and 0 will have exact same effect as 1; in fact:
```
--errorMax:0 # stops after 1 error
--errorMax:1 # stops after 1 error …
```
> refs #9906; --errorMax:10 allows stopping after 10 errors (more robust than nim check)

- changelog.md
- lib/impure/nre.nim
- lib/impure/nre/private/util.nim
- tests/stdlib/nre/captures.nim
- tests/stdlib/nre/match.nim
- tests/stdlib/nre/replace.nim
I'd like community feedback on this PR because it contains some significant breaking nre changes.
> Fix for #9243, nre returns "" instead of nil for missing matches 

- changelog.md
- compiler/pragmas.nim
- compiler/semstmts.nim
- tests/pragmas/tcustom_pragma.nim
Found use cases where I need to shield pieces of code from some of the analysis stages.
Pragma blocks are now kept in the typed AST in all cases, later compilation passes have no problems dealing with them.
> Language feature: implement custom pragmas in pragma blocks

- lib/pure/memfiles.nim
Let handles be seen outside of `memfiles` module so that "updating" operations (like eg., resizing a file and re-mapping) do not need
to worry about race conditions of re-opened paths, renamed parent
directories and that sort of thing.  Operating directly on already
open handles is both safer and more efficient than relying upon the
stability of filesystem paths.
For example, I have a little routine to resize a writable map that was opened with `allowRemap=true` that makes it very easy to work with growing output files in a memory mapped setting:
```Nim
import posix
proc remap*(f: var MemFile, newFileSize: int) =
when defined(windows): error("Not yet supported for windows.")
else:                     #XXX if mremap unavail need to munmap,ftrunc,mmap
proc mremap(old: pointer; oldSize, …
```
> Let handles be seen outside of `memfiles` module so that "updating"

- compiler/semtypinst.nim
- tests/objects/twhen1.nim
Long story short, even if the type contains no reference at all to its
generic parameters we still have to walk its AST and evaluate any
nkRecWhen nodes that semRecordNodeAux skipped due to the type being a
generic one.
We also must be careful to modify the type `n` node in place since it
may be referenced by the caller as seen in the tillegaltyperecursion
test.
I found this to be the nicest solution to the problem, we can't perform this resolution before the type is fully constructed as some `when` statements may refer to generic parameters and performing yet another (it'd be the third) pass over the type in order to resolve the remaining `nkRecWhen` is not that nice performance-wise.
This fixes #8417 and half of #7378.
> [WIP] Pervasive replacement of nkRecWhen in generic types

- lib/pure/asyncnet.nim
- lib/pure/nativesockets.nim
- lib/pure/net.nim
Unfortunately this required some code duplication because the doConnect() from asynccommon.nim only works with addrInfo which does not make sense for AF_UNIX. 
makeUnixAddr() was moved to nativesocket and exported, other comments from @dom96 on earlier request were fixed.
> Added basic AF_UNIX support to asyncnet. 

- compiler/cmdlinehelper.nim
Fixes https://github.com/nim-lang/Nim/issues/4446
Fixes https://github.com/nim-lang/Nim/issues/8991
Fixes https://github.com/nim-lang/Nim/issues/9420
Fixes https://github.com/nim-lang/Nim/issues/9589
Fixes https://github.com/nim-lang/Nim/issues/9153
Fixes https://github.com/nim-lang/Nim/issues/9120
Note that there is no need to re-enable these symbols because a few lines later we already re-process the command line argumesnts -
https://github.com/nim-lang/Nim/blob/b104f77444beb3a19732ad5d7728ce2109325be9/compiler/cmdlinehelper.nim#L91
> Undefine some symbols and globalOptions when processing nimscript
