lib/pure/collections/tables.nim
Before that toCountTable wouldn't even compile and newCountTable had the previous behaviour of setting everything to 1.
=> Fix  toCountTable and newCountTable

lib/pure/parsecsv.nim
Changed unnecessarily mutable bindings to immutable bindings. Added mutable access to rowEntry proc.
=> Parsecsv mutability

lib/pure/strutils.nim
* Removed +1 causing substr slicing to skip chars on first iteration of while loop
=> FIXUP: Fixed wordWrap indexing

compiler/cgen.nim, tests/ccgbugs/tresult_of_array.nim
=> fixes #7332

lib/pure/asyncfile.nim, tests/async/hello.txt, tests/async/tasyncfile.nim
#7347 is actually a combination a two issues:
* first, getFileSize, which is already described by @PMunch 
* second,  proc readAll call proc read, f.offset at EOF not updated properly
both issues are fixed by this PR
=> fixes #7347, asyncfile.getFileSize

doc/manual/lexing.txt
It was mentioned in the issue and on the forums that the manual was not clear here. I tried to clarify and remove the ambiguity.
Please do review to make sure that I am indeed technically accurate :)
=> Fix #7304 by clarifying integer width in manual

doc/manual/stmts.txt
=> Fix small typo in the documentation

lib/js/dom.nim
Add window.performance, window.performance.now(), window.devicePixelRatio, window.scrollX and Y, style.overflowX and Y, node.getBoundingRect.
=> Add some missing things to dom.nim

compiler/vmgen.nim, tests/casestmt/tcasestm.nim
Fixes #7407. Also made sure branches with calls to noreturn procs also work in VM
=> Fixes #7407

compiler/semtypes.nim, tests/array/tarray.nim
=> semcheck negative array length

compiler/parser.nim, tests/parser/ttypeclasses.nim
=> Fix parser bug with type classes

compiler/installer.ini
=> Enable RISC-V 64bit platform

lib/core/macros.nim
It's just a comment for people who are curious about where the actual implementation is. This comment would have helped me if I had it when I was exploring this file.
=> added comment to macros

changelog.md
Added the changes made in #6978 to the changelog
=> Add recent `times` changes to changelog

compiler/jsgen.nim, compiler/jstypes.nim, compiler/lambdalifting.nim, compiler/main.nim, compiler/nim.nim, compiler/options.nim, compiler/rodread.nim, lib/system.nim, lib/system/gc_regions.nim, lib/system/jssys.nim
* I don't think PHP and JS are that similar, this makes JS gen confusing.
* PHP output was never advertised or really documented.
=> Remove PHP backend.

compiler/filter_tmpl.nim, compiler/renderer.nim
Related to https://github.com/nim-lang/c2nim/pull/130
=> Fix renderer's errors

lib/pure/times.nim, tests/stdlib/ttimes.nim
=> there is no hour 0 in am/pm time (see #7620)

lib/pure/algorithm.nim
the current test cases didn't catch that smart binary search wasn't correct. For me this is a big warning that there much more that is not properly tested in the standard library. But for now I just added a test for binarySearch.
=> test binarySearch, fix for search in empty.

compiler/vmgen.nim
Hopefully I didn't break anything
=> fixes #7774

lib/pure/options.nim
=> options: use isSome

changelog.md, compiler/ast.nim, compiler/astalgo.nim, compiler/evaltempl.nim, compiler/importer.nim, compiler/parser.nim, compiler/pragmas.nim, compiler/semdata.nim, compiler/semexprs.nim, compiler/semmagic.nim, compiler/semstmts.nim, compiler/sigmatch.nim, compiler/types.nim, doc/manual.rst, lib/core/macros.nim, lib/pure/strutils.nim, lib/pure/terminal.nim, lib/pure/xmldom.nim, tests/generics/module_with_generics.nim, tests/generics/t5602_inheritence.nim, tests/macros/tstructuredlogging.nim, tests/macros/ttemplatesymbols.nim, tests/modules/definitions.nim, tests/modules/proxy_module.nim, tests/overload/tparam_forwarding.nim, tests/threads/tthreadvars.nim
Please see the commit messages for a more detailed explanation and rationale.
=> Allow templates to be passed as symbols to macros

lib/pure/collections/sets.nim, tests/collections/tsets.nim
=> Add proc hash for HashSet and for OrderedSet

lib/pure/net.nim
=> Add connectUnix and bindUnix to net docs

config/nim.cfg, lib/pure/concurrency/threadpool.nim, lib/system/atomics.nim
=> Minor fixes to enable tcc

config/nim.cfg
Some linking details will need to be added later but this is a start.
=> Provide configuration for Genode toolchain

changelog.md, lib/pure/algorithm.nim
1st step.
Added overloaded proc ```binarySearch[T, K]``` with the ```cmp``` parameter.
=> binarySearch improvements

compiler/options.nim
sorry, there is no test, because I don't know how to make a test case for this kind of bug
=> fixes #7696, add ConfigRef.arguments initialization

lib/pure/pegs.nim
This adds a compile time check on the file logging function in the PEG library.
=> Patch the PEG library to work with the JS backend

compiler/options.nim, lib/packages/docutils/highlite.nim, lib/pure/colors.nim, lib/system/sysstr.nim
Except unicode.
Why binaryStrSearch needed in sysstr?
=> Use new binarySearch everywhere

lib/pure/math.nim
See these.
[Binary GCD algorithm - Wikipedia](https://en.wikipedia.org/wiki/Binary_GCD_algorithm)
https://qiita.com/SatoshiTerasaki/items/a7ada593560747354a43 (Japanese)
[Julia's gcd](https://github.com/JuliaLang/julia/blob/d386e40c17d43b79fc89d3e579fc04547241787c/base/intfuncs.jl#L28-L49)
[Nim's gcd](https://github.com/nim-lang/Nim/blob/master/lib/pure/math.nim#L447)
[Julia's trailing_zeros](https://github.com/JuliaLang/julia/blob/d386e40c17d43b79fc89d3e579fc04547241787c/base/int.jl#L240-L249)
[Julia's thread when binary GCD is implimented](https://github.com/JuliaLang/julia/pull/8410)
[Stein's (binary) GCD algorithm (iterative version) - Nim Forum](https://forum.nim-lang.org/t/3659)
Current Nim's gcd uses Euclidean algorithm but Binary GCD algorithm is faster in expected time for random …
=> Faster binary gcd algorithm

compiler/cgen.nim, tests/misc/åäö.nim, tests/testament/tester.nim
=> Support multi byte characters in module names

lib/impure/db_sqlite.nim
Update sqlite example to use empty strings to use empty strings instead of nil.
=> Update sqlite example to use empty strings.

compiler/vmgen.nim, tests/vm/tvmmisc.nim
=> Fix for newStringOfCap in VM

compiler/ccgcalls.nim, compiler/ccgexprs.nim, tests/system/tsystem_misc.nim
=> support empty toOpenArray

lib/system.nim
Last PR was for master branch instead of devel, thanks @Yardanico
=> Fix GC_getStatistics calling itself GC_disableMarkAndSweep in JS (again)

lib/pure/asyncmacro.nim, tests/async/tasync_traceback.nim, tests/async/tasynctry.nim, tests/async/tasynctry2.nim
First commit is just a cherry-pick of @dom96's commit.
Second commit fixes the tests.
=> Async try ripout

compiler/ccgexprs.nim, tests/concepts/t6770.nim
=> Correct field lookup in concept types

compiler/hlo.nim, compiler/patterns.nim, compiler/sigmatch.nim, tests/template/tpattern_with_converter.nim
fixes #7980 by temporary disabling converters while pattern templates are being matched
=> Fixes 7980

lib/pure/strutils.nim, tests/niminaction/Chapter1/various1.nim, tests/niminaction/Chapter2/explicit_discard.nim, tests/niminaction/Chapter2/no_def_eq.nim, tests/niminaction/Chapter2/no_iterator.nim, tests/niminaction/Chapter2/no_seq_type.nim, tests/niminaction/Chapter2/resultaccept.nim, tests/niminaction/Chapter2/resultreject.nim, tests/niminaction/Chapter2/various2.nim, tests/niminaction/Chapter3/various3.nim, tests/niminaction/Chapter3/various3.nim.cfg, tests/testament/categories.nim
* MD5 hashes of Nim in Action tests are now checked to prevent accidental modification.
* ``strutils`` module now exports unicode.toLower/toUpper.
* Added smaller code samples from Chapters 1-3.
=> Higher Nim in Action coverage plus regression fix.

lib/pure/times.nim
`format` used a proc parameters instead of a `Timezone`, which is not consistent with the rest of the api (not a breaking change since the proc is only added on devel). I also removed two examples that could fail for some timezones.
Fixes #8032
=> Change inconsistent parameters in times.nim

compiler/ccgexprs.nim
This kills three birds with a stone, #6280, #6899, #6133.
I can probably add a test for the latter if you want.
=> Fix minor codegen issue with static data types

compiler/semexprs.nim, compiler/semfold.nim, compiler/types.nim, tests/concepts/treversable.nim
Fixes #7705, fixes #7703, fixes #7702
=> More concept fixes

compiler/commands.nim
=> Warn the user if the specified verbosity level is wrong

compiler/ccgstmts.nim, tests/casestmt/t7699.nim
=> Reject enums with holes when computedGoto is used

compiler/ccgexprs.nim, tests/iter/t8041.nim
=> Fix codegen for mInSet magic and empty sets

compiler/sem.nim, tests/sets/t2669.nim
=> Check the RHS when building a set

compiler/vm.nim, tests/vm/tvmmisc.nim
Also made a tiny step towards supporting `ref ref T` types in the VM.
=> Fixes #6689

compiler/vm.nim, tests/vm/tvmmisc.nim
=> Fix vm regression

compiler/types.nim, tests/concepts/t7952.nim
=> Fix constant folding of len() with concept type

compiler/semgnrc.nim, tests/pragmas/tcustom_pragma.nim
=> Fix use of custom pragmas in generic procs

doc/basicopt.txt
was hard to find
I'd even refer to https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-compile-time-define-pragmas if that's not too long (personally I don't care about archaic 80 col width limit, but maybe some do)
=> better doc for hard to find --define:SYMBOL:VAL

compiler/renderer.nim, tests/macros/tmacrostmt.nim
=> Fix render bug 

compiler/sem.nim
=> make runnableExamples use a private nimcache so that they can be tested in parallel

lib/pure/terminal.nim
Fix terminal.nim to be GCSAFE.
Fix deprecated callsite().
=> Fix terminal.nim to be GCSAFE.

compiler/ccgtypes.nim, tests/misc/åäö.nim
=> Bugfix for modules with multi byte characters in the name

compiler/semtypes.nim, tests/casestmt/t8333.nim
=> Resolve converter call to constants in case arms

compiler/renderer.nim, tests/macros/tmacrostmt.nim
=> Fix render bugs

compiler/parser.nim, compiler/renderer.nim, tests/macros/tmacrostmt.nim
It is supposed a fix for #8348
Originally, I thought that adding ``()`` around nkStmtListExpr in renderer would be enough, but the parser continue to complain. Therefore  I am not sure what is the right approach anymore.
I have added flexComment to the parsePar in the parser, have no idea if it is right or wrong thing to do.
If there are better approaches to fix this, let me know.
Fixes #8348
=> Render bug:  if expression with statement list expression as condition

lib/pure/collections/sets.nim, tests/sets/tsetpop.nim
```nim
proc pop*[A](s: var HashSet[A]): A =
##
var elem: A
for h in 0..high(s.data):
if isFilled(s.data[h].hcode):
elem = s.data[h].key
excl(s, elem)
return elem
raise newException(KeyError, "set is empty")
```
=> add sets.pop procedure (analogue to python)

lib/pure/ioselects/ioselectors_kqueue.nim
@andreaferretti please confirm
=> Fixed typo introduced in #8428 that leads to InvalidIdent assertion

doc/mytest.cfg
/cc @yglukhov  sent out this PR to clarify (wasn't clear after reading https://nim-lang.org/docs/parsecfg.html) but feel free to correct if my assumption is wrong
=> [trivial] [docs] document that --flag is same as flag in cfg config files

compiler/types.nim, tests/errmsgs/t8434.nim
fixes #8434 (hopefully in a reasonable way ...)
=> fix #8434 (incomplete info in errmsg about 'required type')

compiler/semcall.nim, tests/generics/t8439.nim
Ugly but needed (?)
Fixes #8439
=> Try conversion to static[T] in generic instantation

compiler/semfold.nim, tests/misc/tsizeof.nim
Title says it all. Test is included
=> Add sizeof for arrays of integral types in VM

lib/pure/net.nim
Reference: https://forum.nim-lang.org/t/4082
Related: #8475 which was made against the `master` branch by mistake.
=> Update example code for UDP sockets

compiler/extccomp.nim
=> fix shell quoting error for static libraries

lib/system/alloc.nim, lib/system/memtracker.nim
`-d:memTracker` does not compile right now.
=> Try to let memTracker compile

lib/pure/httpclient.nim
Store the body completion future at the client and wait for it to
complete before issuing additional requests. This allows the body
FutureStream reader to drain the stream and read buffers to be freed
asynchronously.
Fix #8109
=> AsyncHttpClient: return from requests before body completion

tests/generics/t6137.nim, tests/generics/t7141.nim, tests/metatype/ttypeselectors.nim
This adds tests for issues tagged v1 that were actually fixed by earlier commits as a "unexpected side-effect".
- #6137
- #7141
- #7231
=> Tests for v1 closed generics/static issues

compiler/transf.nim, tests/closure/t8550.nim
Replacing the `for` body with a nkEmpty node is not the right thing to
do.
Waiting for CI run, don't merge yet.
=> Mysterious fix for #8550

koch.nim, tests/testament/tester.nim
Minor change to help people (e.g. like myself) who are starting out :)
Currently, the readme mentions the use of `./koch tests cat async`, but
the help text for koch doesn't mention it. Helptexts are modified
accordingly.
=> Clarify usage of "Test" argument in Koch

lib/pure/strutils.nim, tests/stdlib/tstrutil.nim
Fixes https://github.com/nim-lang/Nim/issues/7478
=> Fixes 7478: splitLines keepEOL option

compiler/sigmatch.nim, tests/converter/tconverter_with_constraint.nim
=> Converters to take into account constraints. Fixes #7520

compiler/parampatterns.nim, tests/compiles/t8630.nim
=> Allow taking address of skForVar variables

compiler/scriptconfig.nim
=> scriptconfig: register passes once

compiler/types.nim, tests/errmsgs/t8339.nim
=> Expand tyAlias when printing nested types

compiler/pragmas.nim, compiler/semstmts.nim, tests/pragmas/t8741.nim
=> Validate pragmas attached to for variables

compiler/vm.nim, tests/macros/tmacrotypes.nim
fixes https://github.com/nim-lang/Nim/issues/8754
=> fixes 8754

lib/pure/htmlgen.nim
Follows the HTML spec here: https://www.w3.org/TR/html50/dom.html#global-attributes
=> Update html attrs to current html spec

compiler/importer.nim, tests/modules/timportas.nim
=> Fix nkImportAs regression

lib/pure/asyncdispatch.nim
=> Handle fut.failed in asyncdispatch.WithTimeout

lib/nimbase.h, tests/ccgbugs/t5345.nim, tests/ccgbugs/t5701.nim
=> Codegen fix for function pointers marked inline

lib/pure/strutils.nim
=> Fix too broad generic match for toHex

compiler/jsgen.nim, lib/system.nim, tests/js/t7249.nim, tests/js/tmangle.nim, tests/js/tstringitems.nim
=> Automatic deref for everything but pointers in asm/emit

compiler/jsgen.nim, tests/js/t7224.nim
=> Sync line generation between C and JS backends

compiler/semexprs.nim, tests/typerel/t8905.nim
=> Fix type comparison in semConv

lib/system.nim, tests/js/t8914.nim
=> Fix insert/delete for JS

compiler/semfold.nim, tests/arithm/tcast.nim
This way we make sure not to end up with weird values every now and
then.
Fixes #7300
Fixes #8909
=> Narrowing casts are applied after every op if needed

compiler/semstmts.nim, tests/ccgbugs/tborrowmagic.nim
Reported by pqflx3 on the forum.
=> Fix semantic pass with borrowed magic procs

lib/system.nim, tests/assert/tfailedassert_stacktrace.nim
=> fix #8928 regression

compiler/pathutils.nim
Regression since f078f272e5080d2b0983b53750e9d0b2d63c5e02.
=> Allow subpaths with single character names

compiler/semexprs.nim, tests/openarray/t8259.nim
=> Always check the deduced type validity for result

compiler/cgen.nim, tests/ccgbugs/tcodegenbug1.nim
=> Fixes 8979

compiler/vmgen.nim, tests/vm/t2574.nim
=> The VM cannot call methods

compiler/semstmts.nim, compiler/transf.nim, nimdoc/testproject/expected/testproject.html, nimdoc/testproject/expected/theindex.html, nimdoc/testproject/testproject.nim, tests/let/t7936.nim
Somehow the test case doesn't crash anymore and the regression in the
doc generation is fixed.
Fixes #9019
=> Revert #7964

lib/pure/asyncmacro.nim, tests/async/t3075.nim
=> Skip nested procedures in .async. macro

compiler/vmgen.nim, tests/vm/t9043.nim
=> Fix for VM codegen with static[T] types

lib/pure/nativesockets.nim
=> Make getSockDomain work with AF_UNIX sockets

doc/nims.rst
Ref: https://github.com/nim-lang/Nim/pull/9061#issuecomment-424127650
/cc @Araq
=> Fix RST formatting; reword a notice about -d:release in .nims

compiler/semfold.nim, tests/distinct/t9079.nim
=> Constant folding should not drop distinct types

lib/pure/asyncmacro.nim, tests/async/ttemplateinasync.nim
This fixes the regression found in niv/websocket.nim#45.
CC @hlaaftana @filipux
=> Fix regression w/ templates defined in async proc

readme.md
=> add link to https://nim-lang.github.io/Nim/ in readme.md

lib/impure/nre.nim
Thanks to @timotheecour [for the suggestion!](https://github.com/nim-lang/Nim/commit/a0ac0b9696f3a79fbde153c63878aea363b09ad4#commitcomment-30755959)
This PR is blocked on  #9170
=> Use runnableExamples for nre example code where possible

build_all.sh
fix "bug" introduced in #9145
/cc @valtron printf doesn't include trailing newline, unlike echo
=> build_all.sh fix bug introduced in #9145

lib/pure/asyncmacro.nim, tests/async/t9201.nim
=> asyncmacro: add nnkSym support for getName()

compiler/ast.nim, compiler/jsgen.nim, lib/js/jsffi.nim, tests/js/tnativeexc.nim
Still left to do:
- Think about what's throwable and what's an `importedException`
- Stress-test this
- Ehh, questions?
=> Try/Catch support for native JS exceptions

compiler/closureiters.nim, compiler/destroyer.nim, compiler/jsgen.nim, compiler/lowerings.nim, compiler/semparallel.nim, compiler/transf.nim, compiler/vmgen.nim, tests/js/t6612.nim, tests/js/tfieldchecks.nim, tests/vm/tcgemptycallarg.nim
To do before merging:
- New test case for
```nim
static:
doAssertRaises(ValueError):
raise newException(ValueError, "Yes")
```
- Some tests for the VM (?)
- Accidentally fixes #6612, add a test case
- Find who thought that adding the field name only to `nkCheckedFieldExpr` was a good idea
=> Field checks for everybody

compiler/pragmas.nim, compiler/semcall.nim, compiler/semdata.nim, compiler/semstmts.nim, tests/macros/tmsginfo.nim, tests/pragmas/foobar.nim, tests/pragmas/t4384.nim, tests/pragmas/t6448.nim
Fixes #6448
Fixes #4384
Slightly more verbose than I wanted.
**Edit** I've managed to mistype the ticket number at least 3-4 times
=> Fix overload resolution for pragmas evaluation

tests/generics/t8694.nim
* was mentioned in https://forum.nim-lang.org/t/4274#26682 by @gemath
* the more general case would be to fix https://github.com/nim-lang/Nim/issues/9216 (later)
=> fix tests/generics/t8694.nim: runnableExamples were not run because of #9216

compiler/cgen.nim, compiler/commands.nim, compiler/jsgen.nim
Add checks to frontend output argument:
- The output file actually being a directory
- A nonexistent path to the output file
=> Fixes #9154

lib/pure/collections/sets.nim
I replaced the incorrect implementation with one copied from `OrderedTable.del`.
Fixes #9005
=> Fix OrderedSet.excl

compiler/ccgstmts.nim, compiler/ccgtypes.nim, compiler/semtypes.nim, tests/ccgbugs/tcgbug.nim
=> fixes #9297

lib/system.nim
`CompileDate` and `CompileTime` timezone (UTC) added to the docs.
=> Proposed solution for issue #9273

doc/codeowners.rst
I took the liberty to edit code owners to match my experience better.
I am very honored with new status. Can I be added as contributor such that issues and PRs can be assigned to me.
IMO, we need to coordinate next steps. Create a chat room and ask code owners to write a roadmap for their components and discuss it.
=> Align to the actual experience

compiler/semfold.nim, tests/distinct/t9322.nim
=> string to string conversion keeps the dest type

doc/contributing.rst
/cc @arnetheduck  you forgot to run a full grep ;-) (but thanks for moving testament in #9137 it makes sense)
/cc @dom96
=> doc: tests/testament/specs.nim => testament/specs.nim

tools/kochdocs.nim
Otherwise the link from `contributing.rst` wont work :)
Thanks for adding me as a code owner
=> Build codeowners.rst

tools/niminst/buildsh.tmpl, tools/niminst/makefile.tmpl
=> Update makefile and buildsh templates for riscv64

tests/concepts/tissues.nim
* closes #6782 
* closes #7114 
* closes #7510
=> put several issues in tests

compiler/semexprs.nim
=> Make sure the annotation for `||` is avail. at CT

compiler/semcall.nim, tests/enum/tenumitems.nim, tests/errmsgs/undeclared_routime.nim, tests/errmsgs/undeclared_routime2.nim, tests/errmsgs/undeclared_routime3.nim, tests/errmsgs/undeclared_routime4.nim, tests/errmsgs/undeclared_routime5.nim, tests/errmsgs/undeclared_routime_compiles.nim, tests/misc/tissue710.nim, tests/misc/tnoop.nim
=> fix #8671 show helpful msg (lookup symbol, eg iterator) on 'attempting to call undeclared routine' error

tests/generics/t5707.nim
Add the code from #5707 as a test case to close the issue.
=> add issue #5707 as test case

lib/pure/strutils.nim
silences some deprecation warnings
=> math.round is not needed in strutils

lib/impure/db_sqlite.nim
=> Update sqlite open(...) example

compiler/lambdalifting.nim
=> improve error message, closes #2361

lib/system/gc_common.nim
Don't use `setjmp` trick for emscripten/wasm, because there are no registers.
=> No setjump in GC for emscripten/wasm

compiler/semexprs.nim, tests/array/tarray.nim
> Sure, if it's simple enough to implement and specify.
The implementation looks pretty simple to me :)
=> Relax the restrictions on the index types

compiler/rodimpl.nim, compiler/semcall.nim, compiler/seminst.nim, compiler/semstmts.nim, compiler/semtypinst.nim, compiler/sigmatch.nim, compiler/types.nim
This was just a simple find-and-replace. Please double-check if this is ok.
=> replace deprecated `safeAdd` with `add`

tests/types/taliasbugs.nim
#4674 was recently fixed by another commit.
=> added test for #4674

doc/contributing.rst
=> [doc] add tips to doc/contributing.rst: git, code review, CI

compiler/destroyer.nim
Generate nkHiddenAddr nodes w/ proper type attached.
=> Remove a hack in the destroyer impl

lib/pure/parsesql.nim, tests/stdlib/somesql.sql
Also adds a `treeRepr` renderer for the SQL nodes.
=> Parse the usage of the SQL's IN operator properly

tests/cpp/t6986.nim
#6986 was fixed by #7513, this just adds the tests so it can be closed.
=> Closes #6986

lib/core/macros.nim
=> Fix name set and get procs in macros (fixes #9569)

changelog.md, compiler/ccgstmts.nim, compiler/sizealignoffsetimpl.nim, compiler/vmgen.nim, lib/pure/strutils.nim
=> Krux02 devel

lib/core/macros.nim, tests/macros/tslice.nim
=> Add proc `[]`(n: NimNode, s: HSlice[T, U]): seq[NimNode] to macros

lib/system.nim
Rationale and benchmarks in https://github.com/nim-lang/Nim/issues/9514
I didn't inline the compiler magics as I suppose it's done by the compiler.
=> Inline generic min and max

koch.nim, nimsuggest/nimsuggest.nim.cfg
=> cleanup installation of nimsuggest; refs #9637 

koch.nim, tools/kochdocs.nim, tools/nimfind.nims
=> add nimCompile to simplify koch; add nimfind to koch tools

compiler/lexer.nim
refs: https://github.com/nim-lang/Nim/issues/9426#issuecomment-431099792
=> make hex digit error msg more helpful

compiler/pragmas.nim, compiler/sizealignoffsetimpl.nim, tests/misc/tsizeof.nim
=> bitsize respected in size calculation.

lib/pure/times.nim
Improved some doc comments and made the warning for `between` a bit scarier.
=> Times module minor cosmetic changes

lib/system/dyncalls.nim, lib/system/excpt.nim, tests/exception/t9657.nim
=> don't raise exception in the default handler

compiler/semmagic.nim, compiler/sigmatch.nim, compiler/sizealignoffsetimpl.nim, tests/destructor/tatomicptrs.nim
Fixes #9781
also fixes issues with sizeof computation for sink arguments
=> Fixes multiple bugs with sink arguments 

compiler/ast.nim, compiler/ccgexprs.nim, lib/system/gc.nim, lib/system/gc2.nim, lib/system/gc_ms.nim, lib/system/gc_regions.nim, lib/system/mmdisp.nim
unused leftovers of a distant past that made it to a dead-code branch I had lying around
=> Remove dead code

lib/pure/times.nim
The POSIX 'clock()' procedure returns process CPU time in an
implementation specific unit, which for historical reasons can be as
large as ~7ms in the case of FreeBSD. Use 'clock_gettime' for higher
accuracy.
=> times: use clock_gettime for cpuTime with POSIX

lib/pure/unicode.nim
=> fixes #9800

doc/backends.rst
=> fix outdated example to invoke Nim from C

compiler/semexprs.nim, tests/errmsgs/tshow_asgn.nim
error messages had non useful error messages, for example in https://github.com/nim-lang/Nim/issues/9762
=> improve line info retreival

compiler/semstmts.nim, tests/controlflow/tstatret.nim
/cc @GULPF 
* improves fix for #9832
* ref: https://github.com/nim-lang/Nim/pull/9841#issuecomment-444057654
=> fix #9832 (fixup)

compiler/vm.nim, tests/vm/tsetlen.nim
/cc @Araq 
* fix #9872: setLen now works properly at CT
* fix #9865
=> fix #9872: setLen now works properly at CT

compiler/lookups.nim, tests/pragmas/tused.nim
=> Enum fields get hintXDeclaredButNotUsed hint even marked with used pragma

compiler/semtypes.nim, tests/errmsgs/t9908.nim, tests/errmsgs/t9908_01.nim, tests/errmsgs/t9908_02.nim
=> Fix enum regression

tools/vccexe/vccexe.nim, tools/vccexe/vcvarsall.nim
Fixes https://github.com/nim-lang/Nim/issues/9955
=> Fix vccexe compilation

compiler/semstmts.nim, lib/deprecated/pure/sockets.nim, lib/pure/unittest.nim
Fixes https://github.com/nim-lang/Nim/issues/9882
=> Give error when case has an else branch even though all cases are already covered

compiler/semtypes.nim, tools/vccexe/vccexe.nim
Fixes https://github.com/nim-lang/Nim/issues/9952
=> enum types can now be assigned values from enum with holes

config/nim.cfg
Fixes https://github.com/nim-lang/Nim/issues/7957
* [EDIT by @timotheecour ] fixes https://github.com/nim-lang/Nim/issues/9973
=> Fix clang not producing debug info in cpp mode

compiler/semfold.nim
Closes https://github.com/nim-lang/Nim/issues/9998
=> Fix internal error when casting to invalid enum value

compiler/extccomp.nim
Closes https://github.com/nim-lang/Nim/issues/8408
Note: There may be a better fix for this, but this was the smallest and simplest I found.
=> Add project directory to include path

lib/pure/logging.nim
Just minor addition to the documentation with the use of operators
=> Adding more documentation to logging.nim

compiler/importer.nim, compiler/semexprs.nim
Closes https://github.com/nim-lang/nimsuggest/issues/80
Closes https://github.com/nim-lang/nimsuggest/issues/100
=> Nimsuggest now shows gotodef for y in `from x import y` 

compiler.nimble
This allows using nimsuggest as a library.
=> Add nimsuggest to installDirs

compiler/semstmts.nim, compiler/semtypes.nim, lib/deprecated/pure/ftpclient.nim
Closes https://github.com/nim-lang/Nim/issues/3060
=> Fixes #3060 and adds error checking for invalid else branches in object variants

changelog.md, lib/pure/os.nim, tests/stdlib/tos.nim
/cc @Araq 
* fix https://github.com/nim-lang/Nim/issues/8255
(only the parts referring to splitFile; I'll re-open another issue for the parts related to parentDir)
=> fix #8255 numerous issues with splitFile

lib/system.nim, tests/js/test1.nim
=> Fixed insert for nil seq in js

testament/categories.nim, testament/specs.nim
=> fix #10049

compiler/semstmts.nim, nimsuggest/nimsuggest.nim, nimsuggest/tester.nim, nimsuggest/tests/ttype_highlight.nim
There's a test attached but disabled by default because I don't know how to make it work with the EPC backend.
=> fixes nim-lang/nimsuggest#76

compiler/semstmts.nim
Closes https://github.com/nim-lang/Nim/issues/10098
=> Fix const tuple unpacking not working for variables > 2

compiler/lookups.nim, tests/errmsgs/treportunused.nim, tests/pragmas/tused.nim
=> fix #10101

compiler/semmagic.nim, lib/pure/typetraits.nim, tests/metatype/ttypetraits2.nim
* fix https://github.com/c-blake/cligen/issues/84
=> fix typetraits.`$` regression https://github.com/c-blake/cligen/issues/84

compiler/parser.nim, compiler/pragmas.nim, compiler/semtypes.nim, tests/enum/tenumfieldpragma.nim, tests/enum/tenumfieldpragmanoannot.nim
Closes https://github.com/nim-lang/Nim/issues/5700
=> Deprecated pragma is now supported on enum fields

compiler/suggest.nim, tests/deprecated/tdeprecated.nim
Closes https://github.com/nim-lang/Nim/issues/10111
=> Show deprecation warning for fields of a deprecated enum

compiler/suggest.nim
Closes https://github.com/nim-lang/Nim/issues/10133
=> Before showing deprecated warning, check whether enum field was marked deprecated or the whole enum type

compiler/semstmts.nim, tests/pragmas/t5149.nim
Fixes https://github.com/nim-lang/Nim/issues/5149
=> exportc not allowed for type aliases

compiler/options.nim, lib/pure/os.nim
Closes https://github.com/nim-lang/Nim/issues/10153
=> fix inconsistent expandFilename on Windows

lib/system.nim
* move up `runnableExamples` definition so can be used more in system.nim
* document that toInt, toBiggestInt round half away from 0 and add runnableExamples to explain
* minor doc fixes
note; `git diff --color-moved` can verify that `when defined(nimHasRunnableExamples):` block was moved without edits
=> move up `runnableExamples` definition so can be used more in system.nim ; document rounding scheme used

doc/manual.rst
Small fixes to a couple of malformed sentences.
=> Minor Fixes to Manual Wording

lib/pure/parsecfg.nim, lib/pure/parsesql.nim, lib/pure/parsexml.nim
=> Remove totally unneeded import of hashes.

changelog.md
Forgot to add an item,  breaking change
=> Add changelog for the isNil JavaScript change

compiler/sem.nim, compiler/semexprs.nim, tests/async/tasyncfilewrite.nim, tests/exception/tdefer1.nim
Closes https://github.com/nim-lang/Nim/issues/10186
=> Fix defer not not-working at top level

compiler/semexprs.nim
closes https://github.com/nim-lang/Nim/issues/9852
=> Show error when trying to export individual enum field

compiler/sizealignoffsetimpl.nim, tests/misc/tsizeof.nim
=> Fix for sizeof bitsize combination

lib/system/strmantle.nim
thanks @timotheecour for spotting this
=> system/strmantle: avoid leaking docs to system.nim

compiler/types.nim
=> Don't use deprecated pragma syntax

compiler/semcall.nim
* ref: https://github.com/nim-lang/Nim/pull/9766#discussion_r246047664
=> fix leftover comment from #9766

build_all.sh, koch.nim
* fix #10030 bootstrap is insulated from user config
* fix #10031
* @kaushalmodi please let me know if this fixes #10030 for you ; it seems to on my end
=> fix #10030 #10031 ; bootstrap is insulated from user config

lib/pure/concurrency/atomics.nim
This commit was missing from https://github.com/nim-lang/Nim/pull/8620. Apologies!
=> Some fixes for new atomics for vcc with C-backend

compiler/pragmas.nim
Refs https://github.com/nim-lang/Nim/pull/10270#discussion_r247158703
=> Cleanup comesFromPush logic

lib/pure/times.nim
https://irclogs.nim-lang.org/14-01-2019.html#20:03:42
=> Expose CTime

doc/lib.rst
Hello! Just an ordinary typo here...
=> lib.rst: fix a typo

compiler/semstmts.nim, compiler/semtypes.nim, tests/proc/tillegalreturntype.nim
Refs https://github.com/nim-lang/Nim/pull/9981#issuecomment-453507608
Closes https://github.com/nim-lang/Nim/pull/9670
=> Disallow untyped return type in proc

lib/pure/collections/sequtils.nim, lib/pure/collections/tableimpl.nim, lib/pure/collections/tables.nim, lib/pure/math.nim, lib/pure/strutils.nim, tests/errmsgs/tunknown_named_parameter.nim, tests/manyloc/nake/nakefile.nim
This is a huge PR which brings improvements to the documentation of four most-used Nim modules:
* strutils
* sequtils
* tables
* math
You can check some before and after screenshots in [this album](https://imgur.com/a/7pRwzfr) to see how the generated .html files look like.
----
Do NOT squash when merging.
=> Better docs for four modules

compiler/commands.nim, doc/advopt.txt, doc/basicopt.txt, tests/misc/tparseopt.nim
=> fix #9629 every binary cmd line option allows on/off/empty=on

lib/pure/base64.nim
Updated documentation for base64 module:
- Intro text
- Formatting of code samples
- See also links
- Runnable examples
refs #10330
=> base64: Updated documentation

lib/pure/collections/deques.nim, lib/pure/collections/lists.nim
=> better docs for lists and deques

compiler/vm.nim, compiler/vmdef.nim, compiler/vmgen.nim, tests/vm/treset.nim
=> Support system.reset in vm

lib/system/arithm.nim
=> Fix corner case of checked div/mod on x86

compiler/semmagic.nim, tests/errmsgs/t10376.nim
=> Finalizer proc must be global

compiler/semstmts.nim, tests/vm/tvarsection.nim
Refs https://github.com/nim-lang/Nim/issues/10296#issuecomment-454492880
=> Fix compileTime pragma applying to whole var/let section

compiler/sigmatch.nim, lib/impure/db_odbc.nim, tests/typerel/tptrs.nim
=> Restrict ptr/ref to ptr/ref implicit conversion

koch.nim, tools/kochdocs.nim
Prevent log truncation in browsers
=> Enable log folding in Travis CI

compiler/cgen.nim
Local variables are declared before anything else.
Fixes #10352 
Marked as backport because it's a regression.
@slangmgh can you try this patch?
=> Restore compatibility with old vcc versions

compiler/semtypinst.nim, compiler/types.nim, tests/generics/tsubclassgenericerror.nim, tests/generics/twrong_generic_object.nim
This might be crap, but this is my attempt at putting a better error message in the compiler.
It doesn't seem to break other things when I run the test suite locally, so that's good.
fix https://github.com/nim-lang/Nim/issues/10342
=> Fix for issue #10342. better message for generic subclass instantiation

tests/array/tarray.nim
#3899 works on current devel. Added the code as a test case.
=> close #3899 by adding test case

compiler/semstmts.nim, tests/vm/tvmmisc.nim
=> Harmonize the var/let and const handling

doc/packaging.rst, readme.md, tools/kochdocs.nim
Initial version of a packaging guide
=> Add packaging guide #5182

compiler/msgs.nim
Fixes https://github.com/nim-lang/Nim/issues/10263
=> Fixed --embedsrc

lib/pure/httpclient.nim
Added import httpClient statements in examples, as it was not obvious for a new started from python regarding what to import
=> Updated httpClient.nim: added import httpClient statements in examples

lib/pure/memfiles.nim
=> Make MemSlice stringification both simpler and faster.

compiler/vm.nim
Fixes https://github.com/nim-lang/Nim/issues/8484
=> Fixes #8484

changelog.md, lib/pure/streams.nim
Fixes #10451 
I also removed two procs that has been deprecated for 6+ years.
=> Improve exception tracking in the streams module

.travis.yml, koch.nim, tools/kochdocs.nim
Helps preventing the annoying log truncation
=> Improve Travis CI folding

lib/pure/oids.nim
I have never used this module, so somebody should double-check if this is ok in a general usage.
=> fix #2796 (oids counter starts at zero)

lib/pure/times.nim
=> times: use clock_gettime() for epochTime()

lib/pure/json.nim
* refs: https://github.com/nim-lang/Nim/pull/10466
/cc @MandeepSinghey
=> fixup #10466 to use runnableExamples

lib/pure/net.nim, lib/windows/winlean.nim
=> Show correct address for ipv6 sockets

tests/deprecated/tdeprecated.nim
=> fix #8063 by adding a testcase for: Deprecation warnings for enum values print twice

lib/pure/uri.nim
CC @narimiran, is the documentation part ok?
=> Add `encodeQuery` and `?` to Uri module

lib/core/macros.nim, tests/pragmas/tcustom_pragma.nim
=> Fix getCustomPragmaVal on `var` fields

compiler/semexprs.nim, tests/macros/t8997.nim
=> Reject assignments with nkEmpty RHS

tests/macros/t8997.nim
=> fix #10591 regression

compiler/semexprs.nim, compiler/semmagic.nim, tests/errmsgs/t10594.nim
=> Stop useless suggestion of unsafeAddr

compiler/transf.nim, tests/tuples/t9177.nim
=> Fix wrong result in tuple assignment

lib/core/macros.nim, tests/pragmas/tcustom_pragma.nim
=> Misc macro things

lib/pure/httpclient.nim
- Fix #10357
- Sorry for the huge Diff
=> Fix #10357

lib/system/channels.nim
Warn users about using channel with spawn. Minor restyle.
=> Add note on channel usage with spawn

compiler/semfold.nim, compiler/vm.nim, lib/core/typeinfo.nim, lib/pure/collections/sharedstrings.nim, lib/pure/os.nim, lib/system/indexerrors.nim, lib/system/jssys.nim, tests/exception/testindexerroroutput.nims, tests/exception/tindexerrorformatbounds.nim, tests/misc/tinvalidarrayaccess.nim, tests/misc/tinvalidarrayaccess2.nim
* reviving https://github.com/nim-lang/Nim/pull/10228 + rebased against latest devel (there were some conflicts); changed CT `gorge` to RT `execCmdEx`
/cc @BontaVlad feel free to close my PR if you want to keep working on it; otherwise this PR should be `rebase+merge` not `squash+merge` to give attributing to @BontaVlad
note: marking as WIP since **I can't test this on my local travis** because of the following un-reported issue, which I'm writing under https://github.com/nim-lang/Nim/issues/8753 (search this entry: "D20190209T011938 megatest linking fails on local appveyor, maybe consumes too much memory") (since I can't open new issues)
=> [WIP] revive #10228 (fix #9880)

lib/pure/random.nim
Here's the updated documentation for the `random` module. There are still a few things that I'd like some feedback on, which are described in the notes below.
Notes about this pull request:
- It's not fully clear to me how to use the `skipRandomNumbers` proc effectively. The current version of the docs for this proc simply copies the corresponding comment in the C implementation, and I left it largely untouched here. The example I wrote isn't really insightful, either. Any suggestions for explaining that proc in a better way are welcome.
- I opted not to use `doAssert` for the runnable examples in this module since code such as `let x = rand(1..6); doAssert x >= 1 and x <= 6` isn't enough to convince me that the proc always works, especially since the default Rand state always starts at …
=> random: Updated documentation

lib/pure/mimetypes.nim
- Lowercase `ext` before querying the `mimedb` on `mimetypes` module (`"exe"` Vs `"EXE"`).
- Change `when isMainModule` to `runnableExamples` so they appear on Documentation.
- Originated from https://github.com/nim-lang/Nim/pull/10621#issuecomment-462169692
=> Lowercase ext arg on mimetypes

nimsuggest/nimsuggest.nim
=> nimsuggest: only log when logging is enabled

compiler/astalgo.nim
``debug`` isn't tested at all, so no tests for you.
* Basically when debug is called without a config ref, the caller probably doesn't care for line information. As it cannot properly be printed anyway, I took it out of the debug output when the config ref isn't available.
* The printed fields now match the actual name of the field (``n`` instead of ``node``, this difference confused me several times)
* The output of symbols is now actually json.
* Symbol doesn't print loc members anymore.
* Symbol position is printed, if it matters.
* debug on enum types was a horrible unusable recursive type printing mess (almost 80000 lines on ``NimNodeKind``). Now the output is usable:
```
tyEnum NimNodeKind, n: {
"kind": "nkEnumTy",
"sons": [
{
"kind": "nkSym",
"sym": {"kind": skEnumField, "name": …
```
=> reduce debug output

lib/js/dom.nim
correction:
```
proc getPropertyValue*(s: Style, property: cstring): cstring
proc removeProperty*(s: Style, property: cstring)
proc setProperty*(s: Style, property, value: cstring, priority = "")
proc getPropertyPriority*(s: Style, property: cstring): cstring
```
complement:
```nim
proc scrollLeft*(e: Node): int {.importcpp: "#.scrollLeft", nodecl.}
proc scrollHeight*(e: Node): int {.importcpp: "#.scrollHeight", nodecl.}
proc scrollWidth*(e: Node): int {.importcpp: "#.scrollWidth", nodecl.}
```
=> some dom proc correction and complement

lib/pure/asyncnet.nim, tests/async/tasyncawait.nim
Port of #3323 with added tests
=> Provide access to getsockname()/getpeername()

.travis.yml, appveyor.yml
- Cache all the things on appveyor, hopefully it won't choke every now and then while trying to download stuff
- Enable `fast_finish` for travis, this should avoid clogging the pipeline with builds that are going to fail anyway
=> Small CI improvements

testament/categories.nim, testament/important_packages.nim
Six more Nimble packages added.
=> add more nimble packages to the test

compiler/semstmts.nim, tests/errmsgs/t10489.nim, tests/errmsgs/t10489_a.nim, tests/errmsgs/t10489_b.nim
=> error message for accidental use of macro

tests/destructor/t7346.nim, tests/enum/tenum.nim, tests/iter/titer12.nim, tests/misc/tsizeof3.nim, tests/misc/tunsignedconv.nim, tests/misc/tunsignedinc.nim, tests/pragmas/tdeprecated.nim, tests/template/tmethodcall.nim, tests/types/tcast1.nim
This adds tests for #7345, #6959, #5522, #5690, #5340, #7238, #4176, #4175, #6436, #5909, #6406.
=> add tests for recently closed issues

compiler/semtypes.nim
=> fix #10678

lib/pure/net.nim, tests/stdlib/tnetbind.nim
Handle empty IPv4 and v6 correctly and add test. Closes #7633
=> Handle IPv6 in bindAddr

changelog.md, lib/posix/posix.nim, lib/posix/posix_utils.nim, tools/kochdocs.nim
Add docstrings and some helper functions.
=> Improve posix module

lib/pure/concurrency/threadpool.nim, lib/pure/hashes.nim, lib/pure/md5.nim, lib/pure/typetraits.nim, lib/system/channels.nim, lib/system/threads.nim
More detailed documentation for:
* md5
* hashes
Mostly cosmetic improvements for:
* threadpool
* typetraits
* channels
* threads
=> improved documentation for several modules

lib/pure/htmlparser.nim
This update htmlparser example to compile with the current stdlib.
=> htmlparser: update example

lib/pure/times.nim
Small fixes for https://github.com/nim-lang/Nim/pull/10710.
=> times.nim: Fix docs for duration conversion procs [ci skip]

compiler/platform.nim, lib/system/platforms.nim
helps nlvm, can be used to add support in std lib
=> add wasm32 platform

compiler/sizealignoffsetimpl.nim, tests/misc/tsizeof.nim
fixes https://github.com/nim-lang/Nim/issues/10762
=> sizealign of union type

compiler/astalgo.nim
the debug proc now optionally puts ansi color codes into the string (turned off on windows)
the idea behind this is, debug normally puts much more information on the screen than you really need. When you look for a specific kind of informanion you can now look for colors as well, as certain output types will have a specific color. That allows easier visual filtering.
=> colorful debug

tests/misc/tsizeof.nim
there is a bug in nim that got me into thinking tsize actually tested what I thought it tested. I added a few sanity checks to ensure it actually does the right thing and fixed it so it does the right thing.
=> tsizeof test is now correct

compiler/renderer.nim
Not sure if this is the best way?
=> Render : for command if last arg list

compiler/ccgmerge.nim, compiler/cgen.nim, compiler/cgendata.nim
frameDefines  are emitted only when they are used
=> fixes dce regression #10703

compiler/nimeval.nim
Should we apply this to nim secret too?
=> Added nimscript support to repl

koch.nim, testament/categories.nim, testament/important_packages.nim
Appveyor wasn't restarting in the previous PR on close/open, so this is another try.
=> testament: catch failing nimble tests

compiler/ast.nim, compiler/condsyms.nim, compiler/vm.nim, compiler/vmdef.nim, compiler/vmgen.nim, lib/core/macros.nim, tests/misc/tsizeof.nim
sizeof alignof and offsetof should really be available from the macros API. This is how I implemented it.
=> sizeof alignof offsetof macros api

tests/ast_pattern_matching.nim, tests/astspec/tastspec.nim
This is a test that I wrote initially to test if my ast pattern matching can be used on everything in the AST spec. It seems this test is pretty useful to test the AST spec itself.
=> add tastspec (and ast_pattern_matching)

lib/system/embedded.nim, lib/system/excpt.nim
abort in C is the equivalent of quitOrDebug in Nim
=> use abort instead of quit

compiler/ccgcalls.nim, compiler/ccgexprs.nim, tests/errmsgs/tcall_with_default_arg.nim
fixes https://github.com/nim-lang/Nim/issues/5604
=> Lineinfo fix

lib/pure/logging.nim
Here's the updated documentation for the `logging` module.
Note that most examples aren't runnable since they would either write to the console or create files. I don't have much else to say about this pull request, otherwise.
Feedback and nitpicks are welcome :)
Refs: #10330, CC: @narimiran
=> logging: Updated documentation

tools/nim-gdb.py
well this could be the starting point for a more sophisticated frame filtering implementation. Right now it is just filtering out the startup functions that have pretty bad lineinformation nor are they interesting for debugging.
=> add NimFrameFilter to nim-gdb.py

compiler/ccgexprs.nim, lib/pure/bitops.nim, lib/pure/math.nim, lib/system/repr.nim, lib/system/sets.nim, lib/system/widestrs.nim
feedback has been applied from here: https://github.com/nim-lang/Nim/pull/10793
=> Unuse deprecated

compiler/layouter.nim, nimpretty/tests/exhaustive.nim, nimpretty/tests/expected/exhaustive.nim
=> fixes #10200

compiler/liftdestructors.nim, compiler/sempass2.nim, compiler/semstmts.nim, tests/destructor/ttuple.nim
included test currently fails with internal compiler error: copy assignment is not available for tuple (MyVal , MyVal)
=> fixes #10940

lib/pure/strformat.nim
no need to wait for integration test, it is just documentation. But please review my spelling.
=> add strformat limitations section

testament/categories.nim, testament/important_packages.nim
* better tests for the existing packages
* enable testing for packages not in packages.json
* add new packages
=> make nimble packages testing more robust

lib/system/excpt.nim, tests/cpp/tterminate_handler.nim
=> alternative fix for #10765

compiler/ccgexprs.nim, tests/destructor/tv2_cast.nim
This is probably total bollocks, but here's my attempt at fixing #11018.
Appreciate advice on how to fix it correctly (if this is wrong)  :)
=> Fix #11018

tools/nim-gdb.py
I did not write the initial version of the $ command in gdb. And I was never able to successfully use it. I always had python exceptions, no useful output. With these changes `$` now works for at least some types that I care about. I tested it for PNode and a few other primitive types.
=> $ command in gdb now works

compiler/ccgexprs.nim, tests/destructor/tv2_cast.nim
And also extend testing a bit.
=> Extend the fix for #11018 to strings

config/nim.cfg
Should fix regression #11000.
I have tried to make vcc config a lot more straightforward.
=> Review of vcc command line arguments

lib/pure/collections/tables.nim
* Continuation of b40a637f
* https://forum.nim-lang.org/t/4789
=> Improve tables docs for del/take

lib/pure/collections/sequtils.nim
Reverts nim-lang/Nim#10974 merged into wrong branch
=> Revert "Add items() over closure iterator"

changelog.md, lib/pure/collections/sequtils.nim
Reimplemented PR into devel branch abd with changelog entry,
Credit goes to @ryukoposting
=> Reimplemented PR 10974

compiler/semtypes.nim, tests/types/tillegaltuplerecursiongeneric.nim, tests/types/tillegaltuplerecursiongeneric2.nim, tests/types/tillegaltyperecursion2.nim
=> Generic tuple recursion fix

lib/pure/streams.nim
Updated documentation for streams module.
- Basic usage
- See also links
- Runnable examples
My english is not perfect.
Please fix or tell me if english sentence was wrong.
ref #10330
=> streams: Update documentation (#10330)

testament/categories.nim, testament/tester.nim
I was tired of the situation, that a test failed, but I did not know what test failed, because ``testament`` removed the important information to find that out. Normally testament hides all output of failed tests and processes. For example in the test below, I do see that there went something wrong, but the information in the failed test isn't much more informative than "yea it failed".
[![image](https://i.imgur.com/Q4eBcxE.png)](https://ci.appveyor.com/project/Araq/nim/builds/24194779/job/nxkih7dtsvtpabtt/tests)
The same applies when a test that should be run, does not compile. It does print an error message, but there is no other compiler output that might help to figure out what went wrong. Here is an example output of the tester that wants to test a test that doesn't compile. The …
=> Append all output on failed test.

compiler/importer.nim, compiler/semtypes.nim, compiler/semtypinst.nim, compiler/types.nim
Fix for https://github.com/nim-lang/nimsuggest/issues/105
Fixes related to https://github.com/nim-lang/nimsuggest/issues/101
=> Fix for nimsuggest 105, few fixes for 101

compiler/semtypes.nim, tests/errmsgs/temptysetparam.nim
#11140 again. was a little overeager deleting branches :)
=> Empty container parameter error msgs

doc/manual.rst, doc/sets_fragment.txt
Add a subchapter on how to use enums and sets to implement bit fields.
=> Document bit fields usage

doc/nims.rst
Add a link to nimscript.rst
Add a suggestion on disabling hints.
=> Run nimscript without "nim e"

compiler/semtempl.nim, tests/tuples/tfortupleunpack.nim
Fix https://github.com/nim-lang/Nim/issues/11164
=> Fix loop tuple unpacking in templates

compiler/semexprs.nim, compiler/semfold.nim, lib/system.nim, tests/misc/tlowhigh.nim
=>  low/high for float ranges 

compiler/ast.nim, compiler/ccgexprs.nim, compiler/ccgstmts.nim, tests/openarray/tptrarrayderef.nim
Attempt at fixing some ptr array deref issues (#11171).
Want the CI results
=> Fixes for ptr array deref codegen

compiler/types.nim, tests/types/tillegaltyperecursion3.nim
=> Fix type recursion check

compiler/ccgexprs.nim, compiler/ccgstmts.nim
Sorry, slight cleanup: removes unnecessary forward decl, remove old debug artifact, flag checking changed for more common case.
=> Ptr array deref nits

compiler/semexprs.nim, compiler/types.nim, tests/errmsgs/tuncheckedarrayvar.nim, tests/macros/tmacros_issues.nim
=> forbid casting to bare unchecked array

compiler/transf.nim, tests/iter/titertypedesc.nim
=> Fix typdesc arg iterators

tests/ccgbugs/tsequence_outoforder.nim
=> Add testcase for #9684

compiler/semtypes.nim
=> fixes #7569, all credit to @vincentvidal

testament/categories.nim, testament/tester.nim
When there is a failed test in testament, it now does also print the command that failed on top of the output from it.
To do this I changed ``execCmdEx2`` to write this command line in an extra output slot. The escaping rules to create the fake command line are pretty crude, but they should work for what is actually used within the testing suit. If the command line string contains some special unicode symbols, for example spaces, the command will probably not be copy-paste-able from the log files into the terminal, but apart from that there should not be any problem.
=> Testament print failed command

compiler/semtypes.nim
=> Fixes #4140

tests/misc/tconv.nim
Was fixed by #7164
Closes #3766
=> Add test case for #3766

compiler/semfold.nim
copy tree here is unnecessary and potentially expensive.
=> fewer tree copies

lib/pure/httpclient.nim
I added getSocket proc to http client and a simple example, this fixes #10958
=> adding getSocket to httpclient #10958 

compiler/semexprs.nim, tests/errmsgs/tmake_tuple_visible.nim, tests/tuples/ttypedesc_in_tuple_a.nim, tests/tuples/ttypedesc_in_tuple_b.nim
fix https://github.com/nim-lang/Nim/issues/3211
=> Tuple error message

compiler/jsgen.nim
Extend #11230 to the js backend.
=> Correct global destructor injections for js backend

lib/pure/asyncstreams.nim
Simple synchronous uses of new_async_http_client have an unnecessary callSoon that incurs a poll(), incurring a delay that, in practice, depends on how busy the event machine is. In naive tests this is 500ms, the default poll timeout. The provided PR replaces this varying delay with no delay.
The change is to asyncstreams.read, which works by assigning the stream callback so that the next write() will complete the future that .read is now returning.
In `stream.callback=`:
```
...
callSoon(future.cb)
```
The difference between 'soon' and 'immediate' is that 'soon' always incurs a poll().
A complete example with its own version of this PR is at https://gist.github.com/jrfondren/abeaef41b69b149945d325c34936f697 . A comment has timings with different build options.
You can also confirm that …
=> fix unnecessary poll() (and default 500ms delay) in some uses of async

lib/pure/unicode.nim
Some Unicode characters don't have the same byte length
in their upper- and lower-case variants.
----
The only "real" change here is the removal of the problematic `lastIndex = i` line. The rest is just done for readability and to be more explicit that calling `fastToUTF8Copy` increases `resultIndex`.
=> fix changing case for Unicode characters which change size

lib/wrappers/openssl.nim
Other dynamic libraries (like libpg) load diffetent openSSL version then what nim loads.
Having two different openSSL loaded version causes a crash.
Use this compile time define to force the openSSL version that your other dynamic libraries use.
See: #10281, #10230, https://github.com/nim-lang/Nim/issues/9419
Use on command line:
```
nim c -r -d:ssl -d:sslVersion=1.0.0 foo.nim
```
Or in nim.cfg
```
define:"sslVersion=1.0.0"
```
=> Add force openSSL version with -d:sslVersion=x.x.x

lib/pure/hashes.nim
=> fix spelling [ci skip]

compiler/semobjconstr.nim
- Fix formatting for bool and ranges
- Remove unnecessary argument
=> Variant ctor followup

lib/pure/parseopt.nim, tests/misc/tparseopt.nim
=> parseopt segfault fix

tools/niminst/makefile.nimf
~~Completely untested.~~ Working, thanks @genotrance for testing.
Generated repo at https://github.com/alaviss/csrc
=> niminst/makefile: add windows support

lib/pure/bitops.nim, tests/stdlib/tbitops.nim
=> Bit operator names 2

compiler/vm.nim, tests/macros/tmacros1.nim
fixes https://github.com/nim-lang/Nim/issues/10751
=> fix for passing tuples as static params to macros

lib/pure/hashes.nim
I just tested some my old code and this change was needed to make it work again.
Unfortunately I'm unable to create a small example which would showcase this problem. (Small examples work even without this change) :/
=> [bugfix] hashes: fix regression for nested containers

lib/pure/os.nim
Fixes https://github.com/nim-lang/Nim/issues/11441.
=> Make -d:tempDir switch work once again [bugfix]

lib/pure/httpclient.nim
=> Documentation, httpclient

doc/basicopt.txt, tools/nim.zsh-completion
=> Fix #11431

lib/pure/oids.nim
Add `hash` function so we can use `Oid` in tables.
=> Enable Oid usage in hashtables [feature]

lib/pure/mimetypes.nim
=> Add nimf to mimetypes

compiler/bitsets.nim, compiler/ccgexprs.nim, compiler/commands.nim, compiler/lexer.nim, lib/pure/collections/sets.nim, lib/system.nim, lib/system/repr.nim, tests/errmsgs/tproper_stacktrace.nim
=> Refactor deprecation

compiler/semfold.nim
when I was trying to write an example on ``shr`` I noticed a regression in semfold when ``-d:nimOldShiftRight`` is active.
=> fix regression in semfold for old right shift

doc/manual.rst, doc/manual_experimental.rst
=> Documentation, pragmas

doc/advopt.txt
- See https://github.com/nim-lang/Nim/issues/11495#issuecomment-502376524
- Fix #11495
:slightly_smiling_face:
=> Fix #11495

lib/system/mmdisp.nim
=> Add boehm gc finalizer [feature]

lib/pure/collections/sequtils.nim, lib/pure/strutils.nim
See https://forum.nim-lang.org/t/4946 for bug report.
=> [bugfix] fix `delete` in strutils and sequtils

doc/nims.rst
- Improve Documentation of NimScript, update and expand.
- Mention the benefits aside of its limitations.
- Add examples.
Just Documentation only, if some section should be omitted let me know I will remove it.
The **Limitations** section at top of the NimScript page kinda looks discouraging for new people so I meant to add a section explaining that is not useless.
:slightly_smiling_face:
=> Documentation NimScript

compiler/dfa.nim
I have managed to hit dfa instruction limit in real world use case. I have hit it in  auto generated proc with 2.1k lines of code with 5 branch case statement
=> increase dfa instruction limit

lib/packages/docutils/highlite.nim
- Add Documentation with examples for `highlite`. Only Docs.
:smiley_cat:
=> Documentation highlite

koch.nim
Add possibility when "koch tools" command is used, nim compiler options to be passed. The current options are kept and the new user specified options will be added to the end of the command line if present.
**Example:**
```
> koch --latest tools -d:danger --debugInfo --lineDir:on
bin\nim.exe c -o:bin\nimsuggest.exe -d:release -d:danger -d:danger --debugInfo --lineDir:on nimsuggest/nimsuggest.nim
...
bin\nim.exe c -o:bin\nimgrep.exe -d:release -d:danger --debugInfo --lineDir:on tools/nimgrep.nim
...
bin\nim.exe c -o:bin\vccexe.exe -d:danger --debugInfo --lineDir:on tools/vccexe/vccexe.nim
...
bin\nim.exe c -o:bin\nimpretty.exe -d:release -d:danger --debugInfo --lineDir:on nimpretty/nimpretty.nim
...
bin\nim.exe c -o:bin\nimfind.exe -d:release -d:danger --debugInfo --lineDir:on …
```
=> Pass additional koch options to the nim compiler

compiler/nodejs.nim
- Remove IO.js compat, clean out (long dead vanished project, superseded by NodeJS).
=> Remove IO.js

lib/system/assertions.nim, tests/assert/config.nims, tests/assert/testhelper.nim, tests/assert/tfailedassert_stacktrace.nim, tests/assert/trelativeassert.nim
Missed this one line in #11574. Also de-duplicated the related code.
=> assertions: properly fix #11545

lib/pure/times.nim
Updates to the documentation for the times module: improved grammar, corrected spelling and typos, added some clarifications.
=> Documentation improvements to the times module

lib/posix/posix.nim
Used template within example was added to imports.
=> Corrected example shown in documentation

lib/wrappers/openssl.nim
=> [bugfix] openssl styleCheck fix: consistent var naming

lib/pure/asyncdispatch.nim, lib/pure/httpclient.nim, lib/pure/net.nim
This PR replaces the use of `epochTime` with `getMonoTime` for the asyncdispatch, net, and httpclient modules. Using a monotonic clock when measuring short durations of time is more robust.
=> Use std/monotimes in the stdlib

lib/pure/dynlib.nim
I'm quite not sure why this code was like this.. as looks completely wrong.
Also failed to build with clang.
Anyway this should be correct, double checked MSDN.
=> Use proper types according to MSDN and fix clang build of windows dynlib

compiler/sigmatch.nim, tests/misc/tlambdadonotation.nim
fixes #11812
fixes #10899
fixes #11367
=> fix #11812

lib/system/threadlocalstorage.nim, lib/system/threads.nim, tests/concepts/texplain.nim
=> fix #11854

lib/pure/random.nim
This pull request mainly adds documentation and examples for the `sample` procs that have a `set` parameter. There are also spelling fixes and other minor changes too.
=> random: minor documentation updates

lib/impure/db_postgres.nim
=> Skip db_postgres.setRow if getRow returns 0 rows

changelogs/changelog_X_XX_X.md
=> note set[T].len alias in future changelog

lib/pure/encodings.nim
Missed empty strings case in #11888. Added test
=> Fixed handling of empty strings for encodings conversions

lib/system.nim
All these lines produce warnings, this PR fixes it.
=> fix warnings in system.nim

lib/core/macros.nim
fixes symptom but not root cause of https://github.com/nim-lang/Nim/issues/11956
=> refs #11956

compiler/renderer.nim
(a little bit similar in spirit to https://github.com/nim-lang/Nim/pull/11939 @Clyybber )
helps with debugging when looking at rendered code (via `repr` etc)
the lack of separator makes it hard to guess what symbol a gensym'ed symbol refers to especially when the symbol ends with a number. This PR makes it clear.
Note this is only a rendering thing, and should not affect semantics.
```nim
import macros
macro fun(): untyped =
result = quote do:
template bar() =
var b = 1
var b1 = 2
var b2 = 3
echo repr(result)
fun()
```
before PR:
```nim
template bar() =
var b424045 = 1
var b1424046 = 2
var b2424047 = 3
```
after PR:
```nim
template bar() =
var b_416045 = 1
var b1_416046 = 2
var b2_416047 = 3
```
=> genSym symbols rendered as b1_416049 instead of b1416049

compiler/procfind.nim, compiler/types.nim, tests/modules/tmismatchedvisibility.nim
Closes https://github.com/nim-lang/Nim/issues/11952
=> Remove duplicate line number from 'invalid forward declaration' error

compiler/closureiters.nim, lib/core/macros.nim, lib/system/excpt.nim
This PR includes @cooldome's PR #11147 along with closureiter transform fixes required for this to work.
=> Fixes #11118

doc/tut3.rst
fixes https://github.com/nim-lang/Nim/issues/11980
=> Fix typos. Apply title case.

lib/pure/net.nim
Fix privkey filename.
Bump up RSA key size.
Add ECDSA example.
=> Update OpenSSL example

lib/pure/complex.nim
this adds an approximation to an assert call that was failing in the issue https://github.com/nim-lang/Nim/issues/11834
=> Add approximation to an assert call in lib/pure/complex.nim

compiler/installer.ini, tools/niminst/buildsh.nimf, tools/niminst/makefile.nimf
These changes add CPU detection for PowerPC64 on FreeBSD.
=> Add build support for FreeBSD/PowerPC64

tests/parallel/tpi.nim
=> fix tests/parallel/tpi.nim

compiler/semstmts.nim, tests/proc/tillegalreturntype.nim
=> forbid auto return type in prototypes

changelog.md, lib/pure/unicode.nim
fixes https://github.com/nim-lang/RFCs/issues/151
=> remove unicode.Rune16 without deprecation period

compiler/parampatterns.nim, tests/destructor/tnewruntime_misc.nim
=> sink T as lvalue

lib/pure/unittest.nim
=> Add delOutputFormatter proc to unittest.nim

compiler/suggest.nim
Fixes https://github.com/nim-lang/nimsuggest/issues/108 and subsequently https://github.com/PMunch/nimlsp/issues/27.
=> fixes nimsuggest/#108: RangeError with d:release

compiler/injectdestructors.nim
=> Revert "Fix #11833 and simplify injectdestructors"

compiler/ast.nim, compiler/condsyms.nim, compiler/vm.nim, compiler/vmdef.nim, compiler/vmgen.nim, lib/core/macros.nim
I constantly need this proc to debug the compiler.
=> add nodeId proc to macros

doc/nimc.rst
Just a doc update. See the docs for more info.
=> Update Android and iOS cross compile docs.

lib/pure/streams.nim
This is a small thing I have wanted to do for a long time.
I did not include the test in the test suite because it runs a bit long and generates large files.
The test referenced in #9026 but you can also find it here:
https://gist.github.com/rayman22201/6b26e1a14b5e4f04776103de976cd8d7
Here are the results I get with this fix:
| program | inputfile | time | line count |
|---|---|---|---|
| wc | hugebin.txt | | 1445417 |
| reader.js | hugebin.txt | 2.94 | 1844688 |
| Nim (custom proc) | hugebin.txt | 11.16 | 1445417 |
| Nim (streams built in proc) | hugebin.txt | 0.58 | 1445417 |
| Nim (File/fgets direct) | hugebin.txt | 0.54 | 1445417 |
| reader.py | hugebin.txt | 1.03 | 1445417 |
| wc | hugestr.txt | | 2077107 |
| reader.js | hugestr.txt | 1.09 | 3094926 |
| Nim (custom proc) | …
=> fix #9026 add a readLineImpl to streams so that FileStreams can be fast

compiler/condsyms.nim, lib/system.nim
magics are already gone, just a cleanup
=> remove nimNoMagic64 define

lib/pure/os.nim
This uses the suggested replacement from #12326
Thanks!
=> Updated the code example in the os module to use better grammar.

lib/core/locks.nim
=> fix #12330

compiler/jsgen.nim, tests/js/t11353.nim
=> Sets need copying in JS

compiler/gorgeimpl.nim
Gorge does not close processes when done
=> Fixed #12337, leaking pipe after gorge

doc/manual.rst, lib/pure/strutils.nim, tests/misc/tsizeof.nim
=> Fixed sizeOf to sizeof

tests/readme.md
=> Fix reference to parseSpec proc in readme

compiler/commands.nim, compiler/options.nim, compiler/vmops.nim, doc/advopt.txt
to allow for compile time profiling.
=> added cpuTime to VM

compiler/layouter.nim, compiler/readme.txt
Useful for writing linters and static code analysis
=> Expose some layouter elements, improve readme

doc/tut1.rst
Fixes #11504 
My first pull request, testing the machinery while doing something very simple... :)
=> [doc/tut1] removed discard discussion in comments

lib/impure/db_sqlite.nim
Added more details about the limits and reasoning behind the API.
Came about from this discussion on IRC: https://irclogs.nim-lang.org/04-10-2019.html#16:58:04
=> Documentation improvements around the db interface

lib/pure/concurrency/cpuinfo.nim, lib/pure/memfiles.nim, lib/pure/strutils.nim, lib/system.nim, lib/system/ansi_c.nim, lib/system/io.nim, lib/system/memory.nim, lib/system/osalloc.nim, lib/wrappers/openssl.nim, readme.md, testament/important_packages.nim, tests/manyloc/keineschweine/lib/estreams.nim
Testing what fails and what can be fixed..
=> Fixes #12187

doc/manual.rst
(so that "lambda" can be CTRL+F'd)
=> [Docs] Mention "lambdas" in the manual, mention the `=>` sugar for anonymous procs

compiler/int128.nim
=> fix mod operator for int128

nimsuggest/nimsuggest.nim
This PR adds a `--find` option to nimsuggest, which will:
- Force nimsuggest to find the real project file of the project.
- If a project file can't be found, use the one passed on the command line.
This allows plugin writers to use nimsuggest's project finding feature without having to call it twice (one to see if a project file can be found, another if it couldn't).
=> nimsuggest: add option to force finding the project file

compiler/pragmas.nim
Fixes @PMunch 's found https://play.nim-lang.org/#ix=1Yjj
=> Fix semCustomPragma when nkSym

compiler/options.nim
This prevents a nimble file from causing a different project to be
targeted instead of the desired one.
Also it's just faster. Found the issue while working with karax.
So for karax, it has a structure like this:
```
├── experiments
│   ├── menus.nim
│   ├── config.nims
├── karax
│   ├── karax.nim
├── karax.nimble
```
Before this PR, running nimsuggest against the `experiments` folder will led it to use `karax/karax.nim` as the project file instead. This causes `experiments/config.nims` to be ignored as it's not in the same project tree as `karax/`, making files in there unable to find karax modules (or uses the nimble-installed version of karax).
This PR fixes the problem.
=> compiler/options: only check the last folder for a candidate

lib/js/jsconsole.nim
Improve `jsconsole` adding the rest of the stable API as documented on the standard at: 
- https://developer.mozilla.org/en-US/docs/Web/API/Console/warn
- https://developer.mozilla.org/en-US/docs/Web/API/Console/clear
- https://developer.mozilla.org/en-US/docs/Web/API/Console/count
- https://developer.mozilla.org/en-US/docs/Web/API/Console/countReset
- https://developer.mozilla.org/en-US/docs/Web/API/Console/group
- https://developer.mozilla.org/en-US/docs/Web/API/Console/groupCollapsed
- https://developer.mozilla.org/en-US/docs/Web/API/Console/groupEnd
- https://developer.mozilla.org/en-US/docs/Web/API/Console/time
- https://developer.mozilla.org/en-US/docs/Web/API/Console/timeEnd
- https://developer.mozilla.org/en-US/docs/Web/API/Console/timeLog
```nim
import jsconsole …
```
=> Improve jsconsole

doc/manual.rst
=> Fix #10804

changelog.md, lib/pure/htmlgen.nim
- Improve `htmlgen`.
- Add `runnableExamples` with `assert`.
- Documentation with links.
=> Improve htmlgen

lib/pure/unittest.nim
=> Backport - Namespace unittest enums to avoid name conflicts

compiler/cgen.nim, tests/untestable/gdb/gdb_pretty_printer_test.py
fix #12426
Thanks to @alehander42 for the patch. I added a test (not yet automatically executed).
=> improve line directive generation

doc/lib.rst
=> Add link to posix_utils.html

compiler/docgen.nim, doc/lib.rst, lib/experimental/diff.nim, lib/impure/nre.nim, lib/nimhcr.nim, lib/packages/docutils/rst.nim, lib/packages/docutils/rstgen.nim, lib/posix/posix_macos_amd64.nim, lib/posix/posix_other.nim, lib/pure/bitops.nim, lib/pure/collections/sequtils.nim, lib/pure/collections/sets.nim, lib/pure/colors.nim, lib/pure/encodings.nim, lib/pure/json.nim, lib/pure/math.nim, lib/pure/os.nim, lib/system.nim, lib/system/gc_regions.nim, lib/system/io.nim, lib/system/sysstr.nim, lib/wrappers/iup.nim, lib/wrappers/mysql.nim, lib/wrappers/openssl.nim, tests/gc/gcbench.nim, tests/manyloc/keineschweine/dependencies/genpacket/genpacket_enet.nim, tests/misc/tunsignedconv.nim, tests/objvariant/tadrdisc.nim, tests/tuples/tuple_with_nil.nim
with the exception of [this](https://github.com/nim-lang/Nim/pull/12553/files#diff-fbba751fdd9bce986252bdd97b979d0b) - nothing seems to depend on the error output
=> fix several typos in documentation and comments

lib/pure/distros.nim
Using `pacman` command in Manjaro Linux
=> Add `or detectOs(Manjaro)`

lib/pure/math.nim
=> added support for openArray's for `gcd` and `lcm`

changelog.md, lib/pure/sugar.nim
... to allow for method chaining.
Superseeds #12593 ?
=> Implemented outplace differently

lib/pure/net.nim, tools/finish.nim
=> fix #11425 - change exception handling

changelog.md, lib/pure/htmlgen.nim
- https://forum.nim-lang.org/t/5519#34453
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang
=> Fix htmlgen html lang

changelog.md, compiler/extccomp.nim, compiler/options.nim, compiler/pragmas.nim, compiler/rodimpl.nim, compiler/wordrecg.nim, doc/manual.rst
Implements https://github.com/nim-lang/Nim/issues/12662
=> implemented a new localPassc pragma

changelog.md, lib/pure/sugar.nim
assumes init call has generic parameters
=> add collect macro

compiler/options.nim, tests/nimble/tnimblepathdollarfail.nim, tests/nimble/tnimblepathdollarfail.nims
See https://github.com/nim-lang/Nim/issues/12767#issuecomment-559650891.
=> Fix #12767

lib/pure/httpclient.nim
=> fix httpclient.lastModified bad pattern in parsing

compiler/commands.nim, compiler/options.nim
=> Path substitution for --out and --outdir

lib/deprecated/pure/events.nim
This just removes my old username. I know the file is deprecated. I don't have any plans to further update it.
=> Update events.nim - Removing of old username.

compiler/semmagic.nim, tests/metatype/ttypedesc2.nim
=> fixes crash on type.name[0] [backport]

doc/manual.rst
Said that you can have custom exceptions and showed how to create and raise them.
=> Added a note + eg about custom exceptions

lib/nimrtl.nim
fixed for 'csuCmpIgnoreStyle' error on hotcodereloading
=> imported cstrutils

compiler/semstmts.nim, tests/errmsgs/t10489_a.nim, tests/errmsgs/t10489_b.nim, tests/errmsgs/t12844.nim
Closes https://github.com/nim-lang/Nim/issues/12844
=> Assigning template to var/let/const gives a proper error

compiler/extccomp.nim
Closes https://github.com/nim-lang/Nim/issues/8921
=> Support cross compiling from host to host

compiler/cgen.nim, tests/destructor/tnewruntime_misc.nim
I am not confident in this fix. Please review the approach.
According to comment only finally block should be considered
=> fixes #12827

compiler/semtypes.nim
Opening for now to see if tests would fail
=> Extending #12911

tools/nimgrep.nim
C:\Users\Test\nimcache\nimterop\nimpcre\buildcache\pcre.h1 matches
Need a newline.
cc @a-mr
=> Fix single match output

compiler/nim.nim
/cc @Araq 
fixes 3 bugs with config.commandLine and cmdline in generated json build file, some of which affect nimBetterRun correctness (controlling whether to recompile or not):
* cmdline was stripping prefix `-` and `--` resulting in ambiguities, eg `c -c`  was resulting in `c c` (`c` and `-c` mean different things!); further that resulted in ugly looking and not pastable cmdline, eg `c f r hints:on nimcache:/tmp/d06 etc...`
* cmdline didn't quote args, also resulting in ambiguities, eg (after fixing above bug):
`--passC:'-w -g'` resulted in `--passC:-w -g`
`--passC:'-w' -g` resulted in `--passC:-w -g`
=> clash!
* cmdline would be repeated 2X (or more) times, eg:
`bin/nim.pr_fix_D20191219T101610_cmdline.3 c -f -r --hints:on --nimcache:/tmp/d06 --passC:"-w -g" …
=> fix 3 commandLine / cmdline bugs affecting nimBetterRun correctness

compiler/extccomp.nim, compiler/options.nim
/cc @stefantalpalaru it should help with https://github.com/status-im/nim-libbacktrace and https://github.com/nim-lang/Nim/pull/12922
/cc @Araq 
* fixes https://github.com/nim-lang/Nim/issues/12735
=> fix #12735 on osx, call dsymutil for debug builds

compiler/extccomp.nim
fix [#12988](https://github.com/nim-lang/Nim/issues/12988)
=> fix #12988

compiler/injectdestructors.nim, tests/destructor/tmisc_destructors.nim
Now uses the dfa for firstWrite analysis.
Eventually I want to implement https://github.com/nim-lang/Nim/issues/13003#issuecomment-570078768 and do init elision along the way.
=> Continue #13002

lib/pure/asyncftpclient.nim
=> Revert "fix the port convert overflow"
