nim-lang/Nim

compiler/transf.nim
This way we can have correct debug flow loops.
It changes the behavior in a debugger from 
```
iterator code..
code1
code2
iterator code ..
code1
for
iterator code ..
code1 
code2
for
```
I think adding a noop line after yield might be best, as maybe yield needs the iterator lineinfo. I am not sure how to add such a line: I tried and codegen seems to optimize it.
Do I need to add a test?
=> Show lineinfo of for in yield

lib/pure/memfiles.nim
See commit comment.  I would also advocate ditching MAP_POPULATE and letting Linux-specific users just set that in their open call if they want it.
It also does not make much sense for MAP_PRIVATE to be used in readonly mode...That map flag is about propagating write changes, but in RO mode there are no writes to propagate.
Anyway, we need at least something like this `mapFlags` to give users the ability to override the poor default choices or activate any other idiosyncratic
platform-specific features.  I'm open-minded about other constructions, but the current state of affairs is you have to page in the whole file right on open which is double-plus un-good, in 1984-ese.
=> Allow an escape hatch for platform specific flags/default override

testament/tester.nim
e.g.: PATH="./bin:$PATH" ./koch tests r stdlib/nre/captures.nim
=> testament: individual tests with more than a subdir in their path

changelog.md, compiler/vmops.nim, lib/pure/os.nim, lib/system/nimscript.nim, tests/vm/tgorge.nim, tests/vm/tvmops.nim
/cc @Araq 
* adds `getCurrentNimExe` support at CT
eg use case: allowing a nim file to get access to the exact same nim compiler that was used to compile it (without needing environment variables etc), which can be useful in some testing scenarios
there are other use cases obviously
* adds a test file for vmops (`getCurrentNimExe` now provides a simple way to test gorge, gorgeEx for example)
[EDIT] notes
* WAS: `getAppFilename`
=> add `getCurrentCompilerExe` to vmops (eg allows to get nim compiler at CT); add tests for vmops

doc/manual.rst
* document NIM_EXTERNC for `emit`
* refs https://github.com/nim-lang/Nim/pull/4010
=> document NIM_EXTERNC for `emit` that avoids link errors with `nim cpp`

lib/pure/pathnorm.nim, tests/stdlib/tos.nim
/cc @Araq @krux02 @dom96
* fix #10017 regression
* fix #10025 regression
=> [os] fix #10017 regression, fix #10025 regression

testament/htmlgen.nim, testament/tester.nim
Fix several testament regressions:
- `testresults.html` now correctly classify skipped tests
- `--targets` is now (again) respected by `testament` to limit backends tested.
=> Testament fixes

compiler/ast.nim, compiler/parser.nim, compiler/semstmts.nim, lib/core/macros.nim
Fixes https://github.com/nim-lang/Nim/issues/6355
While this works for all the cases I tried, there may still be bugs.
Review carefully.
=> Const tuple unpacking

compiler/semtypes.nim, tests/proc/typed.nim, tests/proc/untyped.nim
Fixes https://github.com/nim-lang/Nim/issues/6970
Fixes https://github.com/nim-lang/Nim/issues/7469
Closes https://github.com/nim-lang/Nim/issues/9669
Fixes https://github.com/nim-lang/Nim/issues/9593
=> proc does not take untyped/typed as argument 

lib/pure/json.nim
document (with a `runnableExamples` unittest) fact that key ordering is preserved
This property is useful in some cases (eg when dumping some value as json string, it's nice to preserve source ordering of keys)
the "purist" approach is that json key ordering is unspecified and shouldn't matter (eg see https://stackoverflow.com/questions/4515676/keep-the-order-of-the-json-keys-during-json-conversion-to-csv) however it's and often recurring pain point, and since we're already preserving key ordering, might as well document that it works within Nim's stdlib.
same as in python, where they realized it can be useful:
https://stackoverflow.com/questions/10844064/items-in-json-object-are-out-of-order-using-json-dumps
> Since Python 3.6, the keyword argument order is preserved and the above can be …
=> [json] document fact that key ordering is preserved

lib/pure/distros.nim
`detectOs` from `distros.nim` won't detect the OS properly if `uname` or `lsb_release -a` do not contain the OS name. I don't know about any other OS's, but I know for a fact that since at least Fedora 27, `uname` reports the OS name as `GNU/Linux` and `lsb_release` is not installed by default.
This commit adds a third `execProcess` call to the necessary `detectOsImpl` code, this time the call executes `hostnamectl`, which contains the OS name. Sample output of `hostnamectl` from my Fedora 29 machine is as follows:
```
Static hostname: anarchy
Icon name: computer-laptop
Chassis: laptop
Machine ID: [redacted for opsec]
Boot ID: [redacted for opsec]
Operating System: Fedora 29 (Workstation Edition)
CPE OS Name: cpe:/o:fedoraproject:fedora:29
Kernel: Linux 4.19.8-300.fc29.x86_64 …
```
=> Add call to hostnamectl in detectOsImpl

testament/categories.nim, testament/tester.nim, tests/testament/tshouldfail.nim
/cc @Araq @krux02 
* fix #9328 testsuite silently ignores a number of tests
* all stdlib modules are now compiled (and run when appropriate), except an explicit blacklist that fails
(previously it ignored deeper nested modules, eg lib/pure/foo/bar.nim)
* that exposed a number of failing tests that were never previously run under CI, see disabledFilesDefault
* ditto with files under tests/
* ditto with identifying modules suitable for megatest
* isJoinableSpec now returns false if there's a nims file
* isJoinableSpec now searches deeper for a nim.cfg (and config.nims) file, since that's how config files work
* show absolute progress (eg: category 10 / 120)
* new --dryrun mode that just completes in ~5 seconds and prints out all the testSpec that would be run; helpful for debugging
* files …
=> lots of testament bug fixes and improvements:

lib/pure/os.nim, tests/stdlib/tos.nim
This makes `walkDirRec` work on Haiku, and also fix a bug causing walkDir to not classify symlink as `pcLinkToDir` on *nix with `relative = true`
=> os.walkDir: correctly evaluate paths when relative = true

lib/system.nim
disambiguates that it's lexicographic order and not the other plausible interpretation of a <= b iff all components are <=
=> clarify doc for <= on tuple uses lexicographic order

lib/pure/distros.nim
Calling `uname -a`, `lsb_release -a`, and only checking the distro name against the entirety of `hostnamectl` can cause false positives in distro detection due to the machine name.
For instance, my machine has been named "anarchy" for quite some time. `uname -a`, `lsb_release -a`, and `hostnamectl` all output the hostname, so `detectOs ArchLinux` returns `true` as `anarchy` contains the substring `arch`.
Changing `uname -a` to `uname -o` fixes the problem for uname, as the `-o` switch only outputs the OS name (`GNU/Linux` on my Fedora machine, but most distros output the actual distro name). The `-d` switch for `lsb_release` outputs only the description, which is `Description:	Fedora release 29 (Twenty Nine)` on my Fedora machine.
`hostnamectl` is different, because you can't use a …
=> Stop false positives in distros.detectOs

lib/pure/collections/intsets.nim
Is this Note regarding assignment operator still valid? From the manual it appears you can overload.
- Expanding on some documentation.
- Fixing some typos.
- And clarifying wording on assignment overload & assign.
=> IntSet documentation notes

lib/pure/times.nim, tests/stdlib/ttimes.nim
This PR removes the usage of `parseutils.parseInt` from the times module in favor of using a local implementation. It has several benefits:
- Correct exception handling. No more `OverflowError`'s for invalid input.
- Faster `times.parse`, because it no longer performs any string slicing.
- `times.parse` no longer accepts signs in weird places. For example, `parse("dd/MM", "+1/+1")` is no longer accepted.
- Underscore is no longer treated as a numeric separator. This means that `parse("2000_01_01", "YYYY'_'dd'_'MM")` is now accepted.
Additionally, I introduced two new exception types so that errors in the format string and the input string can be treated differently.
=> Remove usage parseutils.parseInt in the times module

lib/pure/random.nim
=> Revert sub-second randomize(). Fixes randomize for JS backend.

changelog.md, compiler/parser.nim
Closes https://github.com/nim-lang/Nim/issues/8514
Closes https://github.com/nim-lang/Nim/issues/1872
<details><summary><b>Deprecated Syntax</b></summary>
<p>
```nim
type B = object {.pragma.}
```
```nim
type T {.shallow.} [X] = void
```
</p>
</details>
<details><summary><b>And, the syntax that has to be used now</b></summary>
<p>
```nim
type A {.pragma.} = object
```
```nim
type T[X] {.shallow.} = void
```
</p>
</details>
=> Pragma syntax is now consistent

tests/tuples/ttuples_various.nim
Tests for https://github.com/nim-lang/Nim/pull/10099.
The third test fails on `58d293d`.
=> Const tuple unpacking: add tests

lib/system/sysio.nim
* `checkErr` now returns the actual system error msg instead of unknown error
eg, for https://github.com/nim-lang/Nim/issues/9634 it now shows:
```
Error: unhandled exception: strerror: `Interrupted system call` [IOError]
```
instead of:
```
Error: unhandled exception: Unknown IO Error [IOError]
```
* ~~introduces an easy / flexible way to deal with problem raised in https://github.com/nim-lang/Nim/pull/4010, ie, allowing `emit` to link correctly regardless of `nim c` or `nim cpp`~~ 
EDIT: just saw we already have `NIM_EXTERNC` available, defined in `lib/nimbase.h`
* ~~I couldn't use: `var errno* {.importc, header: "<errno.h>".}: cint ## error variable` since it gave `Error: cannot 'importc' variable at compile time`
and besides, accessing `errno` through a proc as I did sounds through …
=> [sysio] `checkErr` now shows actual system error msg instead of unknown error

compiler/semmagic.nim, lib/pure/typetraits.nim, lib/system.nim, tests/system/tsystem_misc.nim
* fixes #5827
* revives https://github.com/nim-lang/Nim/pull/7100 by addressing comments and fixing test failures
/cc @dom96 I kept your 1st commit so your name is still there
=> revives: Move typetraits.`$` to system. Fixes #5827

doc/advopt.txt
documenting this flag to increase its discoverability and increasing likelihood corresponding bugs (eg https://github.com/nim-lang/Nim/issues/10106) will get fixed; furthermore that flag requires other flags and setup (import nimprof) so needs to be documented to avoid user frustration when they try `--profiler:on` and `profile_results.txt` doesn't get written
=> document --profiler:on

lib/pure/times.nim
* workaround for https://github.com/nim-lang/Nim/issues/10121#issuecomment-450453369
* allows profiling nim compiler itself with valgrind's callgrind, eg:
```
nim c -d:release -d:valgrind_workaround_10121 --passC:-g compiler/nim.nim
valgrind --tool=callgrind --fullpath-after= compiler/nim c compiler/nim.nim
callgrind_annotate callgrind.out.$pid
```
this workaround is needed until upstream valgrind fixes this, just filed https://bugs.kde.org/show_bug.cgi?id=402696
=> refs #10121

lib/pure/math.nim, lib/pure/random.nim, tests/stdlib/tmath.nim
CDF is a standard ident in all things related to random numbers/sampling,
and full words "cumulativeDistributionFunction" would be silly long, in
this case, IMO.  We use lowercase `cdf` to make it not look like a type,
remove all looping from `sample` letting callers do it.  Besides just
side-stepping any `sampleSize` name choice, callers may want to filter
out samples anyway which this makes slightly simpler.
Also add two variants of `cumsum`, value return and in-place update
distinguished by the var-ness of the first argument.  Add tests for
`int` and `float` for both `cumsum` and the new `sample`.  (The sample
tests exercise the value return mode of `cumsum`.)
Functionality pre-this-PR `sample(a, w)` is now the almost as simple
`for i in 0..<n: sample(a, w.cumsum)`, but this new code …
=> Resolve things raised in https://github.com/nim-lang/Nim/issues/10081 ?

compiler/msgs.nim, tests/discard/tneedsdiscard.nim, tests/method/tmapper.nim, tests/modules/tmismatchedvisibility.nim
* factored out from https://github.com/nim-lang/Nim/pull/9766 to keep it smaller
makes it consistent with way other procs display col, eg:
```
coordToStr(context.info.col+1)]
```
compiler/msgs.nim:
```
```
=> fix off by 1 error in `col` shown by toFileLineCol

compiler/semtypes.nim
Closes https://github.com/nim-lang/Nim/issues/5635
Also allows (because a similar code `var x: ExplicitEnum` compiles)
```
import tables
type
ExplicitEnum = enum
Val1 = 1 
MyObj = ref object
table: ExplicitEnum
let obj = MyObj()
echo obj.table
```
which currently gives ` Error: field not initialized: table`
=> Show field not initialized warning only when `notnil` used

lib/pure/os.nim, tests/stdlib/tos.nim
A port of b6257f3f212036216fb4aeb521a3d120222b237c for version-0-19 branch
/cc @Araq
=> os.walkDir: correctly evaluate paths when relative = true [0.19]

lib/pure/unicode.nim
* as instructed in #2353, provides a short description why
there are no specialized procs for seq[Rune]
* adds several examples to better explain what some functions do
* small fixes (double backticks, add missing dots, etc.)
----
There are no code changes and I've run `nim doc` locally and all runnable examples are passing, so I think `[ci skip]` is ok here.
=> [backport] improve unicode docs, fixes #2353 [ci skip]

lib/system.nim, tests/system/tsystem_misc.nim
before PR:
```
doAssertRaises(Exception):
raise newException(Exception, "foo")
```
gave: `Error: exception already handled`
after PR: it passes
=> fix bug in doAssertRaises when exception==Exception

doc/nimc.rst
=> Fix Typo in Compiler Guide

lib/system/jssys.nim, tests/js/test2.nim
On JS this crashes, but shouldn't.
```nim
doAssert getCurrentException() == nil
doAssert getCurrentExceptionMsg() == ""
```
=> Guard against null exception (JS)

lib/system.nim, lib/system/helpers.nim
Some unrelated documentations have leaked into the top-level of system.nim. This PR fixes that.
=> fix system.nim documentations

lib/pure/os.nim
The tuple returns `name` instead of `filename` as seen here: https://github.com/nim-lang/Nim/blob/be0a4d1342b05815e25f9a51bda0cf199a6d439e/lib/pure/os.nim#L378
=> Fix the tuple returned by `os.splitFile()` in documentation

.gitignore, testament/categories.nim, testament/tester.nim
* sort megatest files for reproducibility / ease of debugging
* output of file `foo.nim` will now be preceded by `megatest:processing: foo.nim` with 2 benefits:
* prevents pathological cases where wrong test output is not detected [1]
* helps debugging when there are test failures (including expected/actual mismatch) as you can now tell where the test failure came from; previously it was pretty bad as you'd have no idea and would have to try to figure it out using grep, which in some cases would be impossibly ambiguous
[1] example:
```
test1.nim: expected to print foo
test2.nim: expected to print bar
```
if test1 produces nothing and test2 produces foo\nbar, a bug would previously go un-detected; after this PR, it will be detected since the output is now:
```
processing test1.nim
foo …
```
=> testament megatest: we can now tell which test failed; helps debugging and prevents certain bugs, plus other fixes

lib/impure/db_odbc.nim
ODBC Errors were presented to the users as a sequence of characters.
I.e.:
>test_oracle.exe
Error: ['H', 'Y', '0', '0', '0', '\x00', '\x00', ...]
test_oracle.nim(15)      test_oracle
test_oracle.nim(8)       test_oracle
db_odbc.nim(534)         open
db_odbc.nim(168)         dbError
Error: unhandled exception: ODBC Error [DbError]
This patch fix the string decoding, creating a real string:
>test_oracle.exe
Error: HY000 [Oracle][ODBC][Ora]ORA-12541: TNS:no listener
test_oracle.nim(15)      test_oracle
test_oracle.nim(8)       test_oracle
db_odbc.nim(534)         open
db_odbc.nim(168)         dbError
Error: unhandled exception: ODBC Error [DbError]
=> Fix ODBC SQL Error string decoding

changelog.md, compiler/ast.nim, compiler/commands.nim, compiler/guards.nim, compiler/options.nim, compiler/semstmts.nim, doc/advopt.txt, lib/core/macros.nim, tests/pragmas/tcustom_pragma.nim
This passes all tests, but it changes the ast attached to var and let symbols, so might need further testing.  It also changes what getImpl returns for those symbols, so may break code using that.
=> add custom pragma support for var and let symbols

lib/wrappers/openssl.nim
fixes #9419
It currently searches for libSSL versions in random order:
`.1.1|.38|.39|.41|.43|.44|.45|.46|.10|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8|`
Its a mystery which one it will pick up. Newest version 1.0.2 is some where in the middle, so its highly likely it will not pick it up.
A better system is to search in order of new -> old:
`.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8|.1.1|.38|.39|.41|.43|.44|.45|.46|.10`
=> Change the search order of libSSL libs from newest to oldest.

lib/pure/os.nim, tests/stdlib/t10231.nim
Darwin has long deprecated the wait `union`, but their macros still assume
it unless you define `_POSIX_C_SOURCE`. This trips up C++ compilers.
This commit duplicates the behavior of `WEXITSTATUS` when `_POSIX_C_SOURCE`
is defined.
=> os.execShellCmd: fixes #10231

.travis.yml, appveyor.yml, koch.nim, tools/kochdocs.nim
=> [CI] fix #10041 move bulk of `travis` and `appveyor` logic to koch.nim

compiler/pragmas.nim, compiler/suggest.nim, tests/deprecated/tannot.nim, tests/deprecated/tnoannot.nim
Works now because of https://github.com/nim-lang/Nim/pull/9582
Refs https://github.com/nim-lang/Nim/issues/9331
=> {.deprecated: msg.} now works for vars and lets

compiler/asciitables.nim, compiler/unittest_light.nim, tests/compiler/nim.cfg, tests/compiler/tasciitables.nim, tests/compiler/tunittest_light.nim
* depends on https://github.com/nim-lang/Nim/pull/10181 when viewing the diff
* useful for easy pretty-printing of tables, see ./tests/compiler/tasciitables.nim
* automatically infers number of rows, cols, and width of each cell
* can be either used with the provided `alignTable(ret)` or arbitrarily customized by calling the iterator `for cell in parseTableCells(s, delim):` directly
after this PR is merged, I'll update `vmgen.codeListing` to use that instead ; it'll generate nicer looking listings (aligned) which are easier to follow, eg:
```
code listing:
103           AsgnStr   r5, r1, r0          #/Users/timothee/git_clone/nim/Nim/lib/system/helpers.nim:7:3
104           LdConst   r6, "(" (9)         #/Users/timothee/git_clone/nim/Nim/lib/system/helpers.nim:7:10
105           Conv …
```
=> add `alignTable`, `parseTableCells` to align/format a tab(etc) delimited table

lib/pure/ioselects/ioselectors_epoll.nim, lib/pure/selectors.nim
#7538: ioselectors allocate all possible file descriptors at start
I'm not able to reopen the issue, so here is a pull request to discuss possible solutions.
I'm having a hard time explaining my colleagues why a trivial Nim program with async I/O uses more then 40MB of memory on our development systems. While discussing this on #nim some people noted that this should probably be fixed.
Here is a simple approach: the selector starts with reasonable fd set size (1024) and increases in powers of two when needed. This prevents the selector to allocate large amounts of memory at startup on systems with a high RLIMIT_NOFILE setting.
=> Reduce epoll selector memory usage

lib/pure/streams.nim
Those are useful in generic code, and `proc write*[T](s: Stream, x: T)` was already public.
=> make Stream.{read,peek} procs public

changelog.md, lib/system.nim
See https://github.com/nim-lang/Nim/issues/9857#issuecomment-452601891
`KeyError` inherits from `ValueError`, but it should probably inherit from `Defect` instead so it's not treated as catchable after this change?
=> ValueError now inherits from CatchableError

koch.nim, tools/kochdocs.nim
* fix #10039 : CI now runs buildTools
* refactoring / simplification
appveyor now a bit more consistent with travis than before PR: previously, some tools were not compiled on appveyor, which could've been due to bitrot
* fix remaining comment from https://github.com/nim-lang/Nim/pull/10183#discussion_r245972871 
> You can easily move kochExe and kochExec to koch.nim btw, but I'm merging this now.
* closes #10250 /cc @cooldome 
* humans can use ./koch tools in most cases (it'll work if no network failure; it'll work up to nimble if there is network failure, and then crash but at least non-nimble tools would be built)
* humans can also use ./koch toolsNoNimble if they don't need to rebuild nimble (which is actually what I'd want in most cases since nimble is hosted / maintaned elsewhere, …
=> fix #10039 : CI now runs buildTools (eg, nimfind wasn't being compiled before); refactoring

lib/js/jscore.nim, lib/pure/times.nim
- Improved docs (notably, a new section explaining the difference between `TimeInterval` and `Duration`)
- Code wrapped at 80 chars
- Lots of formatting fixes with the help of nimsuggest
- `times` now uses `posix.Tm` instead of defining it again (it still needs to be defined for windows though)
- Added more wrappers in `jscore` so that no wrapping code for JS is needed in the `times` module anymore
- Removed a few procs that has been deprecated since `v0.8.10` and `v0.14.0`.
Fixes #7315 
Fixes #10243
=> Times cosmetic changes

lib/pure/concurrency/atomics.nim
Work in progress on C++11 style atomics (currently [here](https://github.com/fragcolor-xyz/fragments/blob/4c86ee316e538cb58ac1882ba9337d28f46b72b9/fragments/threading/atomics.nim)). Let me know what you think.
Usage examples:
```nimrod
var
flag: AtomicFlag
value: Atomic[int]
expected: int
while not flag.testAndSet(moAcquire): spin()
value.compareExchange(expected, expected + 1, moRelaxed)
```
Some points of discussion:
- The C version currently only uses C11 style `_Atomic` for types with a size of 64 bits or less. This is because `importc` doesn't allow the same patterns as `importcpp` on generic types.
- Because of this and because `sizeof` can't always be evaluated, only some builtin types are spin-less in C that could otherwise be atomic.
- VCC is taking some shortcuts currently. It …
=> [RFC] Better atomics

testament/tester.nim
* refs #10249
addresses this comment from @cooldome 
> Megatest should display what nim command was executed with all the arguments and the file path in verbose mode
and shows things like:
```
(msg: "execCmdEx2", command: "compiler/nim c --nimCache:nimcache/tests/megatest_0d61f8370cad1d412f80b84d143e1257 -d:testing --listCmd megatest.nim", options: {poUsePath, poStdErrToStdOut})
```
the root cause of #10249 is different though, and I will explain later what's going on
=> refs #10249 ; more debug info to diagnose failures

lib/wrappers/openssl.nim
* fix #10281 (workaround) `OpenSSL error` breaking nimble and every package #10282
this reverts the recent changes made for #10230, but only for OSX, which is where things started breaking badly; a future PR can find a better fix  /cc @treeform @alaviss @dom96 
after this PR  `./nimble test` works again
if anyone has an idea for a test please help
=> fix #10281 (workaround) `OpenSSL error` breaking nimble and every package

.gitignore, lib/pure/os.nim, lib/pure/osproc.nim, lib/std/special_paths.nim, testament/lib/stdtest/specialpaths.nim, tests/nim.cfg, tests/stdlib/t10231.nim, tests/stdlib/tos.nim, tests/stdlib/tosproc.nim
* fix #10273 : execShellCmd now returns nonzero (instead of 0) when child killed with signal
* this is a serious bug as ignoring errors can have bad consequences
* this could happen when child dies because of SIGSEGV, eg due to infinite recursion causing stack overflow
* execShellCmd(cmd) now returns the same exit code as if you ran `cmd` in your shell, instead of 0
* add tests for this in tests/stdlib/tosproc.nim
* rename exitStatus() to exitStatusLikeShell() to make its meaning clear and distinguish from exitStatus variables which aren't necessarily referring to shell exit status
* fix minor bug in .gitignore
* properly fixes this https://github.com/nim-lang/Nim/issues/10231#issuecomment-452190306:
> Looks like POSIX compat is a mess on Darwin. I guess this could just be fixed with a …
=> fix #10273 execShellCmd now returns nonzero when child killed with signal + other fixes

doc/nims.rst
When I used setCommand as shown in the example, I get this warning on build.
Warning: Using `setCommand 'nop'` is not necessary.
Maybe I'm missing something, but it seems like the documentation is outdated.
=> setCommand nop, outdated documentation

lib/pure/random.nim
Well this doesn't directly fix #10258, but it provides an alternative that does work reliably for the very common corner case.
=> added proc rand of integer type

lib/pure/collections/tables.nim, tests/stdlib/tmget.nim
I base this work on top of @BontaVlads work here: #10226. This still needs to be reviewed. I did this because I saw some time ago a C++ conference talk about the design problems in c++ where reading from a table causes changes in the table. I don't use count table on my own, but I saw how the decisions were heading towards the exact same problems that were talked about in the talk. I am sorry it was really a long time ago so I can't provide a link to it.
What I did, I removed `proc `[]`*[A](t: var CountTable[A], key: A): var int`, because that either has to raise an error when the key is not found or modify the table. Neither is desireable and in nim there is a nice alternative, the `[]=` procedure. This coveres almost all practical use cases of returning a reference, it is syntactically …
=> Fixes 10065

compiler/lineinfos.nim, compiler/unittest_light.nim, lib/pure/parseopt.nim, tests/compiler/tunittest_light.nim, tests/misc/tparseopt.nim
* fix #9951: parseopt.cmdLineRest is now correct (previously didn't handles spaces, quotes, single quotes, empty arguments)
* this cleans up implementation, see lib/pure/parseopt.nim
* fix #9842: `nim -r` is now correct, as a result (ditto, previously didn't handles spaces, quotes, single quotes, empty arguments)
* unrelated improvement in compiler/unittest_light.nim which I could put in separate PR if really needed
* verbosity:0 now silences hintCC
I had to add `joinable:false` to avoid test failure, but https://github.com/nim-lang/Nim/pull/10293 will allow to remove `joinable:false`
=> fix #9842 #9951: `nim -r` and parseopt.cmdLineRest are now correct

testament/tester.nim
* refs #10249
* refs #10266
logging commands helps if debugging is needed (as requested here https://github.com/nim-lang/Nim/issues/10249#issue-397487069) but this PR hides it under a flag `--verboseCommands` so they don't introduce spam by default
=> refs #10249 #10266; each command logged only if --verboseCommands:true

tests/parallel/twrong_refcounts.nim
twrong_refcounts was failing in cpp mode because `getRefcount` from
```
lib/system/gc.nim:131:50:proc internRefcount(p: pointer): int {.exportc: "getRefcount".} =
```
gets mangled as C++ in `nim cpp`:
```
nm stdlib_system.cpp.o|grep getRefcount
000000000000d140 T __Z11getRefcountPv
```
whereas on the import side:
```
proc getRefcount*[T](x: ref T): int {.importc: "getRefcount", noSideEffect,
deprecated: "the refcount never was reliable, the GC does not use traditional refcounting".}
```
gets the declaration mangled as `extern C`, not `extern C++`, which points to a limitation we should address soon, such as ability to have `extern C` exportc procs in `nim cpp` ( a few syntaxes were discussed; will be addressed in future PR's)
So this PR introduces a workaround until we get ability to have …
=> fix twrong_refcounts in nim cpp mode

koch.nim
seems like
```
exec("env NIM_COMPILE_TO_CPP=false $1 boot" % kochExe.quoteShell)
```
will be run twice identically when travis runs the 2 top-level tests
```
- os: osx
env: NIM_COMPILE_TO_CPP=false
- os: osx
env: NIM_COMPILE_TO_CPP=true
```
whereas  `./koch boot`  in c++ mode will never be run; this PR fixes that so that `./koch boot`  will run once in c mode, once in C++ mode
when i converted travis code to nim code (`runCI`), `exec("env NIM_COMPILE_TO_CPP=false $1 boot" % kochExe.quoteShell)` was directly translation of what the travis code did
=> [CI] runCI runs `kochExec "boot"` regardless of nim mode

compiler/extccomp.nim, doc/nimc.rst, tests/float/tfloatnan.nim
* fix #10305 nim cpp is now nan-correct at CT #10310 and added a test that would fail before PR
* should fix these failing tests in CI (with nim cpp)
* tests/float/tfloatnan.nim
* lib/pure/math.nim
* tests/float/tfloatmod.nim
I finally figured out root cause of #10305, but it was a rather painful debug session
Here's a minimal test case to explain what's going on:
```cpp
#include <stdio.h>
#define CASE_VOLATILE // otherwise const folding optimizer kicks in
int main (int argc, char *argv[]) {
#ifdef CASE_VOLATILE
volatile double a1 = 0.0;
#else
double a1 = 0.0;
#endif
double a2 = 0.0;
double a3 = a1 / a2;
int t = a3 == 0.0;
int t2 = a3 == a3;
int t3 = a3 != a3;
printf("a3=%g,t=%d,t2=%d,t3=%d\n", a3, t, t2, t3);
return 0;
}
```
```
clang++ -o /tmp/D20181107T193702 -ffast-math -O3 …
```
=> fix #10305 nim cpp is now nan-correct at CT

lib/system/mmdisp.nim
The Boehm GC only needs interior pointer checking if pointers in global
variables or on the heap point to the interior of an object rather than
the beginning. If this does not happen, then checking for interior
pointers causes additional overhead, in particular because any objects
whose sizes are an exact multiple of two words gain another two words of
padding, wasting memory.
If checking of interior pointers is still desired, this can be achieved
by setting the environment variable GC_ALL_INTERIOR_POINTERS.
Pointers on the stack will always be treated as potential interior
pointers, as compiler optimizations may advance the only live reference
to a point past the beginning of an object.
=> Disable interior pointer checking by default for the Boehm GC.

compiler/dfa.nim, compiler/vm.nim, compiler/vmgen.nim
when investigating VM bugs codeListing is very useful. This PR improves formatting a bit:
* table is now aligned thanks to alignTable (from #10182)
* `--listFullPaths` is now honored if present inside code listing
* `opcIndCall, opcIndCallAsgn` opcodes are now more useful/easier to interpret, eg:
```
64            IndCallAsgn r2, r3, r4
=>
64            IndCallAsgn r2, r3, nargs:4
```
which helps ppl looking at the listings by better reflecting meaning of `4` here (note: nargs include 1 for the output; plus 3 for input params)
* minor code refactoring
* debugging enabled via `-d:nimVMDebug`; it's sufficiently useful to enable via a `defined`
I found these useful when debugging for FFI at CT PR
with `--listFullPaths -d:nimVMDebug` 
```
PC 101 opcLdConst ra 0 rb 8 rc 128
PC 102 opcIndCall …
```
=> improve vmgen.codeListing formatting

lib/pure/parseopt2.nim, tests/misc/tparseopt.nim
* same fix as https://github.com/nim-lang/Nim/pull/10291 but applied to parseopt2 instead of parseopt
* see tests that verify this (the added tests failed before this PR)
> No it is not "properly quoted", that is impossible because the quoting rules depend on the used shell on Unix.
it works for all the ones I've tried: fish, bash, sh, zsh, so  `properly quoted` seems a valid statement
```
fish
Welcome to fish, the friendly interactive shell
timothee@timotheecourmbp17 /p/t/d08> /tmp/nim//app 'a1 a2' '' 'a3"b' "a4'b"
@["a1 a2", "", "a3\"b", "a4\'b"]
```
```
bash
bash-3.2$ /tmp/nim//app 'a1 a2' '' 'a3"b' "a4'b"
@["a1 a2", "", "a3\"b", "a4\'b"]
bash-3.2$
```
```
sh
sh-3.2$ /tmp/nim//app 'a1 a2' '' 'a3"b' "a4'b"
@["a1 a2", "", "a3\"b", "a4\'b"]
```
```
zsh
/tmp/d08  0.000 $ /tmp/nim//app 'a1 …
```
=> parseopt2.cmdLineRest is now correct too

changelog.md, lib/pure/parseutils.nim
Fixes #9857.
For the procs that only parse positive numbers, no exception was previously raised for negative numbers. I've changed this so that all inputs that are outside of the valid range result in a `ValueError`.
I haven't touched `parseSaturatedNatural`, because I'm guessing the whole point of that procedure is that it doesn't raise any exception, so I don't know what it should do when it encounters a negative number.
I also haven't touched `parseHex`,  `parseOct` or `parseBin`, so those procs still use `OverflowError`.
=> Improve exception usage in parseutils

build_all.sh, doc/advopt.txt, koch.nim
* fix #10030 /cc @kaushalmodi 
* this prevents a user's config.nims to mess with bootstrap when he uses features not yet known by older nim  (older = one that's bootstrapped from c sources)
minimized example that failed before this PR and works after this PR:
```
mkdir foo && cd foo
```
cat config.nims
```
echo "should be used during boostrap"
import os
```
```
git clone https://github.com/nim-lang/Nim
cd Nim
sh build_all.sh
```
=> properly fix #10030 by skipping all external configs

lib/pure/json.nim, tests/stdlib/tjsonmacro.nim
EDIT (since https://github.com/nim-lang/Nim/pull/10010#issuecomment-454223393)
see tests/stdlib/tjsonmacro.nim for how tuples are jsonified; it's now consistent with D and python for both named and un-named tuples
```
block test_tuple:
doAssert $(%* (a1: 10, a2: "foo")) == """{"a1":10,"a2":"foo"}"""
doAssert $(%* (10, "foo")) == """[10,"foo"]"""
```
=> json: support tuple

nimsuggest/nimsuggest.nim
This allows editor plugin writers to avoid rapidly launching nimsuggest until they hit a free port.
=> nimsuggest: add an option to bind to a free port

lib/pure/times.nim, lib/std/time_t.nim, tools/kochdocs.nim
As explained in https://github.com/nim-lang/Nim/pull/10301#issuecomment-454280263, I think it's a bad idea to export this symbol. The `times` module is not a wrapper module, and the fact that it wraps `time_t` on Windows is just an implementation detail that might not be true in the future.
If we want to wrap C runtime library stuff for Windows it should be done as a separate module.
cc @genotrance
=> Revert export of times.CTime; add std/time_t instead.

compiler/semexprs.nim, compiler/semstmts.nim, tests/cpp/t10241.nim
Failing to do so lead the codegen to emit invalid code sometimes,
especially when C++ references were involved.
A wonderful bug that I've introduced myself some time ago :thinking: 
Fixes #10241
=> Properly wrap discarded statements

.travis.yml, koch.nim, lib/system.nim, tests/exception/t9657.nim
* [CI] now enables `NIM_COMPILE_TO_CPP=true` to run without allow_failures
* adds workaround for https://github.com/nim-lang/Nim/issues/10343
* fixes bug caused by `csources` being built assuming `raise_id` even though stdlib was updated in meantime to use `raiseId` ; this workaround can be removed after the next release of csources (but nothing will break if it's not removed)
* requires these other PR's the be merged first: EDIT: DONE!
* https://github.com/nim-lang/Nim/pull/10314 sdl_test (MERGED)
* https://github.com/nim-lang/Nim/pull/10313 twrong_refcounts (MERGED)
* https://github.com/nim-lang/Nim/pull/10310 (MERGED)
* tests/float/tfloatnan.nim
* lib/pure/math.nim
* tests/float/tfloatmod.nim
=> [CI] now enables `NIM_COMPILE_TO_CPP=true` to run without allow_failures

compiler/semasgn.nim, compiler/semdata.nim, compiler/semexprs.nim, compiler/semstmts.nim, tests/destructor/helper.nim, tests/destructor/terror_module.nim
* Disallow type bound operations to be defined in the different then type
* make `semasgn.nim` usable without semantic pass Context
=> destructors: first step towards fixing #9617

tools/vccexe/vccenv.nim
I got following error when I try to compile testvcc.nim.
This commit changed `expandFilename` so that if `filename` doesn't exist, it raise OSError.
But tools/vccexe/vccenv.nim was not fixed.
https://github.com/nim-lang/Nim/commit/e9a192c36fb62331db0bbd308433e56fc771c352#diff-2fd1cb6fa2de35053b75e69dcddfd419
This PR fix unhandled exception but still I cannot compile a testvcc.nim with --cc:vcc option.
I will make an issue about it later.
testvcc.nim:
```nim
echo "foo"
```
testvcc.nims:
```nim
--cc:vcc
```
Log:
f:\temp>nim c -r testvcc.nim
Hint: used config file 'f:\temp\nim-0.19.9\config\nim.cfg' [Conf]
Hint: used config file 'f:\temp\testvcc.nims' [Conf]
Hint: system [Processing]
Hint: testvcc [Processing]
CC: stdlib_system
CC: testvcc
Error: execution of an external compiler program …
=> Fix unhandled exception that raised when `nim c --cc:vcc`

lib/core/macros.nim, tests/pragmas/tcustom_pragma.nim
``getCustomPragmaVal()`` now returns a tuple if more then one field is available in the custom annotation. 
For backwards compatibility with the original behavior, single field annotations are returned as a value, multiple fields are returned as a named tuple.
As the original annotation always has field names, even if there is only one field, I feel it might be better if the result is always a tuple, but this will of course break things.
=> Fixed getCustomPragmaVal to allow multiple fields in custom annotations

lib/system.nim
`*=` never worked for bool, so didn't implement a deprecation path.
fixes #10257
=> deprecate += and friends for bool and enum

lib/pure/parseutils.nim
Fixes a regression caused by #10284
When fixing this, I realized that #10284 also caused a regression in compiler error messages. Integer literals that are larger than `high(int64)` will now give the message "invalid number: ..." instead of "number out of range: ...", because `lexer.nim` uses `strutils.parseBiggestInt` which will raise a `ValueError` for both cases. Possible solutions:
- Make `lexer.nim` use `parseutils.parseBiggestInt` instead
- Make the `parseutils.parseX` procs raise `RangeError` instead of `ValueError` for to large/small numbers
Let me know what's preferred and I'll fix that as well.
Fixes #10340
=> Fix parseutils.parseBiggestInt regression

lib/pure/uri.nim
Updated documentation for uri module:
- Intro text
- Code samples
- Runnable examples
refs #10330
CC @narimiran
=> uri: Updated documentation

compiler/lexer.nim, tests/errmsgs/tinteger_literals.nim
- Show correct error message for to large int64 literals (fix for regression caused by #10284)
- Reject uint64 literals that are to large (previously the value wrapped around)
=> Fix lexer error messages for to large numbers

compiler/parser.nim, compiler/semstmts.nim, nimsuggest/tests/taccent_highlight.nim
Previously nimsuggest would highlight the following as:
```
proc `$$$`
^~~
```
This fixes it into:
```
proc `$$$`
^~~
```
=> Correct lineinfo for accent quoted symbols in proc definition

compiler/sigmatch.nim, tests/typerel/t4799.nim, tests/typerel/t4799_1.nim, tests/typerel/t4799_2.nim, tests/typerel/t4799_3.nim
The type matching is done on the `T` of the `varargs[T]` so the
conversion must be performed to `T` and not to the whole type.
This problem is only noticeable with the cpp backend since C doesn't
give a damn shit about your fucking (wrong) types.
Fixes #9845
=> Fix subtype conversion w/ varargs arguments

compiler/vm.nim, tests/vm/tconstobj.nim
Hopefully the type-check phase already rejected all the invalid conversions by the time we execute the VM bytecode.
Am I too optimistic?
Problem reported by chrisheller on the Nim Forum, there's no associated ticket.
=> Object downconversion in VM should not copy

lib/pure/asyncmacro.nim
Fixes #9816
The doctest is broken so no tests for you.
=> Restore the docstring during the .async. transform

lib/pure/collections/intsets.nim, lib/pure/collections/sets.nim
=> Better docs for sets and intsets

lib/pure/parseopt.nim
Here's the updated documentation for the `parseopt` module.
I found the top-level documentation to be too brief regarding some details, especially with the `shortNoVal` and `longNoVal` parameters, so I expanded it greatly. I'm not sure if it's too verbose, though. Besides that, I added examples, see also docs, and I amended proc documentation.
However, when I add `runnableExamples` to `cmdLineRest`, `remainingArgs`, and the two `getopt` iterators, running `nim doc` afterwards results in a SIGSEGV, and I have no idea why. Thus, I placed their examples within the documentation comments for now. If it's not already reported (haven't checked), I might create an issue for that later.
Refs: #10330, CC: @narimiran
=> parseopt: Updated documentation

lib/impure/db_odbc.nim, lib/wrappers/odbcsql.nim
This fixes the wrong integer types in odbcsql and db_odbc.
Should fix the problem mentioned in the comments - the variables next to the `sz` variable were corrupted because of a wrong pointer type.
=> Fix wrong integer types in odbcsql and db_odbc

compiler/semstmts.nim, tests/exception/texceptions.nim
=> Fix semantic analysis with noReturn proc in tail pos

lib/pure/bitops.nim, tests/stdlib/tbitops.nim
These procs allow for easier bit fiddling on integer types, which is common on embedded systems or other low level C APIS, for example:
```
DDRB.setbit PD3
iflag.clearBits(IXON, IXOF, IXANY)
```
which is more readable then
```
DDRB = DDRB or PD3
iflag = iflag and not (IXON or IXOF or IXANY)
```
Ideally, the procs for manipulating multiple bits should also use ``BitsRange[T]`` in the type, but I can not get this to work due to #10337.
=> Added basic bit manipulation procs to bitops

nimsuggest/tester.nim, nimsuggest/tests/taccent_highlight.nim, nimsuggest/tests/ttype_highlight.nim
The EPC backend of nimsuggest currently doesn't support nimsuggest
highlighter, see nim-lang/nim-mode#140
Re-enable disabled highlighting tests.
=> nimsuggest/tester: disable highlight tests for epc

compiler/semexprs.nim, compiler/semtypes.nim, tests/macros/tquotedo.nim, tests/statictypes/tstatictypes.nim
I'm not sure if this is actually a fix or more of a hack. :)
The test case at least reproduces the same error as @mratsim's laser code.
The problem without this PR seems to be that we end up in `semObjConstr` with a `nkEmpty` node as the first child. I assume that's because `typ.base` in `semSym` extracts the node we need as a child later on in `semObjConstr`. 
If there's a better fix for this, feel free to close.
=> fix #10339 by returning type attached to nkEmpty

compiler/semexprs.nim, compiler/semtypes.nim, nimsuggest/tests/tgeneric_highlight.nim, nimsuggest/tests/tqualified_highlight.nim, nimsuggest/tests/ttemplate_highlight.nim
Lineinfo for templates is inconsistant across the compiler, for example:
doAssert true
^        ^
a[int](10)
^^    ^
The `^` marks where the compiler thinks the template starts.
For qualified call, we got the same situation with `proc`s before #10427:
system.once
^
Generics lineinfo within template declaration is also incorrect, for
example, this is where the compiler believes the `T` in `[T]` is:
template a[T](b: T)
^
This PR addresses all of these problems.
=> compiler/sem*: better lineinfo for templates

changelog.md, lib/pure/xmltree.nim
Beside writing a documentation, this PR adds a new proc `toXmlAttributes`, which just calls `strtabs.newStringTable`:
```nim
proc toXmlAttributes*(keyValuePairs: varargs[tuple[key, val: string]]): XmlAttributes =
newStringTable(keyValuePairs)
```
Usage:
```nim
let att = {"key1": "first value", "key2": "second value"}.toXmlAttributes
```
This allows using `newXmlTree` and  `attrs=` procs from this module without the need to import strtabs and create a string table, which is passed to these procs (which take `XmlAttributes`), making the whole process more transparent and easier.
=> better docs: xmltree

compiler/sem.nim, nimsuggest/tests/tmacro_highlight.nim
The compiler believes these are where a macro call starts (marked with
`^`):
m "string"
^ ^
This commit addresses that.
=> compiler/sem: correct macros lineinfo

compiler/msgs.nim
The old logic wasn't very useful because
`relPath` is almost always shorter than `absPath`,
e.g. `../../../../../` is shorter than `C:\Program Files`.
This way allows the usage of a relative path for
at most two levels deep, e.g. `../../relPath`,
otherwise the absolute path is used.
=> fix #9556 [backport]

lib/pure/parsecsv.nim
Updated documentation for parsecsv module.
- See also links
- Runnable examples
ref #10330
=> parsecsv: Updated documentation (#10330)

compiler/sempass2.nim, tests/effects/teffects7.nim
Exceptions raised inside a nkFinally/nkExcept block are not caught by
the block itself.
Fixes #3886
=> Fix exception tracking in try blocks

lib/pure/uri.nim
1) Use `assert` in code sample.
2) Updated wrong runnableExample in `combine()`.
=> uri: Update documentation typo

compiler/destroyer.nim, compiler/dfa.nim, tests/destructor/tmove_objconstr.nim
I have also noticed is that new `isLastRead` can crash with integer overflow because `fork` did `variantA+1` without checking if `variant(A) == high(int)` which does happen due to `goto high(int)` instructions.
Fixes #10462
=> isLastRead regression fix

doc/lib.rst, lib/pure/collections/heapqueue.nim
- ``HeapQueue`` is no longer a `distinct` type (using `distinct` makes it harder to extend the API in the future without breaking old code).
- The `` `[]` `` and `del` procs now takes a `Natural` instead of a `int`.
- Added the procs `clear` and `$`.
- Deprecated the `newHeapQueue` procs. Since `HeapQueue` is not a `ref` type, their naming is nonstandard. I've added a new `initHeapQueue` proc instead, but since seqs no longer require initialization the proc doesn't actually do anything. Maybe it's good to have it anyway for forward compatibility in case ``HeapQueue``  will require initialization in the future?
- Some examples, runnableExamples and comments
=> Cleanup heapqueue module

.travis.yml, tools/ci_testresults.nim
Make it easier to spot failed tests without having to scroll across all the logs.
=> Print error summary in Travis CI

config/nimdoc.cfg, nimdoc/testproject/expected/subdir/subdir_b/utils.html, nimdoc/testproject/expected/testproject.html, nimdoc/testproject/expected/theindex.html
The only thing added is `dt pre > span.Keyword ~ span.Identifier`, but because of some rearranging, git diff looks larger than it is.
See the screenshots below for a before–after comparison.
=> fix documentation css

compiler/docgen.nim, lib/system.nim
The important commit is the second one, right now the Nim Convention :tm: is not respected by `code-block` `:file:`.
One more nit, if one specifies a `:file:` directive the file it points to gets `importStmt` prepended to it and that's IMO bad behaviour if you want to do something like I do [here](https://github.com/LemonBoy/cassette/blob/0d727bae8a387629e4fe0f4b8632db1b179740fc/src/cassette.nim#L20,L22). I think the snippet should always be written to its own file or compiled&run from the specified location instead.
[1] `Nim's convention: every path is relative to the file it was written in`
=> Misc fixes

lib/pure/json.nim
Explained the proc \"pretty\" in detail, file: json.nim with comments and sample program
=> Explained the proc \"pretty\" in detail, file: json.nim with comments and sample program

doc/regexprs.txt
`re` `{` is now more documented by providing usage examples in `?`, `*` and `+` rows.
Anything more than that would just raise hundred new questions "why is `{` documented in detail, and X isn't?".
For those who would like to learn more, the documentation already provides links to http://www.pcre.org/ and http://perldoc.perl.org/perlre.html
This also fixes wrong table formatting:
=> fix #9471 (re quantifier `{` under-documented)

compiler/modulepaths.nim, tests/dir with space/more spaces/mspace.nim, tests/dir with space/tspace.nim
This allows spaces in imports, by using the following syntax:
* `import "directory with spaces" / subdir / file`, or
* `import "directory with spaces/subdir/file"`
=> fix #10042 (allow spaces in import)

lib/pure/times.nim
These procs should have been deprecated a long time ago. I think their original purpose was to implement a conversion for `Time` to `DateTime`. However, that conversion was rewritten a long time ago and doesn't use these procs anymore. They are extremely niche and it's unlikely that anyone uses them, so they are just api bloat that should be removed.
=> Deprecate the times.countX procs

lib/pure/distros.nim
/cc @dom96 because of https://github.com/nim-lang/nimble/pull/607#issuecomment-459850375
@Araq I don't understand your commit 0ecec83 `distros.nim: brew usually requires 'sudo'` ; where did you get this information from?
I've been using brew for years and never needed `sudo` when running `brew install foo` (there may be exceptions in rare corner cases, eg `brew cask install`, but i'm not even sure of that)
while installing brew itself **may** require `sudo` (or may have, in the past), (eg to agree to xcode license agreement), using sudo for `brew install` is not only not required but also probably not even allowed, see official docs:
* https://docs.brew.sh/Installation 
> This script installs Homebrew to /usr/local so that you don’t need sudo when you brew install
* see also: …
=> brew (almost?) never requires sudo

compiler/ast.nim, compiler/condsyms.nim, compiler/options.nim, compiler/pragmas.nim, compiler/semfold.nim, compiler/wordrecg.nim, doc/manual.rst, lib/pure/strtabs.nim, tests/misc/tdefine.nim
This implements the first part of my proposal [here](https://github.com/nim-lang/RFCs/issues/124#issuecomment-458716461).
Turns out that `-d:flag` was already interpreted the same as `-d:flag=true`, so no change needed there except a documentation update.
`strtabs` didn't support deletion before, so condsyms.nim used `"false"` for keys that should be deleted as a workaround. This was problematic since it was impossible to differentiate between `--define:flag=false` and `--undef:flag` even though they mean different things. I've solved it by implementing `strtabs.del`.
=> Implement {.booldefine.}

lib/pure/strtabs.nim
I forgot to push this before #10533 was merged... Since the strtabs.del implementation is based on the one for tables the strtabs.nextTry implementation must match the one for tables.
=> Change strtabs.nextTry to match the assumption in strtabs.del

lib/pure/asynchttpserver.nim, lib/pure/asyncmacro.nim
The keep-alive handling is very rough, there's no support for `Keep-Alive` directives nor a way to specify a timeout/limit of the connections in the pool.
=> Fix regression in AsyncHttpServer (plus other niceties)

doc/intern.rst, doc/manual.rst
* this documents that multiple `yield` in inline iterator cause code bloat
it's probably by design and not a bug but should be documented as it's a gotcha; see example below:
/cc @Araq 
```nim
iterator myiter(): int =
yield 10
yield 11
proc main()=
for a in myiter():
echo "done"
main()
```
generates with `--embedsrc -d:release`:
```
N_LIB_PRIVATE N_NIMCALL(void, main_audQMEKlkQTCwd9cxcZvVCg)(void) {
{
NI a;
a = (NI)0;
//    for a in myiter():
a = ((NI) 10);
//      echo "done"
echoBinSafe(TM_12xtM2ZmWTyc1IoNCQwzsA_2, 1);
//    for a in myiter():
a = ((NI) 11);
//      echo "done"
echoBinSafe(TM_12xtM2ZmWTyc1IoNCQwzsA_2, 1);
}
}
```
* see also https://github.com/nim-lang/Nim/pull/10545#discussion_r253651739 for relevant discussion, where `os.parentDirs` was deemed unsuitable in …
=> [ci skip] document that multiple `yield` in inline iterator cause code bloat

tests/config.nims, tests/nim.cfg
I ran ``./koch tests r tests/ccgbugs/twrongrefcounting.nim` on https://github.com/nim-lang/Nim/pull/10559 and got the very unhelpful:
```
FAIL: tests/ccgbugs/twrongrefcounting.nim C
Test "tests/ccgbugs/twrongrefcounting.nim" in category "tests"
Failure: reNimcCrash
Expected:
Gotten:
```
ie, empty `Gotten` instead of:
```
Gotten:
system module needs: echoBinSafe
```
The root casue is `switch("colors", "on")` in my `~/.config/config.nims` which messes with how testament verifies outputs;
note, this is a reasonable thing to put in a user config (I even had it under `when not defined(testing):` but that still didn't work; perhaps because not every call to `nim` inside testament has `-d:testing`
plus, might as well make it simple and working for everyone without requiring them to edit their …
=> prevent common user config to interfere with testament

doc/contributing.rst, doc/docstyle.rst
you can check the output using:
```
bin/nim rst2html -d:boot --putenv:nimversion=0.19.9  --git.url:https://github.com/nim-lang/Nim -o:web/upload/0.19.9/contributing.html --index:on doc/contributing.rst
open web/upload/0.19.9/contributing.html
```
changes:
* missing backticks which didn't render well
* fixes wrong code, eg `doAssert: not 1 == 2` became invalid
* double backticks isn't necessary anymore since 5ef5dc86c523c760b83050b6192f00b6a0816bce which supports the simpler / more familiar markdown link syntax
* fixes issues I encountered in https://github.com/nim-lang/Nim/pull/10434
* reflect newly added nim features (eg deprecated for enum etc)
* mention `nim doc --docInternal` which allows doc comments for private symbols to appear
* `.. code-block:: nim` => `.. code-block::` for code …
=> [doc] lots of fixes in doc/{contributing,docstyle}.rst

compiler/semstmts.nim, tests/macros/tmacrotypes.nim
=> Avoid evaluating macros twice in type sections

compiler/ccgexprs.nim
According to https://hownot2code.com/2016/08/18/null-pointer-dereferencing-causes-undefined-behavior/ this was an undefined behaviour.
=> Fixes #10568: Fix null pointer dereference in address computation for incrSeqV3.

lib/pure/times.nim, tests/stdlib/ttimes.nim
This PR replaces the implementation of `times.between` with a more robust one. I've also added a lot of test cases for the proc (many of them failing before this PR) to ensure I'm not just moving the problem around.
I've also deprecated the `times.toTimeInterval` proc since its only reasonable use was to calculate a `TimeInterval` between two dates, which `between` now does better in every way.
=> New implementation of times.between

tests/config.nims
* followup on #10573
* among other tests, helps `tests/errmsgs/tproper_stacktrace.nim` pass in a user config that contains `--excessiveStackTrace:on`, and also now `megatest` passes too
=> followup on #10573: prevent common user config to interfere with testament (excessiveStackTrace)

compiler/sempass2.nim, tests/effects/teffects8.nim
This is the MVP in order not to get a completely useless error message
from the compiler.
Fixes #10579 
Please note that this won't make NimYAML compile unless the `raises:` tags are removed.
This "regression" is more of a "progression" since before #10455 we'd just cover up the issue and, as it's common wisdom, a hidden exception raised at runtime is worse than an error at compile time.
Of course we could always improve the current algorithm (and make `raise` illegal outside of `except` bodies ?) but that's something for another day.
=> Fix handling of reraise in effect tracking

compiler/ccgstmts.nim
Decrement the frame length before closing the parent scope.
Fixes #10589
=> Fix codegen when debugger is enabled

compiler/msgs.nim, compiler/suggest.nim, nimsuggest/tests/tsetter_highlight.nim, nimsuggest/tests/tsi_highlight.nim
Previously the compiler would generate suggestions based on the symbol
identifier length, but that might not reflect the actual representation
of it within the actual source code.
This commit implements a simple source scanner for the suggest module to
address the problem outlined above.
Fixes nim-lang/nimsuggest#24.
A side effect is that `nimsuggest` will be less efficient when dealing with large files.
=> compiler/[msgs, suggest]: improve highlighter accuracy

tools/finish.nim
I'm trying to automate the installation of Nim on a Windows machine.  Having a `-y` mode like this would help.
**THIS IS AN UNTESTED CHANGE** because I haven't dug in to learn how to build this myself yet.
=> Add non-interactive installer flag (-y) to finish.nim

compiler/ccgtypes.nim, compiler/sighashes.nim, tests/ccgbugs/tsighash_typename_regression.nim
Empty types introduced by a template produced the same hash of the
"clean" type sharing the same name.
=> Fix edge case in type hashing

lib/system.nim, lib/system/excpt.nim
Just keep system.nim cleaner. Excpt already contains other excption , signal handlers
=> Move cpp exception handler from system to excpt next to the signal handler

compiler/semstmts.nim, compiler/semtypes.nim, tests/casestmt/tcaseexpr1.nim, tests/casestmt/tincompletecaseobject.nim
this PR is a side effect of another PR that I did. I was bothered that the error message only said that not all cases in the case statement were covered, bit it didn't tell me what was missing. So I made the error message print the missing enum values.  The values are separated by a comma, so that the values can be copied from the output into a new of branch to cover the missing values.
=> Print missing case labels

lib/pure/json.nim
Ideally I think all collection types in the stdlib should be serializable to JSON, but no idea where to define the procs. I doubt it's acceptable to import all collection modules into the JSON module? Either way, the tables module is already imported into the JSON module, and it's an important type for dealing with JSON, so this is a good start.
I noticed that `toCountTable` didn't work because the proc order was wrong, so I fixed that as well.
=> Add procs for serializing tables to JSON

lib/system/sets.nim
for: https://gist.github.com/brentp/7d440560968c3ac97c40de17200e404a
this speeds up the system.sets time from ~0.2 to ~0.06
in release mode. This is still slower than intsets and
tables (which both are ~0.01).
This assumes that most sets will be sparse.
fixes #10617
=> sets: avoid calling countBits32 for 0

lib/core/typeinfo.nim
See forum discussion: [pros/cons of dissecting types via getTypeInfo() vs getTypeImpl()?](https://forum.nim-lang.org/t/4622)
=> In typeinfo's doc comment, warned that rtti will evolve and suggested alternative approaches.

lib/pure/xmltree.nim
See https://en.wikipedia.org/wiki/XML#Escaping and https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML
=> Use standard XML escaping

compiler/semtypinst.nim, tests/generics/tgenerics_various.nim
If one marks a generic type with `gcsafe` that tag is not propagated to the parent `tyGenericInvocation` and `handleGenericInvocation` becomes a lovely endless loop due to the flag mismatch.
Now, the use of `gcsafe` for types is not documented in the manual and is only used by the `Channel` type (I suppose that's needed in order to be able to use them in gcsafe code), and I'm not sure if removing it altogether is correct. 
Git blame shows that this special flag-matching rule was introduced in 4033929127 in order to make the lookup over the instantiated types sensible to the presence of such a flag **for procedures**.
=> Prevent endless loop in generic instantiation

.travis.yml
EDIT: CI failure un-related since it's appveyor failure and I'm only changing .travis.yml
=> travis:upgrade to xenial (trusty end of life is april 2019)

compiler/semfold.nim
Since tyCString is convertible to a tyPointer we must be extra careful
to emit a cast to (void*) in order to appease clang++.
Reported by masnagam on the Nim forum.
=> Fix codegen problem with strict C++ compilers

.travis.yml
no point in running `./koch runCI` if `nim c koch` fails (avoids a weird looking error when `nim c koch` fails)
=> fix travis: add set -e in script

lib/pure/random.nim
/cc @demotomohiro
> State of xoroshiro128+ must not be 0 or it generates 0 forever.
I ran into this gotcha before: after calling `randomize(0)`, `rand(int)` generates 0 forever; this PR enforces that seed is nonzero to avoid puzzling behavior.
https://github.com/nim-lang/Nim/pull/10546#issuecomment-462204717 added a documentation for the fact that `seed` needs to be nonzero but this PR enforces this with a `doAssert`.
I'm not sure there's any valid use case for `randomize(0)` (which generates constant, non-random data) but if there is one, IMO it'd be better via a different API, eg `initNonRandom()` or another name, otherwise it's error prone (easy to miss this point in docs)
=> randomize: added doAssert(seed!=0) to avoid invalid (non-random) behavior

bin/nim-gdb, build_all.sh, compiler/ast.nim, compiler/ccgexprs.nim, compiler/evaltempl.nim, compiler/pragmas.nim, compiler/semmagic.nim, compiler/semtempl.nim, compiler/suggest.nim, koch.nim, lib/pure/math.nim, testament/specs.nim, tests/concepts/texplain.nim, tests/converter/tgenericconverter2.nim, tests/enum/tenummix.nim, tests/errmsgs/tunknown_named_parameter.nim, tests/generics/trtree.nim, tests/misc/tradix.nim, tests/misc/tsizeof.nim, tests/objects/tobject3.nim, tests/stdlib/tosproc.nim, tests/system/t7894.nim, tests/system/talloc2.nim, tests/types/tfinalobj.nim, tests/vm/tvmops.nim, tests/vm/tzero_extend.nim
My ongoing work to make Nim work on 32 bit Linux. Not everything works yet.
Notes:
* The change in build_all.sh isn't necessary. It was just visual noise to my eyes.
* changes in nim-gdb starter script are made to get better error messages on a system that is not yet set up correctly with gdb and nim on the path, like my initial installation of debian.
* alignof didn't forward to the c backend at all. It just returened -3 when the size was unknown. Now it properly forwards to the C and C++ backend (needs different handling).
* on 32 bits float behaves slightly different so tests with floating point operations need to be more robust to floating point errors.
* some tests related to sizeof have been integrated into tsizeof wher the proper infrastructure for size testing is given. 
* …
=> 32 bit fixes

tests/system/talloc2.nim
in my 32 bit fixes branch I made a hack to talloc2 to disable it on 32 bits before I introduced the feature to the tester specs. I forgot to reverse those changes in that PR, here is the missing part.
This change does not affect any test result, it is just the way, how the test is disabled, that is different.
=> disable talloc2 on 32 bits

compiler/types.nim, nimsuggest/tests/tsug_template.nim
This makes signatures generated for nimsuggest correctly distinguish
template/macro/converter from proc.
=> compiler/types: correctly generates signature for non-proc types

lib/system.nim
deprecated some leftovers that are still there in system.nim from a time when there was no unsigned integer.
Will fix #10560
=> deprecated leftovers from era of no unsigned integer types

doc/tut1.rst, doc/tut2.rst
The issue is, when I got started with Nim, I got confused in the tutorials, as I thought that the object type always had an object overhead, and only the tuple type is the overhead free type. This is of course wrong, but from my experience in the chat with other people, this is not only my problem.
* To fix this issue, I changed the order, so the object type is now introduced before the tuple type.
* The object type is introduced as the default type to encapsulate data.
* The tuple type is introduced as a variant of object, with details on the differences.
* Initially the object type was introduced in the chapter of object oriented programming. This introduction has been stripped out, but the section that initially introduced the object type is still there, but it has been reduced to the …
=> introduce object before tuple

appveyor.yml, testament/categories.nim, testament/important_packages.nim
This adds more nimble packages to our testing. 37 packages are now tested.
Some of the packages have dependencies. For those packages, we first do `nimble install` so the dependencies are installed before we clone the repo and run the tests.
This means that the iterator `listPackages` now returns one more field: `tuple[name, url, cmd: string, hasDeps: bool]`.
Two packages (Arraymancer and Neo) are dependent on BLAS, so OpenBLAS is added to Appveyor environment.
=> add more nimble packages for testing

lib/pure/mimetypes.nim
Return result when found. Sorry for the huge Diff.
**Before:**
- Search a mime.
- Result found.
- Wont return result, keeps iterating the whole `mimedb` for no reason whatsoever.
- Return result.
**After:**
- Search a mime.
- Result found.
- Return result.
:cat:
=> Return result when found on mimetypes

config/nimdoc.cfg
Currently only modules (i.e. `*.nim` files) had links to "Manual", "Standard library" and "Index". Now also documents (i.e. `*.rst` files) have those links at the top of the left column.
=> add links to every document, fixes #5515

koch.nim
* fix #10659 `koch boot` fails on windows with choosenim-installed nim: proxyexe.nim error
* [minor] avoids 1 copy and adding compiler/nim0.exe
=> fix #10659 `koch boot` fails on windows with choosenim-installed nim: proxyexe.nim error

doc/lib.rst, lib/packages/docutils/highlite.nim, lib/packages/docutils/rst.nim, lib/packages/docutils/rstast.nim, lib/packages/docutils/rstgen.nim, nimsuggest/sexp.nim
Until #8164 is properly fixed (i.e. when you'll be able to do `import highlite` instead of `import packages/docutils/highlite`), document the correct way to import those files.
(The same has already been done for `std/sha1`, for example)
=> document proper imports, fixes #8164

lib/pure/osproc.nim, nimsuggest/crashtester.nim, nimsuggest/tester.nim, tests/async/tupcoming_async.nim, tools/vccexe/vcvarsall.nim
Other than more informative docs, fixes typo in the name `poDemon` to `poDaemon`.
=> better docs: osproc

lib/pure/times.nim, tests/stdlib/ttimes.nim
As suggested in #10679, I've implement procs for converting a duration to some specific unit: `inHours`, `inMilliseconds` and so on. The old versions named `hours`, `milliseconds`, etc have been deprecated. I've also deprecated the proc `fractional`, as it mostly existed to justify the stupid behavior of the `milliseconds`/`microseconds`/`nanoseconds` procs. After this PR, the details of how a `Duration` is normalized is just an implementation detail, as all the procs that exposes it have been deprecated. 
I discovered an off-by-one error for the procs `weeks`/`days`/`hours`/`minutes`/`seconds` when used with negative durations, which is also fixed in this PR.
Closes #10679
=> Replace the duration conversion procs with new improved ones

compiler/sigmatch.nim, lib/pure/json.nim, lib/system.nim, tests/range/trange.nim
Introduce the `isIntConv` rule for unsigned types.
Do not allow mixed-signedness conversions between ranges and scalar types.
Let's see what breaks.
=> Tighten the conversion from tyRange to scalar types

compiler/semexprs.nim, tests/errmsgs/tstaticexprnotype.nim, tests/errmsgs/tstaticexprscope.nim
Bring this in line with how plain blocks are analysed and avoids codegen
errors if one references variables defined in such a block.
@mratsim 
WRT #10628, this PR lets you do something like this `let a = static: input(bindSym"x")`
=> Open a new scope for `static:` expr blocks

lib/pure/collections/sets.nim
> currently the constructor for HashSet is not consistent with our conventions. It should be called initHashSet.
Fixes this inconsistency.
=> use `initHashSet` and `toHashSet`, fixes #10730

tools/nim-gdb.py
these changes allow to execute nim, nimble and koch directry from within the gdb command interpreter. These commands have been added to streamline the _edit-compile-debug_ cycle.
This has been done in inspiration of ``make`` that is already available within gdb as a command.
=> add gdb commands: koch, nim, nimble

compiler/docgen.nim, compiler/main.nim
Fixes regression caused by ca4b971bc81b2e751e0388d80896fde7079b1679.
`nim doc foo.nim` will now generates `foo.html` instead of `foo/foo.html`
=> compiler/[main,docgen]: don't put generated doc in subfolder

compiler/commands.nim
=> compiler/commands: keep extension for output file

lib/pure/os.nim
This information can prevent unintentional data loss.
=> Make doku of os.moveFile() more precise.

compiler/ccgmerge.nim, compiler/lexer.nim, compiler/nimlexbase.nim, compiler/vmgen.nim, lib/packages/docutils/rst.nim, lib/pure/lexbase.nim, lib/pure/parsecfg.nim, lib/pure/parsecsv.nim, lib/pure/parsejson.nim, lib/pure/parsesql.nim, lib/pure/parsexml.nim, lib/pure/pegs.nim, lib/pure/streams.nim, nimsuggest/sexp.nim, tests/stdlib/tjsonmacro.nim
enable parsing of json at compile time (without even touching the json module). The implementation is done and locally it works, it just needs a test.
minor side effects:
* kill ``chrSize`` constant. It is always 1.
* kill a few ``when defined(js)`` branches (simpler code)
* support down casting in the vm (``nkObjUpConv`` ¯\\\_(ツ)\_/¯)
* the stream interface has one more proc: ``proc readDataStr*(s: Stream, buffer: var string, slice: Slice[int]): int``. This is needed because I could not find a way to implement the pointer based interface on the vm.
* the pattern ``var buf = arg.buf`` to put the buffer of the parser into a local variable is now slow (breaking performance change).
* parsers have been refactored to not use ``var buf = arg.buf`` anymore (js target will benefit from this).
* …
=> StringStream and parseJson in vm

lib/core/macros.nim
Unfortunately, I don't have a simple test case that demonstrates the issue, but it's easy to explain.
Notice how some of the `newLit` overloads are both generic and recursive. When you instantiate the overload for `object` for example, this may also instantiate the overload for `seq` (because a `seq` can appear as field inside an object). But notice how the opposite is also true (a `seq` will often contain objects). This leads to a compilation errors when `newLit` is used with certain complicated types. I've discovered the issue during the development of our [confutils library](https://github.com/status-im/nim-confutils).
Luckily, the the issue is easy to fix with the forward declarations I'm adding here.
=> Prevent certain compilation errors with `macros.newLit`

lib/pure/htmlparser.nim
Not sure if this is necessary, but I think it is better to have the identifiers in examples match the actual identifiers used in the source instead of something that works but doesn't exactly match
(If this gets rejected, I'll get the message and not propose these kind of changes in the future).
=> Matching actual proc name

compiler/extccomp.nim
`conf.nimcacheDir` might be empty during build, which results in the
json build instructions being generated in the current directory. This
commit fixes the problem by using `getNimcacheDir`, which generates a
valid `nimcacheDir` should it be empty.
Fixes #10768
/cc @zah: This regression was introduced by ca4b971bc81b2e751e0388d80896fde7079b1679.
I suspect that there are more places in the compiler where the same
issue might apply.
=> compiler/extccomp: use getNimcacheDir for writing build instruction

compiler/astalgo.nim
Since the ``debug`` proc is the default way for me to inspect nodes in the compiler for my debugging work, I was very frustrated with how unintuitive and inconsisted it printed out the information. So I put some effort to redesign it. The output should be understandable for someone who did not write the debug proc and does not have a lot of knowledge to use the ast.
* Indentation is now properly fixed. Children are now always indented more than the parent.
* consistently json (except where it can't)
* vertical and horizontal space is used efficient.
* no recursion depth limit anymore
* relative line numbers on detected cycles
Last but not least, the code is now written in a consistent style so that it should be easy to modify it for custom needs. There is no one size fits all debug proc, …
=> More depth debug proc

lib/pure/bitops.nim
Shouldn't testing bit require only immutable access? I think this is a typo
=> Remove var

lib/pure/osproc.nim
The doc states "Make sure to pass options explicitly.", but the example didn't. 
Since constructing a string for the shell with appropriate quotes is non-trivial, the first example should be how to use `execProcess`  including `args`
=> Follow the documentation's recommendation

compiler/docgen.nim, config/nimdoc.cfg, lib/pure/asynchttpserver.nim, nimdoc/testproject/expected/subdir/subdir_b/utils.html, nimdoc/testproject/expected/testproject.html, nimdoc/testproject/expected/theindex.html
* exports are the least important field in the docs:
they are put in the last place (at the bottom)
* indent text after proc/type declaration for an easier navigation
(noticeable difference between declarations and examples)
* quickfix invalid style in `asynchttpserver`
=> documentation style tweaks

compiler/astalgo.nim, compiler/semexprs.nim, compiler/semmagic.nim, compiler/sempass2.nim, compiler/transf.nim, tests/macros/tmacrostmt.nim
magic call to `mAddr` is now preserved till transformation stage where it is rewritten into `nkHiddenAddr`.
It is now possible to delete `nkAddr` node kind completely, let me know if you are interested in this kind of breaking change.
=> fixes  #10807

lib/pure/bitops.nim, tests/stdlib/tbitops.nim
``reverseBits`` can be implemented shorter like following code.
But it is about x10 slower when T is uint64.
```nim
proc reverseBits2*[T: SomeUnsignedInt](x: T): T {.noSideEffect.} =
const nbits = sizeof(T) * 8
result = 0
for i in 0..<nbits:
result = result or (((x shr i) and 1) shl ((nbits - 1) - i))
```
=> bitops: add reverseBits and test

lib/system/dyncalls.nim, lib/system/excpt.nim
In Windows, a HWND is a HANDLE which is a PVOID so a pointer in Nim: [source](https://docs.microsoft.com/en-us/windows/desktop/winprog/windows-data-types)
Otherwise, the MSVC compiler will complain:
```
nim\lib\system\excpt.nim(35): warning C4047: 'function': 'HWND' differs in levels of indirection from 'int'
nim\lib\system\excpt.nim(35): warning C4024: 'MessageBoxA': different types for formal and actual parameter 1
nim\lib\system\dyncalls.nim(33): warning C4047: 'function': 'HWND' differs in levels of indirection from 'int'
nim\lib\system\dyncalls.nim(33): warning C4024: 'MessageBoxA': different types for formal and actual parameter 1
```
=> Make HWND a pointer instead of a cint and fix MSVC compiler warning

lib/pure/net.nim, tests/untestable/network/README.md, tests/untestable/network/stdlib/tnet.nim
Finds the local IP address used to reach an external address.  No traffic is sent.
Supports IPv4 and v6. Raises OSError if external networking is not set up.
Works cross-plaftorm.
=> Detect local "egress" IP address

compiler/parser.nim, tests/proc/tfunc_type.nim
The node `nkFuncTy` does not exist hence it can be used here. As far as I got, it is intentional not to have `nkFuncTy`. The solution is to add `{.noSideEffect.}` pragma in this case.
=> fixes #10838

compiler/docgen.nim
Nightlies have been failing due to an issue with `:test:` in `code-block`.
On Windows, it fails because the import path contains `\`.
```nim
import "C:\Users\gt\Desktop\DL\programming\nimdevel\lib\pure\htmlparser.nim"
```
`htmlparsers.nim` is the only one using `:test:` since the last commit.
=> Snippet fix

config/nimdoc.cfg, nimdoc/testproject/expected/subdir/subdir_b/utils.html, nimdoc/testproject/expected/testproject.html, nimdoc/testproject/expected/theindex.html
The explicit style on the span.attachedType used in the toc was
removed. The included style sheet extended for this tag+class
with both the original visibility:hidden as well as display:none
to solve the issue.
Expected output files were update to reflect this change.
=> fixes #10857 invisible span had width

compiler/renderer.nim
Types which have pragmas have the following AST so it is necessary to break the first son in two parts:
```
TypeSection
TypeDef
PragmaExpr
Postfix
Ident "*"
Ident "Foo"
Pragma
Ident "bycopy"
GenericParams
IdentDefs
Ident "T"
Ident "U"
Empty
Empty
ObjectTy
Empty
Empty
RecList
IdentDefs
Ident "x"
Ident "int"
Empty
```
=> docgen: generate pragma after generic, fixes #10792

compiler/vmdef.nim
Updated to the latest Nim and started to hit this limit.  No changes in macros.
I couldn't find any regressions. Our macros analyse the full function call tree all the way to magic primitives, looks like internals of stdlib became more complicated hence deeper levels of recursion are required for our macros.
=> increase VM limit

changelog.md, compiler/ccgstmts.nim, lib/system.nim
Following our discussion on IRC, this adds an overload with parallel `countup` functionality using OpenMP.
Unfortunately testing OpenMP is tricky due to:
- non-deterministic behaviour
- stacktraces/string allocation in OpenMP threads will crash the program
Though we can probably test that the serial version compiles and gives the proper output, we just need to not pass `--passC:-fopenmp --passL:-fopenmp` to the compiler.
Example program:
```Nim
const str = [
"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"
]
for i in `||`(0, 9):
echo str[i]
for i in `||`(0, 9, 3):
echo str[i]
```
Compile with
```
../Nim/bin/nim c -r -d:release --passC:-fopenmp --passL:-fopenmp -o:build/omp_block build/omp_block.nim
```
C code
```C
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
NI i;
NI i_2; …
```
=> Add OpenMP overload with stepping

compiler/ccgcalls.nim, compiler/cgen.nim, compiler/commands.nim, compiler/extccomp.nim, lib/nimhcr.nim, lib/system/timers.nim, tests/dll/nimhcr_integration.nim
there are 3 things in this PR:
- within a module the "_actual" functions are called directly instead of going through an indirection through a function pointer & a trampoline - this increases runtime performance by at least 20% or much more - depending on the software/platform
- dynamically linking to the Visual Studio runtime so each .dll for each module does not contain a statically linked runtime - .pdb files drop in size from 6mb to 300kb and the .dll files drop significantly to well below 100kb as well
- fixed a bug with the output directories for the .dll files when HCR is on
=> improvements on the hot code reloading support

lib/nimbase.h
Typedef is unused per Araq. Will see how CI reacts to removal.
=> Fix #10907 - remove unused typedef string

appveyor.yml
Testing packages sometimes randomly fails because of some
reason not connected to Nim (e.g. github is down).
Currently, that would prevent "regular" appveyor tests
from running.
Changing the order will allow "regular tests" to run
regardless of the outside problems with packages.
=> change the order of appveyor tests

compiler/semexprs.nim
fixes https://github.com/nim-lang/Nim/issues/10890
the checkMinSonsLen was a leftover from this PR here: https://github.com/nim-lang/Nim/pull/9354/files. It turns out the generic solution provides much better error messages. No new test case necessary as I think it's not worth it.
=> remove check for better error message

lib/pure/md5.nim
This was caught (indirectly) by multithreaded tests.
=> md5: add missing .gcsafe. to the forward declarations

compiler/cgen.nim, tests/cpp/tretvar.nim
I managed to fix it without fully reverting 0cc6e124254a2222e04d1226fe9c362d20f38cd5.
Just light increase in single use scope for cpp imported procs not just constructors.
=> fixes cpp codegen regression #10948

compiler/ccgcalls.nim, compiler/ccgtypes.nim, compiler/cgen.nim, compiler/parampatterns.nim, tests/types/tlent_var.nim
adds support for unsafeAddr for `lent T` returned type.
fixes #10942 by passing by reference object and tuples if `lent T` is returned
=> fixes #10942. Lent T bug

compiler/commands.nim
In my opinion ``--debugger:native`` is too verbose. I need it frequently. ``-g`` doesn't really make any sense to me either, but that is the name that gcc uses and I already remembered it.
=> add alias for --debugger:native

compiler/semstmts.nim, tests/types/tinheritref.nim
fix for #10721 
This fix is tiny. But in my opinion this is code smell. Why does sfPure nead spcial treatment? Do other flags need this treatment as well?
=> Pure ref object

nimpretty/nimpretty.nim
Although `nimpretty --help` says `--indent:N[=2]`, the default value of indent was 0.
I thought implementation is wrong, so I set the default value of `opt.indWidth` to 2.
As a side effect, #9811 is fixed.
The bug is because `getIndentWidth` in `compiler/layouter.nim` is called whenever `--indent=N` option is not set.
=> fixes #9811

compiler/parser.nim
Now the warning is raised only in the cases when there is an
inconsistency in the style (spacing vs no spacing):
* `if a>_b`      --> warning
* `if a_>___b`   --> no warning
=> relax warning about inconsistent spacing

changelog.md, lib/pure/strformat.nim, lib/pure/times.nim, tests/stdlib/genericstrformat.nim, tests/stdlib/tstrformat.nim, tests/stdlib/tstrformatMissingFormatValue.nim
* ``strformat.format`` is renamed to ``strformat.formatValue``, so it does not clash with ``strutils.format``.
* The (in my opinion complicated and weird logic) in the ``callFormat`` templates is removed entirely. ``formatValue`` has to follow the interface ``formatValue*(value: T; specifier: string; res: var string)``. Hacks to support alternative interfaces are removed.
* Libraries can overload ``formatValue`` to enable custom types within to be used in the ``&`` macro.
* Libraries have full control over the meaning of the ``specifier`` string for their own types. 
* The changes above enable an implementation for the ``nim_glm`` types to be used in the ``&`` macro.
* fixes https://github.com/nim-lang/Nim/issues/7632
* the macro ``&`` is moved below the definition of ``formatValue``, so …
=> Strformat symbol binding

changelog.md, lib/std/sha1.nim
Enough said?  I needed to hash just a sub-range of a `MemFile` via `toOpenArray[char]`, but other slice contexts can presumably benefit from this, too.
=> Make `secureHash` accept any `openArray[char]`, not only `string`.

lib/pure/random.nim
The examples from #7698 now work:
```nim
import random
let cslice = '0'..'F'
let r = rand(cslice)
type
Op = enum
Halt
Inc
Dec
let opslice = Halt..Dec
let op = rand(opslice)
```
=> random: works for slices and enums, fixes #7689

lib/core/macros.nim
`macros.newIfStmt` segfaults on empty/invalid input. Makes it an error message instead.
=> Add len check for newIfStmt to avoid segfault

lib/pure/collections/tables.nim, tests/collections/ttables.nim
As long as we are importing algorithm, it seemed reasonable to let the user override the sort order without redefining cmp.  The defaults have not changed.  I'd like to add a test or two for this functionality, but first...
Attempts to modify a CountTable after a sort() don't go well.  In my experiment, with many items, my program appeared to hang.  What about adding an `unsafe` boolean or similar and raising a runtime error in the event of a misbehaving mutate?
=> faster CountTable sort(), optional SortOrder

compiler/lineinfos.nim, compiler/semstmts.nim, doc/nimc.rst, tests/ccgbugs/twrong_setconstr.nim, tests/sets/tsets.nim
This removes warnings about the shadowed identifier (including `var result` inside of a template), but keeps the warning about shadowed `result` in procs.
=> remove shadow warning, fixes #10732

compiler/semtempl.nim
whenever "stackTrace" is in the stack trace, it's lineinfo was not helpful.
=> callsite lineinfe for stackTrace template

compiler/sigmatch.nim, tests/ccgbugs/t5701.nim
Simply a missing injection of ``nkHiddenStdConv`` for varargs. There are probably other problems with varargs yet that have been solved for normal parameter passing already, simply because varargs doesn't share the code with normal parameter passing.
=> Fix varargs int32

compiler/ccgcalls.nim, compiler/ccgexprs.nim, compiler/ccgstmts.nim, compiler/ccgtypes.nim, compiler/cgen.nim, compiler/docgen.nim, compiler/jsgen.nim, compiler/nim.cfg, compiler/ropes.nim
This PR doesn't implement any optimizations yet. All it does is, it sets the constraint for `%` in ropes to have a compile time format argument. All these changes are the changes to make the compile time argument passing possible.
=> fewer ropes

lib/impure/nre.nim, lib/pure/asyncdispatch.nim
These are the only two modules with imports above documentation, which breaks nimsuggest's documentation display.
=> Documentation import fixes

lib/impure/db_mysql.nim, lib/impure/db_odbc.nim, lib/impure/db_postgres.nim, lib/impure/db_sqlite.nim, lib/js/asyncjs.nim, lib/pure/asyncdispatch.nim, lib/pure/asyncftpclient.nim, lib/pure/asynchttpserver.nim, lib/pure/asyncmacro.nim, lib/pure/asyncnet.nim, lib/pure/base64.nim, lib/pure/dynlib.nim, lib/pure/htmlgen.nim, lib/pure/parsecfg.nim, lib/pure/times.nim, lib/pure/unittest.nim, lib/system/threads.nim
While writing an rst-to-org converter for the Nim docs I found some modules which use `-` for headers and `~` or `=` for subheaders (and even `^`, though only two instances in the entire library), which was inconsistent with how it's done in the majority of modules and the manuals. Also fixed a few other inconsistencies regarding example sections and a couple async modules which still have their module names as the top section.
=> Fix header inconsistencies in documentation

lib/pure/collections/tables.nim
It didn't match with the corresponding section in the manual.
Edit: gah I forget that [ci skip] exists; sorry about that
=> tables: fix link

doc/docgen.rst, doc/manual.rst
Flag docSeeSrcUrl as deprecated.
Add quick start paragraph.
Add links from the language manual.
=> Update docs around docSeeSrcUrl #6071

lib/pure/times.nim
I discovered that the `times.nanoseconds` proc only had a deprecation doc comment and not the pragma, so I added the pragma.
=> Add missing `deprecated` pragma

lib/pure/collections/sequtils.nim, lib/system.nim
A very simple, very tiny addition, but this PR adds a little bit of code to system.nim that I've always found to be helpful:
```Nim
iterator items*[T](xs: iterator: T): T =
for x in xs():
yield x
```
All it does is iterate over the items yielded by a closure iterator. This sounds redundant and stupid, but it allows the `mapIt`, `allIt`, `filterIt`, etc. templates in sequtils to be used with closure iterators
I was originally going to put this snippet in sequtils, since AFAIK the only time it's helpful is with the sequtils templates, but found that the other `items` implementations are all in system.nim, so I figured I'd keep that consistent.
=> Add items() over closure iterator

compiler/vmgen.nim
See #11111, cc @cooldome.
This fix a corner case where nkIdentDefs can be left in the AST at the codegen stage.
Unfortunately I don't have a small testcase, I'm also not sure what the difference between ast and astdef is.
=> Fix #11111 nkIdentsDef left in vmgen

compiler/sighashes.nim
silly bug fixed. bug appeared when code was moved from separate file from sighashes.nim and sighashes contained a proc with the same name
=> symBodyHash bug fix

changelog.md, lib/pure/collections/hashcommon.nim, lib/pure/collections/setimpl.nim, lib/pure/collections/sets.nim, lib/pure/collections/sharedtables.nim, lib/pure/collections/tableimpl.nim, lib/pure/collections/tables.nim, testament/tester.nim
A lot of code has been moved around so the diff looks bigger than it really is.
* hashcommon.nim (this is a new file):
* `template rawGetKnownHCImpl` 
* setimpl.nim (this is a new file): 
* `template initImpl`
* `template rawInsertImpl`
* `template inclImpl`
* sets.nim:
* `proc isValid` is now deprecated
* tableimpl.nim:
* `template maybeRehashPutImpl`
* `template initImpl`
* `template insertImpl`
=> Initialized collections

compiler/jsgen.nim
fix for #11133
given (invalid) jscomp.nim and (valid) jscomp2.nim:
```nim
proc test() {.compileTime.} =
echo "can only be called at compile time?"
test()
```
```nim
proc test() {.compileTime.} =
echo "can only be called at compile time?"
const x = block:
test()
42
echo "ok"
```
Nim compiles the invalid code without complaint, and then JS dies at runtime:
```
$ nim js --run jscomp.nim
Hint: used config file '/usr/local/Cellar/nim/0.19.4/nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: jscomp [Processing]
Hint: operation successful (5883 lines compiled; 0.037 sec total; 4.547MiB peakmem; Debug Build) [SuccessX]
Hint: /usr/local/bin/../Cellar/node/11.14.0_1/bin/node /Users/jfondren/nim/learn/nimcache/jscomp.js  [Exec]
/Users/jfondren/nim/learn/nimcache/jscomp.js:28
test_25003();
^ …
```
=> fix #11133, error on runtime use of compile-time procs in JS target

lib/pure/random.nim
The proc description is unchanged because the code is almost verbatim of the current description. This is one possible fix. Other ideas: Make another proc with just signature `T: range`. When T is range, error out with a suggestion to use the `HSlice` rand instead. Also: Is there anywhere I should add tests?
=> Fix unexpected result of rand on a range #11015

compiler/semstmts.nim
Fixes #7470
`discard typeof(1)` is an error, implying `discard int` should be too.
=> Discarding a type is an error

lib/pure/includes/osenv.nim, lib/pure/includes/oserr.nim
Fixes error on devel on `import ospaths`.
`nimdevel\lib\pure\includes\oserr.nim(4, 10) Error: This is an include file for os.nim!`
=> Fix ospaths import error

lib/system.nim, tests/iter/tcountup.nim
fix #11099 
The `..<` iterator did not have the same overloads as the `..` iterator. Then the generic template ``..<`` was expanded which eventually caused the bug.
* The generic `..<` template is now restricted to not match the general untyped ast anymore.
* Provide the exact same overloads to `..<` as `..`.
=> Fix ..< iterator

compiler/injectdestructors.nim, compiler/liftdestructors.nim, compiler/sighashes.nim, tests/destructor/topt.nim
Fixes destructor regressions I have encountered in the last 2 weeks.
One was related to generic distinct: for destructor lifting we allow distinct types to ahve its own destructor, hence hash needs to be different. But it is not enough to hash distinct sym if type instantiation is involved.
Other one: destructor was not found because it was tyAlias, tyGenericInst away.
=> Destructor lifting fixes #11149

compiler/docgen.nim
Fixes https://github.com/nim-lang/Nim/issues/10687
=> Fix `nim doc` ignoring doc comments with implicit returns and implicit conversions

lib/pure/collections/tables.nim
This is similar to `items` iterator for strings and seqs.
=> tables: check for mutation when iterating

lib/system/iterators.nim, tests/ccgbugs/twrong_tupleconv.nim, tests/destructor/twidgets.nim
* fix pairs, mpairs, mitems for cstring for JS backend
* add mutation check for pairs and mpairs for strings and seqs
* change the assertion message - modifying (changing elements) is not
a problem, changing the length is
=> iterators: several small fixes

build_all.sh
This allows running things such as `./build_all.sh --cpu i386` instead of manually having to run `./csources/build.sh --cpu i386` and continuing to manually run the rest of `build_all.sh`.
=> Pass command line arguments from build_all.sh to build.sh

lib/pure/random.nim
Fix #11198 while preserving  #10998 fix for https://github.com/nim-lang/Nim/issues/7698
=> Reallow float ranges in random module

lib/pure/unidecode/unidecode.nim
The existing example doesn't actually have the intended output:
```
nim> echo unidecode("\x53\x17\x4E\xB0")
SNdeg
nim> echo unidecode("\xe5\x8c\x97\xe4\xba\xac")
Bei Jing
```
moreover, it's misrendered in the HTML as `unidecode("x53x17x4ExB0")` with backlashes stripped.
When replaced with the Chinese, the produced HTML looks good and it actually unidecods into "Bei Jing" as intended.
=> (docs) fix unidecode.unidecode example input string

lib/pure/asyncdispatch.nim, lib/pure/asyncfutures.nim, lib/system/excpt.nim
This is incredibly useful for figuring out possible leaks caused by stuck async procs/futures.
Here is an example from my server during a leak: 
You can see some counts at 6k+. Normally they are all 0 or `1`. I will also be adding support for this in my prometheus package which will make analysing this an absolute dream
=> Implements pending future tracking in async.

doc/manual.rst
Just a typo I found while reading this part of the manual...
`[ci skip]` is used since this code isn't tested (there is no `:test:` role before it) because it is most likely pseudo-code, based on the algorithms prior to this one.
=> manual: fix typo in inImplicitlyConvertible

lib/system/repr.nim
Not a big deal, but adding the at sign might be a bit less surprising output. Arrays are `[]`, seqs are `@[]`
=> repr on seq now outputs @[]

compiler/ast.nim, compiler/ccgexprs.nim, compiler/ccgtypes.nim, compiler/cgmeth.nim, compiler/evalffi.nim, compiler/jsgen.nim, compiler/liftdestructors.nim, compiler/lowerings.nim, compiler/patterns.nim, compiler/plugins/locals.nim, compiler/sem.nim, compiler/semdata.nim, compiler/semexprs.nim, compiler/semstmts.nim, compiler/semtempl.nim, compiler/semtypes.nim, compiler/sigmatch.nim, compiler/suggest.nim, compiler/types.nim, compiler/vmdeps.nim, compiler/vmgen.nim, lib/system/hti.nim
I don't know why this hasn't been done before. I enconter tyExpr and tyStmt and it recularly confuses me which one of them is untyped and which one is typed. This gets rid of the legacy once and for all.
=> rename tyExpr/tyStmt to tyUntyped/tyTyped

compiler/cgen.nim, compiler/injectdestructors.nim, compiler/modulegraphs.nim, tests/destructor/objFile.nim, tests/destructor/texplicit_move.nim, tests/destructor/tglobaldestructor.nim, tests/destructor/topt.nim
Fixes #9799
Refs #11217
I consider this a WIP as
- I don't know if this should really belong in ModuleGraph or in myClose
- ~generated temporaries for globals leak into topLevelVars such as in https://github.com/nim-lang/Nim/blob/devel/tests/ccgbugs/tsequence_outoforder.nim and thus only get destroyed at the end of the mainModule or cause generating invalid C. EDIT: This also the reason the tests currently fail...~
EDIT: Fixed!
- It is not yet implemented for the other backends
=> Fix destructor injections for global variables

compiler/cgen.nim, tests/compiler/tcppCompileToNamespace.nim
There was not a single test case for ``cppCompileToNamespace`` in the entire test suite. How was this accepted into Nim? And btw `ccodeCheck` can't be used to ensure that ``cppCompileToNamespace`` generates the correct code, because it only works with C and javascript?!
Anyway, this should fix #11194
=> fix #11194

lib/wrappers/postgres.nim
Expose `PQinitOpenSSL` so we can disable libpq from initializing OpenSSL if it's already done by someone else.  Will help to address some problems in #9419.
=> Expose api to disable autoinitializing OpenSSL.

lib/system/atomics.nim
"New code should always use the ‘__atomic’ builtins rather than the ‘__sync’ builtins." - https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html
=> cas(): use an "__atomic" builtin instead of the legacy "__sync" one

lib/pure/collections/tables.nim
I don't have time to dig into the compiler to fix this, so I'm offering this quick fix in case it's useful.
TL;DR: e1515b53d1992aa8 breaks JS target because the Nim compiler outputs a function call which does not exist for the `move` (odd that the Nim compiler didn't complain about this function not existing...)
=> Workaround "move not found" exception in JS when using tables.

lib/impure/nre.nim, lib/impure/re.nim
Use the same PCRE function for freeing up the memory as nre.nim does.
=> fix #11139 (re.nim memory leak)

lib/impure/db_sqlite.nim
Updated documentation for db_sqlite module.
- See also links
- Example codes
db_sqlite is impure module and need to be installed sqlite3.
Therefore I wrote example codes by `code-block` documentation comment, not `runnableExamples`.
My english is not perfect.
Please fix or tell me if english sentence was wrong.
ref #10330
=> db_sqlite: Update documentation (#10330)

compiler/semexprs.nim, compiler/semstmts.nim, tests/iter/treciter.nim
Instead of
```
t.nim(6, 18) Error: recursive dependency: 'all'
```
the message is now a bit more informative:
```
t.nim(6, 18) Error: recursion is not supported in iterators: 'all'
```
=> More specific error message for unsupported recursion in iterators

lib/pure/times.nim
```
proc getDateStr*(dt = now()): string {.rtl, extern: "nt$1", tags: [TimeEffect].} =
runnableExamples:
echo getDateStr(now() - 1.months)
result = $dt.year & '-' & intToStr(ord(dt.month), 2) &
'-' & intToStr(dt.monthday, 2)
proc getClockStr*(dt = now()): string {.rtl, extern: "nt$1", tags: [TimeEffect].} =
runnableExamples:
echo getClockStr(now() - 1.hours)
result = intToStr(dt.hour, 2) & ':' & intToStr(dt.minute, 2) &
':' & intToStr(dt.second, 2)
```
=> getDateStr and getClockStr takes a default now() parameter so that it would be easier for getting a date or clock string nearby.

compiler/idents.nim, lib/pure/hashes.nim
* multibyte hashing for:
* string and string slices
* cstring
* string, ignoring case
* string, ignoring style
* openArray of byte or char
=> faster hashing

changelog.md, compiler/extccomp.nim, compiler/sem.nim, compiler/semexprs.nim, compiler/semstmts.nim, compiler/semtempl.nim, compiler/semtypes.nim, compiler/vm.nim, lib/core/macros.nim, lib/pure/pegs.nim, lib/system/assertions.nim, nimsuggest/tests/tsug_template.nim, tests/ccgbugs/tnocodegen_for_compiletime.nim, tests/fields/tfields.nim, tests/lookups/test.nim, tests/macros/tcomplexecho.nim, tests/macros/tgettypeinst.nim, tests/macros/tmacro5.nim, tests/macros/tmacro6.nim, tests/macros/tmacrostmt.nim, tests/metatype/tmetatype_issues.nim, tests/template/template_various.nim, tests/vm/texcl.nim, tests/vm/tstaticprintseq.nim, tests/vm/ttouintconv.nim
This PR aims to clean up some leftovers from the expr/stmt distinction. ``stmt`` has been renamed to ``typed``, but it still means "statement", so basically an expression of type void. But I don't think that the name really makes a lot of senes here. I have decided to actually use the type void here from now on, because that is what is used everywhere else in the compiler as well.
* ``macro foo() = ...`` and ``macro foo(): void = ...`` is now allowed. It doesn't mean that the macro has no result, it means that the macro generates an expression of type ``void`` (a statement).
* ``macro foo(): typed = ...`` triggers now a deprecation warning. You should use ``void`` or no return type declaration at all, as has the exact same semantic meaning of ``typed`` until now.
* As macros now use the …
=> Allow void macro result

changelog.md, lib/system.nim
Don't let `addQuoted` use now-deprecated `add` for ints and floats (see PR #11292).
Add changelog entry about this deprecation.
=> finish #11292: fix `addQuoted` and add changelog entry

.travis.yml
- Use Travis `homebrew` addon instead of installing by hand. This skips the `update` phase that took a lot of time (300s+).
- Parallelize csources building, which shaved half the build time (42s -> 20s) for OSX, doesn't seem to affect Linux.
=> travis: minor opimizations

compiler/commands.nim, compiler/extccomp.nim, compiler/platform.nim
More helpful then having to look in the source:
```
command line(1, 2) Error: unknown CPU: 'amd6'. Available options are: i386, m68k, alpha, powerpc, 
powerpc64, powerpc64el, sparc, vm, ia64, amd64, mips, mipsel, arm, arm64, js, nimvm, avr, msp430, 
sparc64, mips64, mips64el, riscv64, wasm32
```
```
command line(1, 2) Error: unknown OS: 'wndows'. Available options are: DOS, Windows, OS2, Linux, 
MorphOS, SkyOS, Solaris, Irix, NetBSD, FreeBSD, OpenBSD, DragonFly, AIX, PalmOS, QNX, Amiga, 
Atari, Netware, MacOS, MacOSX, Haiku, Android, VxWorks, Genode, JS, NimVM, Standalone, 
NintendoSwitch
```
```
command line(1, 2) Error: unknown C compiler: 'help'. Available options are: gcc, switch_gcc,
llvm_gcc, clang, lcc, bcc, dmc, wcc, vcc, tcc, pcc, ucc, icl, icc, clang_cl
```
=> list available options for --cpu: or --os: if the passed option is not found

changelog.md, compiler/ccgexprs.nim, compiler/lexer.nim, lib/pure/bitops.nim, tests/misc/tsizeof3.nim
It was disabled intentionally 7 years ago (https://github.com/nim-lang/Nim/commit/840e5f34efa77afa4eed5233172c8a2c16c6d456), but maybe it's time to give it another try.
Fixes #11311
=> Enable range checking for unsigned integers

lib/system.nim, tests/manyloc/standalone/barebone.nim
Unconditionally enabled operators `[]` and `[]=` for strings. I don't see much sense in disabling just those operators, since there still remain seq counterparts, and they "require" GC just as well.
=> Fixed #9762

compiler/ast.nim, compiler/astalgo.nim, compiler/condsyms.nim, compiler/evaltempl.nim, compiler/pragmas.nim, compiler/sem.nim, compiler/semexprs.nim, compiler/vm.nim, compiler/vmgen.nim, lib/system.nim, lib/system/alloc.nim, lib/system/inclrtl.nim, tests/macros/macro_bug.nim, tests/macros/tsame_name_497.nim, tests/misc/thallo.nim, tests/objects/toop1.nim, tests/parser/toprprec.nim, tests/template/template_various.nim, tests/template/ttempl2.nim, tests/template/ttempl3.nim, tests/template/twrongmapit.nim, tests/template/utemplates.nim
Immediate templates and macros are deprecated for years now. This PR removes them.
=> Remove immediate pragma

.travis.yml, koch.nim, tests/errmsgs/twrong_at_operator.nim, tests/gc/closureleak.nim
~~Currently 32-bit Linux doesn't bootstrap. I don't know if it's my fault or `devel` got a regression.~~
**EDIT:** Tested with a known good config, this is a `devel` regression caused by 3a06022071d3ecf62c8e2f4812062e2e2fe71954
Bonus goodies:
- `after_failure` is now triggered correctly and will print out a nice summary of failed tests.
/cc @Araq
=> travis: cleanup & add 32-bit Linux testing

lib/pure/net.nim
Currently the net module doesn't compile when the ``--taintMode:on`` flag is passed to the compiler. Not well tested, I've only tried it by patching my local stdlib files.
=> Make net module compile with --taintMode:on

compiler/installer.ini, tools/niminst/buildsh.nimf
Nim currently fails to build on Debian/sparc64. The two changes in this PR should fix that.
=> Add build support for Linux/sparc64

compiler/installer.ini, tools/niminst/buildsh.nimf
Nim currently fails to build on Debian/m68k. The two changes in this PR should fix that.
Note: This PR will need to be rebased once #11365 has been merged.
=> Add build support for Linux/m68k

compiler/ccgstmts.nim, compiler/lineinfos.nim
The fix for #1286 is only detectable at runtime. This PR warns the user at compile time.
https://irclogs.nim-lang.org/01-06-2019.html#20:47:18
=> Warn about object case transitions at compile time

lib/pure/collections/sets.nim
This pull request fixes A ∖ B being displayed as A B instead, and also fixes a few typos.
=> sets: minor documentation fixes [ci skip]

compiler/installer.ini, tools/niminst/buildsh.nimf
Nim currently fails to build on Debian/alpha. The two changes in this PR should fix that.
=> Add build support for Linux/alpha

lib/posix/posix_other.nim, lib/system/platforms.nim
This PR contains two additional changes currently missing for sparc64.
For one, adding sparc64 as a platform to lib/system and secondly, defining SO_REUSEPORT to match the kernel ABI on sparc64.
=> Additional platform definitions for sparc64

tools/niminst/buildsh.nimf, tools/niminst/makefile.nimf
LD is used to specify the linker (in most cases, `ld`). However, Nim
wants the C compiler for linking, so we switch this to CCLD instead,
which should lighten the burden on confused packagers.
=> niminst: get rid of LINKER / LD

config/nim.cfg
Add compiler for arm64 and riscv64, remove path to compiler binaries.
=> Genode compiler configuration for arm64 and riscv64

lib/system/threads.nim
When creating a thread in a thread like in this code example:
```Nim
import os
proc threadInThreadProc() {.thread.}=
echo("Hello from thread in a thread.")
proc threadProc() {.thread.} =
var thread: Thread[void]
createThread(thread, threadInThreadProc)
thread.joinThread()
when isMainModule:
var thread: Thread[void]
createThread(thread, threadProc)
thread.joinThread()
```
The expected behaviour/output should be:
```
Hello from thread in a thread.
```
But it fails with:
```
/opt/Nim/lib/system/threads.nim(145, 6) Warning: 'threadProcWrapStackFrame' is not GC-safe as it accesses 'p' which is a global using GC'ed memory [GcUnsafe2]
/opt/Nim/lib/system/threads.nim(186, 8) Warning: 'threadProcWrapper' is not GC-safe as it calls 'threadProcWrapStackFrame' [GcUnsafe2] …
```
=> Fixed "is not GC-safe as it calls 'createThread'" when creating a thread in a thread

lib/nimbase.h, lib/system.nim
From a grep of my `usr/include` its defined elsewhere in a couple libs. An undef in the lib header could be used instead, but renaming comes at little cost and avoids possible friction with wrappers.
=> rename (un)likely macros

changelog.md, compiler/semobjconstr.nim, tests/objvariant/trt_discrim.nim
Immutable parameters should be fine for runtime discriminator construction.
=> parameter runtime discriminators

lib/core/typeinfo.nim, lib/pure/marshal.nim, lib/pure/parsecfg.nim
Removes old style case object transitions I could find in the stdlib.
fixes #11395
=> stdlib case transitions

changelog.md, compiler/semstmts.nim, compiler/semtypes.nim, compiler/vm.nim, doc/manual.rst, tests/metatype/ttypeselectors.nim
superseeds https://github.com/nim-lang/Nim/pull/11393
implements this RFC: https://github.com/nim-lang/RFCs/issues/148
=> pass typedesc as NimNode to macros

compiler/vm.nim, lib/core/macros.nim, tests/coroutines/titerators.nim, tests/macros/tmacro1.nim
Getting the value from a statically known enum value should be simple.
https://github.com/nim-lang/Nim/issues/6785#issuecomment-497202951
=> intVal works now on enum field symbols

lib/pure/strscans.nim
Amend two typos in the documentation of strscans library:
- `a ^* b` instead of `a ^+ b`.
- Remove hyphen from `$w` ASCII identifier `[A-Z-a-z_][A-Za-z_0-9]*`
(matching `IdentStartChars` definition in parseutils).
See my comments in:
- https://forum.nim-lang.org/t/4906#30712
=> Fix strscans Docs

.gitignore
Add to `.gitignore` rule for `/tools/dochack/dochack.js`.
After building locally Nim and running `koch docs`, the `dochack.js`
file was showing up in Git working tree as a new untracked file.
Closes #11374.
=> Ignore dochack.js

lib/system.nim, lib/system/io.nim.cfg
Fixes https://github.com/nim-lang/Nim/issues/10800
The code which has been deleted in this PR was added by @Araq here https://github.com/nim-lang/Nim/commit/1d1be03d81a380d6d2e15bd1e4a0873fe64ada5f with the message `make 'doc io.nim' work`. Apparently, removing those changes makes it work. But I dunno if it breaks something. So lets wait for the CIs to do their work.
=> fix `koch docs` failing at io.nim with `import os` in config.nims

compiler/vmgen.nim, tests/vm/tcastint.nim
Cast around integer types in the VM. No size limitations anymore. The code is also shorter now.
=> VM can now cast integer type arbitrarily.

lib/pure/os.nim, tests/stdlib/tos.nim
Additionally, use normalizePathEnd to suffix the dir name with "/" or
"\\" as appropriate for the current OS.
Fixes https://github.com/nim-lang/Nim/issues/11439.
=> Use TMPDIR env var if available to get the temp dir name

koch.nim
Fixes https://github.com/nim-lang/Nim/issues/11427.
=> Ensure that koch-built nim exe has +x perm for u/g/others [bugfix]

lib/pure/streams.nim
```nim
import streams
var strm = openFileStream("somefile.txt")
echo strm.readLine()
strm.close()
```
Current exception message is below.
> Error: unhandled exception: cannot open file [IOError]
I think that error message needs file name.
I changed exception message to below.
> Error: unhandled exception: cannot open file stream: somefile.txt [IOError]
=> streams: change error message of `openFileStream`

nimpretty/nimpretty.nim
Nimpretty doesn't work anymore for absolute paths, which is how the vscode uses nimpretty. I just used the same code from the nim `--out` option.
=> [bugfix] fix nimpretty for absolute paths

lib/pure/asyncdispatch.nim, lib/pure/asyncfutures.nim, lib/pure/includes/oserr.nim, tests/async/tasyncclosestall.nim
This took a damn long time to solve. Main blockers were #11231 and the spaghetti code. I've ended up refactoring some code along the way, even though in the end I didn't need to use it, I still prefer the refactored version.
Ran ``./koch tests r tests/async/tasyncclosestall.nim`` and ``./koch tests cat async`` to verify that all is looking good. Plus tested it on my game.
=> Fixes async IO operations stalling even after socket is closed.

doc/tut1.rst
Does -d:release still turn off *some* checks or should the sentence changed more?
=> Update tut1: -d:release does not turn off *all* runtime checks anymore

lib/system.nim
```nim
static: quit("exiting")
```
=> [bugfix] fix quit errormsg in nimvm

lib/core/macros.nim
This looks nicer, is more consistent with the module, and gives lineinfo.
=> [refactoring] error instead of quit for basename

doc/tut2.rst
Monospace `untyped` like elsewhere in the tutorial.
=> Minor formatting fix in tut2 [skip ci]

lib/system.nim
Right now, the <See "For loop macros"> link in https://nim-lang.github.io/Nim/system.html#ForLoopStmt points to https://nim-lang.github.io/Nim/manual.html#macros-for-loop-macros.
It should point to https://nim-lang.github.io/Nim/manual.html#macros-for-loop-macro. (note the removal of 's' at the end)
=> Fix the link to "For Loop Macro" section

changelog.md, lib/pure/strutils.nim, tests/stdlib/tstrutil.nim
The new tests pass for me.  The old tests pass with the change mentioned in the `changelog.md` line.  I also added a couple lines to the documentation for `find` to be clearer about the return value.  I went with "slice order" for (`start`, `last`) parameters.  See discussion in https://github.com/nim-lang/Nim/issues/11430 .  Reversing 3 proc param orders is an easy tweak if you want, though.
=> Attempt to close https://github.com/nim-lang/Nim/issues/11430

changelog.md, compiler/scriptconfig.nim, lib/pure/includes/osenv.nim, lib/system/nimscript.nim, tests/newconfig/tfoo.nims, tests/stdlib/tos.nim
Fixes https://github.com/nim-lang/Nim/issues/11452.
Keeping this as draft until someone can suggest how to pass *nil* to `setEnvironmentVariableA` / `setEnvironmentVariableW` (see https://github.com/nim-lang/Nim/issues/11452#issuecomment-500391205). /cc @cheatfate
=> Add os.delEnv and nimscript.delEnv

lib/pure/smtp.nim
Add command `STARTTLS` for support SMTP Server with an encryption type starttls
=> Add starttls for smtp

doc/tools.rst
- Fix #11434
- Remove `c2nim` as a tool that comes with Nim itself (is now a Nimble package).
- Add `niminst` as a tool that comes with Nim itself.
- Add `nimpretty` as a tool that comes with Nim itself.
:slightly_smiling_face:
=> Fix #11434 , Update Tools Documentation

nimsuggest/nimsuggest.nim
The default starting parameters for `line` and `col` were switched.
See line 141: "line starts at 1, column at 0, dirtyfile is optional".
Also, in `TLineInfo` object, `line` is uint16, `col` is int16.
=> [bugfix] fix #11482, fix nimsuggest range error

lib/pure/random.nim
The original example which fails:
```nim
import random
proc onLoad() {.exportC.} =
let r = initRand(1560090106546000100)
when isMainModule and defined(c):
onLoad()
```
----
The error is triggered here: 
```nim
result.a0 = ui(seed shr 16)
```
(inside of `initRand` proc) because `1560090106546000100 shr 16` is larger than `uint32.high`, which is what `ui` is in JS backend. (It is `uint64` in C backend).
> The value that I used above was generated by `randomize`
Here is what `randomize` does for JS backend:
```nim
let time = int64(times.epochTime() * 1_000_000_000)
```
and then `time` is used as `seed` parameter in the above code, which, even after the shift-right, produces numbers larger than `uint32.high`.
=> [bugfix] fix #11450, random.initRand crashes in JS backend

lib/pure/math.nim
`Math.cbrt()` exists:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/cbrt
The binding was missing for the JavaScript backend.
=> Add `cbrt()` bindings for the JS Target

compiler/semexprs.nim, tests/array/tarray.nim, tests/array/tidx_lit_err1.nim, tests/array/tidx_lit_err2.nim, tests/array/tidx_lit_err3.nim
```nim
let x = [int: 1, int: 2]
echo [bigEndian: 1][bigEndian] # type mismatch 
```
=> literal array indices

lib/pure/smtp.nim
Fix unhandled exception if we use `yield` and look exception in `failed` property
=> Fix smtp.nim unhandled exception

lib/core/macros.nim
This implementation looks nicer when the ast is preted. The old version triggered a regression in Nim in my OpenGL macros.
=> change newLit on Seq

lib/pure/collections/tableimpl.nim, lib/pure/collections/tables.nim
This was reported on IRC, see the [reported example](https://play.nim-lang.org/#ix=1Mhr).
=> [bugfix] fix OrderedTable default initialization

lib/pure/collections/tables.nim
This solves the bug reported on IRC:
```nim
import tables
var test = newSeq[Table[string, string]](1)
for key, table in test:
for k, v in table:
discard
var test2 = newSeq[OrderedTable[string, string]](1)
for key, table in test2:
for k, v in table:
discard
```
=> [bugfix] fix OrderedTable iterators

lib/system/gc_common.nim
I am writing my own coroutine module, but I needed those procs in order to deal with the GC.
On windows they did not work with *cpp* backend due to the `dynlib` + `exportc` convolution :)
=> Add dynlib to nimCoroutines related gc procs

config/nim.cfg
As discussed on IRC: https://irclogs.nim-lang.org/24-06-2019.html#18:13:02
This will not disable full paths in stacktrace atm, you'd need to have `--listFullPaths:off` also. I'm pretty sure I've figured out the culprit, and will send a PR for that soon.
=> [other] nim.cfg: disable excessiveStackTrace on release

lib/system/assertions.nim
Fixes #11545.
Currently `--listFullPaths:off` is also needed to get rid of the full path as well, thanks to this
https://github.com/nim-lang/Nim/blob/436f57065197bee86c9539b75de3a73e5bda3f10/compiler/msgs.nim#L158-L165
I'll probably try to patch around this later...
=> [bugfix] assertions: make assert follow excessiveStackTrace

lib/pure/cgi.nim
When an HTTP request with a zero CONTENT_LENGTH is made,
attempting to access addr(result[0]) raise an exception as the 0 index
is out of bound
=> [bugfix] Fix out of bound access in cgi module

compiler/msgs.nim, compiler/options.nim
This PR introduce the following changes:
- Confine `--listFullPaths` to only affect compiler messages (as designed). All test cases from #9766 have been tested to ensure nothing broke.
- Minor cleanup to `toMsgFilename`, should now prefer `/home/test.nim` over `../home/test.nim`
Potential problems:
- Since `toFilename` could have been used for compiler messages also, this change may cause certain compiler messages to stop respecting `--listFullPaths` (haven't found any). Patching those ocurrances to `toMsgFilename` should be enough however.
=> compiler/[msgs, options]: confine --listFullPaths to compiler messages

tools/vccexe/vccexe.nim, tools/vccexe/vccvswhere.nim
Implemented VS 2017 and 2019 discovery using `vswhere.exe` tool.
Tested on Windows 10 x86 and x64.
=> VCC discovery using vswhere (#6540)

compiler/msgs.nim, compiler/reorder.nim, compiler/semstmts.nim
This is a follow up of #11583 covering cases of `toFilename` used for compiler messages that I've missed.
/cc @timotheecour
=> compiler/[msgs, reorder, semstmts]: use toMsgFilename where appropriate

compiler/ccgstmts.nim, compiler/msgs.nim
This PR introduces the following changes:
- Change `toFilename` meaning to only return the filename. For the relative path to the current project, use `toProjPath`. This should bring consistent behavior between C codegen and other codegen in terms of the file name inlined into the generated source.
- The C codegen will now use `quotedFilename()` for generating exception raising code, which should bring its behavior inline with `--stacktrace:on` (and possibly speed the codegen up a bit because of it's cached).
Fixes #11572 for all backends.
=> msgs, ccgstmts: fixes #11572

lib/system/repr.nim
```
import typetraits
var a:int
var b = a.addr
echo b.type.name
echo b.repr
var c = new int   
echo c.type.name
echo c.repr
```
```
ptr int
ptr 0x557736e5aca0 --> 0
ref int
ref 0x7f697999c048 --> 0
```
=> Make repr print 'ptr' for ptr types instead of 'ref'

config/nimdoc.cfg, nimdoc/test_out_index_dot_html/expected/index.html, nimdoc/test_out_index_dot_html/expected/theindex.html, nimdoc/testproject/expected/subdir/subdir_b/utils.html, nimdoc/testproject/expected/testproject.html, nimdoc/testproject/expected/theindex.html
Aside of resulting in more consistent appearance across browsers, this also fixes input form rendering when using Firefox with a dark system theme on Linux.
=> Implement some custom formatting for input fields in the documentation

lib/pure/json.nim
Adds the 'keys' iterator to JsonNode so that you can iterate over the keys of a JSON object.
=> Add 'keys' iterator to JsonNode

lib/system/timers.nim
* refs #11591
wrong header was used, which was one of the issues mentioned in https://github.com/nim-lang/Nim/issues/11590
I also fixed uint64 to uint64 (cf https://developer.apple.com/documentation/kernel/1462446-mach_absolute_time) for correctness in case user includes `sytem/timers` and wants to use `mach_absolute_time` ; this'll get converted to int64 (`Ticks`) anyways, but header should IMO reflect the real type whenever possible.
I didn't fix numer/denom but added a note (would require cast or conver to int32 otherwise compiler error)
https://nim-lang.github.io/Nim/times.html mentions this:
```
proc getTime(): Time {...}
Gets the current time as a Time with up to nanosecond resolution.
```
while technically correct, this doesn't mention the fact that on OSX (and maybe in other …
=> [bugfix] fix mach_absolute_time header; refs #11591

compiler/semstmts.nim, compiler/vm.nim, compiler/vmgen.nim, lib/pure/parseopt.nim, lib/system/repr.nim
* nim now allows using dynamic shared libraries at compile time when compiled with `-d:nimHasLibFFI`, extending the scope of #10150 to cover `{.dynlib:mylib.}`, not just `{.importc.}` which was only for symbols dlsym'd from the main running executable
this is especially useful as we can now call arbitrary compiled user code at CT imported as a shared library (eg regex, or access global variables via wrappers, or to speedup CT operations by avoiding the VM interpretation, or writing to stderr at compile time)
* fixes #8405 (issue was marked as closed but wasn't actually fixed AFAIK, see https://github.com/nim-lang/Nim/issues/8405#issuecomment-507422748) 
/cc @awr1 @ccll 
/cc @zah because you asked about that bug here https://github.com/nim-lang/Nim/pull/10150#issuecomment-451903510
#8405 …
=> fix #8405: -d:useNimRtl now works even when {.rtl.} procs are used at compile time; CTFFI now works with {dynlib}

lib/pure/math.nim
In the documentation for math.nim, the link to the strformat module in the "See also" section at the top of the documentation is broken so it takes you to https://nim-lang.org/documentation.html instead of https://nim-lang.org/docs/strformat.html. This patch fixes that.
=> Fixed the broken link to the strformat module in math.nim

lib/std/sha1.nim
Make `newSha1State`, `update` and `finalize` procedures from the `sha1` module public in order to be possible to compute single _sha1_ hash of multiple separate blocks of data.
=> Make public some sha1 module procedures

doc/manual.rst
There is no explanation about block expression in the manual.rst.
So I added it.
=> manual: document block expression

compiler/ccgexprs.nim
* fixes https://github.com/nim-lang/Nim/issues/11651
note that this PR doesn't introduce spurious symbols in binary, eg:
```nim
proc foo1() = when false: discard
proc foo2() {.exportc.} = when false: discard
```
if `foo1` wasn't generated before PR in binary (eg not referenced), it won't be generated after PR
but `foo2` will get generated after PR as it's marked `exportc`
Note that:
`proc foo {.exportc.}` without body is still generating CT error (unless an implementation follows somewhere in module), nothing changes here
=> fix #11651 exportc symbol not exported, leading to link error

compiler/layouter.nim, nimpretty/tests/exhaustive.nim, nimpretty/tests/expected/exhaustive.nim
Because of the change in indentation, the diff looks larger than it really is. Here is the added logic:
```nim
var dontIndent = false
for commentLine in splitLines(lit):
if i == 0 and (commentLine.endsWith("\\") or commentLine.endsWith("[")):
dontIndent = true
wr em, commentLine, ltComment
elif dontIndent:
wrNewline em
wr em, commentLine, ltComment
else:
```
-----
Before this PR, nimpretty change the formatting and would produce stuff like these:
```nim
=================        ====================================================
Sign                   Meaning
=================        ====================================================
``+``                    Indicates that a sign should be used for both
positive as well as negative numbers.
``-``                    Indicates that a …
```
=> nimpretty: don't touch formatted multiline comments

compiler/layouter.nim, nimpretty/tests/expected/simple4.nim, nimpretty/tests/simple4.nim
This bug has been spotted by @dom96 when nimpretty was run on stdlib ([link](https://github.com/nim-lang/Nim/pull/11646#discussion_r300143128)).
The problem was that `","` was **not** guaranteed to be the semi-last token (`em.endsWith(",", " ")`) because of `optionalNewline`, and if that was the case — nimpretty would use semicolon as the default separator.
...only to fail again when a similar situation (comma, followed by `optionalNewline` token, followed by the space) arose and then it failed to convert comma to semicolon.
E.g.:
```nim
proc readBuffer*(f: AsyncFile; buf: pointer, size: int): Future[int] =
```
```
=> nimpretty: improved detection of commas and semicolons

lib/experimental/diff.nim
- Add documentation for Diff.
- Add Examples.
- Typo on Docs returns `seq` not `array` actually.
:slightly_smiling_face:
=> Documentation Diff, Typo

lib/nimbase.h
* NIM_NEW_MANGLING_RULES hasn't been used for a while IIRC, so that branch is dead
* the other branch defines unused macros
* cgen.initFrame is the new place where nimfr_ etc is defines, since a few releases already
=> [cleanup] nimbase.h: remove dead code which was confusing

compiler/ccgexprs.nim, compiler/semexprs.nim, compiler/semfold.nim, compiler/semmagic.nim, compiler/sizealignoffsetimpl.nim, compiler/vmgen.nim, tests/misc/tsizeof.nim, tests/misc/tsizeof2.nim
* `offsetof` did not work on tuples with named fields before. This has been fixed.
* Make `offsetof` fallback to `offsetof` from C/C++, similar to `sizeof` `alignof` fall back to their C/C++ counterparts. 
* Fix a few bugs where the field offset was set to ``szUncomputedSize`` instead of ``szUnknownSize``.
* Add test that ensure that the fallback to the C/C++ backend actually works.
* Reduce code redundancy a little bit.
* Finally introduce the `OffsetAccum` type, even though it isn't used much yet.
=> Offsetof fixes

lib/pure/collections/LockFreeHash.nim, lib/pure/collections/critbits.nim, lib/pure/collections/deques.nim, lib/pure/collections/hashcommon.nim, lib/pure/collections/heapqueue.nim, lib/pure/collections/intsets.nim, lib/pure/collections/lists.nim, lib/pure/collections/rtarrays.nim, lib/pure/collections/sequtils.nim, lib/pure/collections/setimpl.nim, lib/pure/collections/sets.nim, lib/pure/collections/sharedlist.nim, lib/pure/collections/sharedtables.nim, lib/pure/collections/tables.nim
This supersedes the initial attempt done in #11646 — this time `nimpretty` was run only on `lib/pure/collections/**/*.nim` to make diffs smaller and easier to review.
Since the last PR, we've pushed several fixes and generally improved `nimpretty`: this time there was lot less need for manual interventions, and fewer edge cases where it fails (produces uglier code than it was originally).
The rationale for this PR is to have these obvious fixes and improvements applied so that in the future the diffs are smaller and more meaningful, so it is easier to spot when `nimpretty` has improved for those corner cases.
=> [other] prettify collections

changelog.md, lib/std/sha1.nim
After making public `newSha1State`, `update` and `finalize` methods from the `sha1` module was forgotten to be made public `Sha1Digest` and `Sha1State` types used by the new public methods.
=> Make public additional types from sha1 module [feature]

compiler/layouter.nim, nimpretty/tests/exhaustive.nim, nimpretty/tests/expected/exhaustive.nim
The problem was that `lineLen` was not being calculated correctly for multiline strings. E.g. `123\n123\n123` would have `lineLen = 11` instead of `3`.
=> nimpretty: fix #11700, no extra newlines

lib/pure/includes/oserr.nim
POSIX does **not** define the exact number for each errors. This caused
a failure in docs building on Haiku.
=> os: confine osErrorMsg example to Linux

changelog.md, doc/lib.rst, lib/pure/times.nim, lib/std/monotimes.nim, tools/kochdocs.nim
This module is similar to `system/timers`, but with some differences:
- Uses the `times.Duration` type where applicable.
- Uses `CLOCK_MONOTONIC` instead of `CLOCK_REALTIME` for posix.
- Support for the JS backend.
=> Add std/monotimes which implements monotonic timestamps

doc/docgen.rst, doc/filelist.txt, doc/intern.rst
A couple of typos-fixes and polishes from reading over the _[Internals of the Nim Compiler](https://nim-lang.org/docs/intern.html)_ document.
Also (second commit), amend in _[Nim DocGen Tools Guide](https://nim-lang.org/docs/docgen.html)_ (`docs/docgen.html`) the Nim repository
URL from `Araq/Nim` to `/nim-lang/Nim`:
* https://github.com/Araq/Nim
* https://github.com/nim-lang/Nim
=> Fix Typos in Internal Docs

lib/pure/collections/critbits.nim
- s/otherbits/otherBits/
- s/newbyte/newByte/
- s/newotherbits/newOtherBits/
=> [bugfix] critbits styleCheck fix: consistent var naming

lib/core/macros.nim
Fixes:
> macros.nim(1423, 35) Warning: `typed` will change its meaning in future versions of
Nim. `void` or no return type declaration at all has the same
meaning as the current meaning of `typed` as return type declaration. [Deprecated]
=> [bugfix] Fix compilation warning in macros.nim

compiler/semcall.nim, compiler/sigmatch.nim, tests/concepts/t3330.nim, tests/concepts/texplain.nim, tests/destructor/tdont_return_unowned_from_owned.nim, tests/errmsgs/t8434.nim, tests/errmsgs/tdetailed_position.nim, tests/errmsgs/tgcsafety.nim, tests/errmsgs/tsigmatch.nim, tests/errmsgs/tunknown_named_parameter.nim, tests/errmsgs/twrong_at_operator.nim, tests/typerel/t7600_1.nim, tests/typerel/t7600_2.nim, tests/varres/tprevent_forloopvar_mutations.nim
* fix #11061
* fix #8305
* fix #7808 
* fix #10285 (was closed but issue remains as mentioned by @bluenote10 in https://github.com/nim-lang/Nim/issues/7808#issuecomment-508905750 : the err msg doesn't show that `closure` is missing; this PR fixes that)
fix other bugs with type mismatch error msgs that I didn't create separate issues for, eg:
*  fix https://github.com/nim-lang/Nim/issues/11061#issuecomment-508969796 sigmatch gets confused with param/arg position after varargs
* fix https://github.com/nim-lang/Nim/issues/11061#issuecomment-508970046 err msg incorrectly says something is immutable
* fix https://github.com/nim-lang/Nim/issues/11061#issuecomment-508970465 err msg doesn't tell you what when wrong when an argument is bound twice
(`errCannotBindXTwice` was removed because of …
=> fix #8305 #7808 #10285 #11061 + other bugs with type mismatch error msgs

lib/core/seqs.nim
With `--newruntime`, shrinking a `seq` destroyed one too many elements/iterated out of bounds. E.g. this crashed
```nim
var x = newSeq[string](1)
x.setLen(0)
```
=> Fix the range of destroyed elements when shrinking a seq

lib/pure/httpclient.nim
Previous solution:
```nim
import httpclient, net
when not defined(ssl):
type SslContext = ref object
proc connectWebsocket*(sslContext: SslContext = when defined(ssl): newContext(protTLSv1, CVerifyNone) else: nil): Socket =
let client =
when defined(ssl):
newHttpClient(sslContext = sslContext)
else:
newHttpClient()
...
```
What this PR will allow:
```nim
import httpclient
proc connectWebsocket*(sslContext = getDefaultSsl()): Socket =
let client = newHttpClient(sslContext = sslContext) 
...
```
=> Export httpclient.getDefaultSsl for APIs that need it

compiler/sizealignoffsetimpl.nim, tests/misc/tsizeof3.nim
test case is included.
Description.
It is not possible to compute the size of the following object without knowing the alignment of `MyImportedType` even if size of `UncheckArray[MyImportedType]` is zero:
```nim
MyType = object
a: int
b: UncheckeyArray[MyImportedType]
```
Alignment of `b` needs to be included to sizeof `MyType` even if size of `b` is zero.
In this case sizeof needs to be delegated back to c/cpp
=> fixes #11792

lib/js/dom.nim
I noticed this was missing.  It has cross browser support: https://developer.mozilla.org/en-US/docs/Web/CSS/opacity#Browser_compatibility
=> Add `opacity` to JS `Style`

compiler/docgen.nim, lib/pure/uri.nim, lib/system.nim, tests/magics/trunnableexamples.nim
this PR allows `runnableExamples` to generate code at module scope, which is needed in some cases where code inside a block would not work. The option is opt-in so no existing code is affected.
See `tests/magics/trunnableexamples.nim` for unittests, it also shows some examples where module scope is needed
=> allow runnableExamples(topLevel=true)

lib/pure/includes/osseps.nim
PR #10629 implementation was rejected, this style was agreeable to [Araq](https://irclogs.nim-lang.org/17-07-2019.html#13:32:41).
I have leveraged code from compiler/platform.nim which was more expansive. There are variations though which I have highlighted in comments. Please review.
Note that RISCOS is not in platform.nim.
=> Fix #10630 - fix broken separators in nim doc

lib/pure/random.nim
In the JS backend `times.epochTime()` gives only millisecond resolution, so there's no point in multiplying by anything larger than `1000`.
The previous larger values were producing `Error: unhandled exception: value out of range [RangeError]`.
=> fix #11772, JS random seed was too large

lib/pure/asyncnet.nim
This resulted in a "value out of range: -1" exception inside `recvInto`
(on the `copyMem` line). Basically readIntoBuf was returning `-1`.
=> Fixes subtle SSL recvInto bug.

compiler/vm.nim, tests/vm/tconstobj.nim
The issue was almost fixed by https://github.com/nim-lang/Nim/commit/44c04b35717336595dad03ac532ee9e141a0e374, but it didn't fix it for implicit conversions.
Fixes #11861
=> Fix VM conversion to var type [bugfix]

compiler/vm.nim, compiler/vmops.nim, tests/vm/texception.nim
This PR fixes a few issues with exceptions in the VM:
- `getCurrentException` was not available (fixes #9920, fixes #11802)
- empty `raise` statement did not work
- the name of the exception was not included in the stack trace, unlike stack traces from the runtime
=> VM exception fixes [bugfix]

compiler/sigmatch.nim, tests/ccgbugs/tnil_type.nim
`type(nil)` is already allowed for concrete parameters, this PR enables `type(nil)` for generic parameters as well.
=> Allow typeof(nil) as generic parameter

compiler/installer.ini, tools/niminst/buildsh.nimf
Nim currently fails to build on Debian/ia64. The two changes in this PR should fix that.
=> Add build support for Linux/ia64

lib/pure/encodings.nim
It turned out that MultiByteToWideChar can convert only to "windows-unicode" which is utf-16 little endian, same goes for WideCharToMultiByte.
=> Fixed utf8<->utf16 conversions on windows

doc/manual.rst
=> Typeclass/Variant clarification in Manual

lib/pure/httpclient.nim, tests/stdlib/thttpclient.nim
Fixes #10726 
Added patch by @xenogenesi and test for AsyncHttpClient.
I've tried to add test for sync HttpClient, but the server wasn't responding.
=> Fix issue 10726 - HTTP response without Content-Length is not accessible

compiler/sigmatch.nim
I did an analysis to find out where most of the copyTree calls come from. This location is by far the location with the most usage call. A small 10 line program had over 100000 copyTree invocations from this location alone. So I just removed it, let's see if it will fail some tests.
I also did a benchmark to compile the compiler with this change. The difference is, even though not as big as I would have hoped, measurable:
```
147922 lines compiled; 5.491 sec total; 514.445MiB peakmem;
147923 lines compiled; 5.298 sec total; 514.43MiB peakmem
```
0.2 seconds difference to compile the compiler. I would have expected to have a bigger impact on peakmem though.
Here are the other copy tree calls hidden (all locations above 1000, identity by stack frame):
``` …
```
=> delete expensive call

compiler/semcall.nim, compiler/sigmatch.nim
```nim
template fun2(a2 = ""; a3: int = 10; a4 = "") = discard
fun2(a3 = 30, "asdf")
```
before PR:
```
/Users/timothee/git_clone/nim/Nim_devel/lib/system/fatal.nim(48) sysFatal
Error: unhandled exception: sons is not accessible [FieldError]
```
after PR:
```nim
/Users/timothee/git_clone/nim/timn/tests/nim/all/t0611.nim(40, 7) Error: type mismatch: got <a3: int literal(30), string>
but expected one of:
template fun2(a2 = ""; a3: int = 10; a4 = "")
first type mismatch at position: 2
positional param was already given as named param
expression: fun2(a3 = 30, "asdf")
fun2(a3 = 30, "asdf")
^
```
=> fix crash on sigmatch, improve error msg

compiler/commands.nim, compiler/options.nim, compiler/vm.nim, doc/advopt.txt, tests/macros/tlocktypednode1.nim, tests/macros/tlocktypednode2.nim, tests/macros/tlocktypednode3.nim, tests/macros/tmacro7.nim
This will emit a proper error message ``typechecked nodes may not be modified`` for code like https://github.com/nim-lang/Nim/issues/11877. Not sure if that can be called a fix though. This check should prevent a lot of crashes due to illegal AST going through the semchecker. It should also prevent a lot of head scratching for programming that actually do modify a typechecked AST and wonder about the weird results and behavior.
=> Lock semchecked ast for macros

lib/pure/logging.nim
If you are using the `terminal` module with the `logging` module and call `resetAttributes()` within your log method override, this error will be prdocued:
`Error: can have an unlisted effect: RootEffect`
Here is an example to reproduce - 
```nim
import logging, terminal
type  
CustomLogger = ref object of Logger
proc logPrefix*(level: Level): tuple[msg: string, color: ForegroundColor] =
case level:
of lvlDebug:
return ("---", fgMagenta)
of lvlInfo:
return ("(i)", fgCyan)
of lvlNotice:
return ("   ", fgWhite)
of lvlWarn:
return ("(!)", fgYellow)
of lvlError:
return ("(!)", fgRed)
of lvlFatal:
return ("(x)", fgRed)
else:
return ("   ", fgWhite)
method log(logger: CustomLogger; level: Level; args: varargs[string, `$`]) =
var f = stdout
if level >= getLogFilter() and level >= …
```
=> Fix effect error in pure/logging.nim

lib/pure/xmltree.nim
So far the documentation on `items` and `mitems` wasn't explicit about whether the iteration recurses down the node's children or not. I had assumed recursion, which turned out to be wrong.
=> Update documentation on `xmltree.items`/`mitems`

lib/system.nim, lib/system/nimscript.nim
Yesterday I sat down to implement `execEx` (returning exit code + output) for NimScript because it looked like it was missing. In the end, I discovered that it is actually available, just under the unexpected name `gorgeEx`. I missed it because:
- looking only at the nimscript module the functionality seems missing => added a mention of `gorgeEx` there.
- `gorgeEx` and `staticExec` actually never mentioned what they return => added.
It was also not clear the me what the `exec` functions do on non-zero exit codes, and I think one of the `raises` annotations were wrong, because `staticExec` swallows non-zero exit codes.
In general, it's quite confusing that process handling is split into three modules system, nimscript, osproc and that they using different naming schemes (exec, gorge, …
=> Improved docs around exec, staticExec, gorgeEx, etc.

lib/core/allocators.nim, lib/system/atomics.nim
Simple programs doesn't compile with newruntimea and vcc.
```nim
echo "hello"`
```
fails with ` Error: 'open' is not GC-safe` because widechars are used and they call allocator.alloc() which is not marked as gcsafe.
with `threads:on` fails because `atomicLoadN` is used in owned references implementation but is not available in `atomics.nim` for vcc.
=> newruntime for vcc fixes

compiler/semgnrc.nim
fixes Example1 from https://github.com/nim-lang/Nim/issues/11947
the problem was that a macro can return an atom (eg via `newLit 134`), so `sonsLen` was incorrect.
the 2nd half of that issue is still there (so it was a separate problem)
=> fix #11947 : generics can safely call macros

lib/pure/httpclient.nim
This caused problems with websockets which reply with "Connection: Upgrade".
=> Fixes regression introduced by #11904.

lib/pure/os.nim, tests/stdlib/tos.nim
This PR improves the implementation of os.splitFile so it correctly splits when the input path has multiple dots before the extension, e.g. `splitFile("/foo/abc....txt") == ("/foo", "abc...", ".txt")`.
=> Fix splitfile

compiler/ccgexprs.nim, compiler/jsgen.nim, compiler/renderer.nim, lib/system/chcks.nim, lib/system/jssys.nim
* fix #10053
```nim
type Kind = enum k1, k2
type Foo = object
case kind: Kind
of k1:
f1: int
of k2:
f2: int
proc main()=
var foo = Foo()
echo foo.f2
main()
```
before PR:
Error: unhandled exception: f2 [FieldError]
in most cases (eg see error msg i got from https://github.com/nim-lang/Nim/issues/11947) this is not very helpful
after PR:
Error: unhandled exception: 'f2' is not accessible using discriminant 'kind' of type 'Foo' [FieldError]
works with `nim js` and `nim c`
I have another PR to fix the VM case, but it depends on this PR so i'll wait until this is merged
=> fix #10053: FieldError exception messages now show discriminant + type

compiler/semstmts.nim, tests/modules/tincludeas.nim
Closes https://github.com/nim-lang/Nim/issues/11872
=> `include` now gives a proper error message for all invalid infix operators

lib/nimhcr.nim
Closes https://github.com/nim-lang/Nim/issues/11718
This issue was occuring because `system always gets fully inited before any other module (including when reloading)`  but system.nim imports many modules whose procs are not yet registered with hcr, so now we ignore such procs till later when they get registered.
=> Fix HCR crash because certain procs were hcrGetProc'ed before being hcrRegisterProc'ed

compiler/lexer.nim
Before
```nim
of tkCharLit:
result = newIntNodeP(nkCharLit, ord(p.tok.literal[0]), p)
getTok(p)
```
had `IndexError` because `p.tok.literal` was empty.
=> nim check, fix #11927, no more empty strings

compiler/semobjconstr.nim, doc/manual.rst, tests/objvariant/trt_discrim.nim
Similar to how the compiler now accepts runtime discriminators if the value is restricted by a case branch, this PR accepts runtime discriminators if they are restricted by a range type. This is especially convenient for constructor procs. Example:
```nim
type
Kind = enum
A, B, C, E
OkRange = range[B..C]
CaseObject = object
case kind: Kind
of B, C:
field: int
else: discard
let rtDiscriminator: OkRange = B
discard CaseObject(kind: rtDiscriminator, field: 1)
```
If this is accepted I'll update the manual as well.
=> Consider range type of runtime discriminator

compiler/evalffi.nim
https://github.com/nim-lang/Nim/pull/10150 has started to bitrot (after in128 changes) because testing it in testament was disabled in c5dbb0379fc431a01220224097f00323df6c9ced
this PR fixes that bitrot, so that 
```
nimble install libffi
nim c -d:nimHasLibFFI compiler/nim.nim # note: requires --styleCheck:hint currently
compiler/nim c --experimental:compiletimeFFI -r tests/vm/tevalffi.nim
```
will work.
But could we revert c5dbb0379fc431a01220224097f00323df6c9ced so that `compiletimeFFI` keeps working ?
I'm heavily relying on that, it enables a lot of things that would otherwise be impossible
=> fix compiletimeFFI bitrot

compiler/ccgcalls.nim, compiler/ccgtypes.nim, compiler/cgen.nim, lib/nimhcr.nim
- adding _actual as a suffix only for calls to an actual proc and not through a global function pointer - fixes #11996
- adding forward declarations for reloadable functions within a module - fix compilation errors when 2 such functions reference each other (+ fixes codegen when methods are used) - fixes #11608
- preserve permissions of copied executable binaries
=> HCR - fix for #11608 and #11996

lib/pure/json.nim, tests/stdlib/tjsonmacro.nim
Fixes #12015. 
If anyone sees a cleaner way to fix this, let me know. :)
edit: 
Just noticed that this does not solve my actual problem. I thought my test case reproduced the same problem, but it seems if generics are involved there are more cases for this to break. I'll reopen once I fix this.
edit2: I fixed it differently after all. The previous fix would fail if a generic was involved.
For some reason the this branch here:
https://github.com/nim-lang/Nim/pull/12016/files#diff-e00d77321d9bf30eaf8e4be863d9b565R1379-R1382
only seems to happen for aliases of `seq[T]`. At least that's the only case I could reproduce that branch. 
I decided to add an `of "tuple"` after all, even though the above mentioned branch would also catch that for clarity.
=> fixes #12015 by also checking kind of `typeNode`

compiler/sem.nim, compiler/semexprs.nim, compiler/semstmts.nim, compiler/semtypes.nim, compiler/sigmatch.nim, tests/range/trange.nim
This is a continuation of PR https://github.com/nim-lang/Nim/pull/11905 by @GULPF.
The changes were rebased on the latest devel (that's the reason why I couldn't just push to that PR), and the second commit addresses the comments from the original PR.
----
Original comment:
This PR fixes a few minor issues with float ranges.
- Int literals are now implicitly convertible to float ranges, just like they are implicitly convertible to float base types
- Fixed this case which used to compile: `const x6: range[0'f32..1'f32] = 2'f64`
- Changed the error message when using NaN in a range type to something more specific
=> Fix several float range issues (supersedes #11905)

lib/system/assertions.nim
Moves 'when enabled' up in `assertImpl()` to avoid `ploc` to be defined but not used.
As a side effect this also seems to slightly speed up compilation.
=> Fixes #12044

compiler/ast.nim, compiler/ccgtypes.nim, compiler/liftdestructors.nim, compiler/sem.nim, tests/destructor/tmove_objconstr.nim
I had to change `fitNodePostMatch` to make the following compile in newruntime: `[(new(int),)]`. 
Otherwise, nkHiddenSubConv node is in the way for tuple elements of array and inject destructor tries to copy non copyable tuple `(new(int),)`
=> lift destructor for openarray 

compiler/dfa.nim, tests/destructor/t12037.nim
It doesn't matter wether `a[...]` is a seq or tuple access, it aliases `a`.
=> Fix #12037

compiler/semmagic.nim, compiler/types.nim, tests/errmsgs/tsigmatch.nim, tests/errmsgs/twrong_at_operator.nim, tests/metatype/ttypetraits2.nim, tests/openarray/t8259.nim
* fix #8569
* fix #8083
* fix #8570
* fixed typename case: fixed `CString` => `cstring` and `Char`=>`char`, `openarray`=>`openArray` (more consistent with all other types, see `typeToStr`)
(also related to #7976)
typeToString gets 2 new options (and typeToString gets exposed as a magic), which in future PRs could replace all existing `TPreferedDesc` options: 
* `preferResolved` to show (recursively) resolved type aliases (`tuple[a: MyInt]` shows as `tuple[a: int]`) (note that `preferDesc` doesn't do that reliably)
* `preferMixed` to show (recursively) resolved type aliases + their aliases when they differ (at the place where they differ): (`tuple[a: MyInt]` shows as `tuple[a: MyInt{int}]`)
this fixes above mentioned bugs and also makes it clear to user what a type resolves to, while also …
=> typeToString can now show (recursively) resolved type aliases; fixes  #8569 #8083  #8570

compiler/ccgtypes.nim, compiler/jsgen.nim, compiler/types.nim, tests/ccgbugs/tnil_type.nim
* Allow `typeof(nil)` as a return type.
* `typeToStr`: `$typeof(nil)` is now `"typeof(nil)"`, not `"nil"`.
Especially makes sense e.g. when `typeof(nil)` is used inside proc type:
```nim
proc foo(a: typeof(nil)) = discard
echo typeof(foo)
```
=> Return typeof(nil)

compiler/vm.nim, tests/tools/tnimscriptwithmacro.nims, tests/vm/tgloballetfrommacro.nim
By default the global context was in mode ``emRepl``. In repl accessing a global ``let`` variable is explicitly allowed. That is why the compiler didn't complain to read from the global let from the macro. This is a bug that I could fix by setting the mode to something else, like ``emStaticStmt``, which seems most reasonable to me.
=> fix #11903

compiler/astalgo.nim, compiler/lexer.nim, compiler/semexprs.nim, compiler/semtypes.nim, compiler/transf.nim, compiler/types.nim, compiler/vmgen.nim, lib/system.nim, tests/arithm/tarithm.nim, tests/converter/tstatic_range_checks.nim
This is the first step to treat uint and uint64 as ordinal types. (They really should be)
=> Uint range checks

changelog.md, compiler/ast.nim, compiler/cgen.nim, compiler/pragmas.nim, compiler/wordrecg.nim, tests/cpp/mexportc.nim, tests/cpp/texportc.nim
* fix https://github.com/nim-lang/Nim/issues/10578
* see added tests
=> exportc now mangles same as importc, fixes #10578

tests/niminaction/Chapter8/sdl/sdl.nim
Partly fixes #12141 - define SDL lib name for OpenBSD and FreeBSD. Other architectures now get a compile error.
=> #12141 Define SDL lib name for OpenBSD and FreeBSD

lib/system.nim
=> Fix #12133 - use libgc.so.4.0 for OpenBSD

compiler/vm.nim, tests/errmsgs/tnnodeadd.nim, tests/errmsgs/tnnodeindex.nim, tests/errmsgs/tnnodeindexkind.nim
Indexing atom NimNode now gives a stacktrace/avoids segfault.
```nim
import macros
macro foo(x: untyped): untyped =
x[0] = newEmptyNode()
foo(38'i8) # 'sons' is not accessible using discriminant 'kind' of type 'TNode' [FieldError]
foo(38'i8) # segfault
foo("abc") # index 0 not in 0 .. 2
```
=> error for indexing atom NimNode kinds

compiler/packagehandling.nim, testament/testament.nim
* `7` `8` are more common (especially in tests) than `@` so `@` seems more appropriate mangling character
* should work on windows as had been mentioned in https://github.com/nim-lang/Nim/pull/8614#issuecomment-413031385 
* should fix https://github.com/nim-lang/Nim/issues/12130 although I wasn't able to reproduce that issue on OSX (might affect linux only)
* /cc @qqtop @juancarlospaco does that fix the problem for you?
```
../bam@bax/cab.nim
=>
..@bam@@bax@cab.nim.c
../bam/bax/cab.nim
=>
..@bam@bax@cab.nim.c
```
the leading `..` could be avoided but IMO is more readable and should be legal anyway
this PR does not try to make the `fakePackageName` a valid nim identifier (shouldn't be needed IIUC); note that this also wasn't the case before this PR, eg:
`nimcache/_7bar.baz7gaz77.nim.c` …
=> fix #12130 ; improve naming scheme in fakePackageName

compiler/vmdeps.nim, tests/macros/tmacrotypes.nim
```nim
import macros
macro t(): untyped =
getType(range) # crash / segfault
t()
```
=> fix range.getType crash

compiler/packagehandling.nim, testament/testament.nim
- Prepend filenames with `@` to avoid leading `.`
- Mangle `/` to `@s`, `#` to `@h`.
=> Fixed c filenames mangling

compiler/ccgcalls.nim, tests/cpp/tempty_generic_obj.nim
`importcpp` references types of real params, so extra `typedesc` params are needed to inject types not in the params/return type of the function. This PR is a QOL improvement for this workaround.
`proc foo[T0; T1](PT0: typedesc[T0], PT1: typedesc[T1], x, y, z, w: csize)`
`foo<'1, '2>(@)` produces `foo<T0, T1>(, , x, y, z, w)`
workaround: `foo<'1, '2>(###, #, #, #)` but param modifications require changes in two places + more verbose.
I'm not aware of any valid usage, but `foo<'1, '2>(#, #, #, #, #, #)` can be used for the old behavior.
This is how the JS backend works too.
=> no commas for empty `importcpp: "foo(@)"` params

lib/system/sets.nim
I'm not sure if `unsafeAddr` is OK here or if there's another way. Processing 64 bits at a time makes the following code 8X faster for the first timing and 2X faster for the 2nd.
```Nim
import times
var s : set[uint16]
var t0 = cpuTime()
for i in 0'u16..uint16.high.uint16:
s.incl(i)
doAssert s.card == i.int + 1
echo cpuTime() - t0
s = {2'u16, 12, 32}
t0 = cpuTime()
for i in 0'u16..uint16.high.uint16:
doAssert s.card == 3
echo cpuTime() - t0
```
=> count 64 bits at a time instead of 8

doc/nimc.rst, lib/system/io.nim
When running nim in android app stdout goes no where, so echo gets ignored.
To redirect echo to the android logcat I added the `-d:echoToAndroidLog` parameter.
I am not sure how to override echo correctly on android. But this worked for me.
=> Add -d:androidNDK to fix echo on Android NDK builds.

compiler/options.nim, compiler/platform.nim, doc/nimc.rst
It was strange using `--os:android` when I wanted to compile for iOS. Note MacOS and MacOSX operating system targets do not work for iOS for some reason. These changes make compiling to iOS work.
=> Add the iOS platform as a compiler target.

changelog.md, compiler/pragmas.nim, compiler/wordrecg.nim, doc/manual.rst, lib/js/jsffi.nim, tests/js/tjsffi.nim, tests/js/tjsffi_old.nim
Introduce the importjs pragma. This does the same think that importcpp does when used in js, but with the difference that importjs isn't a misnomer.
=> importjs symbol

compiler/parampatterns.nim, compiler/semexprs.nim, tests/lent/tnot_allowed_lent.nim
For now I am rejecting this code in sempass.
Then it is possible to lower if/case expression into statement in transf:
```nim
x = 
if  b > 0: stmtList1
else: stmtList2
```
Into:
```nim
if  b > 0: 
stmtList1MinusLastExpr
x = LastExprInStmtList1
else:
stmtList2MinusLastExpr
x = LastExprInStmtList2
```
and add support for ifExpr/CaseExpr in isAssignable.
This would also simplify codegen, vmgen, injectdestructors and would decrease number of temporary variables used.
=> fixes #12224

lib/pure/asyncdispatch.nim, tests/async/t12221.nim
This fixes a small issue where a timer that had been completed while
code executed would still wait for more events before being considered
completed. This would in some scenarios incur a 500ms delay to the
completion of a timer.
=> Fix issue with long wait for passed timer [bugfix]

lib/system/gc.nim
I don't know why it was using `c_fprintf(stdout,` when `c_printf` is simpler. I guess some thing is no longer exporting `stdout` .. so it breaks.
=> Fix -d:logGC compile error: 'stdout not defined'

lib/pure/concurrency/threadpool.nim
Just another small documentation fix...
By the way, congrats on releasing 1.0!
=> threadpool: fix link in docs [ci skip]

doc/manual.rst
It was explicit in the BNF, but the English text implied it was allowed. I'm not married to this wording, but it seemed worth stating in the prose since it isn't a common restriction in other languages.
PS- congrats on 1.0!
=> Explicitly state that trailing underscores are banned

compiler/packagehandling.nim
Replacing colon seem to do the trick. I didn't find unit tests for these procs, so none are updated.
=> Fix #12242, replacing ":" with "@c" in packages.

compiler/installer.ini, compiler/platform.nim, lib/system/platforms.nim, tools/niminst/buildsh.nimf
Nim currently fails to build on Debian/hppa. The two changes in this PR should fix that.
=> Add build support for Linux/hppa

lib/core/locks.nim, lib/core/rlocks.nim, testament/testament.nim, tests/stdlib/tsharedtable.nim
Before, it would let you compile, and then throw a linker error with no threads.
This make Locks module work like Threads and Threadpool.
Just a small Quality of Life fix.
=> Locks modules should give a compile error when threads are not enabled.

tools/nimgrep.nim
This fixes a couple of color highlighting issues for nimgrep on Linux:
- bug of option --nocolor being ignored on posix when output is connected to terminal. It's because of the wrong ordering of posix handling and CLI option processing code
- it's impossible to force it to display in colors. A new option --color:always is added. So nimgrep will follow the convention used by GNU grep, Git, Mercurial, etc. of having options --color [never | always | auto].
=> fix nimgrep color on posix #7591

changelog.md, compiler/semstmts.nim, tests/vm/teval1.nim
Reboot of https://github.com/nim-lang/Nim/pull/10515
Credit goes to LemonBoy
=> Fixes #10514

lib/pure/streams.nim, tests/stdlib/tstreams3.nim
And with the last commit it also works for the js backend at compile time (unfortunately this required a bit of code duplication).
=> More of StringStream now works at compile time

lib/pure/os.nim, tests/stdlib/tos.nim
I tested following code on both windows and linux before making this PR.
```nim
import os
echo relativePath("/foo", "/foo/bar")
echo relativePath("/foo", "/Foo/bar")
echo relativePath("/foo/a", "/foo")
echo relativePath("/foo/a", "/Foo")
echo relativePath("/foo/a", "/bar")
```
Output on windows:
```
..
..\..\foo
a
..\foo\a
..\foo\a
```
Output on linux:
```
..
..
a
a
../foo/a
```
`relativePath` compared characters in a path in wrong way.
=> Fix how os.relativePath handle case sensitiviy

compiler/layouter.nim
Split closeEmitter into renderTokens and writeOut.
renderTokens can be used independently
=> Refactor closeEmitter to make it more modular

lib/pure/os.nim, lib/windows/winlean.nim, tests/stdlib/tos.nim
Before making this PR, `os.relativePath` returns wrong path when a root of `path` and a root of `base` are different.
```nim
import os
echo relativePath(r"c:\foo", r"d:\bar")
echo relativePath(r"\\foo\bar\x", r"\\foo\baz\")
```
output:
```
..\..\c:\foo
..\bar\x
```
This PR uses `PathIsSameRootW` or `PathIsSameRootA` windows API to compare roots of input paths.
If they were not same root, returns `path` as is.
But `PathIsSameRootW` or `PathIsSameRootA` seems don't support [DOS device paths](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#dos-device-paths).
This code test `PathIsSameRootW`.
https://gist.github.com/demotomohiro/81702d8a0bf951d6a46b9954093d69bb
APIs in pathcch.h header supports DOS device paths but there is not API to compare root of paths and they are …
=> On windows, os.relativePath returns path as is when roots are different

compiler/extccomp.nim
This PR helps in the following use case:
You have compiled external file using `{.compile.}` pragma  once. Now you changed the file but there is a mistake and file no longer compiles. You rerun Nim to see error message once again, but Nim no longer compiles the file because it is cached and Nim not recompile until file change again.
By removing stale obj file we make sure that only successful compilations get cached.
=> External file compilation improvement

nimsuggest/nimsuggest.nim
A new socket is created for each iteration and leak immediately thanks
to the accept() call replacing the created socket with the client socket.
This commit fixes that.
=> nimsuggest: fix tcp socket leak

build_all.bat, readme.md
Create `build_all.bat` and make the build instructions same as for `build_all.sh`.
=> Easier build instructions for windows - just run `build_all.bat`.

compiler/renderer.nim, nimdoc/testproject/expected/testproject.html, nimdoc/testproject/expected/theindex.html, nimdoc/testproject/testproject.nim
Only uses the special fix from 69658ad for negative octal literals, fixes #11131 and #12287
=> renderer letAux fix only for octal literal

nimsuggest/nimsuggest.nim
Same as e9fa4c9b9c8e2926449399a69a02676936bb842c, but for the epc backend which is used by emacs and
vscode plugin.
Since the EPC backend only deal with one connection per nimsuggest
instance, only one socket is leaked, thus not as servere as with the tcp
backend.
=> nimsuggest: fix tcp socket leak for epc backend

lib/pure/net.nim
I add documentation of sock.recv on net.nim per dom96 comment
> sock.recv(123), you're asking for 123 bytes, the behaviour of recv on buffered sockets is to always return 123 bytes (unless something bad happens like the socket disconnecting)
> This is documented for the async recv: https://nim-lang.org/docs/asyncnet.html#recv%2CAsyncSocket%2Cint (**we should copy these docs to net as well**).
=> documented behaviour of recv on bufferd socket of net.nim

compiler/options.nim, nimsuggest/nimsuggest.nim
This can be used to let nimsuggest users know which project is
nimsuggest being in charge of, so they can know when should a new
nimsuggest instance be spawned.
An another usage is to debug the project file finding feature.
=> nimsuggest: add a command that returns the project file

compiler/options.nim
The compiler can now correctly find the project file of a nimble package. This should help with editor plugins that wants to use nimsuggest.
The algorithm is based on [nim.nvim](https://github.com/alaviss/nim.nvim)'s algorithm, which has yielded good results.
Fixes nim-lang/nimsuggest#109
=> compiler/options: improve project file detection

lib/pure/collections/sets.nim, lib/pure/hashes.nim, tests/collections/ttables.nim, tests/collections/ttablesthreads.nim
Running https://github.com/cwpearson/nim-issue-11764/blob/master/slow_set.nim on my machine, which is the test case for https://github.com/nim-lang/Nim/issues/11764 produces the following before/after results:
Before this PR:
```
(1) time 0.017153174
(2) time 1.512243921
(3) time 18.05979435
(4) time 17.861573436
(5) time 11.350780583
(6) time 0.003636462999999424
(7) time 16.871593051
(8) time 0.002521137000002227
```
After this PR:
```
(1) time 0.022618518
(2) time 0.02331171199999999
(3) time 0.01813793399999999
(4) time 0.01471349299999999
(5) time 0.008311381999999992
(6) time 0.01135809600000001
(7) time 0.02215919299999999
(8) time 0.002485686000000015
```
Summary: this PR makes HashSets and HashTables about **three orders of magnitude faster** for large amounts of (u)int keys, …
=> fix #11764, faster hashing of (u)int

doc/manual.rst
=> Fix #10824

lib/pure/random.nim
Before this change an error was raised:
`Error: 'ui' should be: 'Ui'`
=> [backport] fix type's case in random.nim

compiler/extccomp.nim, config/nim.cfg
- Add [`-no-ident`](https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html#index-fno-ident) for GCC when build for Release.
**TLDR:** 
GCC likes to [spamm](https://github.com/msys2/MINGW-packages/issues/21) a string about timestamps, versions, and RedHat(?) on the binaries, this removes that string from the binaries when build for release.
```console
$ echo "echo 42" > hello.nim
$ nim c -d:release --listCmd hello.nim
gcc -c  -w -O3 -fno-strict-aliasing -fno-ident  -I/home/juan/code/Nim/lib -I/home/juan/code/temp4 -o /home/juan/.cache/nim/hello_r/stdlib_io.nim.c.o /home/juan/.cache/nim/hello_r/stdlib_io.nim.c
gcc -c  -w -O3 -fno-strict-aliasing -fno-ident  -I/home/juan/code/Nim/lib -I/home/juan/code/temp4 -o /home/juan/.cache/nim/hello_r/stdlib_system.nim.c.o …
```
=> Add no-ident for GCC when build for Release

lib/pure/concurrency/cpuinfo.nim, lib/pure/memfiles.nim, lib/pure/strutils.nim, lib/system.nim, lib/system/ansi_c.nim, lib/system/io.nim, lib/system/memory.nim, lib/system/osalloc.nim, lib/wrappers/openssl.nim, testament/important_packages.nim, tests/manyloc/keineschweine/lib/estreams.nim
=> Revert "Fixes #12187"

config/nim.cfg
`vcc.options.linker.always` in `config/nim.cfg` was ignored when Nim call `vccexe`.
This PR fix the option name so that `/F33554432` is passed to `vccexe`.
=> Fix vcc linker option name in config/nim.cfg

compiler/guards.nim, tests/array/tarray.nim
=> [backport] Fix #12466 , make sameTree() handle uint literals correctly

doc/manual.rst
=> manual fix about method call syntax

lib/std/monotimes.nim
`getMonoTime` was previously broken on the JS backend due to `getJsTicks` returning the wrong unit.
=> Fix JS bug in std/monotimes

lib/pure/math.nim
- Improve `math` module documentation.
- I see new users search for stuff like `xor` and `clamp` on `math` but they cant find it, because its on `system`.
=> Documentation Math module 

compiler/semcall.nim, nimsuggest/tests/tcallstrlit_highlight.nim
nimsuggest should now be able to highlight functions in generalized raw string literals correctly.
=> compiler/semcall: return the correct lineinfo for nkCallStrLit

compiler/extccomp.nim
When I create `nim.cfg` with `vcc.options.always = "/nologo"` and run `nim c --cc:vcc test.nim`, Nim called vccexe.exe like
`vccexe.exe /c --platform:amd64/nologo ...`.
Then I got error because there is no space between `--platform:amd64` and `/nologo`.
=> Fix Nim specify wrong option to vccexe when vcc.options.always is set

compiler/semtypes.nim, nimsuggest/tests/tobj_highlight.nim
The line info should now points to the `a`, not the `*`, like this:
a*: string
^
Additionally this fixes nimsuggest's highlighting of exported object
fields.
/cc @narimiran
Also, there are two `proc`s around that does this "unwrapping" in the compiler. I'm thinking of unifying them into one `proc`, but I don't know how should I name it. Any suggestions?
Those two `proc`s are: `getCallLineInfo()` in `semcall` and `getLineInfo()` in `semstmts.semIdentDef()`.
=> compiler/semtypes: improve lineinfo for exported object fields

doc/lib.rst, lib/pure/colors.nim
...because the `graphics` module was removed from the standard library in 2015.
=> Remove sentences referring to the graphics module

config/nim.cfg
When I run nim with `--cc:vcc` option and nim call vccexe to link object files, cl.exe output following message:
```
Microsoft(R) C/C++ Optimizing Compiler Version 19.00.24210 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.
```
And when I got error message from cl.exe, it output following message:
```
Microsoft(R) C/C++ Optimizing Compiler Version 19.00.24210 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```
I don't think these messages are needed to be displayed.
So I added `/nologo` option to config\nim.cfg to suppress these message.
`/nologo` option was used in config\nim.cfg before but following commit removed it. …
=> Add /nologo option when nim call cl.exe

doc/intern.rst
fixes https://github.com/nim-lang/Nim/issues/12503
=> integer literal documentation [ci skip]

lib/pure/json.nim, lib/system.nim, tests/stdlib/tjsonmacro.nim
On top of some refactoring fixes https://github.com/nim-lang/Nim/issues/12479
=> Extent json.to testing to VM, add workrounds for VM bugs.

lib/pure/strformat.nim, tests/stdlib/tstrformat.nim
I want to use ``strformat.fmt`` to put Nim variables in GLSL code that are embed as string literal in Nim code.
But GLSL code have many ``{`` and ``}`` characters and I don't want to escape them.
So I added 2 ``fmt`` macros that use specified characters instead of ``{`` and ``}``.
=> [feature]strformat: add 2 'fmt' macros that use specified characters instead of '{}' 

changelog.md, lib/pure/os.nim
Behavior of the paths processing routines is made uniform as expected in all languages (and matches the one in Python), splitPath() docstrings are updated, tests are added for both splitPath() and splitFile().
=> splitPath() behavior synchronized with splitFile()

lib/pure/colors.nim
This pull request has two commits for the two parts that ended up being related anyway.
First, for some reason, the `mix` template somewhat works in 0.20.2, but using it in 1.0+ causes this error:
```
/home/jjp/code/nim/color_test1.nim(9, 8) template/generic instantiation of `assert` from here
/opt/nim/lib/pure/colors.nim(137, 14) Error: redefinition of 'ar`gensym250057'; previous declaration here: /opt/nim/lib/pure/colors.nim(136, 7)
```
The first commit fixes that. It also fixes #11339; the second example mentioned in that issue spews out C compiler errors in 0.20.2 and produces the above error with 1.0+. With this change, both examples within that issue produce the expected output.
After that, I converted `mix`'s example into a runnable one to help catch regressions, and I decided to …
=> colors: fix 'mix' template and make most examples runnable

doc/backends.rst
instead show c2nim users manual directly from github.
this fixes issue #12537
=> [backport] fix broken link to non-existing c2nim manual html, fixes #12537 [ci skip]

compiler/evalffi.nim
Prevented building compiler with `nimHasLibFFI`.
=> Fix code style errors

lib/core/macros.nim
This is another fix in the vein of https://github.com/nim-lang/Nim/pull/10760 with the exact same explanation.
=> Fix newLit for objects having string fields

lib/system/jssys.nim
- Improve `Math.Trunc()` code on JS, had weird whitespaces and indents. Code is literally same.
```nim
if (!Math.trunc) {
Math.trunc = function(v) {
v = +v;
if (!isFinite(v)) return v;
return (v - v % 1)    ||    (v < 0 ? -0 : v === 0 ? v : 0);
};
}
```
```nim
if (!Math.trunc) {
Math.trunc = function(v) {
v = +v;
if (!isFinite(v)) return v;
return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
};
}
```
=> Improve Math.Trunc on JS

appveyor.yml, azure-pipelines.yml, tools/downloader.nim, tools/finish.nim, tools/urldownloader.nim
@dom96 has updated the mingw32.7z and mingw64.7z links to point to the 6.3.0 version which is currently being used in our CI tests. Updating all references to that so that updating mingw going forward will simply require updating the symlinks on nim-lang.org.
Choosenim will [also](https://github.com/dom96/choosenim/pull/143) use these links going forward.
I'll make a separate PR for the nim-lang.org website.
=> Switch mingw links

compiler/linter.nim, lib/posix/posix.nim, lib/posix/posix_linux_amd64.nim, lib/pure/strutils.nim, lib/system.nim, lib/system/ansi_c.nim, lib/system/io.nim, lib/system/memory.nim, lib/system/osalloc.nim, lib/system/strmantle.nim, lib/system/threadlocalstorage.nim, lib/windows/winlean.nim, lib/wrappers/openssl.nim, tests/cpp/temitlist.nim, tests/cpp/tempty_generic_obj.nim, tests/manyloc/keineschweine/dependencies/enet/enet.nim, tests/manyloc/keineschweine/lib/estreams.nim, tests/misc/tidentconcatenations.nim
Implement the proposal by @Araq in https://github.com/nim-lang/Nim/pull/12447#issuecomment-543135658_
It is actually harder to maintain backwards compatibility with this change instead of https://github.com/nim-lang/Nim/pull/12321. Explicit conversions like `csize(x)` or `cast[csize](x)` would work no matter if `csize` is defined as `int` or `uint`. The new type `csize_t` and deprecating `csize` forces user of `csize` into one of these options:
* Ignore deprecation warnings
* Drop support for Nim versions that don't provide `csize_t`
* Copy the definition of `csize_t` into the project with some `when declared` condition.
* Avoid using `csize`/`csize_t` all together and use `int`/`uint` directly.
This still does break backwards compatibility, since I did change functions that return …
=> introduce csize_t instead of fixing csize

lib/core/macros.nim, lib/pure/os.nim, lib/system.nim
Fixes https://github.com/nim-lang/Nim/issues/10477.
I have expanded more on these in my notes, but didn't know the best way to translate those to the docs: https://scripter.co/notes/nim/#fetching-various-paths.
=> Add docs to better distinguish among getProjectPath, getCurrentDir and currentSourcePath

changelog.md, compiler/jsgen.nim
- JSGen Indent be all spaces, instead of randomly mixed spaces and tabs, for generated JavaScript.
=> JS improve indent

lib/system/sets.nim
`countBits32` is now fixed in the same way that `countBits64` was already patched earlier (by adding `'u32` where needed).
=> [backport] fix #12395

compiler/suggest.nim, nimsuggest/tests/tcon_variable.nim
This allows for the type of a variable to be retrieved.
=> compiler/suggest: add variable support to `con`

changelog.md, lib/pure/collections/sequtils.nim, tests/manyloc/argument_parser/argument_parser.nim
Earlier the tuples had named fields "a" and "b" and that made it
difficult to assign the zip returned seqs to other vars which expected
seqs of tuples with field names other than "a" and "b".
=> Make sequtils.zip return seq of anonymous tuples

compiler/nimconf.nim
I'd like to use this for a package manager.
=> export nim.cfg parser for use by other tools

doc/tut3.rst
Derivative of `b*pow(x, 2)` is `2*b*x`, while old version had `2*a*x`
=> doc/tut3.rst: Fix typo in Introduction

compiler/commands.nim, compiler/options.nim, doc/advopt.txt
Per title; resets the list of Nimble search paths so that they may subsequently be manipulated by further `nimblePath` options.
=> add --clearNimblePath; fixes #12601

compiler/nimconf.nim
Per title, needed in order to put `--define:foo=bar` in `nim.cfg` whatfer package management purposes.
=> restore --define:key:val in nim.cfg and fix #12367

compiler/injectdestructors.nim, compiler/pragmas.nim, compiler/sempass2.nim, compiler/sigmatch.nim, lib/pure/concurrency/cpuinfo.nim, lib/pure/includes/osenv.nim, lib/pure/osproc.nim, lib/pure/parseopt.nim, nimsuggest/nimsuggest.nim, tests/ccgbugs/tmissingderef2.nim, tests/ccgbugs/tuple_canon.nim, tests/float/tfloat4.nim, tests/iter/titer_issues.nim, tests/macros/tgettype.nim, tests/macros/tgettypeinst.nim, tests/macros/tmacro1.nim, tests/macros/tmacro4.nim, tests/macros/tmacros1.nim, tests/metatype/tymatrix.nim, tests/misc/tbug511622.nim, tools/dochack/fuzzysearch.nim, tools/nimfind.nim, tools/niminst/niminst.nim
Removed unused imports, as reported by our CI/nightlies logs.
I got annoyed by having **560+** `Warning: imported and not used` messages there.
Please double-check all the changes in the first commit, because our CIs might not hit every branch of the code where some imports might be used, or there might be some other usage of those files.
=> Remove unused imports

changelog.md, compiler/vm.nim, lib/core/macros.nim, tests/macros/tmacro1.nim
The reason for this is that it is pretty annoying in macros to unwrap all these backtick and export markers. Almost everywhere in the language an identifier is equivalent to the same identifier but quoted. 
When writing macros, the macro usually doesn't handle the backtick initially and then it doesn't work and you wonder why and then you realize: "ah backticks, this special snowflake, I love it". In this PR I made `eqIdent` just skip this node internally it it doesn't care if any of it's arguments is backticked or Not. The same is true for the export marker in proc names.
But what made me actually implement this PR is this line of code that I stubled upon:
https://github.com/status-im/nim-stew/blob/master/stew/shims/macros.nim#L149
Aparently it is not just me who wants this behavior …
=> backtick and export marker handling in `eqIdent`

compiler/importer.nim, compiler/pragmas.nim, compiler/semdata.nim, tests/pragmas/twarning_off.nim, tests/pragmas/warn_module.nim
Fixes  #11826 
Fixes  #5050
Importing of a module changes ConfigRef, it needs to be preserved and then restored.
=> Alternative fix for #5050 and #11826 

lib/pure/random.nim
proc randomized*() uses time releated function which is not available on
standalone, so disable this function for standalone.
=> allow `random` module to be used in standalone:

lib/system/excpt.nim, tests/cpp/tterminate_handler.nim
Calling `throw` inside terminate handler causes undefined behavior. It is mitigated by trying to deduce exception type without rethrowing.
=> Fix crash in terminate handler

lib/system.nim
Fix compilation warning: conversion from XXX to itself is pointless [hintConvFromXtoItselfNotNeeded]
=> fix compilation warning

changelog.md, lib/pure/collections/tables.nim
Rationale: these procs exist for `Table`, they should also exist for `OrderedTable` and `CountTable`.
Fixes #12519.
=> fix #12519: introduce OrderedTable.take, CountTable.del, CountTable.take

lib/pure/strutils.nim, tests/stdlib/tstrutil.nim
* removed usage of split
Also I think it should accept parameter ``decimalSep`` instead of guessing the separator.
=> Version of trimZeros without temp strings

lib/posix/posix.nim, lib/posix/posix_openbsd_amd64.nim, lib/system/threadlocalstorage.nim
Fixes #12135 and fixes #12109 
Note that the `posix_other_consts` file is used (the same goes for `posix_macos_amd64`) as I can't get `detect.nim` to run on OpenBSD.
=> Fix #12135 and #12109

compiler/int128.nim
Before this PR, `tests/misc/tconv.nim` fails when the compiler
is compiled without `-d:danger` flag.
Bear in mind that even without the asserts, the values outside of
a given range are still checked and a meaningful error message
(from `compiler/semexprs.nim`) is printed.
=> remove two asserts in int128.nim

lib/pure/parseopt.nim
When trying to evaluate a Nimble file which imports a Nim module
I was getting the following errors for some reason:
```
/Users/dom/projects/nim/lib/pure/parseopt.nim(229, 46) Error: ambiguous call; both system.paramCount() [declared in /Users/dom/projects/nim/lib/system/nimscript.nim(65, 6)] and os.paramCount() [declared in /Users/dom/projects/nim/lib/pure/os.nim(2613, 8)] match for: ()
```
I didn't look too closely at the cause and just fixed this code.
=> Fixes ambiguity errors when evaluating Nimble files.

compiler/ccgtypes.nim, compiler/semtypes.nim, tests/macros/tinvalidtypesym.nim, tests/misc/talignas.nim
This problem isn't caught in `tsizeof`, because that test case include `stdalign.h` from using `alignof` already.
The fix in the error message is an unrelated to alignof. I fixed it because I think that ``"type expected, but got symbol 'MyType' of kind 'Type'"`` isn't that useful.
=> fix regression in align

changelog.md, doc/apis.rst, lib/pure/collections/tables.nim
Discussion both in
https://github.com/nim-lang/Nim/pull/12600
and in
https://forum.nim-lang.org/t/5499
indicates that everyone is happy/happier with ``pop``.
This just renames the brand new ``take``s to ``pop`` and installs inline
aliases/wrappers to preserve ``Table.take`` and ``TableRef.take``.
Update apis.rst to try to maintain consistency of remove-and-return procs.
=> ``take`` -> ``pop``

doc/manual.rst
I think that subsections `Namespaces`..`Importcpp for objects` following `ImportJs pragma` section are actually subsections of `ImportCpp pragma` section.
=> Fix wrong section hierarchy in the manual

lib/pure/base64.nim, lib/pure/httpclient.nim, lib/pure/strutils.nim
Per title, rewrite some error messages to remove runtime `repr` calls, enabling use with newruntime.
=> replace some runtime repr in stdlib for gc:arc

tests/js/tconsole.nim
whenever I test locally the test suite fails with the following error:
```
FAIL: tests/js/tconsole.nim JS -d:nodejs
Test "tests/js/tconsole.nim" in category "js"
Failure: reOutputsDiffer
Expected:
Hello, console
1 2 3
1 'hi' 1.1
Gotten:
Hello, console
1 2 3
1 hi 1.1
FAIL: tests/js/tconsole.nim JS -d:nodejs -d:release
Test "tests/js/tconsole.nim" in category "js"
Failure: reOutputsDiffer
Expected:
Hello, console
1 2 3
1 'hi' 1.1
Gotten:
Hello, console
1 2 3
1 hi 1.1
```
The problem is, console.log is underspecified stuff that does things sometimes differently. [Here is a related question about that on stack overflow](https://stackoverflow.com/questions/53746913/why-does-console-log-log-strings-with-quotes-in-some-cases). I guess it is just a matter of time until nodejs might be updated on …
=> fix in tests/js/tconsole

compiler/extccomp.nim, compiler/lineinfos.nim, compiler/vmdeps.nim
* fixes #12663  /cc @treeform /cc @araq
`nim c -r main.nim` would not recompile in case `test.txt` changes in `staticRead("test.txt")`
(it would recompile in case `-r` was not provided though)
`nim c -r main.nim` would recompile in case `test.txt` changes in `staticRead("test.txt")`
this simply keeps track of files used inside staticRead in a new `conf.m.extraFileDeps` field; it renames `nimfiles` to `depfiles` to keep track of any dependency (nim files + files in extraFileDeps)
* one could expose a `proc addDependency(file: string)` that would put file inside `conf.m.extraFileDeps` that'd work with other files known by user to be a dependency (not via staticRead but via some other indirect way the user knows about, eg indirectly called via`staticExec` but there could be other scenarios) …
=> fix #12663 staticRead now creates a dependency for rebuilds

tests/async/tasyncclosestall.nim
This test is very flaky, this change might help reducing the
number of failings (usually solved by restarting the test suite).
Refs https://github.com/nim-lang/Nim/pull/12694#issuecomment-557583790
=> [backport] increase the timeout for 'tasyncclosestall'

changelogs/changelog_0_18_1.md, compiler/liftdestructors.nim, compiler/semcall.nim, doc/intern.rst, doc/manual.rst, doc/manual_experimental.rst, lib/wrappers/linenoise/linenoise.c, tests/assert/tassert2.nim, tests/deps/x11-1.0/xkb.nim, tests/deps/x11-1.0/xkblib.nim
Should be non-semantic.
Uses https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines to find likely typos.
=> Fix spelling typos

lib/impure/re.nim, lib/pure/asyncnet.nim, lib/pure/base64.nim, lib/pure/httpclient.nim, lib/pure/net.nim, lib/pure/sugar.nim, testament/backend.nim, testament/categories.nim, testament/htmlgen.nim, testament/testament.nim, tools/nimfind.nim
This commit fixes the style issues that were present in the `lib/`, `tools/`, and `testament/` directories. This was done by adding a temporary `config.nims` file in the root directory containing nothing but `--styleCheck:error`, and fixing any issues that come up when compiling.
Now, compiling a project with `--styleCheck:error` doesn't fail due to the standard library.
This PR closes out #12687
=> Fix style issues in lib/, tools/, and testament/. Fixes #12687.

compiler/commands.nim, compiler/nimblecmd.nim, compiler/options.nim, config/nim.cfg, tests/nimble/tnimblepathdollar.nim, tests/nimble/tnimblepathdollar.nims
Per discussions in https://gist.github.com/genotrance/35504ed532f9cb836f11fd02b5bf1145.
Adding Nim capability to handle `$nimbleDir` substitution in `--path` flags
- `$nimblePath` and `$nimbleDir` both are supported
- Handled differently than other $ substitutions since it is one to many
- Every `$nimbleDir` added to Nim will be added to `searchPaths`
- If `$nimbleDir = ["$home/.nimble/pkgs", "$projectpath/nimbledeps/pkgs"]`
- `--path:"$nimbleDir/pkg-0.1.0"` will `searchPaths.add(["$projectpath/nimbledeps/pkgs/pkg-0.1.0", "$home/.nimble/pkgs/pkg-0.1.0"])`
Cc @Araq @dom96 @disruptek
=> Substitute $nimbleDir in --path flags

lib/pure/math.nim, lib/pure/unicode.nim
This fixes some tiny issues with using Nim on 16-bit platforms. Not
entirely sure why the AVR chip I was compiling for with "cpu = avr" was
detected as 16-bit, but that's probably another issue..
=> Fix for 16 bit platforms

lib/system.nim, tests/compilerapi/myscript.nim, tests/compilerapi/tcompilerapi.nim
This prevented echoing objects / tuples from compiling on nimscript.
=> make addQuoted work on nimscript

lib/pure/collections/sequtils.nim
The proc already handled the case where `last` is out of bounds, so this is imo just a bugfix.
Fixes #12388
=> Fix sequtils.delete bug with out of bounds indexes

.builds/freebsd.yml, .gitignore, lib/pure/os.nim, lib/system.nim, readme.md, testament/specs.nim, tests/dll/client.nim, tests/js/tconsole.nim, tests/niminaction/Chapter8/sfml/sfml_test.nim, tests/stdlib/tgetaddrinfo.nim
Fixes #12113 
Fixes #12103 
Linked to #12105 - this adds FreeBSD CI support where the other adds OpenBSD.
There are a few tests currently failing on FreeBSD. I've opened some issues for some of them and will open more after the current test run completes.
=> #12103 - CI for FreeBSD

compiler/msgs.nim
`fileInfoIdx` assumed `isKnownFile` was set to true. Wasted a bit of time before realizing this.
=> Always set fileInfoIdx's isKnownFile

compiler/vmdef.nim, compiler/vmgen.nim
The size and location of the registers in the instructions are now all derived from a single definition, allowing the register layout to be easily changed.
This supersedes https://github.com/nim-lang/Nim/pull/12742, which tried to do too much in one PR.
The final goal is to increase the register sizes in the `TInstr` to allow for longer jumps and more registers, separate PRs will be opened for this later.
=> Refactored VM register layout.

compiler/packagehandling.nim
Unlike Unix, Windows is multiple root file system. I cannot create a relative path from 2 absolute paths with different drive.
When `relativeTo` cannot create a relative path, it returns absolute path as is.
This fix replace all `os.DirSep` and `os.AltSep` in the path returned from `relativeTo`.
=> Fix #12734

compiler/extccomp.nim
This change is very similar to PR https://github.com/nim-lang/Nim/pull/12380.
Except PR https://github.com/nim-lang/Nim/pull/12380 helps for external c/cpp files introduced with `{.compile.}` pragma while this PR makes sure it also recompiles external file listed on the command line (or cfg/nimscript) with `--compile` command line option. During command line processing the conf.cmd is not yet set causing incorrect behavior in `externalFileChanged`.
=> Fix external file recompilation 2

compiler/injectdestructors.nim
`pArg` and `p` are now unified and the new `p` takes a ProcessMode parameter indicating wether the `n` will be consumed (evade destructor injections), is a sink argument, or should be processed normally.
This PR is based on the latest araq-arc-devel branch.
=> Refactor injectdestructors

lib/impure/db_mysql.nim, lib/system.nim
If we have following users table in mysql and "email" column have null data
|id|name|email|
|---|---|---|
|1|John|null|
```
echo db.getRow(sql"SELECT * FROM users")
```
expects
```
@["1", "John", ""]
```
However we get an error
```
/nim/lib/impure/db_mysql.nim(310) getRow
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
=> fix db_mysql getRow() when column is null error raised

lib/pure/terminal.nim, tools/nimgrep.nim
Those are a few changes to nimgrep:
- add context printing (lines after and before a match)
- add exclude/include options for files and exclude for directories
- add a `--newLine` style option for starting matching/context
lines from a new line
- add color themes: 3 new themes (ack, gnu, bnw) besides default `simple`
- enable printing of multi-line matches with line numbers
- proper display of replace when there was another match replaced at
the same line / context block 
- improve cmdline arguments error reporting
- improve error printing
- improve symlink handling
- context printing: handle Posix file endings with native appearance
- rename dangerous `-r` argument. Having -r as --replace is dangerous: it can be easily confused with --recursive, and indeed a few popular Unix tools like …
=> nimgrep improvements

compiler/vm.nim
/cc @Araq 
before PR:
Error: unhandled exception: intVal [FieldError]
whenever setting a ptr or pointer field (assigning a ptr variable at CT already works)
after PR:
setting a ptr or pointer field works
there are many use cases, here's a simple one (example1 with pointer field) and a more elaborate one (example2 with ptr field)
example below requires building nim with -d:nimHasLibFFI and compiling with --experimental:compiletimeFFI for importc at CT
```
nim c -d:timn_D20191206T095533 --app:lib --outdir:$build_D/lib/ t0816b.nim # only needed for example2
nim c -r --experimental:compiletimeFFI t0816.nim 
```
t0816.nim:
```nim
import system/ansi_c
import ./t0816b
proc c_malloc*(size: csize_t): pointer {.importc: "malloc", header: "<stdlib.h>".}
proc c_fprintf*(f: CFilePtr, frmt: cstring): …
```
=> VM: allow setting ptr/pointer fields at CT

lib/pure/math.nim
Added minor change to check for floating point subnormality, both for float32 and float64. It seems this was anticipated but never implemented, hence the note "XXX: fcSubnormal is not detected!"
=> Fixes classify function to detect subnormal floating points

changelog.md, lib/pure/strtabs.nim, tests/stdlib/tstrtabs.nim
The `mode` field is not exported.  This works around that, as well as providing more succinct typical usage.
=> add a StringTable.clear that requires no mode specification

lib/nimbase.h
`HAVE_STDINT_H` wasn't defined for the AVR compiler so the `NU32` integer type was typedef'ed to an `unsigned int`. On the AVR platform however an `unsigned int` is 16 bits in size. This would lead to weird behaviour when trying to use these types. This check fixes the issue by defining `HAVE_STDINT_H` when the AVR compiler sets the `__AVR` flag.
=> Fix AVR target to define ints properly

changelog.md, lib/core/macros.nim, lib/pure/sugar.nim, tests/closure/tcapture.nim
This `capture` macro works for more cases than `closureScope`. See examples below.
__UPDATE__: move to `sugar` module, and `freshIdentNodes` is used (dependency on
#12705 is eliminated)
~~Note: this macro depends on PR #12705.~~
```nim
import macros, sequtils, strformat, sugar
proc t1_1() =
let m = @[proc (s: string): string = "TO " & s, proc (s: string): string = "NOT TO " & s]
var l: seq[proc (s: string): string] = @[]
for it in m:
capture [it]:
l.add(proc (s: string): string = it(s))
let r = l.mapIt(it("merge #12705"))
echo r[0] & ", or " & r[1]
```
`TO merge #12705, or NOT TO merge #12705`
```nim
proc t1_0() =
let m = @[proc (s: string): string = "TO " & s, proc (s: string): string = "NOT TO " & s]
var l: seq[proc (s: string): string] = @[]
for it in m:
closureScope:
l.add(proc (s: …
```
=> introduce capture macro

compiler/vmdef.nim, tests/vm/tfarjump.nim, tests/vm/tmanyregs.nim
Increases range from from 32K to 8M instructions. Leaves plenty of space in `TInstr` that can later be used for other purposes.
Fixes #12727, supersedes #12742
=> Increased TInstr field sizes: allow long jumps and 65535 VM registers

lib/pure/json.nim
D20191212T144944
fixes regressions introduced in 21cbfd72ec9fce04fab98326376651806c8adf0b /cc @krux02 
```nim
import std/json
type
Foo* = ref object # no bug with `object`
z1*: string
Baz* = ref object
foo2*: Foo # bug
proc testAll*()=
let s = """{"foo": {"z1": "hi"}}"""
let j = parseJson(s)
discard j.to(Baz)
testAll()
```
before 21cbfd72ec9fce04fab98326376651806c8adf0b
```
/Users/timothee/git_clone/nim/timn/tests/nim/all/t0832.nim(64) t0832
/Users/timothee/git_clone/nim/Nim_temp/lib/pure/json.nim(1216) testAll
/Users/timothee/git_clone/nim/Nim_temp/lib/pure/json.nim(480) []
/Users/timothee/git_clone/nim/Nim_temp/lib/pure/collections/tables.nim(263) []
Error: unhandled exception: key not found: foo2 [KeyError]
```
after 21cbfd72ec9fce04fab98326376651806c8adf0b
``` …
```
=> fix json regression

compiler/semtypes.nim, tests/proc/untyped.nim
* this PR removes a stdlib special case and makes typed/untyped params in magic procs explicitly allowed (even in non-stdlib modules).
It makes it easier to define magic procs in user defined modules (eg for customizing the compiler)
* a test case is included
=> allow typed/untyped params in magic procs (even if not in stdlib)

lib/system/formatfloat.nim
I have been trying out clang_cl compiler from LLVM 9.0 with Nim. Found it prints out nan differently than vcc on windows. NaNs are printed as `nan(ind)`.
=> NaN floatFormat with clang_cl 

tools/nim-gdb.py
this allows to use ``$nimstreq`` on nim strings in gdb. The best use is for writing conditionals on breakpoints, e.g. ``break typeSectionFinalPass if $nimstreq(c.module.name.s, "scratch")``.
=> add $nimeq for gdb

compiler/semobjconstr.nim, compiler/semstmts.nim, compiler/semtypes.nim, tests/casestmt/tincompletecaseobject2.nim, tests/objvariant/tnon_zero_discrim_err.nim
The types in `casestmt/tincompletecaseobject2.nim` did not give missing values in error message before. This PR is mostly moving stuff out of semobjconstr into semtypes with some cleanup.
Also adds a test back that was hijacked.
=> Better case coverage error message for alias and range enum

tests/async/tasyncclosestall.nim
* fix #12919 tasyncclosestall flaky: Address already in use
=> fix #12919 tasyncclosestall flaky: Address already in use

lib/system.nim
`reset(x)` now means setting x to its default value for new and old runtime alike.
Closes #12935
=> system.reset is no longer magic

compiler/ccgstmts.nim, tests/casestmt/t12785.nim
As discussed on IRC, all let and var sections processed by inject destructors are put into stmt lists, which the [code generating computedGoto can't handle](https://github.com/nim-lang/Nim/blob/devel/compiler/ccgstmts.nim#L555), leading to #12785 
It's not super clean, but the least invasive solution I came up with.
=> Fix #12785

doc/manual.rst, lib/system.nim
1. mark closureScope as deprecated in code;
2. update manual to use `sugar.capture`.
=> update document for `closureScope` and `capture`

compiler/semstmts.nim, compiler/semtypes.nim, tests/casestmt/tincompletecaseobject2.nim
I find this useful but may be too verbose for others given that half `char` values are represented as hex literals.
opinions?
=> case coverage error message for `char`

lib/system.nim, tests/system/tlenvarargs.nim
* fixes https://forum.nim-lang.org/t/3717#23156 How to count varargs[untyped] inside of template?
* fixes https://github.com/nim-lang/Nim/issues/11117 varargs[T].len as const expression
`lenVarargs` can actually be implemented as follows:
```nim
macro lenVarargs*(a: varargs[untyped]): untyped = newLit len(a)
```
but that requires a dependency on macros.nim, so is unsuitable for "low-level" code that can't have such dependency, eg:
* see myecho in provided test file tests/system/tlenvarargs.nim: it defines a simple yet useful alternative to echo that also prints file:line:col before printing its arguments (to makes it obvious in printouts where the echo came from); it is useful (in particular for debugging) even in cases where a depdency on macros.nim would otherwise cause circular …
=> lenVarargs: number of varargs elements

lib/pure/httpclient.nim
The request hostname do not necessarily equal to Host http header. Current logic do not allow customzie Host header, but always append another, even there is one supplied.
=> Allow customize Host header in httpclient

compiler/nim.nim, lib/system/excpt.nim
Lightweight stack traces using an external libbacktrace wrapper: https://github.com/status-im/nim-libbacktrace
This addresses https://github.com/nim-lang/Nim/issues/12702 and will be helped by https://github.com/nim-lang/Nim/issues/12735 (on macOS)
These stack traces require `--debuger:native` for debugging symbols and look the same as Nim's default ones: https://travis-ci.org/status-im/nim-libbacktrace/jobs/626489399
This small PR adds support for libbacktrace both in the compiler itself (try it with `./koch boot -d:libbacktrace --debugger:native -d:release`) and in external programs that `import libbacktrace`.
This last requirement is unfortunate. Is there some stdlib module, besides "system", where I can plug this instead of asking users to import it?
Also, any elegant way of showing …
=> generic stack trace overriding mechanism

lib/pure/httpclient.nim, lib/pure/streams.nim, lib/system.nim
Also addresses (or attempts to address) #12968, but I'm not sure if splitting the `nimvm` branch further with `taintMode` is the correct way to go. I'd appreciate feedback on this. Thanks in advance!
=> Added fix for handling TaintedStrings in streams and httpclient

lib/system/ansi_c.nim
Stack traces on an unbuffered stderr get out of sync with line-buffered
stdout - usually on Windows terminals or CI logs. This fixes it by
calling C's fflush() on the output buffer in the procedure used for
printing stack traces.
=> c_fflush() the rawWrite() buffer

compiler/nimblecmd.nim
Per disruptek/nimph#102 the `getPathVersion` gets confused when a parent directory is named like `...-#...`.
=> fixes disruptek/nimph#102 multi-level nim.cfg use

compiler/pragmas.nim
=> fix #12985 {.push.} now does not apply to generic instantiations

compiler/injectdestructors.nim, compiler/liftdestructors.nim, compiler/lowerings.nim, tests/destructor/t12037.nim, tests/destructor/tmisc_destructors.nim
While working on PR  https://github.com/nim-lang/Nim/pull/12992 I came up with idea how number of sink calls be significantly reduced. `isFirstWrite` is used to detect if it safe to optimize `=sink` calls to bitwise `memmove` calls. So far  `isFirstWrite`  is true if it is `let x = ..` or `var y = ...` outside of the loop, but further PRs can potentially use control flow graph to optimize assignments as well. In similar fashion as we have `isLastRead` we also will need `isFirstWrite` to make it happen.
This PR contains all changes of https://github.com/nim-lang/Nim/pull/12992. As I used it as a starting point.
=> Sink to MemMove optimization in injectdestructors

compiler/sempass2.nim, tests/destructor/ttuple.nim
=> fixes #13026

compiler/ast.nim, compiler/cgen.nim, compiler/evalffi.nim, compiler/pragmas.nim, compiler/vm.nim, compiler/vmdef.nim, compiler/vmgen.nim
/cc @Araq 
* VM now supports `importc var`
in particular, it does work with ptr types (eg `CFilePtr = ptr CFile`) or primitive (eg float32 etc), and with either header or dynlib pragma
```nim
var
mystderr2* {.importc: "mystderr", dynlib: libF.}: CFilePtr # with C: FILE* mystderr;
myc_float32* {.importc, dynlib: libF.}: float32 # with C: `float myb_float32; `
myerrno2* {.importc: "errno", header: "<errno.h>".}: cint
```
the resulting code works as expected, in particular works same as with non-VM code, eg: see example1
* bugfix: importc procs returing ptr types (eg ptr float32, pointer etc) are now handled correctly
* remove hardcoded values stdin/stdout/stderr/vmErrnoWrapper in importcSymbol: the compiler is now able to correctly importc these symbols without any hack
furthermore, …
=> VM: support importc var, ptr/pointer types, cast int <=> ptr/pointer

lib/packages/docutils/rst.nim, tests/stdlib/trst.nim
If `start-after` is given as a string option, only lines that follow the first line containing that string are included. If `end-before` is given as a string option, only lines that precede the first lines containing that string are included.
=> Rst parser respect `:start-after:` and `:end-before:` in `include` directive

compiler/docgen.nim
Addressing #12771 
This is also included in the docgen documentation [here](https://nim-lang.org/docs/docgen.html) but its not respected as reported in the issue.
=> Allow `-o` option for `buildIndex`

testament/important_packages.nim
I'm the author of package `nimly`.
The right command for full testing of nimly is `nimble test` and the module `tests/test_nimly` is a subpart of the test.
I'm sorry for there is a test with confusing name.
I will rename `tests/test_nimly` after the release of next version nim.
=> Modify the test command for nimly (nimble-package)

compiler/commands.nim
previously, if a nim.cfg had `--styleCheck:error`, you wouldn't be able to disable it with `--styleCheck:hint`, and `--styleCheck:off` would just hide all the hints
this fixes it
=> [easy] --styleCheck:hint now works

lib/wrappers/postgres.nim
refers to https://www.postgresql.org/docs/9.4/libpq-status.html
=> add pqserverVersion,pqconnectionNeedsPassword,pqconnectionUsedPassword

changelogs/changelog_X_XX_X.md, lib/core/macros.nim
Now it supports:
```nim
Status* {.pure.}
PragmaExpr
Postfix
Ident "*"
Ident "Status"
Pragma
Ident "pure"
```
=> basename supports pragmaexpr

compiler/lineinfos.nim, compiler/main.nim, compiler/options.nim, testament/testament.nim
before PR
```
Hint: operation successful (29712 lines compiled; 0.434 sec total; 24.406MiB peakmem; Debug Build) [SuccessX]
```
after PR:
```
Hint: operation successful (29712 lines compiled; 0.434 sec total; 24.406MiB peakmem; Debug Build) project: /Users/timothee/.cache/nim/manual_d/manual/manual_snippet_101.nim output: /Users/timothee/.cache/nim/manual_d/manual/manual_snippet_101 [SuccessX]
```
* useful when it's not obvious where output goes (eg could have some `--outdir` or other flags controlling where things go or their extensions etc)
* EDIT: another example is with --app:lib which generates platform specific `pathto/libfoo.dylib` 
* also especially useful when the nim cmd was run programmatically instead of directly at cmdline, eg when running `./koch docs` you'd previously had …
=> make SuccessX show project file + output file

lib/pure/includes/osseps.nim
Misplaced separator, which was constantly breaking compilation on Haiku OS, was deleted.
Fixed #13017.
=> Deleted misplaced separator

compiler/evalffi.nim, compiler/sem.nim, compiler/types.nim
* remove all remaining warnings when build nim (with -d:nimHasLibFFI)
* remove dead code
=> remove all remaining warnings when build nim (with -d:nimHasLibFFI)

lib/nimbase.h
this prevents clashes with systems where 'noinline' might be already defined
=> Use '__noinline' instead of 'noinline' for N_NOINLINE gcc attribute

lib/pure/osproc.nim
`si.hStdOutput` is already checked.
`si.hStdInput` was not checked after taking return value of `createFileW`.
=> Fix error check code in osproc

changelog.md, lib/pure/typetraits.nim, lib/system/inclrtl.nim, tests/metatype/ttypetraits.nim
* fix #6454
* typetraits: genericParams
returns a type tuple of generic params of a generic instantiation
* typetraits.len: len of a tuple or type tuple
* get: get ith element of a type tuple (without which `genericParams` is not very useful)
```nim
type Foo[T1, T2]=object
type Foo1 = Foo[float, int]
doAssert genericParams(Foo1) is (float, int)
doAssert genericParams(Foo1).len == 2
doAssert genericParams(Foo1).get(0) is float
doAssert (int, float).get(1) is float
```
* this supersedes https://github.com/nim-lang/Nim/pull/8554 providing the better API (returning a tuple instead of passing in an index, which would've required yet another api to get the generic number of args) suggested in https://github.com/nim-lang/Nim/pull/8554#issuecomment-410997964 by @zah
* there is an existing …
=> typetraits: fix #6454; genericParams; tuple len; tuple type get

lib/pure/asyncftpclient.nim
because the port max value is 65535,  but the toU16  method  is cast to the int16 so it's can contain max value is 32768 so  some times overflow.
=> fix the port convert overflow

lib/system.nim
* every non-trivial `{.pop.}` now has a comment, showing what has been popped
* `when` statements are broken down to smaller chunks and nesting levels have been reduced wherever possible
* minor style fixes
=> System cleanup, part 1

lib/system/ansi_c.nim, lib/system/imports_common.nim, lib/system/io.nim, tests/vm/tevalffi.nim
follow-up now that https://github.com/nim-lang/Nim/pull/12877 got merged. This enables the use case from https://github.com/nim-lang/Nim/pull/12840
`fprintf(cstderr, msg)` + friends now works at CT (with -d:nimHasLibFFI / --experimental:compiletimeFFI as usual)
```nim
import system/ansi_c
proc main()=
c_fprintf(cstderr, "hello world stderr\n")
write(stderr, "hi\n")
static: main()
main()
```
=> VM FFI: write(stderr, msg) and fprintf(cstderr, msg) now work at CT

compiler/extccomp.nim
I am not using `vccexe` tool to run `cl` compiler so got tired of compilation and link warnings:
```
warning: unknown argument  `--platform:amd64` is ignored
```
=> pass platform argument only if vccexe is used

compiler/platform.nim, lib/system.nim, lib/system/excpt.nim, lib/system/io.nim, lib/system/mmdisp.nim, lib/system/osalloc.nim
Note: draft only.
Added a new OS target for running Nim on embedded targets with very basic OS support, the goal is to require only ANSI C features and nothing else. This new `--os:ansic` is ideally used together with `--useMalloc` and `--gc:arc` and might replace `--os:standalone` one day.
This solves:
- The creation of a static RAM area for heap management, now we rely on `malloc()` and `free()` only
- Prevents creation of stack trace info in RAM when stack traces are disabled
- Disabled SIGABRT hack for `gotoBasedExecptions`
=> Added 'ansic' os support for minimal (embedded) targets

changelog.md, lib/pure/os.nim, lib/pure/times.nim
`toSeconds` is deprecated because it's badly named (ambiguous, etc) but is useful and I use it; eg times represented as float is convenient and commonly used in several applications (eg when dealing with video or other time series)
this PR adds:
* `toUnixFloat` replaces toSeconds
* `fromUnixFloat` overload, which is the reverse of toUnixFloat modulo rounding errors
* this PR also fixes a bug in deprecated `fromSeconds*(since1970: float)` which used to crash for negative input; now it uses the new implementation`fromUnixFloat` which correctly handles negative inputs 
* supersedes https://github.com/nim-lang/Nim/pull/12441
* I removed `since` annotation from toUnixFloat since it was making CI fail (`toSeconds` now is implemented from it and I don't want to duplicate the implementation; not …
=> times: toUnixFloat, fromUnixFloat

azure-pipelines.yml, compiler/condsyms.nim, compiler/evalffi.nim, koch.nim, lib/system/ansi_c.nim, lib/system/io.nim, testament/specs.nim, tests/vm/mevalffi.nim, tests/vm/tevalffi.nim
* prevents future regressions (especially platform specific ones) caused by that code not being tested in CI (there were a bunch in the past since -d:nimHasLibFFI was introduced, which is not surprising for code not being tested)
* speaking of which fixes one such regression on windows
* minimal impact on CI runtime, as I'm only compiling nim with -d:nimHasLibFFI once (no bootstrapping via koch boot), and running a single test (./tests/vm/tevalffi.nim)
* [EDIT] -d:nimHasLibFFI now works for freebsd and i386, so that it now works on all posix platforms in CI (freebsd, linux i386, amd64, osx)
* [EDIT] `nimHasLibFFIEnabled` is now defined when nim itself was compiled with -d:nimHasLibFFI; `nimHasLibFFIEnabled` is named differently from `nimHasLibFFI` on purpose to avoid confusion between …
=> enable testing -d:nimHasLibFFI mode

compiler/commands.nim, compiler/jsgen.nim, compiler/options.nim, compiler/sourcemap.nim
I am adding support for sourcemaps.
You can pass `--sourceMap:on` and that implies `--lineDir:on` . 
I've fixed some of the linedir for js and I removed some generated comments from `system/jssys.nim`)
I am basically adding a new pass that works on the generated source and builds source nodes based on the line directives: that seems to be correct (as jsgen doesn't generate other comments, so if one hasn't emitted // line , it should be ok, and you can emit `#line` in C too).
I'll add some tests: for now it seems to work for some files in my project, but I haven't dogfooded it too much. The implementation is based on mozilla's source-map lib
=> Sourcemap for JS

compiler/suggest.nim, nimsuggest/tests/top_highlight.nim
The operator fetching proc is greedy, so operators such as `%*` in
expression `%*{}` can't be highlighted.
This commit fixes that.
=> compiler/suggest: highlight squashed operators

lib/pure/asyncmacro.nim, tests/async/tasync_misc.nim, tests/async/tasync_noasync.nim, tests/async/tasync_nofuture.nim, tests/async/tasync_traceback.nim, tests/async/tasyncawait_cyclebreaker.nim
Adapted  https://github.com/status-im/nim-chronos/pull/47 for asyncdispatch with support for multisync : credit for the original impl to @yglukhov !
=> Make await a template

lib/system/gc_regions.nim, tests/gc/tregionleak.nim
This PR introduces these changes:
- `withRegion` now returns the modified `MemRegion`. The signature has also been changed to account for this.
- `withScratchRegion` now correctly deallocate the scratch region
=> gc_regions: cleanup & fixes for deallocation

changelog.md, lib/core/macros.nim, tests/pragmas/tcustom_pragma.nim
rewrote the customPragma macros for more mudular use.
=> getCustomPragma is split up in more usable chunks

compiler/modulepaths.nim, compiler/nimblecmd.nim, lib/std/sha1.nim, tests/compiler/tnimblecmd.nim, tests/stdlib/tsha1.nim
Implemented support for Nimble local cache with package directories a checksum of the package at the end of their names. Now the compiler supports package paths in the form:
* /path_to_nimble_cache_dir/pkgs/package_name-1.2.3-FEBADEAEA2345E777F0F6F8433F7F0A52EDD5D1B
* /path_to_nimble_cache_dir/pkgs/package_name-#head-042D4BE2B90ED0672E717D71850ABDB0A2D19CD2
* /path_to_nimble_cache_dir/pkgs/package_name-#branch-name-DBC1F902CB79946E990E38AF51F0BAD36ACFABD9
Related to nim-lang/nimble#127
=> Add changes required by Nimble lock file support
